### ISSUE TITLE
False Positive: IWYU says <type_traits> is required when using <chrono>

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1003]
Reproducible here:

```cpp
#include <chrono>

using namespace std::chrono_literals;

int main()
{
    auto y = std::chrono::steady_clock::now() + 30s;
    bool z = std::chrono::steady_clock::now() > y;
}
```

IWYU says:
```
main.cpp:8:47: warning: std::__success_type<std::chrono::duration<long, std::ratio<1, 1000000000>>>::type is defined in <type_traits>, which isn't directly #included.

main.cpp should add these lines:
#include <type_traits>
```

**Comment by kimgr** [comment]
I've looked into this a little bit more, and I don't have clear handle on the problem.
It looks like `std::__success_type`, a support type from `<type_traits>` is part of the return type of chrono's `operator>()`, and is then attributed to the expansion location.
I can't think of a systemic way to tell that apart from other template uses, so I'm not sure how to short-circuit it, or push attribution to the template definition location.
I'll try to debug it some more and see what I can deduce.

**Comment by kimgr** [comment]
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/ffe6c3fe3a1dac9a4b577f4b07ef378ede933554 (and, as it turns out, probably a bit before that).
