### ISSUE TITLE
iwyu creates too much noise

### ISSUE THREAD

**Issue by Spongman** [include-what-you-use/include-what-you-use#1006]
I must be doing it wrong.

I have a simple project with a header, `myheader.hpp`:

````
#pragma once
#include <boost/regex.hpp>
struct MyClass {
  boost::regex my_regex{"blah"};
};
````

and some source files that include that header.

when i run it through iwyu, get this: `myheader.hpp` no longer includes `boost/regex.hpp` (why?)
and _every_ source file that included `myheader.hpp` now includes all this junk:

````
#include <boost/regex.hpp>
#include <assert.h>
#include <ctype.h>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/regex/v5/basic_regex.hpp>
#include <boost/regex/v5/cpp_regex_traits.hpp>
#include <boost/regex/v5/match_results.hpp>
#include <boost/regex/v5/perl_matcher_common.hpp>
#include <boost/regex/v5/perl_matcher_non_recursive.hpp>
#include <boost/regex/v5/regex.hpp>
#include <boost/regex/v5/regex_format.hpp>
#include <boost/regex/v5/regex_fwd.hpp>
#include <boost/regex/v5/regex_match.hpp>
#include <boost/regex/v5/regex_replace.hpp>
#include <boost/regex/v5/regex_search.hpp>
#include <algorithm>
#include <iterator>
#include <map>
#include <memory>
#include <set>
#include <streambuf>
#include <string>
#include <utility>
#include <vector>
````

why all this noise? the `boost/regex.hpp` include is required to use `myheader.hpp` why remove it from that file? and why add all the additional junk that's implicitly included by that file?

I would expect this tool to _remove_ things that aren't used, not add more stuff.

i'm using the `clang_12` branch.

**Comment by kimgr** [comment]
You should probably be using the boost mappings, e.g. `include-what-you-use -Xiwyu -m boost-1.75-all.imp ...`.

But I think there's also something wrong with IWYU's understanding of template expansion currently, so it looks like many symbols used inside a template are attribute to wherever said template is instantiated.

**Comment by Spongman** [comment]
But why is any of that necessary/relevant? A simple examination of the preprocessor include order shows that all of those includes can be reduced to the first one. No language parsing necessary.

**Comment by firewave** [comment]
Actually, it differs wildly per Boost library. Just as expected from it since every library is somewhat different.

In case of Boost.Regex all the inner ones are implementation headers and should not be included in the user code at all.

For other libraries there's some very high-level headers which include *everything* of the library or "module" whereas you might only require a single include and it is valid just have that one.

And again others have such subtle dependencies that even with the help of include-what-you-use you cannot reduce those completely but just to a more sensible level.

Yet others have a mixture of valid and implementation headers which come up.

It depends on the structure and size of your project if want to get involved with getting those cleaned up.

**Comment by Spongman** [comment]
Right and `#include <boost/regex.hop>` - the include that’s removed from the header, and also the _first_ include that iwyu added to the cpp file - includes them all, making all the other includes added to the cpp file redundant.

**Comment by kimgr** [comment]
@Spongman Did you use the mappings and did the problem persist?

The way IWYU currently works, there's no way for it to know which of the headers in the include graph are public user-facing headers, and which are private. That information needs to be provided by the user.

If this is purely a matter of using the right mappings, I figure we can close it, but if there's confusion around template ownership even with mappings, we can probably make the bug more specific than "creates too much noise".

**Comment by kimgr** [comment]
No new information in almost a year, I'm going to close this. There have been some template attribution fixed recently that may make this slightly better, but mappings are necessary for libraries like Boost.
