### ISSUE TITLE
additional implementation includes suggested for `termios` usage

### ISSUE THREAD

**Issue by firewave** [include-what-you-use/include-what-you-use#1015]
```cpp
#include <termios.h>

void f(void)
{
	struct termios oldt, newt;
	tcgetattr( 0, &oldt );
	newt.c_lflag &= ~( ICANON | ECHO );
	tcsetattr( 0, TCSANOW, &newt );
}
```

```
input.cpp should add these lines:
#include <bits/termios-c_lflag.h>  // for ECHO, ICANON
#include <bits/termios-struct.h>   // for termios
#include <bits/termios-tcflow.h>   // for TCSANOW

input.cpp should remove these lines:

The full include-list for input.cpp:
#include <bits/termios-c_lflag.h>  // for ECHO, ICANON
#include <bits/termios-struct.h>   // for termios
#include <bits/termios-tcflow.h>   // for TCSANOW
#include <termios.h>               // for tcgetattr, tcsetattr
```

https://man7.org/linux/man-pages/man3/tcflow.3.html

**Comment by kimgr** [comment]
See also https://pubs.opengroup.org/onlinepubs/007904875/basedefs/termios.h.html for the POSIX spec, which I think we should use as a first approximation.

The available mappings for termios only cover some basic stuff:
```
$ git grep termios
gcc.libc.imp:  { include: [ "<bits/termios.h>", private, "<termios.h>", public ] },
gcc.symbols.imp:  { symbol: [ "cc_t", private, "<termios.h>", public ] },
gcc.symbols.imp:  { symbol: [ "pid_t", private, "<termios.h>", public ] },
iwyu_include_picker.cc:  { "cc_t", kPrivate, "<termios.h>", kPublic },
iwyu_include_picker.cc:  { "pid_t", kPrivate, "<termios.h>", kPublic },
iwyu_include_picker.cc:  { "<bits/termios.h>", kPrivate, "<termios.h>", kPublic },
```

Patches for more detailed mappings would be welcome.

**Comment by alejandro-colomar** [comment]
I have that (and other types) also pending in the man pages.
`struct termios` is likely going to be a difficult one because there are different versions, AFAIR.
If I document the type in the man-pages, I'll send you a patch with that info, but that'll take a looong time.
If someone is interested in adding a patch to system_data_types(7), It'd be welcome too :)

**Comment by kimgr** [comment]
I think this will be closed by https://github.com/include-what-you-use/include-what-you-use/pull/1026

**Comment by kimgr** [comment]
Closing this now that #1026 is merged.
