### ISSUE TITLE
fix_includes erroneously removes namespace alias

### ISSUE THREAD

**Issue by gedankenexperimenter** [include-what-you-use/include-what-you-use#1022]
When I run `fix_includes.py` on the following file (piping IWYU's stderr to it) with the `--nosafe_headers` option, it removes not just the unused header, but also the namespace alias near the bottom:
```c++
#pragma once

#include <stdint.h>

namespace outer {
namespace middle {
namespace inner {

enum Foo {
  FOO,
  BAR,
  BAZ,
};

}  // namespace inner
}  // namespace middle

namespace inner = middle::inner;

}  // namespace outer
```
It also removes the line with the closing brace for the `outer` namespace, which is even more problematic.

I ran the following command on the above file (named `foo.h` below) to reproduce the problem:
```console
include-what-you-use -x c++ foo.h 2>&1 | fix_includes.py --nosafe_headers
```

**Comment by kimgr** [comment]
@gedankenexperimenter Thanks! Just to let you know that I've seen this, but haven't had a chance to sit down and try to do anything about it. It does seem like `fix_includes.py` is broken here.

**Comment by kimgr** [comment]
This one-character patch appears to fix it:
```diff
diff --git a/fix_includes.py b/fix_includes.py
index 69b7003..67f2a03 100755
--- a/fix_includes.py
+++ b/fix_includes.py
@@ -104,7 +104,7 @@ _NAMESPACE_START_RE = re.compile(r'\s*(namespace\b[^{]*{\s*)+(//.*)?$|'
                                  r'\s*(HASH_NAMESPACE_DECLARATION_START)')
 # Also detect Allman and mixed style namespaces.  Use a continue regex for
 # validation and to correctly set the line info.
-_NAMESPACE_START_ALLMAN_RE = re.compile(r'\s*(namespace\b[^{]*)+(//.*)?$')
+_NAMESPACE_START_ALLMAN_RE = re.compile(r'\s*(namespace\b[^{=]*)+(//.*)?$')
 _NAMESPACE_START_MIXED_RE = re.compile(
   r'\s*(namespace\b[^{]*{\s*)+(namespace\b[^{]*)+(//.*)?$')
 _NAMESPACE_CONTINUE_ALLMAN_MIXED_RE = re.compile(r'\s*{\s*(//.*)?$')
```
:grin:

I'll write up a test as well, but I think this is a reasonable fix.

**Comment by kimgr** [comment]
@gedankenexperimenter Please take a look at #1055
