### ISSUE TITLE
how can i get the decl in "stmt"

### ISSUE THREAD

**Issue by leinjay** [include-what-you-use/include-what-you-use#1023]
when i trave the astcontext with "RecursiveASTVisitor.h", i get the top level decl by "getTranslationUnitDecl", but it only return the decl of global var in the c++ source file, how can i get the declstmt of this decl, such as:
`using foo_name::CFoo; using std::vector; int global = 10; int main() { return 0; }
`"global" is the global var in c++, how can i get the declstmt of "int global = 10"
please guide me or give me an example, thank you so much!

**Comment by kimgr** [comment]
Does this have anything to do with IWYU as such, or are you really asking about how the RecursiveASTVisitor works?

**Comment by leinjay** [comment]
> 

because I want to know the end of a stmt by using stmt->getendloc (), so I can delete it accurately

**Comment by leinjay** [comment]
> > 
> 
> because I want to know the end of a stmt by using stmt->getendloc (), so I can delete it accurately

such as the bad writing “using name space std” etc.

**Comment by leinjay** [comment]
> It sounds like you're writing your own Clang tool. Consider reaching out on the Clang community for support on the AST APIs instead. Depending on what you're trying to do, I think you might be better off using AST Matchers, but this is not the place to discuss it.

thank you so much，I am trying to writting the tools on basic of iwyu，I have read the iwyu and changed some code of iwyu，I wish I have the chance to share that if I made it

**Comment by kimgr** [comment]
This doesn't look like an IWYU issue, so I'm going to close it. Good luck with your tool!

**Comment by leinjay** [comment]
> This doesn't look like an IWYU issue, so I'm going to close it. Good luck with your tool!

thank you again!
