### ISSUE TITLE
[question] Tests are failing on conda build

### ISSUE THREAD

**Issue by xmnlab** [include-what-you-use/include-what-you-use#1033]
Hi everyone, I am trying to create a conda package for iwyu but I am having problems with some tests:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=496908&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1829

this is my local log: https://pastebin.com/3FWt3b8e

these are the dependencies I defined for this: https://github.com/conda-forge/staged-recipes/pull/18539/files#diff-a5bb0ffdd63449f80dc6064b6eaa5e2a3e3cf5e44a0959ba77779175211f708fR17-R29

and this is my build script: https://github.com/conda-forge/staged-recipes/pull/18539/files#diff-ef3efe985f967e54713618b3c5927fe9ee8b98f417586400782a65f8851af725R2

any clue about could be missing? thanks!

**Comment by xmnlab** [comment]
any tip would be very appreciated :)

**Comment by kimgr** [comment]
@xmnlab It looks like there's no C++ standard library available... which seems kind-of odd?
```
$ grep "fatal error:" testlog.txt 
tests/cxx/badinc.cc:60:10: fatal error: 'typeinfo' file not found
./tests/cxx/badinc-i2.h:13:10: fatal error: 'vector' file not found
tests/cxx/fwd_decl_of_nested_class_defined_later.cc:14:10: fatal error: 'utility' file not found
tests/cxx/iterator.cc:18:10: fatal error: 'algorithm' file not found
./tests/cxx/libbuiltins-direct.h:10:10: fatal error: 'cmath' file not found
tests/cxx/no_char_traits.cc:26:10: fatal error: 'iostream' file not found
tests/cxx/no_deque.cc:13:10: fatal error: 'queue' file not found
tests/cxx/no_fwd_decl_std.cc:16:10: fatal error: 'utility' file not found
tests/cxx/operator_new.cc:15:10: fatal error: 'new' file not found
./tests/cxx/overloaded_class-i1.h:13:10: fatal error: 'vector' file not found
./tests/cxx/placement_new-i1.h:13:10: fatal error: 'new' file not found
tests/cxx/precomputed_tpl_args.cc:14:10: fatal error: 'vector' file not found
./tests/cxx/prefix_header_attribution-d1.h:14:10: fatal error: 'new' file not found
tests/cxx/quoted_includes_first.cc:15:10: fatal error: 'iostream' file not found
tests/cxx/scope_crash.cc:21:10: fatal error: 'string' file not found
tests/cxx/std_size_t.cc:20:10: fatal error: 'cstdio' file not found
tests/cxx/stl_container_provides_allocator.cc:19:10: fatal error: 'memory' file not found
./tests/cxx/uses_printf-d1.h:13:10: fatal error: 'cstdio' file not found
```
I don't know how that's expressed in conda, but you probably want libstdc++ or libc++ in the test environment.

**Comment by xmnlab** [comment]
oh got it! I will check why it is happening .. thank you so much!

**Comment by xmnlab** [comment]
@kimgr 
I still working on this ... I have a bigger picture now:

- conda use its own compilers installation (so it is not in the default paths)
- when conda is building the package it sets a lot of variables for the compilation, including CXX, CC, CFLAGS etc
- the compilations works fine but ctest breaks
- conda build keep the whole packaging files available, so I can test it manually. with the lib already created, if I just run ctest (with no conda build env variables) all tests work fine.


so maybe it is something in the code that is expecting the headers in the default paths? is there a way to define different paths?
for example: I found this one: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_tool_test.py#L103

do you know if there are any other places that I would be aware and check?

thanks for all the help and for your attention!!

**Comment by kimgr** [comment]
@xmnlab The Clang compiler (on whose libraries `include-what-you-use` is built) sort of assumes a Unix Filesystem Hierarchy Standard (FHS) tree layout. So if the compiler executable is `/usr/bin/clang`, it will look in `/usr/bin/../include/clang/<version>/` == `/usr/bin/include/clang/<version>` for its builtin headers (`<stddef.h>`, `<stdint.h>`, ...) and I think in `/usr/bin/../include/c++/<version>` for the C++ standard library headers.

IWYU "inherits" this behavior, since we use the Clang libraries without modifying this policy (much).

Maybe you can run IWYU with `-v -###` for tests to get more information about its search paths?

**Comment by xmnlab** [comment]
@kimgr thank you so much for your attention and explanations, really appreciated that.

this is the result of the command you mentioned:

```bash
$ include-what-you-use -v -###

clang version 13.0.1 (https://github.com/conda-forge/clangdev-feedstock b741c7551b48482d08d2f65a791b7602c1f23c9d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651085154144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin
Found candidate GCC installation: /mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651085154144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0
Selected GCC installation: /mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651085154144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
error: unable to handle compilation, expected exactly one compiler job in ''
```

it seems it is raising an error .. do you have any idea how I could handle that?

**Comment by kimgr** [comment]
Not in detail, no. I meant to tweak the iwyu args of the test run to include these flags, but I suppose it will give something similar.

So are there any standard library headers in the `mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651085154144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho` tree?

What does e.g. `find . -name vector` in fat directory say? I'm guessing it's empty. You somehow need to install a stdlib there.

**Comment by xmnlab** [comment]
I have this:

```bash

16:35 $ cd /mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651085154144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/
xmn@kichwa (2022-04-27 16:35:40):/mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651085154144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho$ find . -name vector
./x86_64-conda-linux-gnu/include/c++/11.2.0/vector
./x86_64-conda-linux-gnu/include/c++/11.2.0/experimental/vector
./x86_64-conda-linux-gnu/include/c++/11.2.0/debug/vector
xmn@kichwa (2022-04-27 16:35:47):/mnt/sda1/storage/miniconda3
```

**Comment by xmnlab** [comment]
I isolated the one test and run it locally with a workaround, and it worked!

```
export iwyu=/mnt/sda1/storage/miniconda3/envs/conda-build/conda-bld/include-what-you-use_1651536695168/work/build/bin/include-what-you-use

$iwyu -Xiwyu --verbose=3 \
  -I${PREFIX}/include \
  -I${BUILD_PREFIX}/x86_64-conda-linux-gnu/include/c++/11.2.0/ \
  -I${BUILD_PREFIX}/x86_64-conda-linux-gnu/include/c++/11.2.0/x86_64-conda-linux-gnu/ \
  -I . tests/cxx/uses_printf.cc
```

now, I need to learn how to do it in the build phase XD
