### ISSUE TITLE
: CommandLine Error: Option 'color' registered more than once!?

### ISSUE THREAD

**Issue by fm123456** [include-what-you-use/include-what-you-use#1043]
`[VM-149-142-centos ~/workspace/iwyu/include-what-you-use]$ cd ../build/bin/
[VM-149-142-centos ~/workspace/iwyu/build/bin]$ ./include-what-you-use 
: CommandLine Error: Option 'color' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)`
hi, all. How to fix this error?

**Comment by kimgr** [comment]
@fm123456 I'm not sure, I haven't seen this particular error, but my guess is it stems from the same library being linked more than once. `color` is not a IWYU option, so the conflict must come from Clang or LLVM libraries.

Can you get your build to spit out verbose commands? What does the link command look like?

**Comment by kimgr** [comment]
Almost certainly not an IWYU bug. Closing for now, feel free to reopen if more information comes to light.
