### ISSUE TITLE
Does iwyu_tool.py support mapping files?

### ISSUE THREAD

**Issue by nachogoro** [include-what-you-use/include-what-you-use#1044]
Running `include-what-you-use` from CMake on my very large codebase isn't ideal (the `cmake --build .` command segfaults eventually, plus it's pretty slow as it needs to compile the whole project).

Using `iwyu_tool.py` on the `compile_commands.json` file works fine, though, so I have been using it successfully. I now need to use a mapping file, but it seems to not be possible:
```
python3 ~/iwyu/include-what-you-use/iwyu_tool.py -j 10 -p . <directory_to_improve> \
    -- "--mapping_file=/home/ng/my_mappings.imp"
```
causes the following error: `error: unsupported option '--mapping_file=/home/ng/my_mappings.imp'`

Are mapping files not supported when using `iwyu_tool.py` or am I missing something?

Cheers!

**Comment by kimgr** [comment]
@nachogoro Ah, great. I was just about to look it up.

It was done that way to allow you to override compiler flags and/or IWYU flags.

**Comment by 1e100** [comment]
FYI all: if you want to pass multiple flags, `-Xiwyu` needs to be specified before each flag.
