### ISSUE TITLE
Backreferences with regexes for include mappings

### ISSUE THREAD

**Issue by ingomueller-net** [include-what-you-use/include-what-you-use#1047]
I would like to do something like this:

```
{ include: ["@<(llvm/.*\.h)>", "public", "\"$1\"", "public"] }
```

That is, declare `"llvm/someheader.h"` as the preferred form for every `someheader.h` given in the form `<llvm/someheader.h>`.

Is something like that possible? If yes, how?

**Comment by kimgr** [comment]
See also:

* https://github.com/include-what-you-use/include-what-you-use/issues/145
* https://github.com/include-what-you-use/include-what-you-use/issues/935#issuecomment-943930251
* https://github.com/include-what-you-use/include-what-you-use/issues/959

So to summarize, I don't think it's currently possible, but I suspect it's not too hard to make it work in `IncludePicker::ExpandRegexes`, https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_include_picker.cc#L1399, if you want to take a stab at it.

**Comment by kimgr** [comment]
As of PR #1123, commit 6fb66575fba17039d1be6c1fc3dca08623163460, there's now support for replacements with backreferences for all regex dialects.
