### ISSUE TITLE
[Discussion] Arbitrary Header Ordering Support

### ISSUE THREAD

**Issue by danielh2942** [include-what-you-use/include-what-you-use#1053]
Hi I want to write a new feature for IWYU that allows you to order headers in some arbitrary fashion and I want to know if it's a-ok to try  add to the codebase.

If this gets the go ahead I'll begin writing an implementation and hopefully have it ready in good time

Why:

Some C++ projects enforce strict ordering of headers in the style guide IE:
```
quoted

first party headers

third party headers

linux-only headers

windows-only headers

C++/C core libraries
```
as it stands if one were to streamline iwyu related changes they would need to implement some sorting feature in a post-processor to handle this. I think it would add some extra convenience to the end user to be able to enforce some arbitrary ordering of headers within IWYU itself by means of a config file.

How it will work:

one would write a config file similar to an imp file (or I could potentially extend imp syntax somehow) containing glob-like strings
I.E
```
firstparty/*
thirdparty/*
windows.h
sys/ioctl.h
```

where the ```*``` glob-like operation is inferred as the last option by default.

they would trigger it by having some flag like ```--grouping_file=<filename>```

when invoked, each include is grouped by the first glob string it would qualify to be in, where it is further sorted using the default IWYU method. (additionally, if ```--quoted_includes_first``` is present, it'll segregate quoted ones from others and do the same :) )

then these groupings are merged and displayed at the end

Potential issues:
could be slow for very large projects

Any suggestions/criticisms welcome :)

**Comment by kimgr** [comment]
Ideally I'd like to get rid of header sorting from IWYU, and let tools like `clang-format` or `clang-tidy` handle that separately.

See also #821 for a link-fest of prior feature requests and discussion.

**Comment by danielh2942** [comment]
cool, I will not proceed with this, I wasn't aware of clang-format or clang-tidy, I'll have a look at them, Thanks! 
closing
