### ISSUE TITLE
How to tell IWYU to completely exclude header from processing

### ISSUE THREAD

**Issue by kuznetsoveugene** [include-what-you-use/include-what-you-use#1056]
Hello, I am dealing with a circular dependency issue with IWYU due to the 3rd party code.
[json\autolink.h](https://github.com/oftc/jsoncpp/blob/master/include/json/autolink.h ) file from is included in one of my source file.

Inside main.cpp
`
#include json.h // which includes autolink.h
`

When I run IWYU on my source code I get error logs

`Cycle in include-mapping:
  "json/autolink.h" ->
  "json/autolink.h"`

How do I let IWYU to ignore fully everything that is inside json.h ? 
It is a 3rd party code that my source file uses and I don't really care how they have their headers arranged but I would like to not see this circle dependency to produce so many entries into the log file.

**Comment by naeimeh69** [comment]
@kimgr Do you mean that breaking cycle would fix the issue that @kuznetsoveugene have?
I have the same issue. I want iwyu to stop checking header files from third party libraries. I think it's different from include cycles. With this issue we need to somehow exclude a directory from iwyu checks.

**Comment by kimgr** [comment]
@naeimeh69 Yes, kind-of. There was a bug in IWYU earlier, where it spontaneously generated cycles in include mappings. You can read all about it in #424. Since this has been fixed, and this issue is closed, let's not mix it up with other third-party concerns.
