### ISSUE TITLE
Is it possible remove only unused include?

### ISSUE THREAD

**Issue by chouzz** [include-what-you-use/include-what-you-use#1076]
For small projects, `iwyu`  may let include more cleaner, but for large projects, `iwyu` will tell user remove one include and add lots of extra `includes` because the source file usually very complex for some history problem, is it possible make `iwyu` only remove unused include?

Also, this make me thought another problem, the message from iwyu is not clear. For example: 

`iwyu` tell me that I should **remove** `a.h` and `b.h` and **add** `c.h` and `d.h`,  there is no detailed reasons for remove includes. This could be multiple situations:
- `a.h` is removed because we can use `c.h` and `d.h` directly.
- `b.h` is removed because we never use it.

so even iwyu tell me which includes should be removed, it didn't tell me why it should be removed. 

Any ideas about how to remove only unused includes?

**Comment by danielh2942** [comment]
in your *.imp file add public-public mappings

I.e

```
[
{ include: [ "<c.h>", public, "<a.h>", public ] },
{ include: [ "<d.h>", public, "<a.h>", public ] }
]
```

this basically says that it's okay to get the symbols from c.h and d.h from a.h

**Comment by chouzz** [comment]
> in your *.imp file add public-public mappings
> 
> I.e
> 
> ```
> [
> { include: [ "<c.h>", public, "<a.h>", public ] },
> { include: [ "<d.h>", public, "<a.h>", public ] }
> ]
> ```
> 
> this basically says that it's okay to get the symbols from c.h and d.h from a.h without telling anything that directly includes c.h or d.h to replace it with a.h (As a heads up the brackets matter in the imp file, if you want to use quotations, have \" in place of the angled brackets)

Thanks your reply. It may works in this file, but I have multiple extreme large projects, I think I can't do it in every files and every projects. I can get compile commands.json files for these large projects, but the requirements need to remove only unused includes, I would like to fork iwyu and implement this besed on it, the basic idea is to add an extra option, this option will remove only unused includes, but I am not sure it is a good idea.

**Comment by parsifal-47** [comment]
@chouzz I have the same experience with this tool, however, I think you can generate mappings with minimal additional effort. You just need to go over all your includes and list their inner includes as "public". I am going to give it a try.

**Comment by parsifal-47** [comment]
it worked, what I did is:
1. make the first round of corrections and substitute all includes as advised.
2. go over ".h" files and mark them as public for their internal includes
3. make another round of corrections using the mapping from "2"

but for large project the amount of false forward declarations is significant, needs additional replacements and corrections, cannot be used continuously
