### ISSUE TITLE
Feature Request: Support for CMake 3.24.0 CMAKE_VERIFY_INTERFACE_HEADER_SETS

### ISSUE THREAD

**Issue by danielh2942** [include-what-you-use/include-what-you-use#1082]
I have been using the new CMake ```VERIFY_INTERFACE_HEADER_SETS``` argument as I am trying to get headers to have the correct includes

the way it works is by creating a new target
```targetname_verify_interface_header_sets``` where each header is given a sourcefile of the pattern ```headername.h.cxx```

I ran IWYU on this new target and all I got was
```
/path/to/lib/target_verify_interface_header_sets/target/foo.h.cxx should add these lines:

/path/to/lib/target_verify_interface_header_sets/target/foo.h.cxx should remove these lines:
- #include <target/foo.h>  // lines 1-1

The full include-list for /path/to/lib/target_verify_interface_header_sets/target/foo.h.cxx:
---
```
there was no advice whatsoever given to the headers
is there some argument I'm missing? 
my invocation is as follows
```
/usr/local/bin/iwyu_tool.py \
    --jobs $(nproc)         \
    -p ${BUILD_DIR}     \
    -- -Xiwyu --mapping_file=/path/mappings.imp \
    -Xiwyu --keep="pch.*" \
    -Xiwyu --cxx17ns \
    -Xiwyu --quoted_includes_first \
    -Xiwyu --update_comments \
    -Xiwyu --comment_style="long" \
    -Xiwyu --max_line_length=120
```

Sorry if this is a silly question/request that is down to me using a misconfigured iwyu instance
thanks in advance!

**Comment by kimgr** [comment]
What is `VERIFY_INTERFACE_HEADER_SETS` supposed to do? Does it just generate an empty `.cxx` file containing include directives for the headers to be verified (which shows that they can compile stand-alone, I suppose)?

If so, there's no need to run IWYU on these source files -- they never use any symbols, and so all `#include`s will be suggested for removal. But maybe I'm misunderstanding what's going on here.

**Comment by danielh2942** [comment]
If I added some functionality to iwyu_tool.py that requires an arg like ```--header_verification``` that detects if a file is in the form ```filename.h.cxx``` and runs analysis on ```filename.h``` instead of that, would that be a good idea?

**Comment by kimgr** [comment]
It seems to me like this feature in CMake is orthogonal to IWYU. The recommended way to use IWYU here is to run it on `filename.h` with the appropriate flags to recognize the language (e.g. `-x c++`). I don't think we should code CMake-isms into IWYU.

There is an IWYU mode in CMake, though, I wonder if it would make more sense to teach that to invoke IWYU the right way for header-set-generated `.cxx` files?

**Comment by danielh2942** [comment]
Good point. I'll try investigate it and see what I can do! thank you!

**Comment by danielh2942** [comment]
Adding on the CMake Side (link: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7762) closing.

**Comment by kimgr** [comment]
Very cool, thanks for following up!
