### ISSUE TITLE
begin_keep

### ISSUE THREAD

**Issue by FStefanni** [include-what-you-use/include-what-you-use#1095]
Hi,

I like to suggest to support a new couple of pragmas:
* `begin_keep`
* `end_keep`

The meaning should be to force keeping of includes between the two pragmas.
This is useful in cases like libraries development: usually there are some headers which just include other ones, to provide the implementation to the library users, e.g.:
``` c++
// header mylib.hpp
#include "MyClass1.hpp"
#include "MyClass2.hpp"
...
```
Currently the only way to suppress the warnings is to insert `// IWYU pragma: keep` in each line, which is not very ergonomic.
With the proposed feature we could instead write:
``` c++
// header mylib.hpp
// IWYU pragma: begin_keep
#include "MyClass1.hpp"
#include "MyClass2.hpp"
...
// IWYU pragma: end_keep
```
Regards

**Comment by kimgr** [comment]
That sounds like a reasonable extension. I guess you could model it on `begin_exports` and `end_exports`. Do you want to take a stab at a patch?

**Comment by FStefanni** [comment]
Hi,

sorry but I have no time to work on this.

Regards

**Comment by danielh2942** [comment]
@FStefanni I implemented the request if you want to have a look at it (It currently won't build as there's another PR I have open that it depends on to fix the CI)

**Comment by FStefanni** [comment]
Hi @danielh2942,

thank you for the pr, great work. 
Just giving a quick check it seems to do exactly what we need (I do not know IWYU internals).

I hope this will be included asap.

Regards.

**Comment by kimgr** [comment]
#1129 is now merged, closing this.
