### ISSUE TITLE
Python3 version of fix_includes.py

### ISSUE THREAD

**Issue by hemberger** [include-what-you-use/include-what-you-use#1096]
Some OSes are no longer shipping with Python2. Would a PR converting `fix_includes.py` to Python3 be welcome? If yes, is there a preferred minimum Python3 version to support?

**Comment by kimgr** [comment]
Is there anything in particular that doesn't work with python3? I did some cross-compat work several years ago, so I was hoping it would still work for both python2 and 3.

**Comment by hemberger** [comment]
Sorry, I should have clarified that it _does_ work with Python3 when explicitly specifying the interpreter. My main concerns are the use of deprecated modules (i.e. `optparse`) and the use of `python` in the shebang (executing as `./fix_includes.py` will fail on systems that either don't provide Python2 or that only link Python2 to `python2`).

At the very least, changing the shebang from `python` to `python3` would improve its usability without sacrificing Python2 compatibility.

I would expect the number of Python2 users to be vanishingly small at this point, but I understand if you'd prefer to wait to migrate until the deprecated modules are actually removed in the latest stable Python3.

**Comment by kimgr** [comment]
To start with, I think it would make sense to switch from optparse to argparse, if that's the breaking point.

Switching the shebang to python3 will break py2-only systems. But if there's a choice between working in general and working for both, we can definitely abandon py2.

**Comment by hemberger** [comment]
> Switching the shebang to python3 will break py2-only systems.

I don't think changing the shebang will interfere with python2-only systems, so long as they are executing it with the python interpreter instead of the shell (since the shebang is ignored when running, e.g., `python2 fix_includes.py`). This is equivalent to the current status for python3-only systems, where you _have_ to run `python3 fix_includes.py`.

**Comment by kimgr** [comment]
Yeah, that sounds like the right tradeoff. Is optparse still in the standard lib for py3 or would  we have to upgrade to argparse (which is probably about time anyway)?

**Comment by hemberger** [comment]
Even though `optparse` was deprecated in python 3.2, it is still in the standard lib (and I have no insight into when it will be removed). The `argparse` replacement was added in python 3.2 as well, so switching to that would require dropping support for any versions prior to 3.2.

If you'd like me to make a PR for any of the changes we've discussed, just let me know. Thanks for taking the time to discuss!

**Comment by kimgr** [comment]
`argparse` was backported to python 2.7 when it was released for 3.2, and I think it would be reasonable to require 2.7 for py2 stragglers.

**Comment by kimgr** [comment]
> If you'd like me to make a PR for any of the changes we've discussed, just let me know.

Oh, yes, please! Unfortunately our master CI is in a bad state currently because of a breaking change in Clang, but hopefully we can review and prepare this with a broken tree. It's sufficiently unrelated that we can probably work through it.

**Comment by sethrj** [comment]
Newer versions of macOS and other Linux distributions only ship with a `python3` executable, no `python`, so the current python scripts are trading compatibility with contemporary systems for compatibility with a 3-years-unsupported Python version. I'd also be happy to submit a pull request to update the shebangs :) 

If we wanted to be fancy, we could also use CMake to inject the shebang on installation based on the found python version—but I think that's overkill given the increasing rarity of python2-only systems.

**Comment by kimgr** [comment]
All shebangs now say `/usr/bin/env python3` and `optparse` has been replaced by `argparse`. I'm calling this done.
