### ISSUE TITLE
iwyu for clang 3.4 fatal error: 'string' file not found

### ISSUE THREAD

**Issue by libing0526** [include-what-you-use/include-what-you-use#1117]
in clang 3.4，iwyu reports an error：`'string' file not found：#include <string>。`

arch is centos x86_64，gcc，g++ is normal：
```
**[root@36b7a7a697b2 build4.0]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.9.4/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib --enable-libstdcxx-allocator --enable-threads --enable-libstdcxx-threads --enable-long-long --enable-threads=posix --enable-tls --enable-libsanitizer --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 4.9.4 (GCC) 

[root@36b7a7a697b2 build4.0]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.9.4/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib --enable-libstdcxx-allocator --enable-threads --enable-libstdcxx-threads --enable-long-long --enable-threads=posix --enable-tls --enable-libsanitizer --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 4.9.4 (GCC) 
**
```
who can tell me why？thanks。

**Comment by libing0526** [comment]
> (I edited the original report to make it easier to read)
> 
> Clang 3.4 is almost 10 years old, so I don't have it fresh in my head :-). It looks like you're in a docker container -- could you try and install Clang 3.4 in the container and see if it has similar trouble finding the GCC headers? I seem to recall there was some compatibility issue there back then.

yes，it's in a docker container. I install Clang 3.4 by source code。
thanks for your answer。I use clang++ compile a c++ program，it reports same error。so it seems like my gcc environment is bad。after i reinstall gcc，it works ok。

**Comment by kimgr** [comment]
Thanks for the update!
