### ISSUE TITLE
Assertion failed: Val && "isa<> used on a null pointer" on dependant template alias

### ISSUE THREAD

**Issue by mous16** [include-what-you-use/include-what-you-use#1140]
include-what-you-use crashes when analyzing the following minum example.
```C++
template<int value, typename Type>
struct ClassValueType
{ };

template<int value>
struct ClassValue
{
    template<typename Type>
    using ClassType= ClassValueType<value, Type>;
};

template<template<typename> typename TemplateClassType>
struct FinalType
{
    static void run() { TemplateClassType<int> instance{}; }
};

template<int value>
void test()
{
    using Type= FinalType<ClassValue<value>::template ClassType>;
    Type::run();
}

int main()
{
    test<0>();
}
```
I've tried it on Windows, with a custom build of LLVM 15.0.5 and IWYU 0.19.

The analysis terminates with the following error:
```
test.cpp:22:55: (8, fwd decl) [ TemplateName ] ClassValue<value>::template ClassType
Assertion failed: Val && "isa<> used on a null pointer", file C:\Users\a00550533\AppData\Local\llvm\include\llvm/Support/Casting.h, line 109
```
[Here](https://github.com/include-what-you-use/include-what-you-use/files/10041558/iwyu_out.txt) you can find full IWYU output in verbose mode. 

I cannot build IWYU nor LLVM in debug mode right now, but after some investigation I realized the assertion is emitted when reaching `iwyu.cc:1532`:
```C++
    if (const auto* shadow_decl = dyn_cast<UsingShadowDecl>(used_decl)) {
```
I unfortunately have a really low understanding of LLVM APIs, but I found out that substituting `dyn_cast` with `dyn_cast_or_null` let IWYU avoid the assertion, and continue to the end of the analysis.

I'm really not able to say if this is a valid fix.

**Comment by kimgr** [comment]
Thanks! It seems like a reasonable fix, but it might mask another problem -- I guess my main question is: why is `used_decl` null here?

Thanks for the self-contained repro, it should be possible to answer that question with that and some debug logging.

**Comment by kimgr** [comment]
FWIW, we come from here when `ReportDeclUse` is called with a null decl: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu.cc#L4138.

The template name kind is a dependent template here, so I think that's why we can't resolve a decl. I think that should probably be checked in this method somehow, but I need to think about that a little more.

**Comment by kimgr** [comment]
I couldn't come up with anything fancier than https://github.com/include-what-you-use/include-what-you-use/pull/1148. Let me know if that works for you.

**Comment by kimgr** [comment]
Fixed as of https://github.com/include-what-you-use/include-what-you-use/commit/68646a5efd4d52aa615ddda1a7ff874b195a93df
