### ISSUE TITLE
Compile failure when build as part of LLVM

### ISSUE THREAD

**Issue by xis19** [include-what-you-use/include-what-you-use#1153]
When using branch `clang_15`, commit 7f0b6c304acf69c42bb7f6e03c63f836924cb7e0, and build iwyu together with LLVM using the following command:

```
cmake -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS=clang -DLLVM_EXTERNAL_PROJECTS=iwyu -DLLVM_EXTERNAL_IWYU_SOURCE_DIR=/path/to/iwyu /path/to/llvm-project/llvm
```

I am seeing the following error:

```
/root/include-what-you-use/iwyu_preprocessor.h:209:72: error: non-virtual member function marked 'override' hides virtual member function
                          clang::SrcMgr::CharacteristicKind file_type) override;
                                                                       ^
/root/llvm-project/llvm/../clang/include/clang/Lex/PPCallbacks.h:122:16: note: hidden overloaded virtual function 'clang::PPCallbacks::InclusionDirective' declared here: type mismatch at 6th parameter ('const clang::FileEntry *' vs 'llvm::Optional<clang::FileEntryRef>')
  virtual void InclusionDirective(SourceLocation HashLoc,
               ^
1 error generated.
```

**Comment by xis19** [comment]
Removing the `override` fixes the compile.

**Comment by kimgr** [comment]
There's a compatibility table in the README. What version/revision is your LLVM checkout?

This particular issue was fixed a while ago: https://github.com/include-what-you-use/include-what-you-use/commit/046ca2238054eeb6817f8d6fa3735c8782e3a511

Presumably for clang 14, so if your LLVM tree is at an older rev, you need the corresponding IWYU branch.

**Comment by kimgr** [comment]
(it could have changed again on llvm master, of course)

**Comment by xis19** [comment]
@kimgr  -- I am using clang 15.0 git head, together with iwyu clang-15 branch

**Comment by kimgr** [comment]
Prove it to me :)

Here are the respective git tags I would expect you to be on:
```
.../llvm-project$ git describe
llvmorg-15.0.0

.../include-what-you-use$ git describe
0.19
```

And you said you did:
```
cmake -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS=clang \
    -DLLVM_EXTERNAL_PROJECTS=iwyu -DLLVM_EXTERNAL_IWYU_SOURCE_DIR=/path/to/iwyu \
     /path/to/llvm-project/llvm
```
Did you explicitly pass `/path/to/iwyu` and `/path/to/llvm-project/llvm`, or the actual paths? What did CMake say in terms of IWYU?

**Comment by Bu11etmagnet** [comment]
> Removing the `override` fixes the compile.

That sounds like the wrong fix. The code will compile and not work correctly, because the function will not be called for a base class.

**Comment by xis19** [comment]
> > Removing the `override` fixes the compile.
> 
> That sounds like the wrong fix. The code will compile and not work correctly, because the function will not be called for a base class.

I agree. Yet I am a user not developer, so it seems making it compile is the priority.

**Comment by xis19** [comment]
> Prove it to me :)
> 
> Here are the respective git tags I would expect you to be on:
> 
> ```
> .../llvm-project$ git describe
> llvmorg-15.0.0
> 
> .../include-what-you-use$ git describe
> 0.19
> ```
> 
> And you said you did:
> 
> ```
> cmake -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS=clang \
>     -DLLVM_EXTERNAL_PROJECTS=iwyu -DLLVM_EXTERNAL_IWYU_SOURCE_DIR=/path/to/iwyu \
>      /path/to/llvm-project/llvm
> ```
> 
> Did you explicitly pass `/path/to/iwyu` and `/path/to/llvm-project/llvm`, or the actual paths? What did CMake say in terms of IWYU?

I was using the right branch for llvm, which is 15.0.6 but it seems my iwyu branch is messed up. After resetting to clang_15 release I was able to compile the code properly. Sorry for the confusion.

**Comment by kimgr** [comment]
Thanks for confirming!
