### ISSUE TITLE
The difference between running on single source file and using with a compilation database

### ISSUE THREAD

**Issue by didebughu** [include-what-you-use/include-what-you-use#1169]
First of all thanks to the IWYU team
I recently used IWYU for some simple c/c++ projects 
by running on each source file or using with a compilation database
and the result seems to be the same
I think there is a difference between the two but I don't know the exact difference
I want to know the difference

**Comment by kimgr** [comment]
There is no difference :)

The compilation database simply contains compiler flags for every source file, so running `include-what-you-use` with a set of compiler flags for file `f.cpp` is the same as running `iwyu_tool.py` with a compilation database for `f.cpp`.

**Comment by didebughu** [comment]
thank you very much
