### ISSUE TITLE
 using iwyu by camke makes my project complie failed，just show nijia subcommand faild 

### ISSUE THREAD

**Issue by Qi-Ming** [include-what-you-use/include-what-you-use#1183]

**Comment by Qi-Ming** [comment]
i saw iwyu warning has cycle in projects，is that leads to complile failed？
![image](https://user-images.githubusercontent.com/34115479/212851811-1e077dc8-0b8b-443b-88bb-9a7a6ad174f3.png)

**Comment by kimgr** [comment]
This was recently [fixed on mainline][1], but is not yet in a public release. See also #424.

[1]: https://github.com/include-what-you-use/include-what-you-use/commit/3511ccdedd8cd33b68fa9a7fa9b2b3048e88a7bd

**Comment by kimgr** [comment]
I'm going to close this as fixed.
