### ISSUE TITLE
fail build IWYU 0.19 with llvm-15

### ISSUE THREAD

**Issue by acababaev** [include-what-you-use/include-what-you-use#1187]
OS: ubuntu:20.04
llvm-15 downloaded from llvm releases and copy to /usr/lib/llvm-15
iwyu 0.19 downloaded from this rep releases

commands:
cd include-what-you-use-0.19; \
mkdir build && cd build; \
cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/usr/lib/llvm-15 ..; \
make

getting error at last linking stage:

```
/usr/bin/ld: /usr/lib/llvm-15/lib/libLLVMOption.a(ArgList.cpp.o): Relocations in generic ELF (EM: 21)
... lot of same messages...
/usr/bin/ld: /usr/lib/llvm-15/lib/libLLVMOption.a(ArgList.cpp.o): Relocations in generic ELF (EM: 21)

/usr/bin/ld: /usr/lib/llvm-15/lib/libLLVMOption.a: error adding symbols: file in wrong format
```

tried to change linkers to gols, getting this error:
`/usr/bin/ld.gold: critical error: /home/artem/Documents/llvm-15/lib/libLLVMOption.a(ArgList.cpp.o): unsupported ELF machine number 21
`

and with lld also didnt work. How to make it work?

UPD
building master include-what-you-use with clang-16 same problem

**Comment by kimgr** [comment]
ELF machine 21 appears to be PowerPC64 according to https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_header. I'm guessing you're not on a PPC-64 system, but accidentally downloaded the wrong LLVM libraries or something?

**Comment by acababaev** [comment]
yes, sorry for that stupid question. I simple get last release llvm-15.07, but for some reason in this version missing package clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz, which was what I needed. I didn't notice his absence and downloaded the most similar one. Thank you so much, putting a star :):)

**Comment by kimgr** [comment]
Glad to hear it worked out! :sweat_smile:
