### ISSUE TITLE
C++20?

### ISSUE THREAD

**Issue by PaltryProgrammer** [include-what-you-use/include-what-you-use#1190]
the code below results in errors shown below  . does iwyu not support C++20?

c:\users\bpwlo\source\repos\simpleCode.cpp:5:22: error: use of undeclared identifier 'std'
        auto _is_integral = std::is_integral_v<int>;
                            ^
c:\users\bpwlo\source\repos\simpleCode.cpp:5:44: error: expected '(' for function-style cast or type construction
        auto _is_integral = std::is_integral_v<int>;
                                               ~~~^
c:\users\bpwlo\source\repos\simpleCode.cpp:5:45: error: expected expression
        auto _is_integral = std::is_integral_v<int>;
                                                   ^

```
#include <concepts>

int main()
{
	auto _is_integral = std::is_integral_v<int>;
	return 0;
}
```

**Comment by bolshakov-a** [comment]
Have you passed `-std=c++20` clang (which underlies IWYU actually) flag on the command line?

**Comment by PaltryProgrammer** [comment]
Yes . below is the full session .
```
go

C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>SET INCLUDE=C:\Users\bpwlo\source\boost_1_81_0;C:\Users\bpwlo\source\repos\bpwSoftware;C:\Users\bpwlo\source\repos;C:\Users\bpwlo\source\repos\bpwSoftware\;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\include;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\atlmfc\include;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared;

C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um;
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>rem include-what-you-use -std=c++20 c:\users\bpwlo\source\repos\bpwSoftware\includes_setup.cpp

C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>include-what-you-use -std=c++20 c:\users\bpwlo\source\repos\simplecode.cpp
c:\users\bpwlo\source\repos\simplecode.cpp:5:18: error: use of undeclared identifier 'std'
        auto _current = std::source_location::current();
                        ^
```

**Comment by kimgr** [comment]
I'm not sure which standard library clang (and thereby iwyu) uses in the msvc environment you've set up there. What does the `<concepts>` header look like?

One completely unfounded theory is that the msvc concepts header preprocesses to nothing if the compiler is not msvc (but clang should emulate msvc, so not sure how that works happen).

**Comment by kimgr** [comment]
Also, which version of iwyu/clang? Mainline?

**Comment by Bu11etmagnet** [comment]
Since iwyu supports `-std`, it should also support `-save-temps`. In that case, no guesses would be needed as to what the headers expand to.

**Comment by kimgr** [comment]
Unfortunately not: https://github.com/include-what-you-use/include-what-you-use/commit/eee6d6a1994d1b2e70bd7c20e8e271318ad28921

**Comment by bolshakov-a** [comment]
I have clang and IWYU built with MSVC (hence, they use Microsoft standard library by default). Here is an output on my system:
```
PS C:\Users\bolsh\source\repos\Project8> ..\iwyu\build\bin\RelWithDebInfo\include-what-you-use.exe .\Source6.cpp
.\Source6.cpp:5:22: error: use of undeclared identifier 'std'
        auto _is_integral = std::is_integral_v<int>;
                            ^
.\Source6.cpp:5:44: error: expected '(' for function-style cast or type construction
        auto _is_integral = std::is_integral_v<int>;
                                               ~~~^
.\Source6.cpp:5:45: error: expected expression
        auto _is_integral = std::is_integral_v<int>;
                                                   ^
PS C:\Users\bolsh\source\repos\Project8> ..\iwyu\build\bin\RelWithDebInfo\include-what-you-use.exe -std=c++20 .\Source6.cpp

Source6.cpp should add these lines:
#include <xtr1common>  // for is_integral_v

Source6.cpp should remove these lines:
- #include <concepts>  // lines 1-1

The full include-list for Source6.cpp:
#include <xtr1common>  // for is_integral_v
---
```

**Comment by bolshakov-a** [comment]
`-isystem` option may be helpful.

**Comment by kimgr** [comment]
@PaltryProgrammer A couple of thoughts:

* You could use `include-what-you-use -v -std=c++20 yourfile.cpp` to have IWYU/Clang print all the arguments forwarded to the frontend (`clang invocation:`)
* Looks like your batch file is broken, the `SET INCLUDE=...` line appears to be wrapped before the last couple of SDK headers. I don't think that has any impact on this behavior, but might be nice to fix
* Do you have `clang` built and available as well? What does `clang -fsyntax-only -std=c++20 yourfile.cpp` say?

**Comment by PaltryProgrammer** [comment]
clang version 17.0.0
Target: x86_64-pc-windows-msvc

msvc `concepts` has these __clang__ pre-preprocessor dependent sections
```
// clang-format off
template <class _Ty1, class _Ty2>
concept _Same_impl = // Must be a distinct concept to provide symmetric subsumption for same_as
#ifdef __clang__
    __is_same(_Ty1, _Ty2);
#else // ^^^ use intrinsic / no intrinsic vvv
    is_same_v<_Ty1, _Ty2>;
#endif // __clang__

_EXPORT_STD template <class _Ty1, class _Ty2>
concept same_as = _Same_impl<_Ty1, _Ty2> && _Same_impl<_Ty2, _Ty1>;

_EXPORT_STD template <class _Derived, class _Base>
concept derived_from = __is_base_of(_Base, _Derived)
    && __is_convertible_to(const volatile _Derived*, const volatile _Base*);

_EXPORT_STD template <class _From, class _To>
#if !defined(__EDG__) && !defined(__clang__) // TRANSITION, DevCom-1627396
concept convertible_to = is_convertible_v<_From, _To>
#else // ^^^ workaround / no workaround vvv
concept convertible_to = __is_convertible_to(_From, _To)
#endif // ^^^ no workaround ^^^

```
https://github.com/include-what-you-use/include-what-you-use/issues/1190#issuecomment-1435968488
Yes i missed two include directories  after repair the session seems succcessful as shown below however i do not understand why it insists on replacing concepts w/ xtrcommon
![apparently successful session](https://user-images.githubusercontent.com/48535920/219958735-1854fcd4-4779-48da-a663-0ab8cb1826e6.png)

**Comment by bolshakov-a** [comment]
> i do not understand why it insists on replacing concepts w/ xtrcommon

It is because `std::is_integral_v` is really placed into `<xtr1common>` in Microsoft implementation. In general, you need [mapping files](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md) for external libraries which map private symbols and headers to public headers. For the standard library, IWYU has some hard-coded mappings for libstdcxx and libcxx implementations. However, there should be an additional standard symbol mapping file shipped with IWYU, which would work with all the implementations, I think. Maybe, somebody will write it some day...

Btw, `std::is_integral_v` is not a concept, but variable template. The IWYU check will probably pass if you replace it with `std::integral`.

**Comment by PaltryProgrammer** [comment]
thank you for informing re/ std::is_integral_v . i apologize for my carelessness

**Comment by bolshakov-a** [comment]
You're welcome! It is acually just a luck that Microsoft defines `std::integral` concept in `<concepts>` header. The need of writing mapping files is probably the most inconvenience with IWYU, but it seems to be inevitable. [Here](https://github.com/Wumpf/iwyu_for_vs_includetoolbox/blob/master/msvc.imp) is a billet for MSVC, but it is obsolete.

**Comment by kimgr** [comment]
Glad to hear that got sorted anyway. Closing.
