### ISSUE TITLE
Operate IWYU for a project

### ISSUE THREAD

**Issue by 988158** [include-what-you-use/include-what-you-use#1191]
Hello:
So far, I have managed to operate iwyu on a single cpp file using the following command:

> $ include-what-you-use $CXXFLAGS test.cpp

However, now I want to perform analysis on my project. I have written a script in python that selects all cpp and h files in my project:
```
import os
import shutil

def findF(path, list):
    for files in os.listdir(path):
        tmpPath = os.path.join(path, files)  
        if os.path.isdir(tmpPath): #recurse the function if the path is a directory
            findF(tmpPath, list)
        elif os.path.isfile(tmpPath): # find the cpp and h file
            if tmpPath.endswith('.cpp')|tmpPath.endswith('.h'):
                list.append(files)
                #print("cpp file & h file: " + files)

t = []
findF('E:\\intern\\mrtrix3', t)
print(t)
```

Now this script will return a list that contains a bunch of file names, for example t=['test1.cpp', 'test2.cpp', 'test3.cpp'.....'test99.cpp']
I wonder how can I apply such list to iwyu so that iwyu can iterates these files, and perform analysis? 

I hope my inquiry makes sense. Thank you!

**Comment by firewave** [comment]
See https://github.com/include-what-you-use/include-what-you-use#how-to-run

**Comment by kimgr** [comment]
Generally, `include-what-you-use` acts as a replacement for your compiler. It needs to be invoked with the same arguments as your compiler normally would, which is why we encourage calling it from your build system.

I don't know if your project _has_ a build system, but I'm guessing it does. If you can't convince it to call `include-what-you-use` instead of your compiler, see if you can extract the compiler arguments from it, and save them in some kind of map from filename -> arguments.

IWYU supports the Compilation Database format, so if you can generate that, you can use `iwyu_tool.py` to drive `include-what-you-use`.

P.S.: check out `os.walk`: https://docs.python.org/3/library/os.html#os.walk

**Comment by PaltryProgrammer** [comment]
i utilize a command line batch file to execute iwyu . works fine . it sets up the build environment as needed . no doubt your code can create a batch file and execute it as well . -Best

**Comment by 988158** [comment]
> Generally, `include-what-you-use` acts as a replacement for your compiler. It needs to be invoked with the same arguments as your compiler normally would, which is why we encourage calling it from your build system.
> 
> I don't know if your project _has_ a build system, but I'm guessing it does. If you can't convince it to call `include-what-you-use` instead of your compiler, see if you can extract the compiler arguments from it, and save them in some kind of map from filename -> arguments.
> 
> IWYU supports the Compilation Database format, so if you can generate that, you can use `iwyu_tool.py` to drive `include-what-you-use`.
> 
> P.S.: check out `os.walk`: https://docs.python.org/3/library/os.html#os.walk

Thank you so much for your reply! Now I have successfully deployed IWYU on my project. Now, how could I save the output of IWYU. Does iwyu have a log file for its analysis?

**Comment by kimgr** [comment]
As far as I can tell, iwyu writes all its output to stderr, so you'd capture that and/or redirect it to a file. How to do that depends a lot on how you launch include-what-you-use, but a web search should help you figure out how to do it in your context.

**Comment by kimgr** [comment]
There does not appear to be anything we need to do in the IWYU project here. Closing. Glad to hear it worked out for you!
