### ISSUE TITLE
request assistance re/ fix_includes.py

### ISSUE THREAD

**Issue by PaltryProgrammer** [include-what-you-use/include-what-you-use#1198]
`include-what-you-use` (iwyu) is running on my Windows system . i am unable to properly execute `fix_includes.py` . i have no knowledge of python . python is installed however . i have attempted from the command line `py < fix_includes.py` but received the message `IWYU edited 0 files on your behalf.` i do not understand how `fix_includes.py` communicates w/  iwyu . i have attempted` iwyu [options and source files as needed] > iwyu_out.txt` w/ the intention of attempting `py < fix_includes.py < iwyu_out.txt` but iwyu.txt is empty post iwyu processing . i seek your kind assistance . Think You Kindly

**Comment by kimgr** [comment]
> iwyu [options and source files as needed] > iwyu_out.txt

IWYU writes all its output to stderr, so you can try `iwyu your args 2>&1 > iwyu_out.txt`.

The `2>&1` spell redirects stderr to stdout, which is then captured in the output file. I think that should work on windows too (otherwise try googling for stderr/stdout redirection, I know it's possible).

Not sure if that's the whole story, but worth a shot.

**Comment by PaltryProgrammer** [comment]
Thank You for You Kind Assistance it succeeded . the iwyu output file was successfully redirected to . however i do not know how to direct fix_includes.py to process it . i attempted as shown below :

```
C:\Users\bpwlo\git\include-what-you-use>py < fix_includes.py iwyu.txt
  File "C:\Users\bpwlo\git\include-what-you-use\iwyu.txt", line 1
    clang version 17.0.0
          ^^^^^^^
SyntaxError: invalid syntax
```

i seek again your kind and generous assistance Thank You Kindly

**Comment by kimgr** [comment]
Can you share the arguments you're passing to iwyu? It looks like you have `-v` in there, which prints a lot of detailed information that `fix_includes.py` can't understand.

**Comment by PaltryProgrammer** [comment]
Greetings Kind Regards Thank You for your Kind and Generous assistance i removed the -v option but still received a syntax error upon processing by fix_includes.py as shown below . below is the entire session .
```
C:\Users\bpwlo\git\include-what-you-use>cd build
C:\Users\bpwlo\git\include-what-you-use\build>cd bin
C:\Users\bpwlo\git\include-what-you-use\build\bin>cd debug
C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>if exist iwyu.txt del iwyu.txt
C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>include-what-you-use -fsyntax-only -std=c++20 -D__cpp_consteval -D_DEBUG -D_CONSOLE c:\users\bpwlo\source\repos\bpwSoftware\includes_setup.cpp  2>iwyu.txt
C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>type iwyu.txt
```
below is iwyu.txt i.e. output of iwyu as redirected from stderr .

```
In file included from c:\users\bpwlo\source\repos\bpwSoftware\includes_setup.cpp:4:

**... many CLang warning messages ...**

c:/users/bpwlo/source/repos/bpwSoftware/includes_setup.cpp should add these lines:

c:/users/bpwlo/source/repos/bpwSoftware/includes_setup.cpp should remove these lines:

**... a lengthy list of #includes to remove ...**

The full include-list for c:/users/bpwlo/source/repos/bpwSoftware/includes_setup.cpp:
---
```
here `py < ..\..\..\fix_includes.py iwyu.txt` is invoked however the console screen displays as below w/ syntax error message.
```
C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug>py  iwyu.txt 0<..\..\..\fix_includes.py
  File "C:\Users\bpwlo\git\include-what-you-use\build\bin\Debug\iwyu.txt", line 1
    In file included from c:\users\bpwlo\source\repos\bpwSoftware\includes_setup.cpp:4:
       ^^^^
SyntaxError: invalid syntax
```

**Comment by PaltryProgrammer** [comment]
thank you kindly for your continued assistance . upon attempting `py fix_includes.py < iwyu.txt` response was `Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.` please note `py  iwyu.txt 0<..\..\..\fix_includes.py` was not entered rather upon entering `py < ..\..\..\fix_includes.py iwyu.txt` via a batch file the console output was `py  iwyu.txt 0<..\..\..\fix_includes.py`

**Comment by kimgr** [comment]
I think they mean the same thing, i.e. "run iwyu.txt through py, and send fix_includes.py to stdin".

You can probably figure out your windows python issues using your favorite search engine, I don't know how that environment works anymore.

**Comment by kimgr** [comment]
I don't think there's much more we can do here. Closing.
