### ISSUE TITLE
False positives for <bits/chrono.h> and <ext/alloc_traits.h>

### ISSUE THREAD

**Issue by mgierlings** [include-what-you-use/include-what-you-use#1199]
`iwyu` shipped with the current (*)buntu LTS suggests to include `<bits/chrono.h>` despite an `#include <chrono>` directive being present. Further accessing a `std::vector<std::string>` via the index operator causes `iwyu` to demand the inclusion of `<ext/alloc_traits.h>`

**Version information**
```
iwyu --version
include-what-you-use 0.17 based on Ubuntu clang version 13.0.1-2ubuntu2.1
```

**Reproduction**
- Create a file `iwyu.cpp` with the following content:
```
#include <string>
#include <vector>
#include <chrono>

int main()
{
	std::chrono::time_point<std::chrono::system_clock> t { std::chrono::system_clock::now() };
	std::vector<std::string> v {""};
	v[0] = "a";
	return 0;
}
```
- Compile with `iwyu ./iwyu.cpp`

**Expected behavior**: No problems reported
**Observed behaviour**: `iwyu` produces the following suggestion:
```
iwyu.cpp should add these lines:
#include <bits/chrono.h>       // for system_clock, time_point
#include <ext/alloc_traits.h>  // for __alloc_traits<>::value_type

iwyu.cpp should remove these lines:
- #include <chrono>  // lines 3-3

The full include-list for iwyu.cpp:
#include <bits/chrono.h>       // for system_clock, time_point
#include <ext/alloc_traits.h>  // for __alloc_traits<>::value_type
#include <string>              // for string, basic_string
#include <vector>              // for vector
```

**Question**
Is there any workaround available to bypass the issue until a fix is available? I've unsuccessfully been looking for something like an `--ignore` option which works opposite to `--keep` and never suggests headers matching a given glob (e.g. `*/chrono.h`, `*/alloc_traits.h`).

**Comment by kimgr** [comment]
You've managed to hit two bugs almost verbatim that are already reported, #1061 and #648, so I'll close this as a duplicate.You can follow the https://github.com/include-what-you-use/include-what-you-use/labels/template-spill label to track this. We're hacking away at this currently, so unless we hit a roadblock, a fix should make it into the next release.

**Comment by kimgr** [comment]
As for workarounds, maybe you could combine `// IWYU pragma: keep` for the public header with `IWYU pragma: no_include` for the private header? https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-no_include

**Comment by mgierlings** [comment]
Thanks for the swift reply. I just tried the suggested workaround. The directives do suppress the warning messages and `iwyu` terminates with with the message `(iwyu.cpp has correct #includes/fwd-decls)` unfortunately it still returns exit code `2` indicating an error. This breaks my CI pipeline because return code `0` is expected.

**Reproduction**
- Create a file iwyu.cpp with the following content:
```
// IWYU pragma: no_include <ext/alloc_traits.h>
// IWYU pragma: no_include <bits/chrono.h>
#include <string>
#include <vector>
#include <chrono> // IWYU pragma: keep

int main()
{
	std::chrono::time_point<std::chrono::system_clock> t { std::chrono::system_clock::now() };
	std::vector<std::string> v {""};
	v[0] = "a";
	return 0;
}
```
- Execute: `iwyu iwyu.cpp; echo "Exit code: $?"` 

**Expected behavior**: `iwyu` exits with return code `0`.
```
(iwyu.cpp has correct #includes/fwd-decls)
Exit code: 0
```
**Observed behaviour**: `iwyu` exits with return code `2`, indicating an error.
```
(iwyu.cpp has correct #includes/fwd-decls)
Exit code: 2
```

**Comment by kimgr** [comment]
That's the success code (unfortunately) for iwyu up until 0.17. It changed to behave more normally in 0.18.

**Comment by firewave** [comment]
It looks like the `<chrono>` issue is actually #1277.
