### ISSUE TITLE
Assembly test will fail on architectures other than x86_64

### ISSUE THREAD

**Issue by bkmgit** [include-what-you-use/include-what-you-use#1201]
The test test_ms_inline_asm will fail on architectures such as Aarch64.  It may be good to either run it if architecture is detected to be x86_64 or make it an optional test.

**Comment by kimgr** [comment]
What does `include-what-you-use --print-targets` say on your system?

Usually `clang` (and thereby IWYU) is built with support for all architectures, mine says:
```
kimgr@lardo:~/code/iwyu/include-what-you-use$ include-what-you-use --print-targets

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    m68k       - Motorola 68000 family
    mips       - MIPS (32-bit big endian)
    mips64     - MIPS (64-bit big endian)
    mips64el   - MIPS (64-bit little endian)
    mipsel     - MIPS (32-bit little endian)
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc32le    - PowerPC 32 LE
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    ve         - VE
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore
```
So it may be possible to just specify the architecture explicitly on the command-line in that test as a cheap first "solution".

**Comment by bkmgit** [comment]
On local machine
```
$ ./include-what-you-use --print-targets
  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    mips       - MIPS (32-bit big endian)
    mips64     - MIPS (64-bit big endian)
    mips64el   - MIPS (64-bit little endian)
    mipsel     - MIPS (32-bit little endian)
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc32le    - PowerPC 32 LE
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    ve         - VE
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore
error: unable to handle compilation, expected exactly one compiler job in ''
```
Am building it for Fedora in cloud, so have excluded that test for other architectures in the rpm spec file:
https://download.copr.fedorainfracloud.org/results/fed500/include-what-you-use/fedora-rawhide-i386/05587380-iwyu/iwyu.spec
Probably an issue with the flag `-fms-extensions`

The tests:
	116 - cxx.test_quoted_includes_first (Failed)
	131 - cxx.test_stl_container_provides_allocator (Failed)
fail on i386
https://download.copr.fedorainfracloud.org/results/fed500/include-what-you-use/fedora-rawhide-i386/05587284-iwyu/builder-live.log.gz

**Comment by kimgr** [comment]
What happens if you patch the test to also pass `-target=x86_64` instead?

**Comment by bkmgit** [comment]
That change works:
https://download.copr.fedorainfracloud.org/results/fed500/include-what-you-use/fedora-rawhide-x86_64/05634699-iwyu/iwyu.spec
https://copr.fedorainfracloud.org/coprs/fed500/include-what-you-use/build/5634699/
build on i386 still fails.

**Comment by kimgr** [comment]
I'm a little confused now. I just looked at what we do in IWYU main: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu.cc#L4325. As far as I can tell, that means all available targets in LLVM/Clang will be initialized. So whether we pass `--target=x86_64` or not, I would assume that target would be initialized.

Did something else change in your build, e.g. more complete Clang package or something?

I'd be happy to patch `ms_inline_asm.cc` in IWYU, but only if I can rationalize to myself why :)

**Comment by kilroyd** [comment]
Just poking on this one. The ms_inline_asm test is also failing on MacOS+M1, with a similar clang setup as above. I notice the actual error wasn't pasted above. For reference, there error I get is:

    tests/cxx/ms_inline_asm.cc:19:3: error: unsupported architecture 'arm64' for MS-style inline assembly
       19 |   __asm {
          |   ^
    ...
    tests/cxx/ms_inline_asm.cc:19: Unexpected diagnostic:
    unsupported architecture 'arm64' for MS-style inline assembly

**Comment by bkmgit** [comment]
Do not think anything else changed.  At the moment the test is excluded:
https://src.fedoraproject.org/rpms/iwyu/blob/rawhide/f/iwyu.spec#_65

**Comment by kilroyd** [comment]
This issue should be fixed now. As part of #1315 the test was annotated to require x86-64 target support
@kimgr fyi

**Comment by kimgr** [comment]
Ah, thanks! @bkmgit could you use latest master without exclusion patch for `ms_inline_asm` and verify that it works in the target environment? Or are you pinned on a released IWYU version?

**Comment by bkmgit** [comment]
Tested on Fedora Rawhide (40) which has llvm 17. Some other tests fail, but the `ms_inline_asm` seems ok:
https://kojipkgs.fedoraproject.org//work/tasks/469/108230469/build.log

**Comment by kimgr** [comment]
Thanks! Didn't get to check all failures, but it looks like most of them are due to missing `<stddef.h>`, i.e. your compiler builtin headers weren't found. If you can get them in place relative to `include-what-you-use`, you should see more representative results. Some detail here: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-install.

Alright, sounds like this issue is fixed anyway.
