### ISSUE TITLE
False positive: include required in class template declaration/definition, not in instantiation

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1210]
Hi!

I find the following false positive on master:

```cpp
// foo.h
#pragma once

template <typename T>
struct Foo 
{
    using V = typename T::value_type;
};
```

```cpp
// foo.cpp
#include "foo.h"

#include <array>

template struct Foo<std::array<float, 1U>>;
```

Run IWYU:
```
$ include-what-you-use  foo.cpp 

foo.h should add these lines:
#include <array>  // for array

foo.h should remove these lines:

The full include-list for foo.h:
#include <array>  // for array
---

(foo.cpp has correct #includes/fwd-decls)
```

Here it does not make sense that `foo.h` includes `<array>` - it's the clients that instantiate the class that must include it.

**Comment by kimgr** [comment]
I can no longer reproduce this on master, I think it's probably been fixed by one of @bolshakov-a's many template improvements. Tagging it as fixed in 0.22, thought I suspect it's already working in 0.21.

**Comment by bolshakov-a** [comment]
> I think it's probably been fixed by one of @bolshakov-a's many template improvements.

LOL

**Comment by carlosgalvezp** [comment]
Awesome, thanks for the update! Will double-check on our side :)
