### ISSUE TITLE
fix_includes deletes #include's does not comment out

### ISSUE THREAD

**Issue by PaltryProgrammer** [include-what-you-use/include-what-you-use#1211]
the result of running `fix_includes` is unused `#include` statements are deleted . i expected them to be commented out . please advise thank you kindly

**Comment by kimgr** [comment]
Oh dear, I hope you didn't lose any work!

IWYU runs with the assumption that all code is under source control, so you can revert undesirable changes easily. Maybe we should make that clearer in the documentation.

**Comment by PaltryProgrammer** [comment]
thank you for your kind assistance . i recall reading though i could not now find where the result of `fix_includes` is commenting out rather than deletion so i was surprised deletion occurred . so my inquiry is does means exist to set behavior of `fix_includes` to perform commenting out . thank you kindly

**Comment by kimgr** [comment]
No, there does not appear to be any such functionality.

And as a general rule: only run IWYU tools on files under source control, and only from a clean working tree, to make sure you don't lose changes.

**Comment by PaltryProgrammer** [comment]
thank you most kindly 😎
