### ISSUE TITLE
Request: Release compatible with LLVM 16

### ISSUE THREAD

**Issue by MehdiChinoune** [include-what-you-use/include-what-you-use#1214]
Could you please release a compatible version with LLVM-16, Maybe 0.19.1 or 0.20.0

**Comment by kimgr** [comment]
Yes, the https://github.com/include-what-you-use/include-what-you-use/milestone/16 milestone covers this. Ideally I would like to get a few more bugfixes in, but I'll try to make time for a release soon.

**Comment by kimgr** [comment]
Release is out: https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.20.
