### ISSUE TITLE
IWYU fails to compile

### ISSUE THREAD

**Issue by tiagomacarios** [include-what-you-use/include-what-you-use#1245]
I haven't compiled IWYU in a while, but the clang16 fork fails to compile when using msvc.

```
include-what-you-use\iwyu_include_picker.cc(378): error C2466: cannot allocate an array of constant size 0
```

I suggest adding `-Wzero-length-array` to the flags used to compile the project.

**Comment by bolshakov-a** [comment]
Already fixed in #1233.

**Comment by tiagomacarios** [comment]
Can someone cherry-pick that into 16?

**Comment by kimgr** [comment]
We're very conservative with backporting, as we don't have much capacity. But this seems like it completely kills MSVC compatibility for IWYU 0.20, and it was a trivial fix, so done: https://github.com/include-what-you-use/include-what-you-use/tree/clang_16.

Note that 0.20 source archives, tags, etc. are still on the original release, this commit only made it to the `clang_16` branch.
