### ISSUE TITLE
how can I use it in Xcode project to detect unused file header

### ISSUE THREAD

**Issue by PiggyChen** [include-what-you-use/include-what-you-use#1254]
I have builded LLVM and Clang by clone the project(https://github.com/llvm/llvm-project), and I successful build include-what-you-use as part of LLVM.
But I am confused how to use the include-what-you-use executable file in my Xcode project to help me detect unused include header file.
I need to change some Xcode build settings configuration to make  include-what-you-use effect?

**Comment by kimgr** [comment]
No news here for more than a month, and nothing much we can do from IWYU's side. Closing.

**Comment by shi-yan** [comment]
here is an instruction https://stackoverflow.com/a/73120984/514025 for exporting compilation database
