### ISSUE TITLE
Crash after "Handle elaborated keywords as fwd-decls" commit

### ISSUE THREAD

**Issue by StailGot** [include-what-you-use/include-what-you-use#1259]
Afterr commit "Handle elaborated keywords as fwd-decls" iwyu crashes on windows + clang-cl + pch

Seems, missing nullptr check in

https://github.com/include-what-you-use/include-what-you-use/commit/5957e2fb928d97446a3905d09e6c317960c4622e

```c++
  bool VisitElaboratedTypeLoc(ElaboratedTypeLoc type_loc) {
    if (type_loc.getTypePtr()->getKeyword() != clang::ETK_None) {
      preprocessor_info()
          .FileInfoFor(CurrentFileEntry())
          ->AddElaboratedType(type_loc);
    }
    return Base::VisitElaboratedTypeLoc(type_loc);
  }
```

Possible fix
https://github.com/StailGot/include-what-you-use/commit/ea21e2d81931b9589adbb5647f3c1fa450b9e4b7

**Comment by bolshakov-a** [comment]
Thanks, but we want rather to stop supporting IWYU invocations with PCH: https://github.com/include-what-you-use/include-what-you-use/pull/1246.

**Comment by StailGot** [comment]
Iwyu heavy used in my compile optimisation system to restore "no pch state". Project huge and legacy, so it will take a lot of time to make it "good". Pch help improve compile speed ~4 times (from 40 to 10 minutes). Drop pch support totally break it. Is any way to keep support pch via some option ?
