### ISSUE TITLE
Path/file name limit in IWYU?

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1263]
Hi! 

We believe we have found an issue where IWYU provides unexpected results on files that have a too long name / path - IWYU confuses them with other files. The problem is solved by shortening the file names. It kind of feels that IWYU is capping the file name at a given length, and by doing that some files that had a unique name receive the same truncated named.

Does IWYU have some hardcoded limit on the file name, and if so could it be extended?

Thanks!

**Comment by kimgr** [comment]
What platform is this?

**Comment by carlosgalvezp** [comment]
Ubuntu 20.04

**Comment by kimgr** [comment]
Interesting. I'm not aware of any static filename limits in IWYU, and I'd be somewhat surprised if LLVM/Clang had them. Do you know what the length cutoff point is?

**Comment by carlosgalvezp** [comment]
Looking more in detail, it seems to be our build system orchestrating the IWYU calls that is doing something fishy, nothing to do with IWYU itself. Sorry for the confusion!
