### ISSUE TITLE
IWYU and Static members

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/include-what-you-use#127]
Originally reported on Google Code with ID 127
```

There seems to be some issue on how to handle static members, when making the report.
I have attached two different cases that do the same but through different ways.

Both samples will declare a static member inside a class by forward declaring the type.
Then on the cpp of that class they will invoke some method on the static member.

1) Plain: In this sample we declare a static member directly inside ZMyTestClass by
forward declaring the type. If you run iwyu notice how it suggests to remove the forward
declaration and replace it by the include itself, while it says that the cpp is correct.
It's not needed, right?

2) ThroughMacro: This sample is closer to what I have here. We have a header that defines
some macros that are used in many classes. Some macros are used for the declaration
and some used for the definition. In those cpp where definition macros are used we
need to include the corresponding header (in this case, myutil.h). The report is suggesting
to remove myutil.h, which doesn't compile.

What do you think?
```

Reported by `dpunset` on 2014-04-14 19:54:05

<hr>
 * *Attachment: [Plain.rar](https://storage.googleapis.com/google-code-attachments/include-what-you-use/issue-127/comment-0/Plain.rar)*
 * *Attachment: [ThroughMacro.rar](https://storage.googleapis.com/google-code-attachments/include-what-you-use/issue-127/comment-0/ThroughMacro.rar)*

**Comment by kimgr** [comment]
Something messed up with locations in `<scratch space>`, I'm hoping to get it fixed. Here's the failure from badinc.cc:

    <scratch space>:254: Unexpected diagnostic:
    kI1ConstInt is defined in "tests/cxx/badinc-i1.h", which isn't directly #included.

    <scratch space>:255: Unexpected diagnostic:
    I1_Class needs a declaration, but does not provide or directly #include one.

    tests/cxx/badinc.cc:1452: Unmatched regex:
    kI1ConstInt is...*badinc-i1.h

    tests/cxx/badinc.cc:1454: Unmatched regex:
    I1_Class needs a declaration

(see http://buildbot.include-what-you-use.com:8010/builders/ubuntu-builder/builds/403/steps/test%20IWYU/logs/stdio)

**Comment by conchurnavid** [comment]
This change causes #334
