### ISSUE TITLE
Caveat in the README seems out of date. Is IWYU production status now?

### ISSUE THREAD

**Issue by dneto0** [include-what-you-use/include-what-you-use#1270]
https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#caveat  says
 

> # Caveat

>  This is alpha quality software -- at best (as of July 2018). It was originally written to work specifically in the Google source tree, and may make assumptions, or have gaps, that are immediately and embarrassingly evident in other types of code.

> While we work to get IWYU quality up, we will be stinting new features, and will prioritize reported bugs along with the many existing, known bugs. The best chance of getting a problem fixed is to submit a patch that fixes it (along with a test case that verifies the fix)!

That seems overly modest now.  If IWYU is production ready, then it should say so, even if there are *small* caveats.

I would have a hard time convincing a third party project to use IWYU with such a large caveat.

**Comment by kimgr** [comment]
I think it's still a fair characterization, even if I have used it for real commercial code bases myself in the past.

There are many, many shortcomings in IWYU, several of which we have no idea how to solve, so I think it's fair to say that it's still early stages.

It's usable for sure, but I don't think I would call it production ready.

**Comment by dneto0** [comment]
Ok, thanks for the confirmation.
