### ISSUE TITLE
Create IWYU version 0.21 to track newly-created LLVM 17 branch

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1276]
Hi!

The LLVM folks have initiated the release of LLVM 17 by creating a Release branch, and current master is now on version 18:
https://github.com/llvm/llvm-project/tree/release/17.x

It would be good to create a new tag/branch version 0.21 for IWYU to match the LLVM 17 branch.

**Comment by kimgr** [comment]
I typically do that on the first breaking change. 17 and 18 still seem to get along with IWYU mainline.

**Comment by carlosgalvezp** [comment]
Ah I see, thanks for the clarification! From a user perspective (who doesn't know the details of what breaks and what not) it's a bit unintuitive though - having a table listing the mapping between IWYU and Clang, and there is a Clang 17 release, one would expect a corresponding IWYU branch/tag to exist there, at least for consistency with previous releases. Otherwise it would seem like IWYU only supports Clang 16 and Clang trunk (18), but not 17.

**Comment by kimgr** [comment]
The general sentiment is "try it and see" -- usually if it compiles, it works.

**Comment by carlosgalvezp** [comment]
Understood, thanks!
