### ISSUE TITLE
`struct timeval` mapped to `sys/time.h`

### ISSUE THREAD

**Issue by firewave** [include-what-you-use/include-what-you-use#1278]
```cpp
#include <sys/select.h>

void f()
{
    struct timeval tv;
    tv.tv_sec = 1;
    tv.tv_usec = 0;
    (void)tv;
}
```

The code compiles but the documentation attributes it to `sys/time.h`.

https://pubs.opengroup.org/onlinepubs/7908799/xsh/systime.h.html
https://man7.org/linux/man-pages/man2/settimeofday.2.html

If you provide both includes it correctly prefers the expected one:

```
/mnt/s/___temp/input.cpp should add these lines:

/mnt/s/___temp/input.cpp should remove these lines:
- #include <sys/select.h>  // lines 2-2

The full include-list for /mnt/s/___temp/input.cpp:
#include <sys/time.h>  // for timeval
---
```

**Comment by kimgr-spire** [comment]
Yes, timeval is provided by both. See https://github.com/include-what-you-use/include-what-you-use/pull/930 for the patch that made it so.

Is this causing any problems in particular?

**Comment by firewave** [comment]
> Yes, timeval is provided by both. See #930 for the patch that made it so.

Those changes seem (at least) partially kind of arbitrary. It somehow seems like introducing mappings to common files which also have it included (assuming to reduce the impact on existing code bases). I do get why this was done but in this case it is clearly documented which header provides it. This is also basically re-introducing reliance on transitive includes.

Also this type in particular is not even listed in the manpage which that other PR refers.

> Is this causing any problems in particular?

Not for me. I just came across this while filing https://github.com/llvm/llvm-project/issues/64336.

**Comment by kimgr** [comment]
Maybe @alejandro-colomar can fill in on the status of the posix/Linux documentation.

In general iwyu has had mappings that limit unnecessary changes around sys includes. They're usually stable enough that it's OK to allow a little imprecision in the name of convenience.

**Comment by alejandro-colomar** [comment]
Hi @kimgr !

I had a similar feeling to whar @firewave is suggesting.  Maybe I shouldn't have added back then so many mappings, and only keep the fundamental header for each type.  That way, we would be strict and force users to include what they use from libc headers, even if the standards guarantee more flexibility.

Back then I didn't do that to not produce a lot of churn reverting part of what I did, but @firewave 's complain gives more strength to those feelings I had.

I'll prepare a patch CCing both of you, and we can discuss it further there, if you want.

Cheers,
Alex

**Comment by alejandro-colomar** [comment]
BTW, going back to this and compare with POSIX again made me realize a typo I had made back then (also in the man pages): I wrote that `clock_t` is provided (among others) by `<sys/time.h>`, but it was really `<sys/times.h>`.  :)

**Comment by kimgr** [comment]
FWIW, my web search for "select.h posix" yielded: https://pubs.opengroup.org/onlinepubs/009604499/basedefs/sys/select.h.html, which says select.h defines `timeval`.

Looking at related docs for time.h, they have the same section: https://pubs.opengroup.org/onlinepubs/009604499/basedefs/sys/time.h.html

So it seems correct to me to allow both.

**Comment by alejandro-colomar** [comment]
Hmm, that's probably a bug in POSIX.  POSIX usually describes types in only one header, and then in other headers just says that they define the type "as described in ...".  In this case, they really define it in the two headers, but I presume that was a mistake, and `<sys/time.h>` was intended to be the canonical header.

**Comment by kimgr** [comment]
The select.h page also says it "may may make visible all symbols from the headers <signal.h>, <sys/time.h> and <time.h>", which I guess is how it exposes timeval. If it's impossible to use the functions in select.h without also having time.h available, I think it's fair to assume select.h re-exports time.h.

**Comment by kimgr** [comment]
After [@alejandro-colomar's example](https://github.com/include-what-you-use/include-what-you-use/pull/1283#issuecomment-1675924844) I see more clearly now that the concern is that `<sys/select.h>` isn't _necessary_ for `timeval`, unless we're also using some of the `select` functions.

I guess that makes sense. It just means that whenever we use e.g. `select()`, we need to include both `<sys/select.h>` and `<sys/time.h>`, which is strictly redundant. I think my preference is for IWYU to be less principled here, and more respectful of working code, but I'm not 100% sure that's the right tradeoff.

Thoughts?

**Comment by alejandro-colomar** [comment]
I try to use IWYU principles when programming, and include stddef and sys/types even if I know they are mostly unnecessary because other headers will provide their definitions.  It's not very cumbersome, because there are only a couple of such headers.  I think it would be doable.

Maybe we could do it gradually, removing mappings for weird identifiers such as `blkcnt_t`, see if people complain, then do it with more common ones life `FILE`, and then in a third version with the most ubiquitous ones, such as `size_t` and `NULL`.

**Comment by kimgr** [comment]
Yeah, I was thinking something like that too. Overall, smaller changes are better :)

**Comment by alejandro-colomar** [comment]
We have a deal :)
