### ISSUE TITLE
IWYU suggests to include header with applied `pragma: export`

### ISSUE THREAD

**Issue by hebasto** [include-what-you-use/include-what-you-use#1280]
Using IWYU version `0.20` and sources similar to https://github.com/include-what-you-use/include-what-you-use/issues/674#issuecomment-546674462:

```
// main.cc
#include "A/a.h"

int main() {
  A a;
  return a.impl->value;
}

// A/a.h
#include "Impl/a_impl.h"  // IWYU pragma: export

struct A {
    A();
    struct Impl *impl;
};

// A/a.cc
#include "a.h"

A::A() {}

// A/Impl/a_impl.h
struct Impl {
    int value;
};
```

This gives:
```
$ include-what-you-use A/a.cc 

A/a.h should add these lines:
#include "/home/hebasto/dev/src/A/Impl/a_impl.h"

A/a.h should remove these lines:

The full include-list for A/a.h:
#include "/home/hebasto/dev/src/A/Impl/a_impl.h"
#include "Impl/a_impl.h"
---

(A/a.cc has correct #includes/fwd-decls)
```

**Comment by kimgr** [comment]
The suggestion is for a.h, and it gets confused about path, so I think the export pragma is a red herring. Do you have a -I switch somewhere that makes Impl/ visible, or is it implicit inside A/?

**Comment by kimgr** [comment]
This is similar enough to #674 that I'm going to call it a duplicate, let's follow up there instead to keep information colocated.
