### ISSUE TITLE
IWYU: error file mpi.h not found

### ISSUE THREAD

**Issue by swiesheier** [include-what-you-use/include-what-you-use#1281]
I built IWYU out-of-tree (clang 14.0.6) and the compilation worked fine. Also, it works on a dummy program that just prints "hello world" to the console. 

My real project uses cmake as build system and I just passed the iwyu binary to cmake as

`cmake -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE = path_to_iwyu_executable ..` 

My project links against an external library (deal.II). If I create an empty .cc file and include just one header of deal.II (without using any symbols from it), iwyu returns the error

```
Error running '/calculate/simon/software/iwyu/build/bin/include-what-you-use': warning: unknown warning option '-Wno-placement-new' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-literal-suffix'; did you mean '-Wno-literal-range'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-class-memaccess'; did you mean '-Wno-class-varargs'? [-Wunknown-warning-option]
In file included from /calculate/dealii-9.4.0/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.4.0-kxrbkaijxclrdrwwu5bxlavjzueiierv/share/deal.II/examples/step-1/step-1.cc:4:
In file included from /calculate/dealii-9.4.0/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.4.0-kxrbkaijxclrdrwwu5bxlavjzueiierv/include/deal.II/grid/tria.h:20:
/calculate/dealii-9.4.0/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.4.0-kxrbkaijxclrdrwwu5bxlavjzueiierv/include/deal.II/base/config.h:540:12: error: 'mpi.h' file not found with <angled> include; use "quotes" instead
#  include <mpi.h>
```

Here, my executable called step-1 includes tria.h (the header I mentioned above), which contains
#include <deal.II/base/config.h> 
config.h contains
#include <mpi.h>

According to the error message, iwyu can not find <mpi.h>. 
However, the file <mpi.h> exists -- it is in the same directory as config.h.

Is there anything I can try to solve this issue? Maybe passing some additional flags when compiling iwyu? Unfortunately, I can not follow the suggestion to use quotes instead as the header comes from deal.II.

**Comment by kimgr** [comment]
Is clang able to compile that tiny project without iwyu? The warning comes from clang's processing of the source file, so iwyu is not directly involved.

**Comment by swiesheier** [comment]
If I just do

`cmake ..`

my tiny project compiles. Here, cmake chooses an mpic++ compiler from openmpi 4.1.5 because deal.II was configured with MPI, i.e, `cmake ..` is equivalent to 

`cmake -DCMAKE_CXX_COMPILER = /path/to/mpic++ ..`

I tried to compile my program with clang++ as

`cmake -DCMAKE_CXX_COMPILER = /path/to/clang++ ..`

Interestingly, this produces the same error as 

`cmake -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE = path_to_iwyu_executable  ..`

which I showed in my question.
Obviously, cmake chooses the above clang++ compiler when I pass the iwyu flag, but I am wondering why.
When I compiled iwyu, I did it with the mpic++ compiler from above as 

`cmake -DCMAKE_CXX_COMPILER = /path/to/mpic++ ../include_what_you_use`

I know that my project with the third party library deal.Ii requires me to choose the mpic++ compiler.

Is there a workaround for me?

**Comment by kimgr** [comment]
Maybe you can pass `-isystem` among the iwyu args to explicitly specify the include path of the library?

**Comment by swiesheier** [comment]
Basically, the `mpic++` compiler is a wrapper compiler which calls the gcc/clang compiler on my system WITH some input paths and linker flags.

So yes I could compile thy tiny project now with `clang++` . However, after including iwyu, I arrived at a well-known problem. See the error message

```
[ 50%] Building CXX object CMakeFiles/step-2.dir/step-2.cc.o
Error running '/calculate/simon/software/iwyu/build/bin/include-what-you-use': warning: unknown warning option '-Wno-placement-new' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-literal-suffix'; did you mean '-Wno-literal-range'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-class-memaccess'; did you mean '-Wno-class-varargs'? [-Wunknown-warning-option]
Cycle in include-mapping:
  <sc_mpi.h> ->
  <sc.h> ->
  <sc.h>
/calculate/simon/software/iwyu/include-what-you-use/iwyu_include_picker.cc:1081: Assertion failed: Cycle in include-mapping
Subprocess aborted
make[2]: *** [CMakeFiles/step-2.dir/build.make:76: CMakeFiles/step-2.dir/step-2.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/step-2.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I have include-what-you-use 0.18 based on clang version 14.0.6 installed. 

I think the issue with include cycles is discussed in #424 and you fixed this in iwyu 0.19, right?
If so, do I have to upgrade to iwyu 0.19, or would this not help in my particular case?

**Comment by kimgr** [comment]
Yeah, the cycle issue should be fixed in 0.19. Or if you're building from source, you should be able to just use mainline. Keep the iwyu/clang compat table from the README in mind, though.

**Comment by swiesheier** [comment]
> Or if you're building from source, you should be able to just use mainline.

What do you mean by that? I installed iwyu 0.18 from the .org [website](https://include-what-you-use.org/downloads/). 

My problem is that I have to stick to clang 14.0.6 for a while. 
But to fix the cycle issue, I have to upgrade to iwyu 0.19 and thus to clang 15,
or is there a solution to use iwyu 0.19 with clang 14?

**Comment by kimgr** [comment]
The only dependency between iwyu and clang is clang's builtin headers. I'm away from keyboard, so I can't go into too much detail, but see if you can get the right headers in the right place for the respective iwyu versions.

**Comment by swiesheier** [comment]
> see if you can get the right headers in the right place for the respective iwyu versions.

At which place in the iwyu folder do I have to do that? In the CMakeLists.txt or looking in the bunch of .h and .cc files? 

When I compile iwyu, I have to specify the path to llvm via cmake (DCMAKE_PREFIX_PATH=/path/to/llvm-14). 
Is this not enough?

**Comment by swiesheier** [comment]
I tried to compile iwyu 0.19 where CMAKE_PREFIX_PATH points to llvm-14. Here is the error

`In file included from /calculate/simon/software/iwyu/include-what-you-use-0-19/iwyu.cc:115:
/calculate/simon/software/iwyu/include-what-you-use-0-19/iwyu_preprocessor.h:209:72: error: non-virtual member function marked 'override' hides virtual member function
                          clang::SrcMgr::CharacteristicKind file_type) override;
                                                                       ^
/calculate/dealii-9.4.0/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/llvm-14.0.6-o5djj5zhf5wzobf3f63ovsoumtvmogth/include/clang/Lex/PPCallbacks.h:122:16: note: hidden overloaded virtual function 'clang::PPCallbacks::InclusionDirective' declared here: type mismatch at 6th parameter ('const clang::FileEntry *' vs 'llvm::Optional<clang::FileEntryRef>')
  virtual void InclusionDirective(SourceLocation HashLoc,
               ^
1 error generated.
make[2]: *** [CMakeFiles/include-what-you-use.dir/build.make:76: CMakeFiles/include-what-you-use.dir/iwyu.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: CMakeFiles/include-what-you-use.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

Maybe you can point me to the places where I have to change something to ensure compatibility between iwyu 0.19 and llvm 14.

**Comment by kimgr** [comment]
Essentially you should be able to revert all commits marked `[clang-compat]` back until the clang_14 branch head.

**Comment by swiesheier** [comment]
After I cloned the repo, I did:

`git checkout clang_14`
`git checkout clang_15`
`git rebase -i clang_14`

There were in total 9 commits marked `clang compat` and I deleted the corresponding lines . During rebase, merge conflicts occurred as for

Refactor CanForwardDeclareType for better sugar tolerance
Avoid redundant enum type reporting

In both cases, I "accepted the incoming changes" as these commits are not tagged with `clang compact`. 
At the end, my local clang_15 branch has 99 commits, 9 less than the orign/clang_15 branch. 

When I try to compile iwyu now, I get

`[ 93%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu.cc.o
/calculate/simon/software/iwyu-0-19/include-what-you-use/iwyu.cc: In member function ‘bool include_what_you_use::IwyuAstConsumer::VisitUnaryExprOrTypeTraitExpr(clang::UnaryExprOrTypeTraitExpr*)’:
/calculate/simon/software/iwyu-0-19/include-what-you-use/iwyu.cc:4023:9: error: ‘RemoveElaboration’ was not declared in this scope
 4023 |         RemoveElaboration(expr->getTypeOfArgument().getTypePtr());
      |         ^~~~~~~~~~~~~~~~~
In file included from /calculate/simon/software/iwyu-0-19/include-what-you-use/iwyu.cc:104:
/calculate/simon/software/iwyu-0-19/include-what-you-use/iwyu_ast_util.h: In member function ‘const void* include_what_you_use::ASTNode::DynCast(const void*) const [with Ignored = void]’:
/calculate/simon/software/iwyu-0-19/include-what-you-use/iwyu_ast_util.h:305:3: warning: control reaches end of non-void function [-Wreturn-type]
  305 |   }
      |   ^
make[2]: *** [CMakeFiles/include-what-you-use.dir/build.make:76: CMakeFiles/include-what-you-use.dir/iwyu.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: CMakeFiles/include-what-you-use.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

Is reverting the commits marked with `clang compact` not enough, or did I miss something?

**Comment by kimgr** [comment]
OK, could you instead try:
```
git checkout -b swiesheier-clang_14 clang_14
git cherry-pick 6d5414fcf38c6e617ad1a2894ed4bd5acf1469f4
git cherry-pick 616927dec4357e09b76357fb9925684e35a23d1c
git cherry-pick 3511ccdedd8cd33b68fa9a7fa9b2b3048e88a7bd
```

to get the three specific commits for cycle-breaking improvements?

**Comment by kimgr** [comment]
@swiesheier Is there anything more we can do from the include-what-you-use project here, or can this issue be closed?

**Comment by kimgr** [comment]
@swiesheier Feel free to reopen if there's anything more you need help with.
