### ISSUE TITLE
can iwyu ignore certain headers?

### ISSUE THREAD

**Issue by swiesheier** [include-what-you-use/include-what-you-use#1282]
Is there an option to tell iwyu to ignore certain headers?

Say I create an own library with cmake that links against a third-party library. 
The executable is then linked against both libraries and contains several headers from each of them.
iwyu should ignore the headers from the third-party-library. 
Is there a way to do this?

**Comment by kimgr** [comment]
Ignore in what sense? Are the third party headers unused, but you want to keep them all the same? Or something else?

**Comment by swiesheier** [comment]
I use cmake to create my own library. This library uses headers from a third-party library. What I want to do is to let iwyu only take care of the headers from my own library. For instance, if there are superfluous headers from the third-party-library, iwyu should not care about that.

**Comment by kimgr** [comment]
Could the keep pragma help: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-keep?

Still not sure what you're trying to do, maybe an example would help.

**Comment by naeimeh69** [comment]
@kimgr 
For example in my library I have a header file called my_lib.h. This header file included date_generators.hpp from boost library and inside CmakeList.txt I have include boot as a sub_directory.
What I expect from iwyu is only analyzing my_lib.h. But what iwyu do is that it analyzes boost header files as well, e.x.
The full include-list for external/boost/include/boost/date_time/date_generators.hpp should add these lines:
The full include-list for /external/boost/include/boost/date_time/gregorian/greg_weekday.hpp:
I think @swiesheier  wants to exclude boost from iwyu analysis. This is what I'm looking for it as well. Am I right @swiesheier?

**Comment by kimgr** [comment]
Have you tried the [keep directive](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-keep)? Something like:
```
#include "boost/date_time/date_generators.hpp"  // IWYU pragma: keep

...
```
If that didn't work, have you tried using [the mappings](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md#specifying-mapping-files) [for Boost](https://github.com/include-what-you-use/include-what-you-use/blob/master/boost-1.75-all.imp)?

In general, no, you can't exclude a library from analysis.

**Comment by naeimeh69** [comment]
@kimgr 
No, I didn't try these options. The project is big and I should think of a way that doesn't need to change all files.
I figured out that it would be better to run iwyu on single files. But now there is another issue. Lets assume that I have the below files:
test/include/foo.hpp
test/src/foo.cpp
And inside test/src/foo.cpp I have "  #include "foo.hpp" ". When I run include-what-you-use test/src/foo.cpp I get the below error:
fatal error: 'foo.hpp' file not found.
How should I fix this issue? How should I make iwyu recognize 'foo.hpp' is test/include/foo.hpp?

**Comment by kilroyd** [comment]
`include-what-you-use` needs the preprocessor options that get passed to the compiler i.e. the `-I` and `-D` compiler options. The easiest way to get this is to get CMake to generate a `compile_commands.json` files by either adding `CMAKE_EXPORT_COMPILE_COMMANDS=ON` to your `CMakeLists.txt` or to add `-D CMAKE_EXPORT_COMPILE_COMMANDS=ON`. Then call `iwyu_tool.py` rather than calling `include-what-you-use`:

    iwyu_tool.py -p $PATH_TO_BUILD_DIR $SOURCES/test/src/foo.cpp

See https://github.com/include-what-you-use/include-what-you-use#using-with-a-compilation-database

**Comment by naeimeh69** [comment]
@kilroyd 
My first plan was to integrate iwyu in the build_system and use cmake. But there are a lot of problem as the project is big and has a lot of third-party libraries. So, iwyu processes third-party header files and also it takes a lot of time to build the project for iwyu. So, I decided to run iwyu on single files. In this way I collect a list of files that I want to check with iwyu.

**Comment by kimgr** [comment]
> So, I decided to run iwyu on single files. In this way I collect a list of files that I want to check with iwyu.

You can do that, but you need to pass the same arguments to `include-what-you-use` as you pass to your compiler. All available alternatives are described here: https://github.com/include-what-you-use/include-what-you-use/#how-to-run.

**Comment by kimgr** [comment]
Still not clear what the question is here, I'll close this for now. Feel free to reopen if more answers are necessary.
