### ISSUE TITLE
Reduce symbol mappings to be even more fine-grained

### ISSUE THREAD

**Issue by kimgr** [include-what-you-use/include-what-you-use#1286]
Created from #1283, by @alejandro-colomar:

In the end, I decided to do the cut for part 1 at a somewhat logical point:

-  Mappings guaranteed by ISO C are respected.
-  Mappings for `<sys/types.h>` and `<unistd.h>` (POSIX.1) are respected.
-  Any other POSIX.1 (or nonstandard) mappings have been removed.

It seems this doesn't affect out test suite, so it seems to be a fair cut point, isn't it?

Please ping me after the next release for part 2.  :)

_Originally posted by @alejandro-colomar in https://github.com/include-what-you-use/include-what-you-use/issues/1283#issuecomment-1675989244_

**Comment by kimgr** [comment]
@alejandro-colomar IWYU 0.21 is just released, so now would be a good time to look into this. Do you remember what part 2 was? :slightly_smiling_face:

**Comment by alejandro-colomar** [comment]
Probably I didn't decide, because I didn't keep a branch with a v2 patch.  Or I forgot.  :)

I propose chopping the remaining POSIX headers: `<sys/types.h>` and `<unistd.h>`.  Those alone should already add many warnings in users.

**Comment by kimgr** [comment]
Remind me: what's the goal? To prefer recommending ISO C headers before POSIX headers?

**Comment by alejandro-colomar** [comment]
Nope.  Being pedantic about IWYU guidelines, even when ISO C and POSIX are designed in a way that multiple headers are guaranteed to provide the same identifier in several places (by inclusion of other headers).

This was the best example of why we want this:
<https://github.com/include-what-you-use/include-what-you-use/pull/1283#issuecomment-1675924844>

```c
#include <monetary.h>

void
foo(size_t n, int arr[n])
{
    for (size_t i = 0; i < n; i++) {
        arr[i] = 42;
    }
}
```

This is perfect POSIX code, but we'll agree to disagree with POSIX.  ;)

**Comment by alejandro-colomar** [comment]
So, we remove secondary headers that ISO C and POSIX say are guaranteed to provide an identifier, keeping only the canonical one, be it from ISO C or POSIX.

**Comment by kimgr** [comment]
Ah, yes. That example is convincing.

So we're looking at a mass update to the symbol mappings, that will probably cause a lot of noise for users, but be more stringent? Oh, yeah, I see the issue title says "symbol mappings". I mean, I love pedantry, please move ahead with it when you have a chance.

**Comment by kimgr** [comment]
I believe this is completed for 0.22.
