### ISSUE TITLE
Regex negative lookahead not working?

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1290]
Hi!

We are bumping IWYU from 0.18 to trunk and now we get warnings about including some header files that we had suppressed via a mapping file. Namely, we have:

```
  {include: ["@<rapidcheck/(?!gtest).*(h|hpp)>",                   "private", "<rapidcheck/gtest.h>",        "public"]},
```

Yet IWYU is warning:

```
foo.cpp should add these lines:
#include <rapidcheck/Assertions.h>
#include <rapidcheck/Gen.h>
#include <rapidcheck/Traits.h>
#include <rapidcheck/Gen.hpp>
#include <rapidcheck/Maybe.hpp>
#include <rapidcheck/Seq.hpp>
#include <rapidcheck/Shrinkable.hpp>
#include <rapidcheck/gen/Arbitrary.hpp>
#include <rapidcheck/gen/Build.hpp>
#include <rapidcheck/gen/Predicate.hpp>
#include <rapidcheck/gen/Transform.hpp>

foo.cpp should remove these lines:
- #include <rapidcheck/gtest.h>  // lines 14-14

```
Is the regex expression above supported, or were we just lucky that it worked until now?

On a side note, it would be good if the IWYU docs documented the type of regex it supports.

Thanks!

**Comment by kimgr** [comment]
It does, see the help text/man page

**Comment by carlosgalvezp** [comment]
So looking at the help, I notice the `--regex` flag and there it specifies that the default is "llvm" regex. 
A google search brings me to this:
https://github.com/llvm/llvm-project/issues/53051

So LLVM regex is based on POSIX regex, which does not support negative lookahead. I suppose that's why it doesn't work!

> It does, see the help text/man page
I still believe it's a bit unintuitive context switch when one is reading the [docs](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md). Perhaps it'd be worth adding something like:

"the regex dialect in use is selected via the `--regex` flag of IWYU".

**Comment by carlosgalvezp** [comment]
If someone comes across this issue - setting `-Xiwyu --regex=ecsmascript` solves the problem!

**Comment by kimgr** [comment]
How about this: https://github.com/include-what-you-use/include-what-you-use/pull/1292?

**Comment by carlosgalvezp** [comment]
Looks great, thank you!
