### ISSUE TITLE
IWYU macro bug

### ISSUE THREAD

**Issue by liuluheng** [include-what-you-use/include-what-you-use#1296]
Say we have the following code `iwyu_rm_macro.cc`

``` cpp
#include <stdio.h>

#define MY_MACRO \
  namespace A {  \
  struct a;      \
  }              \
  int b = 0;

MY_MACRO

int main() { printf("%d\n", b); }
```
Then we run below
```
$ bin/include-what-you-use iwyu_rm_macro.cc

wyu_rm_macro.cc should add these lines:

wyu_rm_macro.cc should remove these lines:
- namespace A { struct a; }  // lines 9-9

The full include-list for iwyu_rm_macro.cc:
#include <stdio.h>  // for printf
---
```
line 9 is `MY_MACRO`, if we run `fix_includes.py`, `MY_MACRO` will be removed. Then the code **CANNOT COMPLIE**.

`IWYU pragma: keep/begin_keep/end_keep` dose **NOT** work on this case.

IWYU version 0.20

**Comment by kimgr** [comment]
Yes, I can reproduce. I think it should be possible to detect that the forward-declaration is inside a macro expansion and just skip the removal.

**Comment by kimgr** [comment]
Huh. There's actually a test for exactly this scenario: https://github.com/include-what-you-use/include-what-you-use/blob/master/tests/cxx/forward_declare_in_macro.cc, except it never imagined that a macro could do two things.

I think it's questionable to remove macros containing forward-declarations, so I think I'll try to change this.

**Comment by kimgr** [comment]
@liuluheng Please take a look at https://github.com/include-what-you-use/include-what-you-use/pull/1365

**Comment by liuluheng** [comment]
@kimgr Thank you for the fix. It appears to be working. I will test the patch as soon as possible.

**Comment by liuluheng** [comment]
@kimgr I had tested it in a real complex macro like [POINT_CLOUD_REGISTER_POINT_STRUCT](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/register_point_struct.h#L64). It WORKs.

**Comment by kimgr** [comment]
Thank you! Available on master now.
