### ISSUE TITLE
no include suggested for `std::swap()`

### ISSUE THREAD

**Issue by firewave** [include-what-you-use/include-what-you-use#1316]
```cpp
#include <string>

void str()
{
    std::string s, s1;
    std::swap(s1, s);
}
```

```
(input.cpp has correct #includes/fwd-decls)
```

The `clang-include-cleaner` standalone application suggests to add `<utility>`.

clang-tidy output:
```
<source>:6:10: warning: no header providing "std::swap" is directly included [misc-include-cleaner]
    2 | 
    3 | void str()
    4 | {
    5 |     std::string s, s1;
    6 |     std::swap(s1, s);
      |          ^
```
https://godbolt.org/z/Pczfsfdqo

Reference:
https://en.cppreference.com/w/cpp/algorithm/swap

**Comment by firewave** [comment]
Possibly related to #377.

**Comment by kilroyd** [comment]
The specialization for `std::swap(std::basic_string, std::basic_string)` is defined to come from `<string>`: https://en.cppreference.com/w/cpp/string/basic_string/swap2

Locally in my libc++ headers, I also see that `swap` definition in `c++/v1/string` (which is the right file).

I think the IWYU behaviour is correct here.

**Comment by kimgr** [comment]
@firewave It might be interesting to see if the recommendation changes if you add another swap, but for int;
```
#include <string>

void f()
{
    std::string s, s1;
    std::swap(s1, s);

    int a = 10, b = 20;
    std::swap(a, b);
}
```

**Comment by firewave** [comment]
I filed an issue upstream: https://github.com/llvm/llvm-project/issues/70665.

> @firewave It might be interesting to see if the recommendation changes if you add another swap, but for int;

```
input.cpp should add these lines:
#include <utility>  // for swap

input.cpp should remove these lines:

The full include-list for input.cpp:
#include <string>   // for swap, string
#include <utility>  // for swap
---
```
