### ISSUE TITLE
include-what-you-use 0.21 crashes with default template arguments

### ISSUE THREAD

**Issue by Jhuighuy** [include-what-you-use/include-what-you-use#1334]
Hi!

The latest version of include-what-you-use (0.21, from brew) crashes with a segmentation fault for the following snippet of code:

```cpp
#pragma once

class Class1 {};

template<class T = Class1>
class Class2 {};

template<class T = Class2<>>
class Class3 {};
```

```sh
$ include-what-you-use ./test.hpp
[1]    51626 segmentation fault  include-what-you-use ./test.hpp
```

It seems something goes wrong with the default value `Class2<>` for the `Class3`'s template parameter.

Everything works fine with version 0.20.

**Comment by bolshakov-a** [comment]
Fixed in PR #1333.

**Comment by kimgr** [comment]
Glad to see your environment is working again; reopening the issue until fix is on master.

**Comment by kimgr** [comment]
Fixed in: https://github.com/include-what-you-use/include-what-you-use/commit/1d6140c7246dc83163f6e040a863ee5b5f3410ca
