### ISSUE TITLE
include-what-you-use does not recognize used names in concepts.

### ISSUE THREAD

**Issue by Jhuighuy** [include-what-you-use/include-what-you-use#1335]
Hi!

include-what-use-use does not "see" what was used inside of `concept` declaration.

Example:
```cpp
#pragma once

#include <type_traits>

template<class T>
concept object = std::is_object_v<T>;
```

Output:
```sh
$ include-what-you-use -std=c++20 ./test.hpp

test.hpp should add these lines:

test.hpp should remove these lines:
- #include <type_traits>  // lines 3-3

The full include-list for test.hpp:
---
```

Example (2):
```cpp
#pragma once

#include <type_traits>

template<class T>
  requires std::is_object_v<T>
void f();
```

Output:
```sh
$include-what-you-use -std=c++20 ./test.hpp

test.hpp should add these lines:

test.hpp should remove these lines:
- #include <type_traits>  // lines 3-3

The full include-list for test.hpp:
---
```

**Comment by kimgr** [comment]
I think this TODO indicates that it's not implemented yet: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu.cc#L4145

**Comment by bolshakov-a** [comment]
I think it is due to another reason: variable templates are not supported. `std::is_object<T>::value` works.

**Comment by kimgr** [comment]
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/a82c71187d3e3a8a0d0caac1034138a02090669d
