### ISSUE TITLE
Segfault on undefined constructors.

### ISSUE THREAD

**Issue by Jhuighuy** [include-what-you-use/include-what-you-use#1369]
Hi everyone! Found another segmentation code on the following snippet of code:

```cpp
#include <tuple>
#include <vector>

class Class {
  Class(); // note: no definition
  std::vector<std::tuple<int>> data_;
};
```

There is no segfault if either constructor is defined, either `std::vector`'s template parameter is a trivial type.

Using version 0.21 from brew. Maybe it is already fixed in the master, cannot check.

**Comment by kimgr** [comment]
You seem to be hitting https://github.com/include-what-you-use/include-what-you-use/issues/1331.

I can repro with your example on 0.21 and latest master runs successfully. You can cherry-pick https://github.com/include-what-you-use/include-what-you-use/pull/1333 onto 0.21 if you want to stay there.

Closing as duplicate.
