### ISSUE TITLE
IWYU wrongly suggests `<debug/...>` when `_GLIBCXX_DEBUG` is defined

### ISSUE THREAD

**Issue by wangtz0607** [include-what-you-use/include-what-you-use#1388]
## Example

**`main.cpp`**:

```c++
#include <vector>

int main() {
    std::vector<int> v;
    return 0;
}
```

Compile with `-D_GLIBCXX_DEBUG` (or add `#define _GLIBCXX_DEBUG` before `#include <vector>`).

## Actual Behavior

```bash
$ include-what-you-use -D_GLIBCXX_DEBUG main.cpp

main.cpp should add these lines:
#include <debug/vector>  // for vector

main.cpp should remove these lines:
- #include <vector>  // lines 1-1

The full include-list for main.cpp:
#include <debug/vector>  // for vector
---
```

## Expected Behavior

IWYU should consider `main.cpp` to have correct #includes/fwd-decls.

## Environment

```bash
$ include-what-you-use --version
include-what-you-use 0.21 (git:dbecade) based on clang version 17.0.6
```

```bash
$ clang --version
clang version 17.0.6
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

```bash
$ gcc --version
gcc (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kimgr** [comment]
@wangtz0607 Looks like we don't have mappings for the debug headers. If you want to work around it yourself, consider writing up a small mapping file (https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md) and apply it using `-Xiwyu --mapping_file=stl-debug.imp`.

**Comment by kimgr** [comment]
I'm working on a set of builtin mappings for the debug headers.

**Comment by kimgr** [comment]
Fix is now on mainline.
