### ISSUE TITLE
Add support for regex for destination in mapping

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/include-what-you-use#145]
Originally reported on Google Code with ID 145

```
The mapping syntax supports a regex expression for the first entry of the mapping. It
would be nice if this could be extended to also be supported for the 3rd entry(=2nd
include). This would be useful if the same include is provided by a lot of other include
files.
```

Reported by `roland@rschulz.eu` on 2014-06-05 05:03:55

**Comment by kimgr** [comment]
Hello, old issue from 2015! As of PR #1123, commit 6fb66575fba17039d1be6c1fc3dca08623163460, there's now support for replacements with backreferences for all regex dialects.
