### ISSUE TITLE
Using IWYU without libc

### ISSUE THREAD

**Issue by florianmarkusse** [include-what-you-use/include-what-you-use#1465]
Hi, 
Love the tool, been using it for all of my projects so far!

I am trying to compile my kernel with IWYU.
Now I am not using the C-standard library, so I have a specific header, `types.h` which contains:
```
#ifndef TYPES_H
#define TYPES_H

typedef short int int16_t;
typedef unsigned char uint8_t;
typedef unsigned short int uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long int uint64_t;

#endif
```
When I run this on files that have this import with the IWYU tool, it suggests the following:
```
Warning: include-what-you-use reported diagnostics:

/home/florian/Desktop/homegrown/code/src/kernel.c should add these lines:
#include <stdint.h>    // for uint32_t, uint64_t, uint8_t

/home/florian/Desktop/homegrown/code/src/kernel.c should remove these lines:
- #include "types.h"  // lines 35-35

The full include-list for /home/florian/Desktop/homegrown/code/src/kernel.c:
#include <stdint.h>    // for uint32_t, uint64_t, uint8_t
#include "bootboot.h"  // for BOOTBOOT
```

Is there a way to let IWYU "know" that it should not suggest this header? Or is this unavoidable and baked into the tool?

Many thanks!

**Comment by kimgr** [comment]
@florianmarkusse A baremetal environment should work with `-Xiwyu --no_default_mappings`. Can't say I've tried it, but it's worth a shot.

**Comment by florianmarkusse** [comment]
Perfect, that works. Thanks for your reply!
