### ISSUE TITLE
Error build in clang_18 branch. 

### ISSUE THREAD

**Issue by buldi** [include-what-you-use/include-what-you-use#1477]
Hi,

I find error in build clang_18 branch.
```
/iwyu/include-what-you-use/iwyu.cc:1856:19: error: ‘CK_HLSLVectorTruncation’ is not a member of ‘clang’
 1856 |       case clang::CK_HLSLVectorTruncation:
```
Analyzing the clang/llvm repository I did not find this, a constant in the code for version 18. This constant is found in the newer version of the code.
I propose deleted this cons in clang_18 branch.

**Comment by kimgr** [comment]
The `clang_18` branch doesn't contain `CK_HLSLVectorTruncation`: https://github.com/include-what-you-use/include-what-you-use/blob/clang_18/iwyu.cc#L1844.

So either there's must be some mistake, or I'm not fully understanding what's going on.

**Comment by buldi** [comment]
Yes, it is my mistake.

**Comment by buldi** [comment]
Yes it is my mistake
