### ISSUE TITLE
build error on master under Windows

### ISSUE THREAD

**Issue by LegalizeAdulthood** [include-what-you-use/include-what-you-use#1485]
```
D:\legalize\llvm\llvm-project\llvm\include\llvm\Support\DXILABI.h(27,3): error C2144: syntax error: 'void' should be preceded by '}' [D:\legalize\llvm\build-iwyu\tools\iwyu\include-what-you-use.vcxproj]
  (compiling source file '../../../include-what-you-use/iwyu_ast_util.cc')
```

Line 27 of `DXILABI.h` contains the following:
```
enum class ParameterKind : uint8_t {
  INVALID = 0,
  VOID,  // line 27
  HALF,
  FLOAT,
  DOUBLE,
  I1,
  I8,
  I16,
  I32,
  I64,
  OVERLOAD,
  CBUFFER_RET,
  RESOURCE_RET,
  DXIL_HANDLE,
};
```

A Windows header files define `VOID` as a macro that expands to `void`.  The offending header is the inclusion of `Shlwapi.h` on line 78 of `iwyu_port.h`.

Hacking in a simple `#undef VOID` after the inlusion of that header results in a clean build.

Branch `clang_18` of include-what-you-use with branch `release/18.x` of llvm/clang builds without errors.

[iwyu-build-log.txt](https://github.com/include-what-you-use/include-what-you-use/files/14608595/iwyu-build-log.txt)

**Comment by kimgr** [comment]
Thanks for the report and for the purposes solution. I'll try to get a fix in place when I have a chance to sit down with IWYU next.

**Comment by LegalizeAdulthood** [comment]
I am about to submit a PR with a simple fix.
