### ISSUE TITLE
Always builds tests if python installed even if python is broken

### ISSUE THREAD

**Issue by HenryMiller1** [include-what-you-use/include-what-you-use#1500]
I'm trying to build IWYU 0.22 for my environment.  I'm getting an error running the python command on line 222 - AttributeError: module 'functools' has no attribute 'cache'.   Then cmake fails shortly afterwards.  I'm not sure if my python install is broken (it is known to be stripped down for "reasons"), or if it is just that 3.6.9 is too old.  Either way, as a user I just want to get this built and I don't care if tests do not run since I trust iwyu developers have run tests.

Seems like the if on line 217 should be protected by more than just python3 found.  Instead there should be an option to build tests as well.  Either that or perhaps you should check the python version if you are depending on something newer than 3.6 which is of cousre old.

**Comment by kimgr** [comment]
@HenryMiller1 Thanks for the heads-up, I wasn't aware `functools.cache` was that new. Added a little backward shim in https://github.com/include-what-you-use/include-what-you-use/pull/1505 -- you should be able to use that patch locally on top of IWYU 0.22 if you want.

**Comment by kimgr** [comment]
Fixed on master [88e4147](https://github.com/include-what-you-use/include-what-you-use/commit/88e414728702390ed8eebf11d14b992a01df1ee0).
