### ISSUE TITLE
Processing overloads from a sole file

### ISSUE THREAD

**Issue by bolshakov-a** [include-what-you-use/include-what-you-use#1525]
IWYU has [a special logic](https://github.com/include-what-you-use/include-what-you-use/blob/93d8793081e5aa457114ef99d1e887390b370e4a/iwyu.cc#L2256-L2289) for handling overloaded functions when they are all in a single file: it suggests to include it in the file defining a template referring to such a set, and suggests not to include in files instantiating such a template. The problem is that whether all the overloads are in a single file or not may depend on the translation unit currently processed. Consider:
```cpp
// overloaded-indirect.h

namespace ns {
void OverloadedFn(int);
void OverloadedFn(char);
}


// overloaded-direct.h

#include "overloaded-indirect.h"


// overloaded-double.h

namespace ns {
void OverloadedFn(double);
}


// tpl.h

#include "overloaded-direct.h"

template <typename T>
void TplFn(T t) {
  ns::OverloadedFn(t);
}


// tpl.cpp

#include "overloaded-double.h"
#include "tpl.h"


// user.cpp

#include "tpl.h"

void User() {
  TplFn(1);
}

```
Note that, in `tpl.cpp`, `#include "overloaded-double.h"` is before including the associated header `tpl.h`. This may occur e.g. because `#include "overloaded-double.h"` is placed in `stdafx.h`, while `user.cpp` may be from another project not using PCH.

When running IWYU on `user.cpp`, clang finds only two overloads from `overloaded-indirect.h`, and IWYU considers hence that `overloaded-indirect.h` should be included directly in `tpl.h`, and doesn't suggest to add anything to `user.cpp`. However, when running on `tpl.cpp`, the third overload from the different file is seen, and IWYU suggests to replace `#include "overloaded-direct.h"` with `#include "overloaded-double.h"` in `tpl.h` (because `OverloadedFn(double)` appears to be the first decl; or not to include anything at all in `tpl.h` if `OverloadedFn` were in the global namespace). It may result in that the code would not be compilable after IWYU run. Even worse, in my example, the code would still be compiled, but with the wrong `OverloadedFn` overload called (because `int` is convertible to `double`)!

Is `processed_overload_locs`-related logic really useful for `UnresolvedLookupExpr`, or may be removed? Or only `AddProcessedOverloadLoc` call should be removed from `VisitUnresolvedLookupExpr`, keeping the logic only at the template definition site? @kimgr, wdyt?

**Comment by kimgr** [comment]
> Is processed_overload_locs-related logic really useful for UnresolvedLookupExpr, or may be removed? Or only
> AddProcessedOverloadLoc call should be removed from VisitUnresolvedLookupExpr, keeping the logic only at
> the template definition site?

I don't have any background knowledge on that one, I'm afraid.

So are you proposing to kill the same-file analysis in `VisitUnresolvedLookupExpr` and always report all of them? I guess some exception needs to be done for operator overloads still?

I found the comment on `processed_overload_locs` enlightening -- https://github.com/include-what-you-use/include-what-you-use/blob/93d8793081e5aa457114ef99d1e887390b370e4a/iwyu.cc#L1106 -- but I'm not sure if it's still necessary after all your recent template provision improvements.

Do you think it's possible to naively report both sides, and then figure out which is the right one in a later pass?

**Comment by bolshakov-a** [comment]
> So are you proposing to kill the same-file analysis in `VisitUnresolvedLookupExpr` and always report all of them?

No, I proposed to keep only the logic written recently by me (don't report all the overloads but keep directly included ones or, maybe, one arbitrary overload for compilability). For qualified calls, on template definition side, it would be identical to the current behavior (because if all the overloads are in a single file then the arbitrary one is in the same file), but would cause a redundant suggestion to include that file also at the instantiation (`User`s) side at the first IWYU pass. Nevertheless, redundancy is better than losing a proper `#include` at all.

For unqualified calls (requiring ADL), it may move an `#include` suggestion from the template definition to the instantiation side (`badinc` has such cases).

Removing only `AddProcessedOverloadLoc` call from `VisitUnresolvedLookupExpr` would keep the current behavior at the template definition side but would cause the redundancy at the instantiation side both for qualified and unqualified calls.

https://github.com/include-what-you-use/include-what-you-use/blob/93d8793081e5aa457114ef99d1e887390b370e4a/iwyu.cc#L1111
I think this comment initially contained the wrong assumption that IWYU can actually determine if all the overloads are in the same file, especially for the case of unqualified calls when the set of overloads may be extended by ADL-founded declarations *after* the template definition. (However, it seems that only qualified call case may result in such worse consequences as in my example).

> Do you think it's possible to naively report both sides, and then figure out which is the right one in a later pass?

Not sure if I've understood the question correctly, but such a behavior seems to be better than the current one.

**Comment by kimgr** [comment]
> > Do you think it's possible to naively report both sides, and then figure out which is the right one in a later pass?
>
> Not sure if I've understood the question correctly, but such a behavior seems to be better than the current one.

I meant if it's possible to discard one of the uses in `iwyu_output` if there turns out to be a duplicate.

But I agree that either way it's better to report to much and end up with compilable code, than the alternative.

I think your reasoning sounds good, but it sounds like there will be regressions compared to status quo. I wonder how bad it will be for the current test suite and for real code. I'm guessing you have a real-world codebase to test on? I no longer do, and I don't think IWYU itself uses any constructs where this would trigger.

Do you think it's worth spending time on a patch to learn more?

**Comment by bolshakov-a** [comment]
I've opened #1528 and #1529. You can see the difference in `badinc`. Also note the difference in `overload_expr-d2.h`. In the second case, `OverloadedFn2` is not required to be included likewise with `TplFn3`.

Don't be confused that the second PR fixes the remaining `UnresolvedLookupExpr`-related bugs, whereas the first one doesn't. They are easy to fix even without removing the same-file logic.

> I meant if it's possible to discard one of the uses in iwyu_output if there turns out to be a duplicate.

The problem is that when running on `user.cpp`, IWYU doesn't know anything about existence of `overloaded-double.h` file and hence whether it will replace `#include "overloaded-direct.h"` in `tpl.h` or not, hence cannot decide if including `overloaded-indirect.h` in `user.cpp` would be redundant or not.

> I'm guessing you have a real-world codebase to test on?

I used IWYU builds with the instantiation-side same-file logic removed (02dbb0dcaac05) and didn't see any problems (but I never launched IWYU on the whole project). However, I've quit my job some time ago, and cannot test the second alternative on that project.

**Comment by kimgr** [comment]
Cool, thanks! I need some more time to get my head around those changes, but it's easier to think about concrete diffs :)

I'm a bit concerned/confused by this change: https://github.com/include-what-you-use/include-what-you-use/pull/1529/files#diff-5468b19db79bc9a4d8e48ef3fbfec669b5d100125568c068490d1420c750d7b5L156.

That was supposed to cover an actual bug: https://github.com/include-what-you-use/include-what-you-use/issues/1229, and I'm surprised that it wasn't, in fact, covered by the changes in `VisitCXXNewExpr`, but somehow `VisitUnresolvedExpr` affects it too.

**Comment by bolshakov-a** [comment]
Seems like the original fix with attributing `operator new` to `<new>` is not affected, just the `AddressOf` function obeys the common logic that its header is not suggested for unqualified call if not directly included. For a qualified call of `std::addressof`, the behavior should not change, I think.

Nevertheless, the fix of just instantiation side seems to be more preferable. I'm just concerned a little about non-determinism (different behavior on scanning different translation units): the command `include-what-you-use -Xiwyu --check_also=tpl.h user.cpp` produces for `tpl.h` an output different from the one produced with `include-what-you-use tpl.cpp`.

**Comment by kimgr** [comment]
> Seems like the original fix with attributing operator new to <new> is not affected, just the AddressOf function obeys the common logic that its header is not suggested for unqualified call if not directly included.

Ah, right -- the test is about `new`, `AddressOf` just showed up as a side-effect. Thanks.

**Comment by kimgr** [comment]
I've looked at both patches now, and I don't really have a preference.

The test changes in badinc.cc stand out as undesirable, but the behavior on master doesn't seem very principled, so it might be better to get rid of it if it has other drawbacks.

Given the number of issues with `unresolvedlookupexpr` tag, it seems like misattribution in unresolved/overload is hitting quite a few people. I'm a little reluctant to make their lives even more difficult without a plan for a better solution. On the other hand, the current behavior doesn't seem to cut it for them anyway.

Have you have a chance to pick a favorite between the two approaches?

**Comment by bolshakov-a** [comment]
Let's proceed with the least drastic approach (#1528).
