### ISSUE TITLE
Can iwyu ignore some headers?

### ISSUE THREAD

**Issue by cheyao** [include-what-you-use/include-what-you-use#1544]
I am using SDL in my project, but iwyu keeps telling me that I should include the module headers, not the all-in-one header:
```
[ 12%] Building CXX object CMakeFiles/TileMap.dir/src/main.cpp.o
Warning: include-what-you-use reported diagnostics:

/home/user/Developer/TileMap/src/main.cpp should add these lines:
#include <SDL3/SDL_events.h>  // for SDL_Event

/home/user/Developer/TileMap/src/main.cpp should remove these lines:
- #include <SDL3/SDL.h>  // lines 1-1

The full include-list for /home/user/Developer/TileMap/src/main.cpp:
#include <SDL3/SDL_events.h>  // for SDL_Event
#include <SDL3/SDL_main.h>    // for SDL_AppEvent, SDL_AppInit, SDL_AppIterate
#include <cstdlib>            // for srand
#include <ctime>              // for time
#include "game.hpp"           // for Game
---
```
But, I've asked on the dev discord, they said that I should include only the all-in-one header. Thus is there someway I can stop iwyu from checking SDL headers?

**Comment by kimgr** [comment]
You can't stop it from checking, but you can force it to use public headers when it finds definitions in private headers, using mappings: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md

**Comment by cheyao** [comment]
Thanks! The mappings worked
