### ISSUE TITLE
What to do with contradictory instructions?

### ISSUE THREAD

**Issue by correaa** [include-what-you-use/include-what-you-use#1557]
Sometimes, and for unknown reasons, IWYU gives contradictory instructions,

For example, below, it tells me to remove `<array>`, only to say later that `<array>`, should be removed.

Same with `<boost/multi/array.hpp>` which I know for a fact that needs to be there.

```
[ 80%] Building CXX object test/CMakeFiles/transform.cpp.x.dir/transform.cpp.o
Warning: include-what-you-use reported diagnostics:

/builds/correaa/boost-multi/test/transform.cpp should add these lines:

/builds/correaa/boost-multi/test/transform.cpp should remove these lines:
- #include <array>  // lines 39-39
- #include <boost/multi/array.hpp>  // lines 37-37
- #include <complex>  // lines 40-40
- namespace test { template <class Involution, class It> class involuter; }  // lines 63-63

The full include-list for /builds/correaa/boost-multi/test/transform.cpp:
#include <array>                     // for array
#include <boost/multi/array.hpp>     // for array, subarray, static_array
#include <boost/test/unit_test.hpp>  // for BOOST_PP_IIF_1, BOOST_PP_IIF_0
#include <complex>                   // for complex, operator*, operator+
#include <cstddef>                   // for ptrdiff_t
#include <functional>                // for negate
#include <iterator>                  // for iterator_traits
#include <memory>                    // for pointer_traits
#include <type_traits>               // for decay_t, conditional_t, true_type
#include <utility>                   // for move, declval
```

At the moment I am adding `// IWYU Pragma: keep` silent the problem, but I am not sure if there is a better reason.

Full log: https://gitlab.com/correaa/boost-multi/-/jobs/7111610840#L1338

**Comment by kimgr** [comment]
Looking at https://gitlab.com/correaa/boost-multi/-/blob/master/test/transform.cpp, it appears to include `boost/multi/array.hpp` and `<array>` twice. IWYU will suggest to remove duplicate includes.

I'm not sure if there's some additional wrinkle I don't understand. You said:
> For example, below, it tells me to remove <array>, only to say later that <array>, should be removed.

Did you mean _should be added_? There are no adds proposed above, it says "add nothing, remove these few includes, and here's what a block of required includes would look like".

**Comment by correaa** [comment]
yes, I mean "added".

I think you are right, it was telling me to remove the repeated includes, but since they were separated by several lines it was not obvious.

Perhaps the message could have said 
```
remove:
#include<boost/multi/array.hpp>  // line 15, duplicated on line 45
```

**Comment by kimgr** [comment]
I'm afraid this by design at the current level of ambition :-).

I'm trying to avoid polishing diagnostics too much, because I believe bigger systemic changes are necessary to get this right, and there are much more interesting problems we can focus on at this state (i.e. trying to report the right things).

I will create a separate diagnostics epic issue, and link all these ideas there.

**Comment by kimgr** [comment]
Bundled into #1563
