### ISSUE TITLE
iwyu branch "master" failed to compile with llvm-19 

### ISSUE THREAD

**Issue by xlvy** [include-what-you-use/include-what-you-use#1574]
The system is ubuntu 18.04. I install llvm-19-dev, clang-19, and libclang-19-dev from llvm official apt sources. When compiling the master branch of iwyu, make complain the following messages:

`In file included from /usr/lib/llvm-19/include/clang/AST/Expr.h:29:0,
                 from /usr/lib/llvm-19/include/clang/AST/DeclCXX.h:22,
                 from /data/iwyu/include-what-you-use/iwyu.cc:105:
/usr/lib/llvm-19/include/clang/Basic/SyncScope.h: In member function ‘virtual bool clang::AtomicScopeGenericModel::isValid(unsigned int) const’:
/usr/lib/llvm-19/include/clang/Basic/SyncScope.h:255:14: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
     return S >= static_cast<unsigned>(System) &&
            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/iwyu/include-what-you-use/iwyu.cc: In member function ‘bool include_what_you_use::IwyuBaseAstVisitor<Derived>::VisitCastExpr(clang::CastExpr*)’:
/data/iwyu/include-what-you-use/iwyu.cc:1855:19: error: ‘CK_HLSLArrayRValue’ is not a member of ‘clang’
       case clang::CK_HLSLArrayRValue:
                   ^~~~~~~~~~~~~~~~~~
/data/iwyu/include-what-you-use/iwyu.cc:1855:19: note: suggested alternative: ‘CK_LValueToRValue’
       case clang::CK_HLSLArrayRValue:
                   ^~~~~~~~~~~~~~~~~~
                   CK_LValueToRValue
/data/iwyu/include-what-you-use/iwyu.cc: In member function ‘bool include_what_you_use::IwyuAstConsumer::VisitClassTemplateSpecializationDecl(clang::ClassTemplateSpecializationDecl*)’:
/data/iwyu/include-what-you-use/iwyu.cc:4090:35: error: ‘class clang::ClassTemplateSpecializationDecl’ has no member named ‘getTemplateArgsAsWritten’; did you mean ‘getTemplateArgs’?
       for (const auto arg : decl->getTemplateArgsAsWritten()->arguments())
                                   ^~~~~~~~~~~~~~~~~~~~~~~~
                                   getTemplateArgs
In file included from /data/iwyu/include-what-you-use/iwyu.cc:129:0:
/data/iwyu/include-what-you-use/iwyu_ast_util.h: In member function ‘const void* include_what_you_use::ASTNode::DynCast(const void*) const [with Ignored = void]’:
/data/iwyu/include-what-you-use/iwyu_ast_util.h:345:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
CMakeFiles/include-what-you-use.dir/build.make:75: recipe for target 'CMakeFiles/include-what-you-use.dir/iwyu.cc.o' failed
make[2]: *** [CMakeFiles/include-what-you-use.dir/iwyu.cc.o] Error 1
CMakeFiles/Makefile2:167: recipe for target 'CMakeFiles/include-what-you-use.dir/all' failed
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by kimgr** [comment]
@xlvy I think something might be wrong with the Debian packages at apt.llvm.org. We use them too for IWYU nightly builds, and even installation fails now with:
```
The following packages have unmet dependencies:
 clang : Depends: clang-19 (>= 19~) but it is not installable
 libclang-dev : Depends: libclang-19-dev (>= 19~) but it is not installable
 llvm-dev : Depends: llvm-runtime (= 1:19.0-58~exp2+0~20240303091736.15~1.gbp3b61b3) but it is not going to be installed
            Depends: llvm-19-dev (>= 19~) but it is not installable
            Depends: llvm but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
from https://github.com/include-what-you-use/include-what-you-use/actions/runs/10087788508/job/27892474114#step:2:292.

Note the llvm-runtime version number:
```
llvm-runtime (= 1:19.0-58~exp2+0~20240303091736.15~1.gbp3b61b3) 
```
20240303 sounds like it's somehow gotten stuck back in March, which matches with the missing `CK_HLSLArrayRValue` -- it landed on April 1: https://github.com/llvm/llvm-project/commit/9434c083475e42f47383f3067fe2a155db5c6a30.

**Comment by firewave** [comment]
That's the usual issue when LLVM branches. It always takes a few days (or even longer) until it is all sorted out depending of the free time of the maintainer. See https://github.com/llvm/llvm-project/issues/100466 for the upstream ticket.

You can check the news at https://apt.llvm.org/ for when the version switches have been applied.

**Comment by xlvy** [comment]
@kimgr @firewave Thank you for your detailed reply, I will keep trakcing the llvm release.

**Comment by firewave** [comment]
The branch switch on `apt.llvm.org` is complete and it should be working again now.

**Comment by kimgr** [comment]
This appears to be working again now. Closing.
