### ISSUE TITLE
Fail to build include-what-you-use as part of LLVM

### ISSUE THREAD

**Issue by mzyKi** [include-what-you-use/include-what-you-use#1631]
I git clone ```include-what-you-use``` in ```clang/tools``` like this
```
clang/tools/
├── amdgpu-arch
├── apinotes-test
├── arcmt-test
├── ......
├── include-what-you-use
```
and checkout ```clang_16``` and my llvm-project branch is ```llvmorg-16.0.6```.
when I run CMake command like the following:
```
cmake -DLLVM_CCACHE_BUILD=ON -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DLLVM_EXTERNAL_PROJECTS=iwyu -DLLVM_EXTERNAL_IWYU_SOURCE_DIR=../clang/tools/include-what-you-use -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLLVM_TARGETS_TO_BUILD=X86 -DBUILD_SHARED_LIBS=ON -DLLVM_ENABLE_Z3_SOLVER=ON -DCMAKE_BUILD_TYPE=Release ../llvm
```
I encounter a error like this:
```
/usr/bin/ld: CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o: undefined reference to symbol '_ZN4llvm3sys22getDefaultTargetTripleB5cxx11Ev'
/usr/bin/ld: /path/iwyu/build/./lib/libLLVMTargetParser.so.16: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have tried to order clangAST after clangSema in include-what-you-use/CMakeLists.txt. But nothing works.
If someone familiar with it, thanks for your help!

**Comment by mzyKi** [comment]
I find one solution to fix build error.But I am not sure whether this is correct.
Fix error by add CMake flags: ``` -DCMAKE_EXE_LINKER_FLAGS:STRING=-Wl,--copy-dt-needed-entries ```

**Comment by kimgr** [comment]
If you want to build as part of LLVM, you should be using this mode instead: https://github.com/include-what-you-use/include-what-you-use?tab=readme-ov-file#how-to-build-as-part-of-llvm. It looks like it landed in IWYU 0.19 for Clang 15, so the `clang_16` branch should have it.

**Comment by fish2bird** [comment]
> I find one solution to fix build error.But I am not sure whether this is correct. Fix error by add CMake flags: `-DCMAKE_EXE_LINKER_FLAGS:STRING=-Wl,--copy-dt-needed-entries`

It works!

And I found `llvm::sys::getDefaultTargetTriple` moved into `libLLVMTargetParser.so.17` from `libLLVMSupport.so.15`, 
'Support' in LLVM_LINK_COMPONENTS, but later not.

**Comment by kimgr** [comment]
Doesn't sound like there's much we can do from the IWYU project here. If you want to play with unsupported build configurations, you can do that without our blessing 🙂. Ok to close?

**Comment by mzyKi** [comment]
Fine,I close this issue.
