### ISSUE TITLE
gcc.stl.headers.imp broken

### ISSUE THREAD

**Issue by VReichelt** [include-what-you-use/include-what-you-use#1647]
The file `gcc.stl.headers.imp` in version 0.23.0 is broken. It contains lines in the format 
`{ "include": "<bits/atomic_futex.h>", "private", "<future>", "public" },`
but that should read
`{ "include": [ "<bits/atomic_futex.h>", "private", "<future>", "public" ] },`
instead.

This is due to the fact that `mapgen/iwyu-mapgen-libstdcxx.py` writes the wrong format
```
    for map_from, mapping_list in sorted(public_mappings.items()):
        for map_to in sorted(mapping_list):
            print('  { "include": %s, "private", %s, "public" },' %
                  (quoted(map_from), quoted(map_to)))
```
(see lines 176 and 182, maybe also lines 155 and 161).

**Comment by kimgr** [comment]
@VReichelt Yikes, thank you for the report! Looks like I tested everything but the external mappings :-(

I'll cook up a patch.

**Comment by kimgr** [comment]
Fixed on master.
