### ISSUE TITLE
Feature request: command line parameters to control output verbosity

### ISSUE THREAD

**Issue by Adriatic1** [include-what-you-use/include-what-you-use#190]
I've just discovered your tool, it's really useful.
My problem is that, when run on my project, I got 2MB result file and it is hard to work with so much info :(

I noticed that, for each file, there are 3 sections of the output:
1. "... should add these lines:"
2. "... should remove these lines:"
3. "The full include-list for ..."

Is it possible to have a parameter to exclude the last (3rd) block of text in the output. After all, 3rd block can be deduced by combining 1st and 2nd block. And it would cut down the output size considerably.

**Comment by kimgr** [comment]
We already have too many arguments, IMHO, and I'm reluctant to add any more.

We've discussed other output formats (unified diff, json, xml), but haven't come around to it yet.

Lately we've started using IWYU more where I work, and we actually use the third block more than the others -- we just copy the third block over to the source file and eye-check it quickly so nothing seems crazy.

**Comment by vsapsai** [comment]
By the way, `fix_includes.py` is [using "The full include-list for..."](https://github.com/include-what-you-use/include-what-you-use/blob/master/fix_includes.py#L291). Don't know if it will work without it.

**Comment by Adriatic1** [comment]
OK, it's your decision.

**Comment by BradleySmall** [comment]
I have had similar issues. Since we don't blindly apply the results (which definitely wouldn't work in our codebase due to portability issues as well as posix compatibility and other concerns.) I have written an awk script that filters out the third block, as well as the few suggestions that we never wish to include.

**Comment by kimgr** [comment]
Bundled into #1563
