### ISSUE TITLE
iwyu_preprocessor.h can’t find clang::MacroDefinition’s definition

### ISSUE THREAD

**Issue by linkmauve** [include-what-you-use/include-what-you-use#192]
This makes master fail to build on an up to date ArchLinux, with clang 3.6.1 on llvm 3.6.1.

When I define `class MacroDefinition;` on line 79, the error then transforms into `error: '…' marked 'override' but does not override any member functions`.

**Comment by kimgr** [comment]
IWYU `master` follows Clang trunk. Try the `clang_3.6` branch instead.

**Comment by nickdesaulniers** [comment]
indeed, WFM:
```
git checkout -b clang_3.6 origin/clang_3.6
cmake -DIWYU_LLVM_ROOT_PATH=/usr/local/lib/llvm-3.6/ ..
make
```

**Comment by linkmauve** [comment]
I can confirm the clang_3.6 branch is working, and since it doesn’t have any non-documentation change aside from the one in this issue I made the include-what-you-use-git package in AUR use this branch: https://aur4.archlinux.org/packages/include-what-you-use-git

Thanks! :)
