### ISSUE TITLE
Compatibility with LLVM/Clang 3.7

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#194]
LLVM/Clang 3.7 were branched three days ago and Release Candidate 1 was tagged yesterday.

I think will be good idea to start port to LLVM/Clang 3.7.

**Comment by kimgr** [comment]
Yes, I noticed the branch e-mail. I'll pull the latest trunks and see that we're still compatible.

**Comment by kimgr** [comment]
IWYU trunk is still compatible with Clang 3.7, so we'll hold off the branch until 3.7 is released or diverges. That way we don't have to merge any IWYU patches to the release branch for no good reason.

Thanks for bringing it up though, I found a new compatibility issue between IWYU trunk and Clang trunk; I'll send a PR for it.

**Comment by EugeneZelenko** [comment]
LLVM/Clang 3.7.0 was released today. Is it possible to create IWYU release?

**Comment by vsapsai** [comment]
IWYU release will take some time. There will be release but I cannot promise when.

**Comment by vsapsai** [comment]
include-what-you-use 0.5 compatible with llvm+clang 3.7 is released. Closing the issue.
