### ISSUE TITLE
fatal error (warning) with Linux's limits.h

### ISSUE THREAD

**Issue by zanchey** [include-what-you-use/include-what-you-use#201]
iwyu gets a bit confused by `/usr/include/limits.h` on Linux, using include-what-you-use 0.4 based on Debian clang version 3.6.1-1 (tags/RELEASE_361/final) (based on LLVM 3.6.1) and include-what-you-use 0.3 based on Debian clang version 3.5.2-1 (tags/RELEASE_352/final) (based on LLVM 3.5.2).

With the file:
```C
#include <stdio.h>
#include <limits.h>

int main () {
    int i = PATH_MAX;
    printf("PATH_MAX: %i\n", PATH_MAX);
    return 0;
}
```

iwyu produces the error:
```
In file included from min.c:2:
/usr/include/limits.h:123:16: fatal error: 'limits.h' file not found
# include_next <limits.h>
               ^

(min.c has correct #includes/fwd-decls)
```

This comes from the following excerpt in the system headers:
```
 /* Get the compiler's limits.h, which defines almost all the ISO constants.

    We put this #include_next outside the double inclusion check because
    it should be possible to include this file more than once and still get
    the definitions from gcc's header.  */
#if defined __GNUC__ && !defined _GCC_LIMITS_H_
/* `_GCC_LIMITS_H_' is what GCC's file defines.  */
# include_next <limits.h>
#endif
```

Under GCC and Clang, this ends up picking up `/usr/include/linux/limits.h`, and neither of them produce the warning.

**Comment by kimgr** [comment]
Curious, I thought `include_next` would be handled the same as with normal Clang.

Are there potentially significant differences if you run Clang with `-v` (verbose output) and IWYU with `-v`?

**Comment by kimgr** [comment]
See also https://groups.google.com/forum/#!msg/include-what-you-use/fnWULxKU61w/RCW6nOeqvdwJ -- that seems like it might be a related problem.

**Comment by zanchey** [comment]
I can't reproduce this any more - I was using the Debian packages and I think there was a mismatch between libclang and iwyu versions.

**Comment by kimgr** [comment]
OK, thanks for getting back to us!

**Comment by ashokbugude** [comment]
Can I please know how is the problem resolved ?

**Comment by zanchey** [comment]
I think the problem was that the libclang and iwyu versions I had installed were different - try making sure they are the same.
