### ISSUE TITLE
Problem with stripped path

### ISSUE THREAD

**Issue by dpunset** [include-what-you-use/include-what-you-use#210]
Hello, long time no see :)

I just encountered a problem with the function ConvertToQuotedInclude. I'll explain.

I noticed that some of the includes suggested by IWYU had a badly formed path. The name of the folder where the header exists was incomplete. I debugged it and here is what I found.

I have a filepath that reads like this as a parameter for this function:

R:/folderA/folderB/folderC/EngineServices/folderD/handle.h

The search_paths vector contains many entries to windows sdk, external middleware, and some of our own projects. One of the projects is this:

R:/folderA/folderB/folderC/Engine

When we iterate through them doing this:

for (Each<HeaderSearchPath> it(&search_paths); !it.AtEnd(); ++it) {
    if (StripLeft(&path, it->path)) {

my path is converted to this:

Services/folderD/handle.h

which is a bad path, this file doesn't exist.

A possible fix would be to apply the strip with the / at the end. If there is no /, we don't strip.

What do you think?

**Comment by dpunset** [comment]
Actually trying that fix myself I noticed that now I get absolute paths for some of the outputs, so the fix is not very good. Would the proper fix be to make sure that EngineServices is part of the search_paths ?

**Comment by dpunset** [comment]
Indeed adding EngineServices as part of the include search path (-IR:/folderA/folderB/folderC/EngineServices/) fixed the issue, but I don't see why I would have to do that since the code compiles just fine with the current command line.
Any idea what the proper fix would be?

**Comment by dpunset** [comment]
I don't know how I tested the fix before, but thinking it twice I thought it should work, so I did it again and it worked. This is the modification I did:

for (Each<HeaderSearchPath> it(&search_paths); !it.AtEnd(); ++it) {
    string itPath = it->path + "/";
    if (StripLeft(&path, itPath)) {

Also I guess that this line is not needed then:

StripLeft(&path, "/");

Sorry for posting so much :_D

**Comment by vsapsai** [comment]
Cannot tell for sure if it is the right fix. Sounds reasonable, though.

I want to clarify how exactly is `R:/folderA/folderB/folderC/EngineServices/folderD/handle.h` included in code? And how is it found without `EngineServices` being in include search paths? Asking to reproduce it in a test case.

**Comment by dpunset** [comment]
the structure of the folders is like this

r:/folder/solution/
r:/folder/solution/libA
r:/folder/solution/libB
r:/folder/solution/libC
...

The search path is like this:

r:/folder/solution

And in every .cpp/.h code is included like this:

#include "libA/myheader.h"
#include "libB/myheader2.h"
etc...

By the way, I noticed that I was indeed getting some absolute paths on the report after applying my fix. I realized that if you have my fix, you must normalize a bit the paths on the search headers, so for example they must be like this:

"r:\folderA\folderB"   -> good
"r:\folderA\folderB\"  -> bad

this is just so that you don't end up with "\\" when doing the strip and then it's not able to find the search path used.

Like I said, I am not sure if this is the best solution you can have but it seems to do the trick.

**Comment by kimgr** [comment]
Hey, welcome back! :-)

Sorry, this got lost in my inbox for a few days.

This looks a little risky:

    string itPath = it->path + "/";

I think it would be more correct to only add the "/" if it doesn't already exist. And the paths in `search_paths` would need to be forward-slash-normalized first.

It would be great to have a unit test for this, I'm sure this code is under test somewhere in more_tests, we just still haven't managed to include that in the build :-/

**Comment by dpunset** [comment]
Hey Kim! :)

Yep, it's what I mentioned at the end of my last post.

**Comment by vsapsai** [comment]
Looks like I was able to reproduce the bug with the following directory structure:

```c++
// tests/issue210/Engine/engine.h
class Engine {};

// tests/issue210/EngineServices/handle.h
class Handle {};

// tests/issue210/test.h
#include "tests/issue210/EngineServices/handle.h"

// tests/issue210/test.cc
#include "tests/issue210/test.h"
Handle h;
```

And run IWYU like `include-what-you-use -I . -I tests/issue210/Engine tests/issue210/test.cc`. Please note that I have added 2 search paths with `-I`. @dpunset, does it resemble your code?

**Comment by dpunset** [comment]
Hi,

Yes it does. Thank you.

David

**Comment by kimgr** [comment]
This sounds like a pretty straightforward fix, can you come back with a small patch that does it? Just paste the changes inline in a comment, or create a pull request, whichever is most convenient for you.
