### ISSUE TITLE
Install fix_includes.py and iwyu_tool.py

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#211]
I think will be good idea to include helper scripts (fix_includes.py and iwyu_tool.py) into installation.

Such scripts are installed for Clang-format and Clang-tidy. See http://reviews.llvm.org/rL247890 for Clang-tidy implementation for CMake and configure.

**Comment by kimgr** [comment]
Thanks, I agree. I accidentally missed iwyu_tool.py for the 3.6 release, but I think fix_includes.py was included. I'll make sure to update my packaging scripts for Windows and FreeBSD before the 3.7 release.

**Comment by EugeneZelenko** [comment]
I'm not sure about packaging scripts, but I think installation should be part of CMakeLists.txt/Makefile.

**Comment by kimgr** [comment]
Yeah, I haven't mustered the energy to read up on CMake install steps. Patches welcome :-)

**Comment by EugeneZelenko** [comment]
It's very trivial 2 line fix. See link in original post.

**Comment by kimgr** [comment]
Oh, cool. I can integrate that and see if I can use CMake more effectively for packaging.

I'm in the middle of something else at the moment, but it makes sense to me that the scripts would be included in the install() section. I'll pick it up when I can.

**Comment by kimgr** [comment]
Ping, see referenced PR #219

**Comment by EugeneZelenko** [comment]
Thank you for help!

However I think will be good idea to install them to share/clang, since Python is platform independent. This will be consistent with other similar scripts location.

**Comment by kimgr** [comment]
I've read the FHS such that share/ is for data files. And I see various Python scripts in my /usr/local/bin, so I would prefer to put them next to the IWYU executable.

IWYU and Clang are not intimately related in a way that I want to put scripts inside Clang's directories.

**Comment by kimgr** [comment]
Where are we with this? I don't have enough Unix experience to know whether `/usr/local/bin` or `/usr/bin` is a good place for scripts, or if `share/` is the way to go. I'll leave it to any self-proclaimed expert :-)

**Comment by daveisfera** [comment]
For what it's worth, on Fedora/RHEL, they are installed in `%bindir` (which maps to `/usr/bin`).

**Comment by kimgr** [comment]
I'd prefer that as well, to make sure they're in the PATH, the same way as `include-what-you-use` itself. I'll make an effort to get the PR as-is merged, thanks!
