### ISSUE TITLE
Multiple test failures.

### ISSUE THREAD

**Issue by Earnestly** [include-what-you-use/include-what-you-use#217]
* clang 3.7.0

*(If there are any other dependencies you need to know, please ask and I'll update them here.)*

Running the tests results in a total of 8 failures.  A lot of them seem strange such many comments about `Unmatched regex:` which might indicate a deeper issue.

Since the output is long, I'll host it [here (gist)](https://gist.github.com/Earnestly/b6149a6d1f44ce173a1b) instead.

Do any of these seem genuine?  Ideally the checking phase of a build should not ignore failures because that somewhat defeats the point of testing but sometimes that is necessary such as glibc's tests being known to fail on certain architectures.

**Comment by kimgr** [comment]
In my experience, it depends mostly on which standard library you're using.

IWYU originated in Google and was built against their specific gcc, glibc and libstdc++ versions, I'm not sure exactly what they are/were. I had it working on a relatively standard Ubuntu 14.04.

Three failures are expected on Windows, and I see one on FreeBSD, both due to standard library differences, as far as I know.

**Comment by Earnestly** [comment]
For what it's worth I'm currently using:

* glibc 2.22.r223.g050f29c-1
* gcc 5.2.0

**Comment by vsapsai** [comment]
It is hard to tell for sure but I suspect that a lot of test failures are caused by
> fatal error: 'stddef.h' file not found

Here is what [Clang docs say about it](http://clang.llvm.org/docs/FAQ.html#i-get-errors-about-some-headers-being-missing-stddef-h-stdarg-h). IWYU looks for builtin includes at a path like `../lib/clang/3.8.0/include`. Based on your setup described in issue #216 it looks likely that these builtin headers aren't there. Can you please check how many tests are still failing after this is fixed?

**Comment by kimgr** [comment]
Also: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/InstructionsForUsers.md#how-to-install

> Why do tests that are designed for different systems run on systems they
> are supposed/known to fail on?

The long-term ambition is that they should pass everywhere, and we haven't had a chance to build an XFAIL mechanism. It seems better to spend the few cycles we have on the former.

**Comment by Earnestly** [comment]
@vsapsai I'm not sure what I'm supposed to be fixing here:

```
% /usr/bin ls -l clang
lrwxrwxrwx 1 root root 9 Sep 25 15:44 clang -> clang-3.7*

% /usr/bin ls -l ../lib/clang/3.7.0/include/stddef.h 
-rw-r--r-- 1 root root 4.4K Oct  3  2014 ../lib/clang/3.7.0/include/stddef.h
```

If it's about the version `3.8.0` then I'm unsure where to make this change as
I can't see this being mentioned anywhere in the test scripts/resources or in
the output of the test results.

**Comment by Earnestly** [comment]
@kimgr That's a fair goal.  I'm just familiar with some tests where this will
never be possible (such as glibc) and find it very odd that they let you run
tests which aren't appropriate unless doing cross-compiliation is used.

It is just makes me feel uneasy to essentially brute-force success for these
cases such as `./run_tests || true` as it feels almost self-defeating.  Indeed
as the situation is automated it feels almost like a waste of time unless you
gather logs regardless of failure and failure is known via a non-zero return 
value.

But I understand anyway, thanks for the rational.

**Comment by vsapsai** [comment]
`include-what-you-use` binary should be in a place where doing a relative `../lib/clang/$version/include` is correct. It's not only for tests, that's what IWYU requires.

**Comment by Earnestly** [comment]
Sorry, but this is simply a build for a package.  It should need to be moved to an unpriviledged location at all.

More specifically, a build of any software should not need it to be installed before it can be tested...

**Comment by vsapsai** [comment]
I agree the experience is crappy. If you don't want to install `include-what-you-use` alongside `clang`, you have to copy builtin headers next to `include-what-you-use`.

This is a long-standing issue. For example, @kimgr [has asked on Clang mailing list](http://lists.llvm.org/pipermail/cfe-dev/2014-April/036513.html) what is the recommended way to provide these headers. There is no ready solution and we didn't get to implementing our own yet. Patches as always are welcome.

**Comment by vsapsai** [comment]
@Earnestly, can you please check how many are there test failures when IWYU can find builtin headers?

**Comment by Earnestly** [comment]
@vsapsai All of the tests pass if using a pre-installed binary in an appropriate location.

**Comment by daveisfera** [comment]
I'm seeing a similar issue when building master on Fedora Rawhide (24). You can see the details in build.log of the scratch build that I did ( http://koji.fedoraproject.org/koji/taskinfo?taskID=11286827 ).

The foo.cc example shown by Earnestly will build fine in the Fedora Rawhide setup where the tests fail and I'm running the tests in the same manner that I have in the past. Is there something that I need to change with this update?

**Comment by kimgr** [comment]
@daveisfera, @Earnestly: You both mention being able to build/compile the `foo.cc` example -- do you both mean with an installed clang/clang++?

If so, that's expected -- Clang will install its headers in the right place *for Clang*, but unless IWYU is in the directory as Clang, it won't be able to find them.

An IWYU package that installs where Clang is not installed must bring the built-in headers along. Unfortunately that runs the risk of "hijacking" the header path if you were to install Clang later. So this is all a bit confused with Clang tools, they're sort-of independent and yet not.

**Comment by Earnestly** [comment]
Yeah, the problem here is with clang itself.  It's very unfortunate.  Perhaps an additional flag to the test tool might be able to provide a path to clang's headers instead of using relative lookups?  I'm sure about this as it sounds a little ugly too and might be quite complex in implementation...

:-(

**Comment by daveisfera** [comment]
Sorry, my original comment was based on adding PWD to PATH would make the tests pass in any directory (which used to be the case) and then my second comment didn't explain well that this has changed with the current release.
Anyways, I put back in the symlinks during the testing in the Fedora packaging and it works now ( http://koji.fedoraproject.org/koji/taskinfo?taskID=11325303 ).

**Comment by kimgr** [comment]
@daveisfera -- that sounds like the other bug, #216, did you get them mixed up?

**Comment by daveisfera** [comment]
Yes, sorry. The original comment was on #216 and that had started the testing of the current build to identify this issue, but it technically wasn't related and I forgot that. But, the remainder of the comment is true and the current version passes all test when I put the symlinks back.

**Comment by vsapsai** [comment]
> Perhaps an additional flag to the test tool might be able to provide a path to clang's headers instead of using relative lookups?
> I'm not sure about this as it sounds a little ugly too and might be quite complex in implementation...

I don't think it is worth doing, @Earnestly. If you need to do something special, it is better to copy headers nearby or add a symlink. And it will work not only for tests but also for other purposes.

**Comment by Earnestly** [comment]
Oh I know, even though it's still somewhat ugly (ever use of symlinking is a hack because Linux lacks proper bind unions) there's not much room given to do things right here and it's not your fault.

As you say, it's probably even hackier to change this so symlinking will have to do, unfortunately.
