### ISSUE TITLE
Add SSL to binary downloads page

### ISSUE THREAD

**Issue by jasonmp85** [include-what-you-use/include-what-you-use#222]
I've got a [homebrew formula](https://github.com/jasonmp85/homebrew-iwyu) for `iwyu`, and while the [checksum](https://github.com/jasonmp85/homebrew-iwyu/blob/d4d549367d323468d148b5ba237cbcdb2a3c951c/iwyu.rb#L24-L27) is a _pretty major_ safeguard, it would still be nice if I could depend on secure transport when [downloading binaries](http://include-what-you-use.org/downloads/).

Is there a place this is provided? Slapping `https://` before `include-what-you-use.org` doesn't appear to work.

**Comment by vsapsai** [comment]
Good suggestion, @jasonmp85. Current include-what-you-use.org configuration doesn't allow to add SSL certificate easily but it is definitely worth doing.

**Comment by vsapsai** [comment]
[Let's Encrypt](https://letsencrypt.org/) looks like a good option. Definitely worth investigating further.

**Comment by jasonmp85** [comment]
Uh, any traction here?

**Comment by ThosRTanner** [comment]
especially as microsoft defender thinks v0.6 contains a trojan

**Comment by jasonmp85** [comment]
Bump. This is important.

**Comment by vsapsai** [comment]
Using Let's Encrypt certificate is going to take more time than I expected. Now I am testing alternative approach with test.include-what-you-use.org Hope I'll be able to show something by the end of the week.

**Comment by vsapsai** [comment]
Please test https://include-what-you-use.org/ I also plan to add HSTS and HTTP-to-HTTPS redirection a little bit later. But it should be good to test and use.

**Comment by kimgr** [comment]
Nice! Works for me, with and without intrusive HTTPS proxy.

**Comment by vsapsai** [comment]
There is no way to add HSTS easily so I'm not going to do that. Though added HTTP-to-HTTPS redirection so now everything is working through https://include-what-you-use.org Except of buildbot but that's another story, much more involved.
