### ISSUE TITLE
Could IWYU be more user friendly if you've made a mess of your mapping file

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#230]
For instance if I have a line that says

    { include: [ "header", "private", "another header", "public"] }

I get an assertion error and I have no idea which part of the file it is objecting to.

**Comment by kimgr** [comment]
Can you be more specific here? What does your mapping file look like (reduced), and what does the assertion error say?

**Comment by ThosRTanner** [comment]
That's the line in question. The assertion says that the map key is not a regex or a filename.

    >include-what-you-use.exe -I c:\Apps\include-what-you-use\bin -Xiwyu --mapping_file=test.imp test.cc
    D:\dev\private\llvm-36\llvm\tools\clang\tools\include-what-you-use\iwyu_include_picker.cc:1037: Assertion failed: IsQuotedFilepathPattern(map_from) && "All map keys must be quoted filepaths or @ followed by regex"

**Comment by kimgr** [comment]
Thanks, it would make sense to be more specific here. The CHECK_ is from before there were external mappings.

**Comment by delaitre** [comment]
@ThosRTanner you can run with `--verbose=8` to get more debug output. I was just hit by the same assert 1h ago and increasing verbosity will print the `map_from` and `map_to` values, which is then easy to spot in your mapping file.

**Comment by ThosRTanner** [comment]
verbose = 8? wow
