### ISSUE TITLE
including <bits/socket_type.h> is suggested by iwyu, while the file itself forbids it

### ISSUE THREAD

**Issue by pseyfert** [include-what-you-use/include-what-you-use#245]
i just tried iwyu on [cern root](https://github.com/pseyfert/root/tree/includewhatyouneed). Mostly successful. (I also saw #90)
One file which gets wrongly suggested to me is:
> /home/pseyfert/coding/ROOT6/roofit/roofitcore/src/BidirMMapPipe.cxx should add these lines:
> #include <bits/socket_type.h>           // for SOCK_STREAM
when doing so, compilation fails because bits/socket_type.h contains the lines:
> #ifndef _SYS_SOCKET_H
> # error "Never include <bits/socket_type.h> directly; use <sys/socket.h> instead."
> #endif
(socket.h is also suggested, they only end up in the wrong order)

**Comment by vsapsai** [comment]
Thanks for the report. It is not clear how did we end up in this situation because there is [a mapping from `<bits/socket.h>` to `<sys/socket.h>`](https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_include_picker.cc#L311).

**Comment by kimgr** [comment]
There doesn't appear to be a mapping from socket_type.h, only socket.h. Also, I still like my attempt at heuristic here, would solve this automatically: https://github.com/include-what-you-use/include-what-you-use/issues/109#issuecomment-111948176

**Comment by vsapsai** [comment]
You are right, Kim. I mixed up `socket.h` and `socket_type.h`. Do you think it is worth marking with some label issues that we've made progress on? Because I completely forgot about issue #109.

**Comment by kimgr** [comment]
Sure, that sounds useful. Maybe both a general status and a more specific root-cause tag, so we can group issues with the same root cause together?

I added a pull request here with a mapping:
https://github.com/include-what-you-use/include-what-you-use/pull/251

**Comment by vsapsai** [comment]
I agree, both a general status and root-cause tags can be useful.
