### ISSUE TITLE
IWYU incorrectly suggests removing declaration used as friend with a global namespace qualifier

### ISSUE THREAD

**Issue by salty-horse** [include-what-you-use/include-what-you-use#254]
For this file:
```cpp
class Bar;
class Foo {
friend class ::Bar;
};
```

Latest IWYU 9929f88f94f704fcf02bc3a924d77c8f905ace58 incorrectly suggests removing ```class Bar;```, which brakes compilation.

**Comment by vsapsai** [comment]
Thanks for report, @salty-horse, that's a good catch. Looks like IWYU got confused by global namespace qualifier. It treated it like `friend class Bar;` which works fine without `class Bar;` forward declaration.
