### ISSUE TITLE
Compile error "too many sections" on windows/msys2/mingw-w64/gcc

### ISSUE THREAD

**Issue by realazthat** [include-what-you-use/include-what-you-use#256]
Compile on Windows 7, in the msys2 environment, with gcc compiler and mingw-w64 runtime headers/libs got me the error `too many sections` and a compile fail.

Here is some console io:

```
realz@realz-PC MINGW64 ~/include-what-you-use/build
$ make
Scanning dependencies of target include-what-you-use
[  7%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu.cc.obj
In file included from K:/realz/dump/mingw-w64/msys64/home/realz/include-what-you-use/iwyu_ast_util.h:19:0,
                 from K:/realz/dump/mingw-w64/msys64/home/realz/include-what-you-use/iwyu.cc:104:
K:/realz/dump/mingw-w64/msys64/home/realz/include-what-you-use/port.h:68:0: warning: "NOMINMAX" redefined
 #define NOMINMAX  // Prevent Windows headers from redefining min/max.
 ^
In file included from K:/realz/dump/mingw-w64/msys64/mingw64/include/c++/5.2.0/x86_64-w64-mingw32/bits/c++config.h:482:0,
                 from K:/realz/dump/mingw-w64/msys64/mingw64/include/c++/5.2.0/utility:68,
                 from K:/realz/dump/mingw-w64/msys64/mingw64/include/c++/5.2.0/algorithm:60,
                 from K:/realz/dump/mingw-w64/msys64/home/realz/include-what-you-use/iwyu.cc:93:
K:/realz/dump/mingw-w64/msys64/mingw64/include/c++/5.2.0/x86_64-w64-mingw32/bits/os_defines.h:45:0: note: this is the location of the previous definition
 #define NOMINMAX 1
 ^
K:/realz/dump/mingw-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/include-what-you-use.dir/iwyu.cc.obj: too many sections (38804)
K:\realz\dump\mingw-w64\msys64\tmp\ccY0rz3g.s: Assembler messages:
K:\realz\dump\mingw-w64\msys64\tmp\ccY0rz3g.s: Fatal error: can't write CMakeFiles/include-what-you-use.dir/iwyu.cc.obj: File too big
K:/realz/dump/mingw-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/include-what-you-use.dir/iwyu.cc.obj: too many sections (38804)
K:\realz\dump\mingw-w64\msys64\tmp\ccY0rz3g.s: Fatal error: can't close CMakeFiles/include-what-you-use.dir/iwyu.cc.obj: File too big
CMakeFiles/include-what-you-use.dir/build.make:62: recipe for target 'CMakeFiles/include-what-you-use.dir/iwyu.cc.obj' failed
make[2]: *** [CMakeFiles/include-what-you-use.dir/iwyu.cc.obj] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/include-what-you-use.dir/all' failed
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

The solution (after googling the issue) was to pass in `Wa,-mbig-obj` to the CXX_FLAGS:

```
realz@realz-PC MINGW64 ~/include-what-you-use/build
$ cmake -G"MSYS Makefiles" .. -DIWYU_LLVM_INCLUDE_PATH=/home/realz/.local/include/ -DIWYU_LLVM_LIB_PATH=/home/realz/.local/lib -DCMAKE_CXX_FLAGS=-Wa,-mbig-obj  -DCMAKE_VERBOSE_MAKEFILE=1
```

Not sure if you want to put this conditionally in the CMakeLists.txt, but I'll just leave this here for any future users who come across the issue.

**Comment by kimgr** [comment]
Thank you! Maybe we should look into trying to shrink iwyu.cc; it's huge and takes too long to compile on most platforms.

For now, I'll put the bigobj switch in for MINGW (I think CMake has a config point to detect it.)

**Comment by kimgr** [comment]
There, can you try the new PR, and make sure it helps? Thanks!

**Comment by realazthat** [comment]
@kimgr Any chance a new error was introduced?

> ```
K:/realz/dump/mingw-w64/msys64/home/realz/include-what-you-use-fork/include-what-you-use/iwyu_ast_util.cc: In function 'std::map<const clang::Type*, const clang::Type*> include_what_you_use::GetTplTypeResugarMapForFunctionExplicitTplArgs(const clang::FunctionDecl*, const clang::TemplateArgumentListInfo&)':
K:/realz/dump/mingw-w64/msys64/home/realz/include-what-you-use-fork/include-what-you-use/iwyu_ast_util.cc:716:59: error: 'const class clang::TemplateArgumentListInfo' has no member named 'arguments'
   for (const TemplateArgumentLoc& loc : explicit_tpl_list.arguments()) {
                                                           ^
CMakeFiles/include-what-you-use.dir/build.make:86: recipe for target 'CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.obj' failed
make[2]: *** [CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.obj] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/include-what-you-use.dir/all' failed
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
```

**Comment by kimgr** [comment]
There's been a breaking change in Clang trunk after the 3.7 branch, and we keep our master compatible with Clang trunk.

You seem to be building against Clang 3.7, so you could do something like:

    $ git checkout remotes/origin/clang_3.7
    $ git cherry-pick a629cbf

to copy the change over to a branch compatible with Clang 3.7.

Hope that helps.

**Comment by realazthat** [comment]
@kimgr it worked (i tried your branch with the latest clang), I no longer got that particular error, but linking indeed takes so long as to fail (the last attempt is still ongoing, for hours). However, i think your check for MSYS specifically is not a good idea, because you can build with many compilers under MSYS, including MSVC, where such an option would almost certainly break things. The check should prolly be for MINGW.

**Comment by kimgr** [comment]
@realazthat Thanks for the clarification, I wasn't sure whether to pick MSYS or MINGW. Will switch in a follow-up (where can I read about MSYS and MINGW? I've never gotten my head around exactly what they are.)

As for your link time, that sounds extreme, but it takes several minutes for me on Windows as well. Do you have a low-end machine (<8GB RAM)?

**Comment by cdglove** [comment]
>
> @realazthat <https://github.com/realazthat> Thanks for the clarification,
> I wasn't sure whether to pick MSYS or MINGW. Will switch in a follow-up
> (where can I read about MSYS and MINGW? I've never gotten my head around
> exactly what they are.)
>

Here's some good info from the MSYS2 project. Which is what I personally
use when I'm using windows.

http://sourceforge.net/p/msys2/wiki/MSYS2%20introduction/

-- chris

>

**Comment by realazthat** [comment]
@kimgr I've got 16 GB of active RAM; I think it is just an artifact of it being so large, `ld` eventually finished but somehow the console didn't get the message. When I `ctrl-c`, i got a sudden huge spurt of linker errors, apparently still a version mismatch in clang, I am assuming that's my fault. Anyway, that is beside the point, the solution *seems* to work, except I can't get a final executable because of version mismatch.

**Comment by kimgr** [comment]
Thanks for all the help!
