### ISSUE TITLE
on fixing includes in headers

### ISSUE THREAD

**Issue by rhl-** [include-what-you-use/include-what-you-use#268]
Hi,

I apologize I don't find it clear from the instructions, how exactly do you process header files with this tool? I can make it process all the cpp files by using:
`    make -k CXX=/path/to/include-what-you-use > /tmp/iwyu.out`
however, it does not just header files I see the note:

> Include-what-you-use only analyzes .cc (or .cpp) files built by make, along with their corresponding .h files. If your project has a .h file with no corresponding .cc file, IWYU will ignore it unless you use the --check_also switch to add it for analysis together with a .cc file.

but, I do not understand two things:

1. how do I use this option in tandem with the "make" instruction above?
passing
 `CXXFLAGS=-Xiwyu --check_also=foobar.h` 
doesn't appear to do anything
2. how do I specify multiple headers? 
For example, I have 500 different headers, do I list `--check_also= header1 --check_also=header2 `? I see in some documentations they can do regex, but, will that search recursively through file directories?

**Comment by vsapsai** [comment]
> how do I use this option in tandem with the "make" instruction above? passing `CXXFLAGS=-Xiwyu --check_also=foobar.h` doesn't appear to do anything

I don't know about `make` enough to tell how to give it extra options. Personally I would try to create some wrapper `include-what-you-use-wrapper.sh` that invokes include-what-you-use with `--check_also`. Not sure if it will work, pretty sure there are better ways to do this.

> how do I specify multiple headers? For example, I have 500 different headers, do I list `--check_also= header1 --check_also=header2`? I see in some documentations they can do regex, but, will that search recursively through file directories?

`--check_also` accepts glob pattern and [uses system-provided pattern matching function](https://github.com/include-what-you-use/include-what-you-use/blob/master/port.h#L76-L85). So I expect it to search recursively. But it won't add new files to compilation. For example, if you have
```c++
// foo.cpp
#include "foo.h"
```
and execute `include-what-you-use -Xiwyu --check_also=bar.h foo.cpp`, it still won't process `bar.h` because it is not included by anyone in this compilation.

**Comment by rhl-** [comment]
just now I ended up doing just that, since I couldn't get check_also to function for me, I ended up handing the .hpp files instead of .cpp files. That seems to basically work, there were a few errors to clean up. Now I am processing the .cpp files, and it seems that again, there are some errors to cleanup.

**Comment by kimgr** [comment]
We run include-what-you-use directly on header files in our setup, something like:

$ find . -name "*.h" | xargs include-what-you-use <flags>
$ find . -name "*.cpp" | xargs include-what-you-use <flags>

And we've cheated and apply the same flags to all files, basically a union of all possible CXXFLAGS (we don't have a lot of variation, so this works for us). That way we don't have to find the correct CXXFLAGS for every header.

**Comment by rhl-** [comment]
Thanks guys. would it be possible for iwyu to do a better job if it was analyzing all of these files together?

**Comment by kimgr** [comment]
Maybe :-)

I'm not so sure, though. There are basically two different kinds of headers (in this context);

1) associated headers -- headers defining the public interface of a .cpp file. IWYU treats these two as a unit, and attempts to optimize for both of them (e.g. move things only used in the implementation to the .cpp file, remove redundancy between them, etc.)

2) freestanding headers -- these could e.g. define inline utility functions, abstract base classes, portability macros, etc. Such headers are typically included by a large number of other headers and .cpp files, but there's no corresponding .cpp file to analyze them through.

I think of these free-standing headers as .cpp files in their own right. Making them compile independently of other code really helps avoid weird implicit header dependencies and include order problems.

Unfortunately, as far as I can see, there's no way for IWYU to magically know whether header `foo.h` is a freestanding project header we want to analyze, or some random third-party header we don't. It does know the difference between associated headers and others.

But if you can use heuristics to find them, you can typically run IWYU on them directly with the right CXXFLAGS.

**Comment by sesse** [comment]
FWIW, I had problems getting --check_also= to work as well, until I gave the full path to the file. The globbing doesn't seem to work too well (in particular, neither * nor ** seems to match a slash).

**Comment by kimgr** [comment]
@sesse: thanks for the datapoint. What platform are you on?

**Comment by sesse** [comment]
Debian testing, using the IWYU package from there (3.7-1).

**Comment by asurti9** [comment]
Hello @kimgr ,
As you mentioned in the previous comments:
`associated headers -- headers defining the public interface of a .cpp file. IWYU treats these two as a unit, and attempts to optimize for both of them (e.g. move things only used in the implementation to the .cpp file, remove redundancy between them, etc.)`
Is there any way where we can treat .cpp and .h as separate unit and explicitly add common headers in both cpp and h files?

**Comment by kimgr** [comment]
@asurti9 Nope, not as far as I know. That said, I've seen a few cases lately where redundancy between .h/.cpp is not removed, so not sure what the policy is there, actually.
