### ISSUE TITLE
Same directory not detected as include paths

### ISSUE THREAD

**Issue by Flamefire** [include-what-you-use/include-what-you-use#271]
I have a file which misses an include to a header in the same directory. iwyu suggests including that header by its full path but the relative path (just the header name) is enough.
I'd consider this a major defect, as absolute paths to project headers will most likely break building on other systems.

Note: I'm using the iwyu_tool.py with a CMake build database on an in-source build (subfolder however)

**Comment by Flamefire** [comment]
This also causes an interesting side-effect as described in #272: If you have a header in the same directory as a cpp file, that is included by the associated header, this header is suggested to add, also it should not. This goes away, when explicitly specifying the cpps directory via `-I`

Testcase: https://github.com/include-what-you-use/include-what-you-use/files/142703/incTest.zip

- running iwyu from inside the directory of the cpp results in correct includes :+1:
- using the absolute path of the cpp suggests adding the header :-1:
- running iwyu from the parent folder and specifing a relative path to the cpp suggests adding the header :-1:
- adding the path to the cpp via `-I` (either absolute or relative) results in correct includes :+1:

**Comment by kimgr** [comment]
Thank you for this rundown! I wonder if this is the same issue as #5 (our oldest bug), they definitely look similar.

I don't have much time to look at this until next week, but I'd love to dig deeper here, and try to find a solution.

**Comment by Flamefire** [comment]
Yes this seems to be a part of #5.
My idea would be, that includes are stored as absolute paths in the iwyu database so the same include even when spelled differently is always recognized. This would fix the issue in #272 
On picking an `#include` directive there should be a choice made, how to abbreviate the path. First impulse would be to go through search paths (converted to absolute paths) and then choose the shortest name. Otherwise one can choose the next-best spelling already found. So if the include appears in a header in the same directory, the same spelling is chosen. If not, pick just any spelling found if it is valid according to the search paths.
I'd even make this an option `--suggest-shortest-paths`

**Comment by kimgr** [comment]
> First impulse would be to go through search paths (converted to absolute paths) and
> then choose the shortest name

See https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_path_util.cc#L181 -- there is logic like this. But it sounds like it's the reverse of what you're suggesting. Can you experiment with variations on this algorithm and see if you can figure out something that would work for you (and the existing test cases)?

**Comment by Flamefire** [comment]
Yes this is the correct position. However I think the error is here: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_path_util.cc#L202

The implicit `-I.` is not exactly this. It should be the directory of the current file. This is not taken into account when dealing with absolute paths.

**Comment by Flamefire** [comment]
@kimgr I think I fixed this properly :) Please have a look at the PR I just opened.

**Comment by kimgr** [comment]
Fixed by 23119ba via PR #276.
