### ISSUE TITLE
Release compatible with LLVM/Clang 3.8

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#278]
Hi!

LLVM/Clang 3.8 is very close to release. What are plans to release compatible version of IWYU?

**Comment by kimgr** [comment]
Now is the perfect time to take a `clang_3.8` branch -- something just changed in LLVM/Clang that broke our build :-)

I think we should be able to drop a new IWYU release closer to Clang this time, we have most of the infrastructure in place now.

**Comment by vsapsai** [comment]
I have merged changes from `master` to `clang_3.8` branch (except of 32d04ee and 380c96a reverting it). I'd like to have fix for issue #109 in this release but cannot promise I'll finish it soon. Are there any other changes you want to have in this release?

**Comment by kimgr** [comment]
Your #109 fix looks promising and I'm also really keen on getting the work by @Flamefire into place.

But I really don't think we need block the 0.6 release on either of them, there's already lots of good stuff in there already.

I'm on the fence -- I'm in no rush to release, but some people seem eager to get an IWYU compatible with Clang 3.8, presumably because the Clang builtin headers are not compatible with IWYU 0.5... Or is there an even more pressing reason?

**Comment by EugeneZelenko** [comment]
I think will be good idea to release IWYU simultaneously with Clang or with little delay.

We build LLVM/Clang in-house, so it's much easier for IT to do job once.

**Comment by daveisfera** [comment]
Doing the release close in timing with LLVM/Clang would be nice, but my workaround for the time being in Fedora is to just do a "pseudo-RC" with the trunk/branch of iwyu at the time when LLVM/Clang is updated in Fedora.

**Comment by brad0** [comment]
Any chance of a release soon? Updating the OpenBSD LLVM package to 3.8 and this is the only project broken with 3.8 (0.5 release)

**Comment by kimgr** [comment]
OK, let's do this. I just uploaded Windows and FreeBSD release archives built from the `clang_3.8` branch.

@vsapsai, can you build for Ubuntu and Darwin?

I'll look into creating a source package and see if I can update the web site.

**Comment by kimgr** [comment]
Source package uploaded.

Web site PR here:
https://github.com/include-what-you-use/include-what-you-use.org/pull/4

I'll let @vsapsai drive the rest of this, he know the release procedure better than I do.

**Comment by vsapsai** [comment]
OK, I pushed `clang_3.8` tag. Will upload archives and update site on weekend.

@brad0, is branch and tag enough for updating the OpenBSD LLVM package?

**Comment by brad0** [comment]
I just need the tarball that goes up on the website. Our ports / packages framework fetches that to build.

**Comment by vsapsai** [comment]
Uploaded source tarball, please try http://include-what-you-use.org/downloads/include-what-you-use-0.6.src.tar.gz

**Comment by mmlb** [comment]
@vsapsai that tarball warns about missing IWYU git version.

```
-- The C compiler identification is GNU 6.1.1
-- The CXX compiler identification is GNU 6.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IWYU out-of-tree configuration
-- Found Git: /usr/bin/git (found version "2.8.2") 
-- Warning: IWYU Git version info not found, DO NOT release from this build tree!
-- Found Curses: /usr/lib64/libcurses.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mmendez/pkgbuilds/include-what-you-use/src/include-what-you-use
Scanning dependencies of target include-what-you-use
[ 14%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o
[ 14%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu.cc.o
[ 28%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o
[ 28%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o
[ 35%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o
[ 42%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o
[ 50%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o
[ 57%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o
[ 64%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o
[ 71%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o
[ 78%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o
[ 85%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o
[ 92%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o
[100%] Linking CXX executable include-what-you-use
[100%] Built target include-what-you-use
```

**Comment by kimgr** [comment]
@mmlb - hmm, yeah, the source tarball won't contain any Git version info. I put the warning there to remind us that it won't be possible to trace back from the binary to the source code version used to build it.

You probably trace that some other way if you're building a port/package, so I think you can ignore the warning. Or build from a Git checkout instead.

**Comment by mmlb** [comment]
ahh ok thanks.

OT: I've previously done something where upon tarball generation I add a file with the git info. Building from git also sends that info into the file.

**Comment by EugeneZelenko** [comment]
@vsapsai, thank you! Works for me.

**Comment by daveisfera** [comment]
0.6 has been built for Fedora [24](http://koji.fedoraproject.org/koji/taskinfo?taskID=14035379) and [Rawhide](http://koji.fedoraproject.org/koji/taskinfo?taskID=14034114).

**Comment by vsapsai** [comment]
Published everything to the website. Thanks everyone for your assistance. I was busy and couldn't make it without your help.
