### ISSUE TITLE
IWYU does not report header for removal

### ISSUE THREAD

**Issue by ggeorgiev** [include-what-you-use/include-what-you-use#295]
Hi,

I was trying to reproduce a completely different issue when I discovered this strange result. Please check https://github.com/ggeorgiev/include-what-you-use/commit/cd119a2ca4ded9ca556a3253958e5ba5a63d16e9

The test returns that the header file is correctly included, even the code in the cc file does not use anything from it.

Thanks,
George

**Comment by kimgr** [comment]
The stems for the cc file and the header are the same, so IWYU considers them associated. The associated header is never removed.

**Comment by ggeorgiev** [comment]
thanks, this explains it
