### ISSUE TITLE
gtest TYPED_TEST argument is not recognized as needed

### ISSUE THREAD

**Issue by ggeorgiev** [include-what-you-use/include-what-you-use#296]
Hi,

I tried to reproduce this in isolation without success. If some more experienced kindly take a look at this.

The code is in this file: https://github.com/ggeorgiev/dbs/blob/master/src/tpool/gtest/tpool-utest.cpp

The issue, in essence, is that when a type is used as an argument for typedef ::testing::Types when consumed from the tests through the TestFixture, is not recognized as needed and the header that provides it is suggested for removal.

Thanks,
George

**Comment by kimgr** [comment]
I'm with phone only, but could this be the same as #283?

**Comment by ggeorgiev** [comment]
I am outdoor too, but it seems so. I will go through the gtest macros to see if this is the case and let you know. Thanks.

**Comment by ggeorgiev** [comment]
It might be. There is a lot macro-wiss going on in gtest. Do you have ETA for issue #283 I can check after it is fixed to see is it fixing my case?

**Comment by kimgr** [comment]
Not really, I don't have any solid ideas for how to fix it, just some vague theories.

**Comment by jru** [comment]
Link is dead. Proposing to close unless @ggeorgiev can recover the repro.

**Comment by kimgr** [comment]
Agree. There's a good chance that it's covered by #283. Let's give @ggeorgiev a few days to report back. And thanks for picking this up!

**Comment by jru** [comment]
@ggeorgiev, if you are able to get a new repro, feel free to let us know and will reopen.
