### ISSUE TITLE
Deduce STL mappings from -stdlib

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#306]
I may be wrong, but it looks like mapping could be specified only manually with --mapping_file.

However STL implementation and its mappings could be deduced automatically from -stdlib compile command line parameters: libc++ for LLVM and libstdc++ for GCC implementation.

**Comment by vsapsai** [comment]
This will be useful when we have incompatibilities between libc++ and libstdc++ mappings. So far libstdc++-specific mappings like `{ include: ["<bits/stl_tree.h>", private, "<map>", public ] }` are safely ignored when they are not applicable.

How does Microsoft STL implementation fit in this scenario?

**Comment by kimgr** [comment]
I think --driver-mode=cl implies the MS STL, so that might be a hook to detect it if none of the others are specified explicitly.

**Comment by kimgr** [comment]
See also #377.
