### ISSUE TITLE
It'd be nice if include what you use told you *why* it felt you needed a #include

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#325]
For instance, include what you use is telling me in a QT project I need QStringList.

However, I've examined the source code and the headers it references and I cannot see any way there's a need for QStringList (admittedly this is not helped by every QT header accidentally including every other QT header). 

If it could tell me what piece of code had lead it to the conclusion a file was necessary then either I could say 'ah yes', or I could file a report with some confidence.

**Comment by Bu11etmagnet** [comment]
Don't examine the source code; that's not what the compiler (and iwyu) sees. Examine the preprocessed source.

**Comment by kimgr** [comment]
I think that's why we have so much logging in IWYU -- most of the decision paths are spewed to the log. Run with `-Xiwyu -v7` and see if you can glean something from there.

**Comment by ThosRTanner** [comment]
Ah. I've managed to interpret the output a bit better after skipping the ages of lexical analysis.

It's because there's a function prototype in the header that returns a `QStringList` which is being called by the source code in question, but then using `QStringList`'s `join` method to turn the result into a string.

So it's correct, but  the actual use is well hidden

This is at line 53:

    .... call_function_that_takes_QString(
                            info.arguments().join(" "),
    ....

Where info.arguments returns `QStringList`. That produces this with -v7

```
(For type class QStringList):
Marked full-info use of decl 0631DA00 QStringList (from C:/Apps/Qt/5.5/msvc2013/include/QTCore/qstringlist.h:93:7) at source/organizer/executableslist.cpp:53:46
source/organizer/executableslist.cpp:53:29: (14) [ ImplicitCastExpr ] 08BD64D0 ImplicitCastExpr 0x8bd64d0 <source\organizer\executableslist.cpp:53:29, col:44> 'const struct QListSpecialMethods<class QString>' <UncheckedDerivedToBase (QList -> QListSpecialMethods)>
`-CXXBindTemporaryExpr 0x8bd6418 <col:29, col:44> 'class QStringList' (CXXTemporary 0x8bd6410)
  `-CXXMemberCallExpr 0x8bd63f0 <col:29, col:44> 'class QStringList'
    `-MemberExpr 0x8bd63d0 <col:29, col:34> '<bound member function type>' .arguments 0x6639680
      `-DeclRefExpr 0x8bd63b8 <col:29> 'const class MOBase::ExecutableInfo' lvalue Var 0x8bd2810 'info' 'const class MOBase::ExecutableInfo &'
```

Along with another 100,000 lines or so of output.

So could an option be implemented that added something like "first used at line" so that this:

```
source/organizer/executableslist.cpp should add these lines:
#include <QStringList>    // for QStringList

```
becomes 

```
source/organizer/executableslist.cpp should add these lines:
#include <QStringList>    // for QStringList, first used at line 53

```

I know there's a point where iwyu decides not to output the comment, but even in that case I'd like to see something, perhaps like

```
source/organizer/executableslist.cpp should add these lines:
#include <QStringList>    // multiple reasons, first used at line 53

```

**Comment by kimgr** [comment]
> I've managed to interpret the output a bit better after skipping the pages of lexical analysis.

Yeah, that bothers me too. Anyone against removing the lexer logging?

**Comment by kimgr** [comment]
Also, I wanted to clarify this:

> Don't examine the source code; that's not what the compiler (and iwyu) sees.
> Examine the preprocessed source.

This is definitely not the case. IWYU analyzes the source code before preprocessing (or at least tries to reconstruct relevant structure before preprocessing), because IWYU operates on `#include` directives and their relation to the logical structure of the program. IWYU analysis after preprocessing would be futile.

**Comment by kimgr** [comment]
I vote to close this issue.

The logging provides all the analysis leading up to IWYU's decision, and now that we log less I think the original problem is basically solved. @ThosRTanner -- agree?

**Comment by kimgr** [comment]
We reduced logging to make it more relevant. I think logging is the feature that solves this user need, so closing.
