### ISSUE TITLE
include what you use reporting missing header with uncalled function in class

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#326]
Am tired and the computer restarted but a minimal case is something like this

header:
    class QStringList;
    struct SomeClass 
    {
        virtual QStringList somefunc() = 0;
        virtual QList<AnotherClass> getStuff() = 0;
    };

source

    struct MyClass
    {
       void myfunc(SomeClass *ptr)
        {
           for (auto thing const &ptr->getStuff()) { ... {
       }
    }

Which reports I need to include <QStringList>. 

Using iwyu on windows 10:
include-what-you-use 0.4 (645) based on clang version 3.6.1 (branches/release_36 238234)

**Comment by ThosRTanner** [comment]
Found out why iwyu was saying it was needed. Closed this issue and added more detail onto request for more information

**Comment by kimgr** [comment]
OK, thanks!
