### ISSUE TITLE
Minimum required CMake version

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#327]
Minimum required CMake version in LLVM/Clang/etc was changed to 3.4.3 recently. I think will be good idea to make it consistent in Include What You Use.

**Comment by vsapsai** [comment]
Technically, for out-of-tree builds we don't need to bump CMake version. But I think it's simpler not to deviate from LLVM+Clang here. Let's give 2 weeks for people to tell if they need CMake 2.8.

If you are using CMake version < 3.4.3 and cannot upgrade it, please notify us. If nobody expresses any objections, minimum required CMake version will be changed to 3.4.3 after 2016-06-19.

**Comment by kimgr** [comment]
We're now past the due date. I can pick this up when I have more time.

**Comment by vsapsai** [comment]
Tested with updated CMakeLists.txt, pushed change in 7554b31.

Sorry for not making the change on time, didn't have access to my IWYU work environment.
