### ISSUE TITLE
IWYU removes an include which is required for pointer arithmetic

### ISSUE THREAD

**Issue by Bothari** [include-what-you-use/include-what-you-use#332]
If a type is used in a file for pointer arithmetic, the header file defining that type still needs to be included. See attached code for an example. 

` 14:15 > ./include-what-you-use.exe c:/Users/mdyckhoff/iwyu-test/test.cpp`

`c:/Users/mdyckhoff/iwyu-test/test.cpp should add these lines:`
`class Foo;`

`c:/Users/mdyckhoff/iwyu-test/test.cpp should remove these lines:`
`- #include "foo.h"  // lines 2-2`

`The full include-list for c:/Users/mdyckhoff/iwyu-test/test.cpp:`
`class Foo;`
`---`

However if I perform this change, the file will not compile, with the error:

`c:/Users/mdyckhoff/iwyu-test/test.cpp:6:15: error: arithmetic on a pointer to an incomplete type 'Foo'
        return (pPtr + count);`

[EDIT: Adding version information. Running IWYU on Windows.

`include-what-you-use 0.4 (645) based on clang version 3.6.1 (branches/release_36 238234)`]

[test-remove-header-pointer-arith.zip](https://github.com/include-what-you-use/include-what-you-use/files/321281/test-remove-header-pointer-arith.zip)

**Comment by Bothari** [comment]
I realised I am running a rather out of date version of IWYU (necessary because I'm integrating it with our toolchain which currently runs on clang 3.6). I have confirmed that the same error occurs with the latest Windows binary available:

`include-what-you-use 0.6 (git:f09b88a) based on clang version 3.8.0 (tags/RELEASE_380/final 269221)`

**Comment by kimgr** [comment]
Thanks for the concise test case. It looks like IWYU doesn't handle binary operators at all -- this should be easily solved by adding a `VisitBinaryOperator` implementation that reports type use of both the left- and right-hand side of the binary op expression.

**Comment by kimgr** [comment]
I did some hacking on this when it came up, then work came in the way.

It turned out to be slightly more complicated, because pointer arithmetic is only a narrow subset of all binary operator uses, I found a clang-tidy check that identifies it like in this patch:
http://reviews.llvm.org/D14582

I'll try to pick this up at some point, but I'm still in crunch.
