### ISSUE TITLE
3.8 recommends includes for things not used in file

### ISSUE THREAD

**Issue by sylvestre** [include-what-you-use/include-what-you-use#334]
Reported by Franz Schrober on http://bugs.debian.org/828734

It was noticed that the upgrade from 3.7 to 3.8 introduced a regression. iwyu
is now recommending includes for things which are nowhere used in a file.

First problem was that this version is not depending on libclang-common-3.8-dev
and thus didn't find some of the headers (see #722132). But it turns out that
this is not the only problems 

E.g it wants me to now include

```
#include <linux/compiler.h> // for __u, __read_once_size, __read_o...
#include "linux/swab.h" // for __fswab16
```

But these things are nowhere used in the file. The only appearances are inside
included headers.

I've tried to create a preprocessed file but it seems that iwyu doesn't report
any problems anymore when the file is already preprocessed. But I've created a
small example which shows the problem and how it related to macros. The test.c
file just uses the functionality from memops.h (this is the abstraction layer)
- stdio.h. memops.h itself is using compiler.h. No functionality from
  compiler.h is used directly in test.c

Compile with macros in memops.h:

```
    $ iwyu test.c -o test.o
    test.c should add these lines:
    #include "compiler.h"

    test.c should remove these lines:

    The full include-list for test.c:
    #include <stdio.h> // for printf
    #include "compiler.h"
    #include "memops.h" // for get_memory_pointer_once
```

And now with the same functionality but implemented as static inline function:

```
    $ iwyu -DIWYU_INLINE_FUNCTION_TEST test.c -o test.o
    (test.c has correct #includes/fwd-decls)
```

So my guess is that the handling of macros is currently broken in iwyu/clang.

**Comment by kimgr** [comment]
This is likely caused by my recent macro-location patch.

Is your small repro Linux/Debian-specific? I'd love a portable repro if you can boil it down, otherwise I can try and find online copies of memops & friends to see if I can reason about their behavior.

**Comment by franzschrober** [comment]
@kimgr Sorry, I failed to understand what you want from me. The code to reproduce the problem is attached to the Debian bug report. Not sure why it should be Debian specific - it is just C code and the commands to run to see the problems are described in the Debian bug report (which was copied here by @sylvestre)

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=828734;filename=iwyu_braindead.tar.xz;msg=5

Does this answer the question? If not, please ask the question again and try to rephrase it.

**Comment by kimgr** [comment]
@franzschrober Sorry, I never went as far as the original report, and I never saw the reproducer. I thought the headers mentioned were Linux headers, and I don't have a Linux system set up, so I was looking for something more self-contained. Much like your original repro case. :-)

Sorry about the confusion, I'll see if I can dig into this at some point.

**Comment by conchurnavid** [comment]
Same problem here. Please revert cf225fcbdb8412c479aba79b1fdde5f39d883141 to fix the problem

**Comment by kimgr** [comment]
@franzschrober @conchurnavid -- assuming you can both reproduce this, can you send me the output of 

    include-what-you-use -Xiwyu -v7 $(additional_args) test.c

I think there are two issues teaming up -- one is to do with my macro change, but the other appears to be system-specific, that it's picking Linux headers instead of your local headers. I can't repro the latter on my systems.

Thanks.

**Comment by conchurnavid** [comment]
[iwyu_334.txt](https://github.com/include-what-you-use/include-what-you-use/files/367282/iwyu_334.txt)

@kimgr did you do your tests with the clang_3.8 branch against llvm 3.8?

**Comment by kimgr** [comment]
Thanks! No, I'm currently testing against our latest master. I can try and set up a 3.8 environment if you think it's something specific to the 3.8/0.6 release.

**Comment by conchurnavid** [comment]
At least everyone who can reproduce it has 3.8/0.6 and the but title already references this version

**Comment by kimgr** [comment]
OK, I read the original report again, there seem to be two issues:

First;

> $ iwyu test.c -o test.o
>    test.c should add these lines:
>    #include "compiler.h"

This is perfectly portable and behaves the same on Windows and FreeBSD. I thought this was another example of the one below, but it appears to be another problem entirely. The log @conchurnavid posted covers this behavior.

Second;

> E.g it wants me to now include
>
>    #include <linux/compiler.h> // for __u, __read_once_size, __read_o...
>    #include "linux/swab.h" // for __fswab16
>
> But these things are nowhere used in the file. The only appearances are inside
> included headers.

This is what I was looking for help to reproduce. So @franzschrober, if you could post an IWYU log excerpt for this problem, it would be much appreciated.

If you can confirm that these are two problems (possibly related), I can split the issue to hopefully lessen the confusion.

**Comment by franzschrober** [comment]
Why should I create a log of the more complicated example of the same problem? I've created the minified version as testcase for a reason

**Comment by kimgr** [comment]
Does the minified testcase repro the mysterious linux #include suggestions on your system? Since it doesn't on mine, I can't troubleshoot it without a log.

If all you care about is the macro misattribution, I have everything I need.

**Comment by conchurnavid** [comment]
Of course, the minified testcase will not show the exact same output because I would have to recreate the linux buildsystem and the linux headers. But here is a build of a single file from the linux kernel which shows this problem
[asd.txt](https://github.com/include-what-you-use/include-what-you-use/files/367309/asd.txt)

**Comment by kimgr** [comment]
Oh, OK, *now* the penny drops -- the original report was from running IWYU on a file from the Linux kernel? I thought it was a run on user code, and IWYU suggested kernel headers be included.

I think I know what's going on now, I'll see if I can patch it up.

**Comment by kimgr** [comment]
Can you try the referenced patch? It might not apply cleanly against 3.8/0.6, but it's trivial enough that you can probably put it in manually.
