### ISSUE TITLE
mappings behaviour changed from 0.5 to 0.6

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#338]
This

```
#include <QDebug>

int main()
{
    qDebug() << "fish";
    return 0;
}

```

with this compile line (on windows)

```

bin\include-what-you-use.exe -Xiwyu --transitive_includes_only -D_MT -D_DLL -m32 -DBOOST_USE_WINDOWS_H -Wno-inconsistent-missing-override --system-header-prefix=Q --system-header-prefix=boost/ -fexceptions -fmsc-version=1800 -DQ_COMPILER_INITIALIZER_LISTS -DQ_COMPILER_DECLTYPE -DQ_COMPILER_VARIADIC_TEMPLATES -D_DEBUG -Xiwyu --mapping_file=share\qt5_4.imp -DUNICODE -DWIN32 -DNOMINMAX -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DGAMEFALLOUT4_LIBRARY -IC:\Apps\Qt\5.5\msvc2013\mkspecs\win32-msvc2013 -IC:\Apps\Qt\5.5\msvc2013\include -IC:\Apps\Qt\5.5\msvc2013\include -IC:\Apps\Qt\5.5\msvc2013\include\QTCore -IC:\Apps\Qt\5.5\msvc2013\include\QTGui -IC:\Apps\Qt\5.5\msvc2013\include\QTWidgets  -I"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE" test.cc

```

with IWYU 0.5 produces this:

```
test.cc should add these lines:
#include <QtDebug>  // for qDebug

test.cc should remove these lines:

The full include-list for test.cc:
#include <QDebug>   // for QDebug
#include <QtDebug>  // for qDebug

---

```

but in 0.6 produces this

```
test.cc should add these lines:
#include <QtDebug>  // for qDebug

test.cc should remove these lines:

The full include-list for test.cc:
#include <QDebug>   // for QDebug
#include <QMessageLogger>  // for QMessageLogger
#include <QtDebug>  // for qDebug

---

```

This addition of `QMessageLogger` is an unexpected regression.

In passing, if I add `QtDebug`, then IWYU 0.5 tells me to **remove** `QDebug`, after which it is happy. However, 0.6 behaves differently and requires `QDebug` as well.

It seems to me that the way mappings are being treated was changed between 0.5 and 0.6 and it feels wrong.

Final note: the `QtDebug`, `QDebug` both are just facades for `#include "qdebug.h"` which contains a friend definition for QMessageLogger, although judging from the fact that the test program still compiles if I add a `QMessageLogger` object to it, Qt has managed to include the appropriate header somewhere inside `qdebug.h`.

**Comment by vsapsai** [comment]
As far as I understand, you are using Qt 5.5. How and where `qDebug` macro is defined? Is the file defining `qDebug` forward declares or includes `QMessageLogger`? Because I don't think the problem you are seeing is caused by mapping change but by [change in handling macros](https://github.com/include-what-you-use/include-what-you-use/commit/178b04f01403ff8cf26fc359640e25ae202c7c4a). The idea is that if macro author forward declares a symbol, IWYU interprets it as macro user being responsible for including file with corresponding symbol.

I didn't run your code with Qt 5.6 but `qDebug` is defined in `include/QtCore/qlogging.h` as
```
#define qDebug QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC).debug
```
And `QMessageLogger` is declared in the same file. So I don't think it will be a problem with Qt 5.6. Don't mean it's acceptable in Qt 5.5, just one more data point for comparison.

**Comment by kimgr** [comment]
Thanks for the analysis. I agree with it, but not the conclusion:

> And QMessageLogger is declared in the same file. So I don't think it will be a problem
> with Qt 5.6. Don't mean it's acceptable in Qt 5.5, just one more data point for comparison.

`QMessageLogger` is declared in the macro file, but it's a complete type declaration, not a forward-declaration. Only forward-decls should be considered use-attribution hints.

With this and #334, I've learned more about macro patterns to the extent that I think I can build the right logic for all these cases.

* Use-attribution hints should only be declarations outside of macro definitions
* Use-attribution hints should only be type declarations with a name
* Use-attribution hints should only be forward-declarations, not complete declarations

That is, I should probably use `IsForwardDecl` from `iwyu_ast_util.h`, together with some macro-detection magic.

I'll see if I can work on this on master.
