### ISSUE TITLE
Add --version option

### ISSUE THREAD

**Issue by Guy-Shaw** [include-what-you-use/include-what-you-use#344]
It would be nice to have a way to have iwyu tell the current version,
as a command-line option.  I mean the version of iwyu, itself,
not of the version of clang being used.

Preferably, a GNU long option '--verbose'.
And that would seem to make sense, since iwyu already
use GNU-style long options.

**Comment by kimgr** [comment]
Have you tried `--version`:

    $ include-what-you-use --version
    include-what-you-use 0.7 (git:1b796e7) based on clang version 3.9.0 (trunk 275441) (llvm/trunk 275437)

I'll leave this open in case I'm missing something.

**Comment by Guy-Shaw** [comment]
Yes, I tried that.  But that is on a version that comes in a package with my Linux distribution.
So, I had better remove that package and build from source.

It occurred to me that a later version of iwyu would have that option.
I search the 'longopts' structure and did not see it there.
But now I see that it is an intercepted option.
So, go ahead and close this issue.

-- Guy Shaw

**Comment by kimgr** [comment]
Ah, I see. Thanks for the confirmation!
