### ISSUE TITLE
Assert in iwyu.cc on Clang code

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#346]
I encountered next assert when run IWYU on tools/clang/lib/Basic/FileManager.cpp.

iwyu.cc:3242: Assertion failed: class_decl && "TemplateSpecializationType is not a TplSpecDecl?"

Both LLVM/Clang and IWYU are based on recent code:

include-what-you-use 0.7 (git:0192de1) based on clang version 4.0.0 (trunk 276298)

**Comment by kimgr** [comment]
Can you get and post a backtrace? I can try and repro this, but it'll take me a while to set up the environment.

**Comment by EugeneZelenko** [comment]
Same problem exists in r278022.

Backtrace is:

#0  0x00002aaaac332625 in raise () from /lib64/libc.so.6
#1  0x00002aaaac333e05 in abort () from /lib64/libc.so.6
#2  0x00000000003e191b in include_what_you_use::FatalMessageEmitter::~FatalMessageEmitter() ()
#3  0x0000000000416ae3 in include_what_you_use::InstantiatedTemplateVisitor::TraverseDataAndTypeMembersOfClassHelper(clang::TemplateSpecializationType const*) ()
#4  0x0000000000414945 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypeLoc(clang::TypeLoc) ()
#5  0x0000000000414217 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypeLoc(clang::TypeLoc) ()
#6  0x0000000000412b80 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypedefDecl(clang::TypedefDecl*) ()
#7  0x000000000041160d in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseDecl(clang::Decl*) ()
#8  0x0000000000416a25 in include_what_you_use::InstantiatedTemplateVisitor::TraverseDataAndTypeMembersOfClassHelper(clang::TemplateSpecializationType const*) ()
#9  0x0000000000414945 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypeLoc(clang::TypeLoc) ()
#10 0x0000000000414217 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypeLoc(clang::TypeLoc) ()
#11 0x00000000004154a0 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseNestedNameSpecifierLoc(clang::NestedNameSpecifierLoc) ()
#12 0x0000000000415419 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseNestedNameSpecifierLoc(clang::NestedNameSpecifierLoc) ()
#13 0x0000000000414fde in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseElaboratedTypeLoc(clang::ElaboratedTypeLoc) ()
#14 0x0000000000414399 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypeLoc(clang::TypeLoc) ()
#15 0x0000000000414217 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTypeLoc(clang::TypeLoc) ()
#16 0x00000000004161ac in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTemplateArgumentLoc(clang::TemplateArgumentLoc const&) ()
#17 0x0000000000415be2 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseTemplateArgumentLoc(clang::TemplateArgumentLoc const&) ()
#18 0x000000000041c95b in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseDeclRefExpr(clang::DeclRefExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#19 0x000000000040a13b in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseDeclRefExpr(clang::DeclRefExpr*) ()
#20 0x000000000040475f in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#21 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#22 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#23 0x0000000000409d28 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseImplicitCastExpr(clang::ImplicitCastExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#24 0x00000000004046ef in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#25 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#26 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#27 0x000000000041c5f8 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCallExpr(clang::CallExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#28 0x00000000004045f2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#29 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#30 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#31 0x000000000041c708 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCXXMemberCallExpr(clang::CXXMemberCallExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#32 0x0000000000404633 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#33 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#34 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#35 0x000000000041c5f8 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCallExpr(clang::CallExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt---Type <return> to continue, or q <return> to quit---
*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#36 0x00000000004045f2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#37 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#38 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#39 0x0000000000407598 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCompoundStmt(clang::CompoundStmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#40 0x0000000000404356 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#41 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#42 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#43 0x000000000041b259 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseFunctionHelper(clang::FunctionDecl*) ()
#44 0x0000000000412eec in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCXXMethodDecl(clang::CXXMethodDecl*) ()
#45 0x00000000004116b3 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseDecl(clang::Decl*) ()
#46 0x00000000004176d0 in include_what_you_use::InstantiatedTemplateVisitor::TraverseExpandedTemplateFunctionHelper(clang::FunctionDecl const*, clang::Type const*) ()
#47 0x0000000000404e80 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#48 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#49 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#50 0x0000000000407598 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCompoundStmt(clang::CompoundStmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#51 0x0000000000404356 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#52 0x00000000004035c2 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#53 0x0000000000403504 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseStmt(clang::Stmt*) ()
#54 0x000000000041b259 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseFunctionHelper(clang::FunctionDecl*) ()
#55 0x0000000000412eec in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCXXMethodDecl(clang::CXXMethodDecl*) ()
#56 0x00000000004116b3 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseDecl(clang::Decl*) ()
#57 0x00000000004176d0 in include_what_you_use::InstantiatedTemplateVisitor::TraverseExpandedTemplateFunctionHelper(clang::FunctionDecl const*, clang::Type const*) ()
#58 0x000000000042bef0 in include_what_you_use::IwyuAstConsumer::HandleFunctionCall(clang::FunctionDecl*, clang::Type const*, clang::Expr const*) ()
#59 0x0000000000424003 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) ()
#60 0x000000000041f524 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#61 0x000000000041e472 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#62 0x00000000003e8514 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt*) ()
#63 0x0000000000425078 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseExprWithCleanups(clang::ExprWithCleanups*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#64 0x000000000041f664 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#65 0x000000000041e472 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#66 0x00000000003e8514 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt*) ()
#67 0x00000000004222c8 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCompoundStmt(clang::CompoundStmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1---Type <return> to continue, or q <return> to quit---
u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#68 0x000000000041f206 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#69 0x000000000041e472 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) ()
#70 0x00000000003e8514 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt*) ()
#71 0x000000000042e9f9 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseFunctionHelper(clang::FunctionDecl*) ()
#72 0x00000000003e6b9c in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXMethodDecl(clang::CXXMethodDecl*) ()
#73 0x00000000003e3c36 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl*) ()
#74 0x00000000003e7cff in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDeclContextHelper(clang::DeclContext*) ()
#75 0x00000000003e39f8 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl*) ()
#76 0x00000000003df113 in include_what_you_use::IwyuAstConsumer::HandleTranslationUnit(clang::ASTContext&) ()
#77 0x00000000006e9af6 in clang::ParseAST(clang::Sema&, bool, bool) ()
#78 0x00000000004c378d in clang::FrontendAction::Execute() ()
#79 0x000000000048e2a8 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#80 0x00000000003de171 in main ()

**Comment by kimgr** [comment]
Thanks! I can't repro on my BSD system, I wonder if maybe it's something to do with a construct in libstdc++. I'll leave this for someone else to troubleshoot, I don't have the resources at hand.

**Comment by vsapsai** [comment]
@EugeneZelenko, was it a clean build or incremental build? Because with clean build on Ubuntu 16.04 I don't hit the assertion.
> /mnt/buildbot_iwyu_trunk/workspace/installed/bin/include-what-you-use --version
include-what-you-use 0.7 (git:7554b31) based on clang version 4.0.0 (trunk 279412)

and I used command

> /mnt/buildbot_iwyu_trunk/workspace/installed/bin/include-what-you-use -DCLANG_ENABLE_ARCMT -DCLANG_ENABLE_OBJC_REWRITER -DCLANG_ENABLE_STATIC_ANALYZER -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/mnt/buildbot_iwyu_trunk/workspace/build_db/tools/clang/lib/Basic -I/mnt/buildbot_iwyu_trunk/workspace/sources/llvm/tools/clang/lib/Basic -I/mnt/buildbot_iwyu_trunk/workspace/sources/llvm/tools/clang/include -I/mnt/buildbot_iwyu_trunk/workspace/build_db/tools/clang/include -I/mnt/buildbot_iwyu_trunk/workspace/build_db/include -I/mnt/buildbot_iwyu_trunk/workspace/sources/llvm/include   -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing    -fno-exceptions -fno-rtti -o CMakeFiles/clangBasic.dir/FileManager.cpp.o -c /mnt/buildbot_iwyu_trunk/workspace/sources/llvm/tools/clang/lib/Basic/FileManager.cpp

**Comment by EugeneZelenko** [comment]
I build IWYU woth LLVM/Clang/LLD/Extra tools, as part of extra tools. I do clean build.

My CMake parameters are:

${CMake}								\
	-DCMAKE_BUILD_TYPE="Release"					\
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON				\
	-DCMAKE_INSTALL_PREFIX:PATH=${InstallDir}			\
	-DCMAKE_C_COMPILER=${LLVMPass1Dir}/bin/clang			\
	-DCMAKE_CXX_COMPILER=${LLVMPass1Dir}/bin/clang++		\
	-DPYTHON_EXECUTABLE=${PythonDir}/bin/python			\
	-DLLVM_ENABLE_LIBCXX=ON						\
	-DLLVM_ENABLE_LLD=ON						\
	-DLLVM_ENABLE_WARNINGS=ON					\
	-DLLVM_INSTALL_TOOLCHAIN_ONLY=ON				\
	-DLLVM_LIBDIR_SUFFIX=64						\
	-DLLVM_TARGETS_TO_BUILD="X86"					\
	${LLVMSourceDir}

**Comment by kimgr** [comment]
See also #150

**Comment by kimgr** [comment]
#150 is now fixed and it seems likely that this issue is a duplicate. Closing.
