### ISSUE TITLE
Is it possible to make IWYU not add forward declarations?

### ISSUE THREAD

**Issue by EFanZh** [include-what-you-use/include-what-you-use#354]
I don’t care if my code’s compiling time is a little longer, but I want my code to look clean and short. Is it possible to make IWYU only organize includes, without introducing any forward declarations?

**Comment by kimgr** [comment]
No, it's not currently possible, but I'm starting to think it might be a nice feature.

**Comment by kimgr** [comment]
Also requested on the mailing list here:
https://groups.google.com/d/topic/include-what-you-use/ITG9mhL-Mt0/discussion

**Comment by cdglove** [comment]
On Tue, 16 Aug 2016 at 15:00 Kim Gräsman <notifications@github.com> wrote:

> No, it's not currently possible, but I'm starting to think it might be a
> nice feature.
>
In my opinion, this is an odd thing to want -- I try to fwd-declare
everything and tell my teams to do the same. I can't think of a good reason
not to do that.

If this is really a feature people want then perhaps it should be added,
but it might also be a point that requires education over a technical fix.
Thoughts?

-- chris

>

**Comment by kimgr** [comment]
Personally I agree, but I think the recent trend comes from Google's updated style guide:
https://google.github.io/styleguide/cppguide.html#Forward_Declarations

I think their motivation holds water for the most part, forward declarations are really brittle in C++.

So for small code bases (not Google), or when you can massively parallellize and cache your builds (Google), this might actually be good advice. For the rest of us; not so much :-)

**Comment by cdglove** [comment]
On Tue, 16 Aug 2016 at 16:01 Kim Gräsman <notifications@github.com> wrote:

> Personally I agree, but I think the recent trend comes from Google's
> updated style guide:
> https://google.github.io/styleguide/cppguide.html#Forward_Declarations
>
> I think their motivation holds water for the most part, forward
> declarations are really brittle in C++.
>
Well, the points are valid, I just don't agree with the actual severity of
the problem -- I have never been bitten by any of the issues listed there
(other than the verbosity of fwd-declarations).

Of course, the size of the projects makes a difference, and I might
misunderstand the scale, but the projects I work on are not exactly small
-- they are somewhere between 10 and 15 million lines.

All of this being said, if it's in the google style guide, it's not an
unreasonable feature to add.

-- chris

**Comment by ThosRTanner** [comment]
As long as it's not forced.

Forward declaring functions is a pretty naff thing to do. It only makes sense to forward declare a class (or a template class - though the latter scares me out a little for some reason). And the comment about having to restructure the code to use pointers rather than members is entirely spurious (and goes totally against the PIMPL idiom which is well understood and provides many benefits).

They have provided one example where it doesn't work and that is what I'd call somewhat contrived.

**Comment by kimgr** [comment]
I would definitely not want to disable forward declarations by default.

**Comment by vsapsai** [comment]
Does anybody know how much Google is using modules? Because with C++ modules forward declarations are irrelevant for compile-time improvements.

**Comment by acmorrow** [comment]
I too would like to see this feature. As noted above, the newer Google Style Guide advocates direct inclusion of headers over introducing potentially embrittling forward declarations. I agree with those above who say that the default should not change, but adding an option to simply always suggest that the fix be to include the associated file seems like it would be an excellent addition.

**Comment by acmorrow** [comment]
Is there some way to get this more visible or re-prioritized on the roadmap? It seems like it should be pretty straightforward (hah!).

There are two closed dupes, several upvotes on this issue, and the motivation for the change is to bring the tool into alignment with the google C++ style guide, which seems wise.

**Comment by kimgr** [comment]
I've recently switched jobs and am a little overwhelmed with that. I think this is a case of "patches very welcome". As I said, it's a reasonable feature, I just don't see myself using it so it's hard for me to make it a priority.

**Comment by kimgr** [comment]
This has now been implemented, closing.
