### ISSUE TITLE
Allow LLVM include order

### ISSUE THREAD

**Issue by purpleKarrot** [include-what-you-use/include-what-you-use#357]
IWYU currently follows Google's include order guideline where system includes come before local includes (https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes). Most projects that I work with follow LLVM's approach, where local includes come before system includes (http://llvm.org/docs/CodingStandards.html#include-style).

**Comment by EugeneZelenko** [comment]
I think .clang-format could be used to determine proper includes order.

**Comment by purpleKarrot** [comment]
@bhupeshpant19jan I no longer care about what include order iwyu uses, because I can regroup the includes with clang-tidy afterwards by setting `IncludeBlocks` to `Regroup`.

**Comment by bhupeshpant19jan** [comment]
But in general, what is the recommended order?
In my existing project it was Clang --> sysroot -->  libc++ ....  But I have changes to Clang --> libc++ --> sysroot, is this correct order?

**Comment by kimgr** [comment]
This is the sort order IWYU imposes:
```
enum class LineSortOrdinal {
  PrecompiledHeader,  // Precompiled headers must come first in MSVC
  AssociatedHeader,  // x.h for x.cc
  AssociatedInlineDefinitions, // Not sure what this is
  QuotedInclude,  // "include.h"
  CHeader,  // Header from the libc
  CppHeader,  // Header from the C++ STL
  OtherHeader,  // Probably any other header (project or third-party)
  ForwardDeclaration  // Forward-declarations should come after includes
};
```

I'm not sure what you mean by "Clang" above, but I'm guessing you mean the builtin headers?

**Comment by kimgr** [comment]
Closing as duplicate of #35.
