### ISSUE TITLE
False positive when using htons and friends

### ISSUE THREAD

**Issue by svenpanne** [include-what-you-use/include-what-you-use#358]
Consider the following short file `foo.c`:

``` C
#include <netinet/in.h>
int my_htons(int x) { return htons(x); }
```

(Yes, `int` is not totally correct here, but this is just for demonstration purposes.) On my Ubuntu 16.04 box `include-what-you-use` (`clang_3.9` branch) issues a false positive:

```
$ include-what-you-use -O -c foo.c

foo.c should add these lines:
#include <byteswap.h>    // for __x

foo.c should remove these lines:

The full include-list for foo.c:
#include <byteswap.h>    // for __x
#include <netinet/in.h>  // for htons

---
```

Note that the `-O` is essential here, otherwise the macro definitions will be different. I was able to boil this example down to 3 files (see [boiled_down.tar.gz](https://github.com/include-what-you-use/include-what-you-use/files/429795/boiled_down.tar.gz), too):
- `foo.c`:

``` C
#include "my_netinet_in.h"
int my_htons(int x) { return htons(x); }
```
- `my_netinet_in.h`:

``` C
#include "my_byteswap.h"
#define htons(x) bswap(x)
```
- `my_byteswap.h`:

``` C
#define bswap(x) ({ int __x = (x); bswap2(__x); })
#define bswap2(x) (x)
```

I've got no clue if this iwyu bug is related to the use of the non-standard statement expression in `bswap` and/or the macro structure itself.

**Comment by kimgr** [comment]
I think it has to do with the macros. It sounds like you're building from source, could you try and apply this patch: https://github.com/include-what-you-use/include-what-you-use/pull/350

Thanks!

**Comment by svenpanne** [comment]
Yes, I'm building from source, but the patch didn't help.

**Comment by kimgr** [comment]
Sorry to hear. Thanks for the reduced example, gives me something to work from.

I won't have time to look at this for a while yet, but I'll try to pick it up soon.

**Comment by kimgr** [comment]
It looks to be a problem with nested macros. If I remove ``bswap2``, everything works as expected.

It's because `__x`` is passed as a macro argument, that fact attributes the use to the passing location, which is in itself a macro. I'll see if I can figure out a way to short-circuit this.

**Comment by kimgr** [comment]
After many moons, I've now circled back to this. And solved it, I think!

You can try this patch on top of master:
https://github.com/kimgr/include-what-you-use/commit/5606e046589cd4e976cff82f2edfa8f2a4258c7a.patch

I'll try to make it a pull request soon.

**Comment by svenpanne** [comment]
I only have clang-3.9 at hand at the moment and IWYU's master doesn't compile against that out-of-tree, so I've tried the patch with the clang_3.9 branch of IWYU. It applied without problems and everything seems to work now. Thanks for the patch!

**Comment by kimgr** [comment]
Thanks for the confirmation, appreciated!

I'll work on cleaning that up so we get can it fixed for the next drop of IWYU.

**Comment by kimgr** [comment]
This should be fixed on master now.
