### ISSUE TITLE
Broken build with trunck LLVM/Clang

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#362]
Several Clang APIs were changed with using std::unique_ptr instead of raw pointers. At least one place in iwyu.cc should be fixed (adding get() call).

**Comment by vsapsai** [comment]
Thanks for letting us know. Fixed build in cf4d4963196a7b66b6ccf8f2eb37d7f71882eb5b. `badinc.cc` test still fails but at least it compiles.
