### ISSUE TITLE
Add Option to Use Clang Compilation Database for Flags

### ISSUE THREAD

**Issue by mellery451** [include-what-you-use/include-what-you-use#366]
It would be very convenient if this tool could optionally get it's compilation flags from the compile database file:  http://clang.llvm.org/docs/JSONCompilationDatabase.html. This file can be generated by cmake builds and is used by a number of other libclang based tools (ycmd, for example). If this tool could be convinced to use the same info, it would greatly simplify the invocation as we would not have to pass the long list of compiler flags.

**Comment by kimgr** [comment]
We have a wrapper script to handle that -- `iwyu_tool.py` -- can you see if that helps?

**Comment by mellery451** [comment]
@kimgr - yes, that's exactly what I need. Thanks for pointing me in the right direction.
