### ISSUE TITLE
rpath in truck LLVM

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#373]
rpath handling was changed in trunk LLVM (probably in r285714), so now IWYU is liked differently then rest of application when built in-tree.

**Comment by EugeneZelenko** [comment]
Changing add_executable to add_clang_executable fix problem for in-tree build. I think will be good idea to try same in out-of-tree build.

**Comment by vsapsai** [comment]
Can you please provide more details what changed and what is the observable change? Want to understand what is the problem and how can we detect it in build system.

**Comment by EugeneZelenko** [comment]
Just run ldd over Clang and Include What You Use executable.

PS

I build with libc++ and libc++abi.

**Comment by kimgr** [comment]
Is this still a problem? I'm not sure how to proceed.

**Comment by EugeneZelenko** [comment]
Yes, it's still a problem. I think it's good idea to change add_executable to add_clang_executable, so Clang, Clang tool extra and IWYU will be built with same set of linking options.

**Comment by kimgr** [comment]
Does `add_clang_executable` work in an out-of-tree build, then?

**Comment by EugeneZelenko** [comment]
I always built in-tree, but probably will not work for out-of-tree build, because neither LLVM or Clang CMake files are included. But for out-of-tree build add_clang_executable could be defined as add_executable.

**Comment by kimgr** [comment]
I'm pretty sure this is solved by 0003739. See revised docs at https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build.
