### ISSUE TITLE
precompiled headers windows

### ISSUE THREAD

**Issue by jcageman** [include-what-you-use/include-what-you-use#392]
Hi,

First of all, thanks for this great tool!

I am trying to use IWYU on a windows code base where we do the following:
Mark PrecompilerHeader.h as precompiled header using /Yu and force include it into the source using the /FI compiler option from windows. Now the problem seems to be that IWYU wants to include the headers which are included in the forced include file again, which is not really what you want. I understand the idiom of IWYU and precompiled headers are completely against it, but are very common in windows projects.

I noticed the option --pch_in_code, but i do not think that is actually going to work here due to the forced include, which is not in the actual code.

Sounds like a missing option to me, since i couldn't find much about it except the above command line option.

Thanks for any help

Kind regards,

Jacob

**Comment by kimgr** [comment]
See the '--prefix_header_includes' option  it was meant to address this. Prefix header is one name for force-included headers.

**Comment by jcageman** [comment]
Great that works! Thanks!
