### ISSUE TITLE
sorting headers per project

### ISSUE THREAD

**Issue by jcageman** [include-what-you-use/include-what-you-use#393]
Hi,

I am trying to get the following style of includes (including the comments):

#include "myownheader.h"

// ProjectA
#include <foo.h>
#include <bar.h>

// ProjectB
#include <baz.h>

//Own project headers
#include "test.h"

Is anything like this possible? At the moment the headers seem to be sorted alphabatically except for my own project headers. Furthermore i notice that myownheader.h is include somewhere in the middle, while i would expect it to be moved to the top of the includes, since in my opinion that is the correct include style.

Note: i already know of --separate_project_includes, but that only orders your own project headers.

Kind regards,

Jacob

**Comment by kimgr** [comment]
No, there's currently no intelligent grouping.

As for the associated header -- it matches the stem (filename sans extension) exactly, so case mismatches are not allowed.

**Comment by jcageman** [comment]
Oke, i debugged a little and it seems that _IsMainCUInclude in fix_includes.py incorrectly misses the header due to rule #1 where canonical_file in my case is the full path to the file, which will never match with the filenames only.

rule #2 only matches in case i put the corresponding header on top of the .cpp to begin with. I modified rule #2 by just always matching on base name

**Comment by kimgr** [comment]
Cool, is it possible to frame this in a testcase for fix_includes.py and provide a patch?

I think we have an issue open on this, somewhere, and I had some concerns, but I can't remember what they were atm...

**Comment by jcageman** [comment]
At the moment my knowledge of the tool is fairly limited, hence i will continu tests and if i have a solid patch i will provide it here.
