### ISSUE TITLE
C++11 enum types are ignored

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#407]
Looks like IWYU ignores C++11 enum types.

For example, cstdint was not suggested for include/llvm/MC/MachineLocation.h (included in lib/Target/Hexagon/HexagonRegisterInfo.cpp or some other target specific files) which contain next declaration:

enum : uint32_t

**Comment by vsapsai** [comment]
Thanks for the report. Looks like we need to add support for some C++11 features.

**Comment by kimgr** [comment]
Fixed by https://github.com/include-what-you-use/include-what-you-use/pull/742
