### ISSUE TITLE
Mapping for type traits

### ISSUE THREAD

**Issue by purpleKarrot** [include-what-you-use/include-what-you-use#434]
`std::unordered_map` internally uses `__decay_and_strip<>::__type` which is defined in `<type_traits>`.
IWYU suggests to include `<type_traits>` whenever `std::unordered_map` is used. It should not suggest it, because `__decay_and_strip<>::__type` is an implementation detail. But that is a separate issue.

As a workaround, I want to map the symbol `__decay_and_strip<>::__type` to the header `<unordered_map>`. However, IWYU seems to ignore that mapping completely. How does the symbol need to be written? I tried `__decay_and_strip<>::__type`, `std::__decay_and_strip<>::__type`, `__decay_and_strip`, `std::__decay_and_strip`, ...

**Comment by kimgr** [comment]
Hmm, I don't know. Maybe you can try cranking the log level up to max (`-Xiwyu -v7` or higher) and see if IWYU says how its current mapping happens? If you spell the type name the same, maybe it works? Types nested inside templates are hard to spell unambiguously...

**Comment by purpleKarrot** [comment]
OK, I used `-Xiwyu -v7` to find out the fully qualified name and added a mapping for that. It works.
Next, I tried the `@`-prefixed regex syntax, but could not get it to work.

I tried to prefix the (tested) fully qualified name with an `@` without making any further changes to the string. Even that fails. Is the `@`-prefixed regex syntax really supported for symbols?

**Comment by kimgr** [comment]
Sorry, I meant to get back to this. No, it's not. See bug #233.

**Comment by kimgr** [comment]
Besides the regex prefix for symbols (which is covered by the other bug), we can close this, right?

**Comment by purpleKarrot** [comment]
Yes. With #443 merged, #233 can be closed too.

**Comment by tkocmathla** [comment]
> OK, I used -Xiwyu -v7 to find out the fully qualified name and added a mapping for that. It works.

@purpleKarrot i realize this was 6 years ago, but if you still have the exact mapping syntax that worked for you, can you please share it here?

**Comment by tkocmathla** [comment]
> > OK, I used -Xiwyu -v7 to find out the fully qualified name and added a mapping for that. It works.
> 
> @purpleKarrot i realize this was 6 years ago, but if you still have the exact mapping syntax that worked for you, can you please share it here?

fwiw, it worked for me to ramp up the IWYU verbosity to find the explicit type (`unsigned char` in my case) and make a rule from that, e.g.:
```
{ symbol: ["std::__decay_and_strip<unsigned char>::__type", "private", "<utility>", "public"] }
```
