### ISSUE TITLE
Document how to use with CMake projects

### ISSUE THREAD

**Issue by Timmmm** [include-what-you-use/include-what-you-use#437]
#164 has a comment saying

> r607 adds a Python driver that lets IWYU integrate with CMake's compilation database.
I'll set this fixed.

But I can't see any mention of this in [the documentation](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/InstructionsForUsers.md) or the readme.

It would be nice to know how to use this. CMake is fairly popular these days (presumably due to the lack of competition!)

Edit: And actually [CMake has built-in support for include-what-you-use](https://stackoverflow.com/a/30951493/265521) now - it would be good to mention that!

**Comment by kimgr** [comment]
Yes, I agree. I'll try to cook up some doc changes quickly.

I love that CMake has built-in IWYU support now, I wish they would've told us :-)

**Comment by kimgr** [comment]
Please take a look at PR #439 and let me know if that makes sense.

**Comment by kimgr** [comment]
PR #439 was just pushed, closing.
