### ISSUE TITLE
iwyu doesn't use forward declare for a simple case

### ISSUE THREAD

**Issue by jcageman** [include-what-you-use/include-what-you-use#446]
foo.h

```
struct SFoo
{
    SFoo(double i_value)
    : m_value(i_value)
   {
   }
   
double m_value;
}
```

bar.h

```
#include "foo.h"

double getvalue( const SFoo& i_rFoo );
```

IWYU suggestion: don't change bar.h, while it can easily forward declare. If you manually change #include "foo.h" to class SFoo; IWYU will also suggest no changes.

the case: the type passed in a method needs to have a implicit constructor and should be passed by const.

I already tracked down the relevant code that causes this issue:
VisitFunctionDecl()
CodeAuthorWantsJustAForwardDeclare, causes the conclusion that when the type is already included the author wants a include and if its not include the author wants a forward declare. My fix currently is to just always return true here, since comments suggest here that it will always be valid C++ and its what i desire, especially in the above seemingly trivial case. Please enlighten me if my conclusions are incorrect. 

IWYU comments:
```
  // There are a few situations where iwyu is more restrictive than
  // C++: where C++ allows a forward-declare but iwyu wants the full
  // type.  
  // 'autocast': if your function has a parameter with a conversion
  // (one-arg, not-explicit) constructor, iwyu requires that the
  // function-author provides the full type of that parameter, but
  // the language doesn't.  (It's ok with all callers providing the
  // full type instead.)
  //

```
What is the exact reason for wanting the full type of an 'autocast'?

edit:
I thought some more about it and the only reason i can think of is that if you always forward declare there are cases the compiler can't know if an implicit conversion is valid, because it doesn't know the full type, hence you get a compile error. Is this the reason why by default you don't add forward declares for types that are implicitly convertible? Example: A is implicitly convertible to B, now you have a header that accepts B in a method,  hence you can forward declare it. When you now want to use the method with type A its not possible unless you include the header of B, because the compiler doesn't know the fact that A is convertible to B.

**Comment by vsapsai** [comment]
You reasoning in edit part is correct. Given your example the following code works.

```c++
#include "bar.h"

void baz() {
    double x = 0.5;
    double y = getvalue(x);
}
```

But if in "bar.h" you forward declare `SFoo` instead of including it, the compilation fails with

```
tests/local/issue446/usage.cc:5:16: error: no matching function for call to 'getvalue'
    double y = getvalue(x);
               ^~~~~~~~
tests/local/issue446/bar.h:4:8: note: candidate function not viable: no known conversion from 'double' to 'const SFoo' for 1st
      argument
double getvalue( const SFoo& i_rFoo );
       ^
1 error generated.
```

**Comment by kimgr** [comment]
I think you're running into IWYU's special handling of author intent, see:
https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhatIsAUse.md#automatic-re-export-conversion-constructors

That is, if the header declaring `getvalue` includes the declaration of `SFoo`, it will be silently re-exported.

But if you avoid including, and instead forward-declare `SFoo`, IWYU treats that as a hint that you want callers to include it, and attributes the use to whoever uses `getvalue`.

So I think this is working as intended, let me know if that makes sense.

**Comment by jcageman** [comment]
Yes, i agree that its working as intended. I now also understand the reason, i will close the issue! Thanks!
