### ISSUE TITLE
Test failure on Fedora Rawhide (27)

### ISSUE THREAD

**Issue by daveisfera** [include-what-you-use/include-what-you-use#447]
I'm trying to update the packaging on Fedora Rawhide (27) to the clang_4.0 branch ( https://github.com/include-what-you-use/include-what-you-use/commit/953970c487b004050d44925bfcc5133be9fa0d7f ) and I'm getting 1 test failing.

Here's the output:
```
FAIL: runTest (__main__.associated_h_file_heuristic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_iwyu_tests.py", line 246, in <lambda>
    {'runTest': lambda self, f=filename: self.RunOneTest(f),
  File "run_iwyu_tests.py", line 217, in RunOneTest
    iwyu_flags, clang_flags, verbose=True)
  File "/builddir/build/BUILD/include-what-you-use-953970c487b004050d44925bfcc5133be9fa0d7f/iwyu_test_util.py", line 455, in TestIwyuOnRelativeFile
    test_case.assertTrue(not failures, ''.join(failures))
AssertionError: 
tests/cxx/associated_h_file_heuristic.cc:17: Unexpected diagnostic:
FILE is defined in <bits/types/FILE.h>, which isn't directly #included.

Unexpected summary diffs for tests/cxx/associated_h_file_heuristic.cc:
+++ 
@@ -1,8 +1,10 @@
 tests/cxx/associated_h_file_heuristic.cc should add these lines:
+#include <bits/types/FILE.h>
 
 tests/cxx/associated_h_file_heuristic.cc should remove these lines:
+- #include <stdio.h>  // lines XX-XX
 - #include <time.h>  // lines XX-XX
 
 The full include-list for tests/cxx/associated_h_file_heuristic.cc:
 #include "tests/cxx/internal/associated_h_file_heuristic.h"
-#include <stdio.h>  // for FILE
+#include <bits/types/FILE.h>  // for FILE
---
```

**Comment by kimgr** [comment]
Aargh. I'm tempted to just add a built-in mapping from ``<bits/types/FILE.h>`` to ``<stdio.h>``. @vspasai, do you have the requisite energy for something more principled...?

**Comment by vsapsai** [comment]
Potentially, we can handle bits-like headers in some special way, similar to what we are doing for x-macros. But in this case I would just add a mapping. More principled is checking other files in `bits/types/`. Another idea is symbol mapping instead of file mapping [to mimic `EOF`](https://github.com/include-what-you-use/include-what-you-use/blob/a2d8e282502cd6018b33f307519ba971b7cc11c2/iwyu_include_picker.cc#L187)

```c++
  { "EOF", kPrivate, "<stdio.h>", kPublic },
  { "EOF", kPrivate, "<libio.h>", kPublic },
```

**Comment by kimgr** [comment]
In this case I think a symbol mapping is a good idea, since `FILE` is documented to live in `<stdio.h>` and/or `<cstdio>`. We already have an equivalence mapping between the two, so just adding a mapping for `FILE` should be enough. Building with that change right now, can post a PR later.

**Comment by kimgr** [comment]
This is now merged to master. @daveisfera, could you cherry-pick 39738d1 onto clang_4.0 and see if it helps? Thanks.

**Comment by kimgr** [comment]
Thanks for the confirmation, closing!
