### ISSUE TITLE
Can IWYU support customized header extensions other than hard-coded .h/.hpp?

### ISSUE THREAD

**Issue by tavaresdong** [include-what-you-use/include-what-you-use#452]
One of my project uses .H extension for header files as a convention,
but IWYU only check corresponding .h/.hpp headers for a source file,
also the fix_includes.py script won't recognize .H files. I have to add --check_also
argument everytime.
So the idea comes to my mind, can we support customized header file extensions, so IWYU
can smartly choose which file extension it should use?

**Comment by kimgr** [comment]
I think it's better for us to just add `.H`.

**Comment by kimgr** [comment]
I can't find any mention of header extensions in `fix_includes.py` -- it only lists source file extensions and considers everything else headers.

@tavaresdong -- can you apply PR #453 and see if it helps?

**Comment by tavaresdong** [comment]
Hi, @kimgr patch #453 is great, and regarding ``fix_includes.py``, see line #1440, when detecting if a file is main-cu, it will fail to detect .H headers

**Comment by kimgr** [comment]
Ah, well spotted! I'll look into it.

**Comment by kimgr** [comment]
Thank you, fixed in current master.
