### ISSUE TITLE
Program works, but iostream header is missing

### ISSUE THREAD

**Issue by neubig** [include-what-you-use/include-what-you-use#454]
First, thanks for developing this tool, it's great!

I'm currently using IWYU compiled in-tree on Mac OS. The LLVM, clang, and IWYU versions were all pulled today, and clang is version 5.0.0.

When I run the program through CMAKE using the specified CMAKE command

    CC=$HOME/usr/local/iwyu-base/llvm/build/bin/clang CXX=$HOME/usr/local/iwyu-base/llvm/build/bin/clang++ cmake .. -DENABLE_BOOST=1 -DEIGEN3_INCLUDE_DIR=$HOME/usr/local/eigen -DPYTHON=`which python` -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="$HOME/usr/local/iwyu-base/llvm/build/bin/include-what-you-use"

Then run make, it seems like it's working for the first file in my build, but then dies after it's printed the info for the file:

    $ make
    Scanning dependencies of target dynet
    [  1%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
    Warning: include-what-you-use reported diagnostics:
    
    /Users/gneubig/work/dynet/dynet/aligned-mem-pool.h should add these lines:
    #include <stddef.h>     // for size_t
    #include <vector>       // for vector
    
    /Users/gneubig/work/dynet/dynet/aligned-mem-pool.h should remove these lines:
    - #include "dynet/except.h"  // lines 7-7
    - #include "dynet/globals.h"  // lines 6-6
    
    The full include-list for /Users/gneubig/work/dynet/dynet/aligned-mem-pool.h:
    #include <stddef.h>     // for size_t
    #include <iostream>     // for string
    #include <vector>       // for vector
    #include "dynet/mem.h"  // for MemAllocator
    ---
    
    /Users/gneubig/work/dynet/dynet/aligned-mem-pool.cc should add these lines:
    #include "dynet/except.h"  // for DYNET_ARG_CHECK, DYNET_ASSERT, DYNET_RUNTI...
    
    /Users/gneubig/work/dynet/dynet/aligned-mem-pool.cc should remove these lines:
    - #include <sstream>  // lines 3-3
    
    The full include-list for /Users/gneubig/work/dynet/dynet/aligned-mem-pool.cc:
    #include "aligned-mem-pool.h"
    #include "dynet/except.h"  // for DYNET_ARG_CHECK, DYNET_ASSERT, DYNET_RUNTI...
    ---
    
    In file included from /Users/gneubig/work/dynet/dynet/aligned-mem-pool.cc:1:
    /Users/gneubig/work/dynet/dynet/aligned-mem-pool.h:4:10: fatal error: 
          'iostream' file not found
    #include <iostream>
             ^~~~~~~~~~

Are there any ideas about the cause of this?

**Comment by kimgr** [comment]
I wonder if this is related to #438? What does `include-what-you-use -v` for some arbitrary source file say?

**Comment by neubig** [comment]
Thanks! Just running `include-what-you-use` instead of incorporating it in `cmake` worked without error. This is enough for my purposes, so I'm going to close this issues.
