### ISSUE TITLE
fix_includes.py: end section unexpectedly follows remove (windows only?)

### ISSUE THREAD

**Issue by JonnyOThan** [include-what-you-use/include-what-you-use#459]
The IWYU output for associated header files on windows frequently uses an absolute path, e.g:

The full include-list for d:/path/to/file.h:

This fails to match the regex because of the colon after the drive letter, which then makes the state machine not see the "full include list" section:

_TOTAL_SECTION_RE = re.compile(r'^The full include-list for ([^:]*):$')

Removing the exclusion for the colon seems to work, and doesn't seem like it would cause any problems because the regex still checks for the colon at the end of the line:

_TOTAL_SECTION_RE = re.compile(r'^The full include-list for (.*):$')

**Comment by kimgr** [comment]
This should have been fixed recently, see ee47cdf. Please close if this solves your problem.

**Comment by JonnyOThan** [comment]
Oops!  Yes, that looks like it would do it.
