### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid control character at

### ISSUE THREAD

**Issue by mbrucher** [include-what-you-use/include-what-you-use#461]
Hi,

I built a cmake project witht he export command option on Windows.
It seems that the commands have << << in them, but this seems to pose problem to the json decoder used by iwyu. Is there a workaround to make this work without having to change the command int he json file?

**Comment by kimgr** [comment]
Hmm, not that I can think of. Can you give a reduced example of a command-line like this?

**Comment by mbrucher** [comment]
An example of the generated file on Windows:
[
{
  "directory": "C:/build",
  "command": "C:\\PROGRA~2\\MICROS~1.0\\VC\\bin\\amd64\\cl.exe @<<
 /nologo /TP -Dproject_EXPORTS /DWIN32 /D_WINDOWS /W3 /GR /EHsc /fp:fast /W3 /MD /Zi /Ob0 /Od /RTC1 -DDEBUG   /FoCMakeFiles\\project.dir\\src\\myfile.cpp.obj /FdCMakeFiles\\core-core.dir\\ /FS -c C:\\src\\myfile.cpp
<<",
  "file": "C:/src/myfile.cpp"
},

It may be an issue with the nmake generator in CMake :/

**Comment by mbrucher** [comment]
An example of the generated file on Windows:
[
{
"directory": "C:/build",
"command": "C:\PROGRA2\MICROS1.0\VC\bin\amd64\cl.exe @<<
/nologo /TP -Dproject_EXPORTS /DWIN32 /D_WINDOWS /W3 /GR /EHsc /fp:fast /W3 /MD /Zi /Ob0 /Od /RTC1 -DDEBUG /FoCMakeFiles\project.dir\src\myfile.cpp.obj /FdCMakeFiles\project.dir\ /FS -c C:\src\myfile.cpp
<<",
"file": "C:/src/myfile.cpp"
},

It may be an issue with the nmake generator in CMake :/

**Comment by kimgr** [comment]
I think this is a CMake bug. The format description for the compilation database says the following about the command entry:
 
> The compile command executed. After JSON unescaping, this must be a valid command to rerun the exact compilation step for the translation unit in the environment the build system uses.

So it sounds like the nmake generator should expand the input placeholder to an actual filename.

**Comment by kimgr** [comment]
@mbrucher Could you raise this with the CMake folks at https://gitlab.kitware.com/cmake/cmake/issues? Maybe they can help determine if this is expected/valid behavior based on your CMake invocation and configuration.

**Comment by kimgr** [comment]
I don't see that there's much we can do here. Closing.
