### ISSUE TITLE
Release compatible with LLVM/Clang 5

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#462]
LLVM/Clang 5 Release Candidate 1 was tagged today. I think will be good idea to prepare correspondent IWYU release.

**Comment by aaronpuchert** [comment]
Any updates on this? The version number was already bumped to 0.9 in 93b85b2e760a0ae6067585f62dc9bc9d002b8067, and there is a branch [clang_5.0](https://github.com/include-what-you-use/include-what-you-use/tree/clang_5.0), but no official release yet.

As a private citizen I can use this just fine, but for packaging and distribution purposes it would be nice to have an official tagged release, maybe even a tarball on the [website](https://include-what-you-use.org/).

**Comment by kimgr** [comment]
@aaronpuchert We've lost a lot of technical infrastructure and manpower as all of the current maintainers switched jobs last year, so I don't think we'll be doing any more built releases for various platforms.

But a source release would definitely make sense, I think we can start with a Git tag on the `clang_5.0` branch and then I'll see if I can get a tarball up at some point.

**Comment by kimgr** [comment]
A `clang_5.0` tag is up now, with a corresponding release:
https://github.com/include-what-you-use/include-what-you-use/releases

I've built this in-tree and seen that all tests pass.

**Comment by aaronpuchert** [comment]
Thanks a lot! The source release is just what I needed.

**Comment by brad0** [comment]
Still need the release up on the website.

**Comment by kimgr** [comment]
I finally got around to updating https://include-what-you-use.org. The release is finally out!
