### ISSUE TITLE
C++11 range loops are ignored

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#463]
Looks like IWYU ignores C++11 range loops.

For example, it was suggested to remove llvm/CodeGen/MachineFunction.h from lib/Target/Hexagon/RDFRegisters.cpp, when constructor iterate through MachineFunction variable:

for (const MachineBasicBlock &B : mf)

**Comment by kimgr** [comment]
Thanks, should be relatively easy to catch.
