### ISSUE TITLE
iwyu keeps suggesting file in lowercase

### ISSUE THREAD

**Issue by jcageman** [include-what-you-use/include-what-you-use#474]
I have one file in our code base that somehow always ends up being suggested to be included in lowercase. E.g on windows path its C:/Adaptor.h, but the include results in #include <adaptor.h>, hence in lowercase. It does not result in a compile error, but because its lowercase it ends up being sorted at the end which is rather weird. Besides that i prefer the include to be upper case like the include file itself.

Any ideas? Even if i include it manually as Adaptor.h and afterwards run IWYU it will remove the file and add adaptor.h (lowercase). I already verified that it actually points to the same file, except for the casing.

**Comment by kimgr** [comment]
Strange. We don't do any case-folding in IWYU, as far as I know. Do you have any includes of lower-case `adaptor.h` elsewhere that

**Comment by kimgr** [comment]
(Oops, mispressed everything. Can follow up on this later.)

**Comment by jcageman** [comment]
I thought exactly that! I actually found a case where we included lowercase version, but i already fixed that before this post. Rerunning IWYU still suggested the lowercase version.

**Comment by jcageman** [comment]
Oke, i should have checked better. Indeed there was a case where #include <adaptor.h> was used, while i only verified #include "adaptor.h"

**Comment by kimgr** [comment]
OK, thanks!
