### ISSUE TITLE
Add an option that never adds forward declarations

### ISSUE THREAD

**Issue by acmorrow** [include-what-you-use/include-what-you-use#475]
Forward declarations are no longer stylish in the google style guide:

https://google.github.io/styleguide/cppguide.html#Forward_Declarations

It would be useful if IWYU had an option to always add the needed includes, rather than adding forward declarations.

**Comment by jcageman** [comment]
Duplicate of #354

**Comment by kimgr** [comment]
Closing as duplicate.
