### ISSUE TITLE
std::function gets private headers suggested

### ISSUE THREAD

**Issue by sesse** [include-what-you-use/include-what-you-use#487]
Hi,

As per IWYU 0.8 (based on clang 4.0.1-1, from Debian), anything std::function gets the wrong headers included:

```c++
#include <functional>

void bar();

void foo()
{
  std::function<void()>(foo) = bar;
}
```

```
atum17:~> /usr/bin/iwyu -std=c++14 -c test.cc

test.cc should add these lines:
#include <bits/std_function.h>  // for function
#include <algorithm>            // for move

test.cc should remove these lines:
- #include <functional>  // lines 1-1

The full include-list for test.cc:
#include <bits/std_function.h>  // for function
#include <algorithm>            // for move
---
```

This is a double error; not only does it suggest <algorithm> when no move was made, but it also suggests a private header from bits/.

**Comment by jcageman** [comment]
Sounds like the mapping files are currently missing for the new location of std::function. It seems the default mappings currently just contain a slightly different mapping:

`{ "<bits/stl_function.h>", kPrivate, "<functional>", kPublic },`

The fix would be to add the following mapping in your own mapping file for now:
`{ "<bits/std_function.h>", kPrivate, "<functional>", kPublic },`
