### ISSUE TITLE
iwyu wants to reomve header with prototype when not the same name as the c file

### ISSUE THREAD

**Issue by BradleySmall** [include-what-you-use/include-what-you-use#491]
If we have a project such that the header file and the c file don't share the same name, and the prototype is located in the header file, it will suggest removing the header file. This leads to warnings about function defined without prototype in scope. Here is a quick example:
---interface.h---
#ifndef INTERFACE_H
#define INTERFACE_H 1
#ifdef __cplusplus
extern "C" {
#endif
int junk(void); 
#ifdef __cplusplus
}
#endif
#endif
--- end ----
---func.c---
#include "interface.h"
#include <stdio.h>

int junk (void) {
   printf("Hello, world!\n");
   return 0;
}
--- end func.c ----
--- output----
$ iwyu func.c
$
$ func.c should add these lines:
$
$ func.c should remove these lines:
$ - #include "interface.h"  // lines 1-1
$
$ The full include-list for func.c:
$ #include <stdio.h>                      // for printf
$ ---

**Comment by jcageman** [comment]
Have seen the same issue, should be easy to reproduce.

**Comment by http404error** [comment]
Experiencing this as well.

**Comment by kimgr** [comment]
This is the same as #179, closing as duplicate (sorry I didn't notice earlier).
