### ISSUE TITLE
need a way to designate that section of output beginning with "The full include-list for" is not output

### ISSUE THREAD

**Issue by BradleySmall** [include-what-you-use/include-what-you-use#493]
I would like to manually correct my files. However, I do not need to see the section beginning with "The full include-list for". Presently I am piping it all through awk and removing it. But I would think it could be a command line argument or other configuration point.

**Comment by jcageman** [comment]
Can you show what your output does look like and how you call iwyu? One option to not get any output from iwyu regarding full include list would be --verbose with an argument smaller than zero. That would basically stop all output, also regarding lines to add and remove.

**Comment by kimgr** [comment]
Duplicate of #190?

**Comment by kimgr** [comment]
Bundled into #1563
