### ISSUE TITLE
In-tree build is broken with trunk LLVM/Clang

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#505]
I got next CMake error since yesterday:

CMake Error at tools/clang/tools/extra/include-what-you-use/CMakeLists.txt:127 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "include-what-you-use".  All uses of target_link_libraries with
  a target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * cmake/modules/AddLLVM.cmake:771 (target_link_libraries)

**Comment by kimgr** [comment]
Thanks, I was surprised our builders hadn't complained, but I don't think there is one for this configuration (mostly because it takes hours to build). I'll take a look in my local in-tree checkout.

**Comment by kimgr** [comment]
Hmm... I don't get the same error here. Some kind of merge conflict problem in your CMakeLists.txt?

**Comment by kimgr** [comment]
For the record, the same thing happened here when I was experimenting with the new CMake setup from issue #499. Still not sure what's going on.

**Comment by EugeneZelenko** [comment]
Thank you for fix!
