### ISSUE TITLE
badinc.cc test fails with -std=c++14

### ISSUE THREAD

**Issue by kimgr** [include-what-you-use/include-what-you-use#510]
Clang recently switched to gnu++14 by default (Clang r320250). That broke our test suite:

    AssertionError: 
    tests/cxx/badinc.cc:1527: Unmatched regex:
    I2_Enum is...*badinc-i2.h

I've done some initial analysis, and it turns out `std::vector` is a completely different beast in gnu++14 compared to gnu++98 (not surprisingly).

There's a comment near line 1527 that indicates the `I2_Enum` use is redundant but harmless. Unfortunately I don't think it disappears for the right reasons with gnu++14. Rather, IWYU's analysis is somehow broken in gnu++98 and broken in a different way in gnu++14.

I think the right move for this is to pin down what's wrong and make it work similarly independent of standard version.

**Comment by kimgr** [comment]
This was worked around in 5788b34c2e22, by removing the expectation for a diagnostic. Never found a root cause for the difference in behavior between gnu++98 and gnu++14 (the difference actually came about as of gnu++11).

**Comment by jru** [comment]
The root cause for this was found with #533 and fixed later here, af84cfc. The diagnostic is now consistent across all -std=gnu++XY versions from c++98 to c++14.
