### ISSUE TITLE
include-what-you-use should report useless "using namespace foo::bar;"

### ISSUE THREAD

**Issue by dpelle** [include-what-you-use/include-what-you-use#515]
include-what-you-use should report useless "using namespace foo::bar;".

Example:
```
$ cat foo.cpp
#include <vector>

// This "using namespace std" is not needed here since std:: 
// prefix is used everywhere.  include-what-you-use should ideally
// report that it's not needed.
using namespace std;

int main()
{
  std::vector<int> v{ 1, 2 };
  return static_cast<int>(v.size());
}
```
```
$ include-what-you-use -std=c++11 foo.cpp

(foo.cpp has correct #includes/fwd-decls)
```

I wish that include-what-you-use reported that
the "using namespace std;" at line 6 in foo.cpp is useless
and suggests to remove it. 

I'm using using-what-you-use version 0.8 (git:c6c4520).

**Comment by kimgr** [comment]
Thank you for the feature idea! I agree this would be nice, but it's not a core IWYU feature (as it has little to do with includes).

**Comment by EugeneZelenko** [comment]
See Clang-tidy's [misc-unused-using-decls](http://clang.llvm.org/extra/clang-tidy/checks/misc-unused-using-decls.html). If it doesn't detect situation you suggested exactly, improvements should be made there.

See also [this enhancement request](https://bugs.llvm.org/show_bug.cgi?id=25460).

**Comment by kimgr** [comment]
If tools already exist for this, I would vote to close the issue. @dpelle -- are you OK with that?

**Comment by dpelle** [comment]
> If tools already exist for this, I would vote to close the issue. @dpelle -- are you OK with that?

Nice that clang-tidy-7 can detect useless "using".
If that's indeed the case, then I'm fine with this ticket being closed.

**Comment by kimgr** [comment]
Thanks, closing. I don't see that we'll get to this anytime soon.

**Comment by EugeneZelenko** [comment]
See also [relevant warning in Clang](https://reviews.llvm.org/D44826) and check if it handle your situation.
