### ISSUE TITLE
Dependent names in out-of-class template methods are ignored

### ISSUE THREAD

**Issue by jru** [include-what-you-use/include-what-you-use#533]
After noticing that the diagnostic from the *badinc.cc* test case removed with 5788b34c was still being reported on Windows platforms, I started investigating..

The reason for it being no longer reported on Linux platforms is that *push_back* for rvalue references (using C++11 or above) is implemented using *emplace_back*, which happens to be defined outside of the vector class.

Following the rabbit hole I figured that #448 is what introduced this behavior, by purposely short circuiting the AST traversal when it finds such constructs. 

As an example of what this can cause consider this code:
```cpp
//---- file: dependent-int.h
void dependent(int);
//----

//---- file: dependent-char.h
void dependent(char);
//----

//---- file: out_of_class.cpp
#include "dependent-int.h"
#include "dependent-char.h"

template <class T>
struct Class {  void method(); };

template <class T>
void Class<T>::method()
{
    dependent(T{});
}

int main()
{
    Class<int> c;
    c.method();
}
//----
```
And this output from IWYU:
```
out_of_class.cpp should add these lines:

out_of_class.cpp should remove these lines:
- #include "dependent-char.h"  // lines 3-3
- #include "dependent-int.h"  // lines 2-2

The full include-list for out_of_class.cpp:
---
```

As a result of not exploring the instantiation of *method()* it does not find the dependent call and suggest a removal that would cause a compilation error.

Funnily enough, if either one of the header files is commented out, IWYU is happy. Not sure why it does that, but I guess it has to do with looking up the unresolved overload by the name if there is only one possible candidate.

**Expected:** IWYU should report that only *dependent-int.h* is wanted. This is exactly what happens when the definition of *method()* is moved inside the class:
```
out_of_class.cpp should add these lines:

out_of_class.cpp should remove these lines:
- #include "dependent-char.h"  // lines 3-3

The full include-list for out_of_class.cpp:
#include "dependent-int.h"  // for dependent
---

```

**Comment by kimgr** [comment]
Thank you for root-causing this! I'm guessing your reduced example behaves the same on all platforms (the difference at this point should only be Microsoft extensions and delayed template parsing)?

It would be nice to get to the bottom of this, because we've also seen related failures on FreeBSD and macOS (or whatever they call it these days :)). I'll see if I can find some time over the coming weeks to explore the rabbit hole a little more.

**Comment by jru** [comment]
Hey,

It does not rely on any library code or special switches so it should behave identical everywhere. I ran it also with the *-fdelayed-template-parsing* option and there is no change in outcome.

[I gave the fix a try](https://github.com/jru/include-what-you-use/tree/ignore-qualifier-out-of-line-methods) and it seems to be working, but of course, it will need more testing. If it doesn't look so terrible I could open a PR and continue the discussion there. 

The main idea is to keep parsing the AST but just skip the bit where the template name triggers an instantiation. Also, I had to put back some expectations of enums in *badinc.cc* but now at least it looks more consistent. 

**Bonus:** 
I found a new scenario that didn't work in IWYU before (afaik): explicitly specialized out-of-line methods.
In the included test case, the last scenario does not get reported when it should.

**Comment by kimgr** [comment]
I'd love to see a pull request for this so I can test on Linux/GCC and FreeBSD/clang environments. In the meantime I'll see if I can get my head around the changes in your branch (my understanding of IWYU's template handling is quite poor).

Thank you!
