### ISSUE TITLE
IWYU's zlib dependency isn't always necessary

### ISSUE THREAD

**Issue by adembo** [include-what-you-use/include-what-you-use#539]
I recently built IWYU in-tree with LLVM 6 and was surprised to see that while the LLVM build succeeded, IWYU failed:
> [100%] Linking CXX executable ../../../../bin/include-what-you-use
> /usr/bin/ld: cannot find -lz
> collect2: error: ld returned 1 exit status
> make[2]: *** [bin/include-what-you-use] Error 1
> make[1]: *** [tools/clang/tools/include-what-you-use/CMakeFiles/include-what-you-use.dir/all] Error 2
> make: *** [all] Error 2

Turns out my CentOS 7.4 system didn't have the zlib-devel package installed, so there was no /lib/libz.so symlink to /lib/libz.so.1. LLVM considers zlib to be optional and indeed the llvm::zlib classes in LLVMSupport.a were stubbed. But IWYU assumes that LLVM always depends on zlib (see #137), and this isn't true.

Installing zlib-devel is easy enough, but it'd be nice if IWYU did the right thing depending on whether zlib exists or not, or (even better) depending on whether the LLVM libraries were built against zlib.

**Comment by kimgr** [comment]
I'm working in the background on fixing some bugs in the official Clang packaging off http://apt.llvm.org/. Once that's done, hopefully we can use normal CMake procedures to pick up build information from LLVM/Clang.

I don't know what the CentOS packaging looks like, but hopefully it installs all CMake goo in the right places. Attached is a little test project you can use to test consumption of Clang packages in CMake. The `configure` script is wired to select `llvm-7` in my dist's install root, so you may want to change the `CMAKE_PREFIX_PATH` argument to match your install. If this works, there's a good chance IWYU will work once the Debian package bugs are fixed.

[cmake.zip](https://github.com/include-what-you-use/include-what-you-use/files/1976428/cmake.zip)

**Comment by kimgr** [comment]
@adembo PR #542 should solve this, can you test it on your platform?

**Comment by kimgr** [comment]
I'm pretty sure this is solved by 0003739b52e0bcefa574ed6dbc5dc7cf78da3cb4. See revised docs at https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build.
