### ISSUE TITLE
Build with trunk LLVM/Clang is broken

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#541]
I tried to build LLVM/Clang r332104 with trunk IWYU and I got:

In file included from llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu.cc:115:0:                      
llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu_preprocessor.h:195:8: error: 'void include_what_you_use::IwyuPreprocessorInfo::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)' marked override, but does not override                                                            
   void InclusionDirective(clang::SourceLocation hash_loc,                                                                                                    
        ^                                                                                                                                                     
In file included from llvm-svn.src/tools/clang/include/clang/Lex/Preprocessor.h:31:0,                               
                 from llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu_preprocessor.h:73,             
                 from llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu.cc:115:                        
llvm-svn.src/tools/clang/include/clang/Lex/PPCallbacks.h:124:16: warning: 'virtual void clang::PPCallbacks::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*, clang::SrcMgr::CharacteristicKind)' was hidden [-Woverloaded-virtual]                                                                
   virtual void InclusionDirective(SourceLocation HashLoc,                                                                                                    
                ^                                                                                                                                             
In file included from llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu.cc:115:0:                      
llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu_preprocessor.h:195:8: warning:   by 'void include_what_you_use::IwyuPreprocessorInfo::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)' [-Woverloaded-virtual]                                                                     
   void InclusionDirective(clang::SourceLocation hash_loc,                                                                                                    
        ^                                                                                                                                                     
In file included from llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu.cc:105:0:                      
llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu_ast_util.h: In member function 'const void* include_what_you_use::ASTNode::DynCast(const void*) const [with Ignored = void]':                                                                                      
llvm-svn.src/tools/clang/tools/extra/include-what-you-use/iwyu_ast_util.h:310:3: warning: control reaches end of non-void function [-Wreturn-type]                                                                                                                                
   }                                                                                                                                                          
   ^

**Comment by kimgr** [comment]
See #540. No need to create issues for API breaks, we have a buildbot sending failure e-mails to the mailing list. Thanks!
