### ISSUE TITLE
fix_includes.py removes forward declares in different namespaces

### ISSUE THREAD

**Issue by chri7325** [include-what-you-use/include-what-you-use#557]
fix_includes.py will remove duplicate forward declare lines that exist in seperate namespaces.  This appears to happen at _DeleteDuplicateLines(file_lines, toplevel_reorder_spans).  This function only checks the string of each class for duplicates to remove.  The toplevel_reorder_spans don't seem to take into account different namespaces, causing the python script to remove the duplicated lines.

For example,
```
// test.cpp
namespace Outer_namespace
{
namespace Inner_namespace_1
{
class Test;
class Fake_class;
} // namespace Inner_namespace_1

namespace Inner_namespace_2
{
class Test;
} // namespace Inner_namespace_2
} // namespace Outer_namespace

Outer_namespace::Inner_namespace_1::Test *test_inner_namespace_1;
Outer_namespace::Inner_namespace_2::Test *test_inner_namespace_2;
```
Will produce
```

test.cpp should add these lines:

test.cpp should remove these lines:
- namespace Outer_namespace { namespace Inner_namespace_1 { class Fake_class; } }  // lines 6-6

The full include-list for test.cpp:
namespace Outer_namespace { namespace Inner_namespace_1 { class Test; } }  // lines 5-5
namespace Outer_namespace { namespace Inner_namespace_2 { class Test; } }  // lines 11-11
```
After running fix_includes.py on the file, the end result is
```
namespace Outer_namespace
{
namespace Inner_namespace_1
{
class Test;
} // namespace Inner_namespace_1

namespace Inner_namespace_2
{
} // namespace Inner_namespace_2
} // namespace Outer_namespace

Outer_namespace::Inner_namespace_1::Test *test_inner_namespace_1;
Outer_namespace::Inner_namespace_2::Test *test_inner_namespace_2;
```

**Comment by chri7325** [comment]
It looks as though this is happening because of the namespace style.  For our codebase, we use the AfterNamespace style for clang format so { is always on the next line.  The script is making assumptions that the style is done with { on the same line as the namespace so the regex for namespace detection doesn't quite work for our coding style.

**Comment by kimgr** [comment]
Thanks, that would be great! Put up a pull request, please!

**Comment by chri7325** [comment]
Sounds good!  Which branch should I issue the pull request for?  We "forked" on clang_5.0 but will probably jump to clang_6.0 soon.  Also, I had a commit to format the code using vscode since it kept doing it to me and I wanted to keep my commits clean.  Should I add this step as well?

**Comment by kimgr** [comment]
The `master` branch, please; we only use the release branches while developing releases, then they go to sleep.

If it's possible to avoid the reformat, I would prefer to leave things alone to minimize churn and keep the blame log cleaner.

**Comment by chri7325** [comment]
Fix was installed and verified with master.
