### ISSUE TITLE
Template explicit instantiation declarations aren't handled properly

### ISSUE THREAD

**Issue by scramsby** [include-what-you-use/include-what-you-use#558]
# Code

## some_class.h

```C++
#pragma once

template<typename T>
class some_class
{
};

extern template class some_class<int>;
```

## some_class.cpp

```C++
#include "some_class.h"

// template instantiations
template class some_class<int>;
```

# Output

```
C:/temp/some_class.h should add these lines:

C:/temp/some_class.h should remove these lines:
- class some_class;  // lines 4-4

The full include-list for C:/temp/some_class.h:
---
```

# Issues

1. The line suggested to be removed is quoted from some_class.h, but the actual line in question with that line number is actually from some_class.cpp.
2. The actual code text doesn't quite match what's actually in the source file.
3. The tool should not be suggesting to remove explicit template instantiations in the first place. Just because they aren't used by the declaring class doesn't mean they won't be used by dependent code.

See [cppreference.com](http://en.cppreference.com/w/cpp/language/class_template#Explicit_instantiation) for description of explicit template instantiation declarations and definitions.

**Comment by scramsby** [comment]
Note: I confirmed that the suggestion goes away if you add an "// IWYU pragma: keep" in the .cpp, despite the instruction being to remove it from the .h.

**Comment by jru** [comment]
Hey there, thanks for the great repro! 

I just opened a PR to fix this. To be exact: it addresses (3), the handling of explicit template instantiations, which is the main issue. 

(1) and (2) have to do with forward declarations only and how they are created by the tool, in *AddForwardDeclare*. In some cases it will select a declaration from a different file and mix the original filename with the source ranges of where it thinks the decl lives, messing up the output big time :) 

Anyway, I think this should probably go into its own issue.  @kimgr Are you good with that?

**Comment by kimgr** [comment]
@jru Yeah, sounds like a good idea, thanks!
