### ISSUE TITLE
Issue while building iwyu on RHEL6 machine

### ISSUE THREAD

**Issue by Abinayasandhiya** [include-what-you-use/include-what-you-use#560]
Hi,

We are trying to install iwyu-0.9 on RHEL6 machine.
Please find below commands which we are trying to use:

cmake -DCMAKE_INSTALL_PREFIX=%{_prefix} -DIWYU_LLVM_ROOT_PATH="/opt/llvm/x86_64/%{llvm_ver}"  -DCMAKE_CROSSCOMPILING=True  -DIWYU_LLVM_INCLUDE_PATH=/opt/llvm/x86_64/4.0.0/include/ ..

make

make install

first step of building seems success but facing issue while building "make".
Please find below issue:
***********************************************************************************************************
/opt/llvm/x86_64/4.0.0.g530a/bin/ld: error: unable to find library -lLLVMBinaryFormat
collect2: error: ld returned 1 exit status
make[2]: *** [include-what-you-use] Error 1
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.58BrJ5 (%build)
*********************************************************************************************************

Anyone help me on this.

**Comment by Bu11etmagnet** [comment]
Hi,

please run 
```
make VERBOSE=1 
```
and post the linker command line (should be the line before the "error:") so we can see what the linker was trying to do and what options did it get.

**Comment by Abinayasandhiya** [comment]
Hi,

Thanks for the help.

Please find below log while run "make VERBOSE=1"

***********************************************************************************************************
-- Configuring done
-- Generating done
-- Build files have been written to: /root/rpmbuild/BUILD/include-what-you-use/build
+ make VERBOSE=1
/opt/cmake/x86_64/3.7.1-1/bin/cmake -H/root/rpmbuild/BUILD/include-what-you-use -B/root/rpmbuild/BUILD/include-what-you-use/build --check-build-system CMakeFiles/Makefile.cmake 0
/opt/cmake/x86_64/3.7.1-1/bin/cmake -E cmake_progress_start /root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles /root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/root/rpmbuild/BUILD/include-what-you-use/build'
make -f CMakeFiles/include-what-you-use.dir/build.make CMakeFiles/include-what-you-use.dir/depend
make[2]: Entering directory `/root/rpmbuild/BUILD/include-what-you-use/build'
cd /root/rpmbuild/BUILD/include-what-you-use/build && /opt/cmake/x86_64/3.7.1-1/bin/cmake -E cmake_depends "Unix Makefiles" /root/rpmbuild/BUILD/include-what-you-use /root/rpmbuild/BUILD/include-what-you-use /root/rpmbuild/BUILD/include-what-you-use/build /root/rpmbuild/BUILD/include-what-you-use/build /root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles/include-what-you-use.dir/DependInfo.cmake --color=
Dependee "/root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles/include-what-you-use.dir/DependInfo.cmake" is newer than depender "/root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles/include-what-you-use.dir/depend.internal".
Dependee "/root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/root/rpmbuild/BUILD/include-what-you-use/build/CMakeFiles/include-what-you-use.dir/depend.internal".
Scanning dependencies of target include-what-you-use
make[2]: Leaving directory `/root/rpmbuild/BUILD/include-what-you-use/build'
make -f CMakeFiles/include-what-you-use.dir/build.make CMakeFiles/include-what-you-use.dir/build
make[2]: Entering directory `/root/rpmbuild/BUILD/include-what-you-use/build'
[  7%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu.cc
[ 14%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_ast_util.cc
[ 21%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_cache.cc
[ 28%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_driver.cc
[ 35%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_getopt.cc
[ 42%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_globals.cc
[ 50%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_include_picker.cc
[ 57%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_lexer_utils.cc
[ 64%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_location_util.cc
[ 71%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_output.cc
[ 78%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_path_util.cc
[ 85%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_preprocessor.cc
[ 92%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o
/opt/gcc/x86_64/6.1.0/bin/c++   -DIWYU_GIT_REV=\"\" -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/opt/llvm/x86_64/5.0.0.g610/include  -fno-rtti -std=c++11   -o CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o -c /root/rpmbuild/BUILD/include-what-you-use/iwyu_verrs.cc
[100%] Linking CXX executable include-what-you-use
/opt/cmake/x86_64/3.7.1-1/bin/cmake -E cmake_link_script CMakeFiles/include-what-you-use.dir/link.txt --verbose=1
/opt/gcc/x86_64/6.1.0/bin/c++    -fno-rtti -std=c++11   CMakeFiles/include-what-you-use.dir/iwyu.cc.o CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o  -o include-what-you-use  -L/opt/llvm/x86_64/5.0.0.g610/lib -Wl,-rpath,/opt/llvm/x86_64/5.0.0.g610/lib: -lclangFrontend -lclangSerialization -lclangDriver -lclangParse -lclangSema -lclangAnalysis -lclangAST -lclangBasic -lclangEdit -lclangLex -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86AsmPrinter -lLLVMX86Info -lLLVMX86Utils -lLLVMCodeGen -lLLVMipo -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMTarget -lLLVMAnalysis -lLLVMOption -lLLVMMCDisassembler -lLLVMMCParser -lLLVMMC -lLLVMProfileData -lLLVMObject -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle -lpthread -lz -lcurses /usr/lib64/libform.so -ldl
/opt/llvm/x86_64/5.0.0.g610/bin/ld: error: undefined symbol: setupterm
>>> referenced by Process.cpp.o:(llvm::sys::Process::FileDescriptorHasColors(int)) in archive /opt/llvm/x86_64/5.0.0.g610/lib/libLLVMSupport.a

/opt/llvm/x86_64/5.0.0.g610/bin/ld: error: undefined symbol: tigetnum
>>> referenced by Process.cpp.o:(llvm::sys::Process::FileDescriptorHasColors(int)) in archive /opt/llvm/x86_64/5.0.0.g610/lib/libLLVMSupport.a

/opt/llvm/x86_64/5.0.0.g610/bin/ld: error: undefined symbol: set_curterm
>>> referenced by Process.cpp.o:(llvm::sys::Process::FileDescriptorHasColors(int)) in archive /opt/llvm/x86_64/5.0.0.g610/lib/libLLVMSupport.a

/opt/llvm/x86_64/5.0.0.g610/bin/ld: error: undefined symbol: del_curterm
>>> referenced by Process.cpp.o:(llvm::sys::Process::FileDescriptorHasColors(int)) in archive /opt/llvm/x86_64/5.0.0.g610/lib/libLLVMSupport.a
collect2: error: ld returned 1 exit status
make[2]: *** [include-what-you-use] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/include-what-you-use/build'
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/include-what-you-use/build'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.08LZIK (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.08LZIK (%build)
***********************************************************************************************************

**Comment by kimgr** [comment]
I think you might need to patch CMakeLists.txt to add `tinfo` or ncurses as a link dependency. We've just recently (on trunk) made the build system follow LLVM's more closely.

**Comment by Abinayasandhiya** [comment]
Hi,

Please find below attached CMakeLists.txt file

[CMakeLists.txt](https://github.com/include-what-you-use/include-what-you-use/files/2078987/CMakeLists.txt)

Please let me know which line we have to patch to fix the issue.

**Comment by Abinayasandhiya** [comment]
Wowww. great....

Installed successfully.

Thanks for your help:)

**Comment by Bu11etmagnet** [comment]
Hmm, if LLVM needs `tinfo`, then LLVM's (not iwyu's) CMakeLists.txt should ensure that it gets linked.

**Comment by kimgr** [comment]
Yes, but IWYU 0.9 does not use LLVM's CMake. IWYU master does, but only since https://github.com/include-what-you-use/include-what-you-use/commit/0003739b52e0bcefa574ed6dbc5dc7cf78da3cb4.
