### ISSUE TITLE
Is this still alpha quality software?

### ISSUE THREAD

**Issue by thedrow** [include-what-you-use/include-what-you-use#564]
The warning in the README is from 2011.
7 years have passed since then.
Is this still alpha quality code?

**Comment by kimgr** [comment]
Matter of perspective, I guess :)

I've looked at that comment a few times over the years, and I still think it reflects the project's status. IWYU works pretty well, but there's still a lot of rough edges and some problems we don't really know how to solve.

Maybe we should just bump the date to make it look less anachronistic.

**Comment by kimgr** [comment]
Updated the CAVEAT section in the README a little in a42f5d356aae5135456bc5bcb9c5d681db2a5a4a. Closing.
