### ISSUE TITLE
Clang headers are still not properly detected

### ISSUE THREAD

**Issue by pfaffe** [include-what-you-use/include-what-you-use#565]
I'm aware this has been reported multiple times already, but I'm still seeing this:
```
/usr/lib64/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/cstddef:50:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
```
I'm building iwyu from source, as well as clang, both latest trunk. I'm building iwyu against an install-tree of clang.

**Comment by kimgr** [comment]
This is tracked in #100, closing as duplicate.

See also https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-install.
