### ISSUE TITLE
iwyu_tool and multiprocessing

### ISSUE THREAD

**Issue by pfaffe** [include-what-you-use/include-what-you-use#566]
PR #444 introduced multiprocessing to iwyu_tool. Turns out this is problematic, since there's a bug (IMO) in python2.7's implementation: it swallows signals sent to the child. So if you hit ctrl-c, nothing happens (besides multiprocessing giving you the finger in the form of a nice stack trace).

I can think of four fixes, ordered by degree of radicalness:
- Bump the python version to 3
- Drop multiprocessing
- Use twisted
- Replace multiprocessing with a custom thread pool

Happy to file a PR, but would like to discuss which of these path's to go first.

**Comment by pseyfert** [comment]
Sorry for that and thanks for reporting. Let's hear what the maintainers have to say. Obviously I have a preference against dropping multiprocessing. From what I googled, SO agrees with you that this is a bug in python. There are suggestions how to fix it within python 2.7 https://stackoverflow.com/a/35134329/ .

**Comment by pfaffe** [comment]
The fix is worth a try, but looking at the multiprocessing code I don't see how it'll work: [process.py](https://github.com/python/cpython/blob/master/Lib/multiprocessing/process.py#L309). The catch-all except doesn't depend on the timeout or cache the signal.

**Comment by kimgr** [comment]
A simple workaround is posted here: https://stackoverflow.com/a/2561809.

It doesn't appear to cover all scenarios, but maybe it's good enough for our purposes? A nice side quality is that it's portable, unlike explicit signal-handling.

**Comment by pfaffe** [comment]
I'm not sure if they tested this solution, and it doesn't make much sense to me in general.

Multiprocesing wild-card catches all exceptions  except SystemExit, see the link I posted. As a hacky workaround we might catch KeyboardInterrupt and raise a SystemExit instead, but that seems icky and not incredibly stable.

**Comment by kimgr** [comment]
It doesn't matter what multiprocessing does internally if the function it calls handles `KeyboardInterrupt` (unless signal handling is messed up, and maybe that's the root problem). It doesn't seem necessary to raise `SystemExit`, just returning from the function should be enough to terminate the worker process.

If you have a consistent repro, could you try it and report back?

Thanks!

**Comment by pfaffe** [comment]
Multiprocessing essentially swallows the signal. The worker process observes and handles it, but the master doesn't terminate as you'd expect it to do, it just prints the stack trace.

It should terminate the master process, and not just the worker. But you're right, SystemExit just terminates the worker, not the master, so that doesn't help.

To repro it, run iwyu_tool on a larger code base, e.g. LLVM, and try to cancel it.
Here's a smaller testcase that shows the same thing: https://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool

Fundamentally we shouldn't be using multiprocessing at all. With it, we create a pool of processes ... which then spawn new processes. We can just spawn the iwyu processes directly, without another layer in between. We don't need parallelism, we need asynchronicity. Multiprocessing is not the right tool for that.

**Comment by kimgr** [comment]
That sounds like a good idea. I agree that it's unnecessary to launch processes just to launch processes (sic).

It'll probably be hard to make it as nice and clean, API-wise, as multiprocessing, but if we can make it happen without a huge amount of code, it would be nice to get rid of multiprocessing.

**Comment by kimgr** [comment]
This is fixed as of dbab9201143deb07f63688d4c6e3402dbd2ca7fe. Closing.
