### ISSUE TITLE
ignoring struct forward declarations

### ISSUE THREAD

**Issue by Akuli** [include-what-you-use/include-what-you-use#573]
`// IWYU pragma: keep` only works with included files and not struct forward declarations, so sometimes I need to  include files when fwd dcling a struct would be enough.

**Comment by kimgr** [comment]
Support for this was added here: https://github.com/include-what-you-use/include-what-you-use/commit/a2d8e282502cd6018b33f307519ba971b7cc11c2

It should be in iwyu 0.8 or 0.9. Which version are you running?

**Comment by Akuli** [comment]
Something very old. I tried compiling a newer IWYU, but I didn't have much luck with it. I should probably just download a newer ubuntu.
