### ISSUE TITLE
find stddef.h error while compile passed with the same commandline parameter

### ISSUE THREAD

**Issue by wangjieest** [include-what-you-use/include-what-you-use#577]
I use clang to compile ue4 single file, it passed, but with iwyu, error as below:
In file included from Runtime/Engine/Public\Engine.h:12:
In file included from Runtime/Core/Public\Core.h:12:
In file included from Runtime/Core/Public/CoreMinimal.h:26:
In file included from Runtime/Core/Public/HAL/PlatformCrt.h:5:
In file included from ThirdParty/Linux/LibCxx/include/c++/v1\new:70:
In file included from ThirdParty/Linux/LibCxx/include/c++/v1\exception:81:
ThirdParty/Linux/LibCxx/include/c++/v1\cstddef(43,15):  fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~

**Comment by kimgr** [comment]
I think you're running into issue #100. There's a condensed problem description and suggested workarounds here: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-install

And finally, there's a brand new pull request up, #576, which will hopefully solve this once and for all.

Please let us know if the documentation helps, and I can close this as a duplicate.

**Comment by kimgr** [comment]
I'm going to assume this is #100. Closing as duplicate.
