### ISSUE TITLE
Allow output to be directed to a file instead of stdout

### ISSUE THREAD

**Issue by jonesmz** [include-what-you-use/include-what-you-use#579]
I'm trying to integrate iwyu into a bespoke build system (Home grown, from before my time at this job), and find the behavior where iwyu prints it's recommendations onto the commandline to be counter productive for what i'm trying to do.

When IWYU is pretending to be a compiler, could an -Xiwyu flag be detected that instructs IWYU to direct it's report to the file indicated by the -o flag (normally used to indicate where to write the object file when compiling)?

This would allow me to have the report sent directly to a file, without needing to cludge weird handling into my build system.

**Comment by kimgr** [comment]
I love bespoke build systems! :)

Wouldn't it be easier for you to just wrap include-what-you-use in a shell script (or batch file, depending on platform) and do your redirects/exit code handling there?

**Comment by jonesmz** [comment]
Honestly.... no, that'd be a lot of changes. It's not a very well put together build system, and I'm trying to integrate directly with the IWYU source code

But if you're not interested in a change like this, I'll probably have to do something like that.

I spent a couple hours last night to see if I could redirect the output, no concrete answer yet, but that's not surprising since i fell asleep staring at the code :-P

**Comment by kimgr** [comment]
Heh, that happens to me all the time.

I think IWYU consistently uses `llvm::errs()` to write output to `stderr`. Maybe it's possible for you to redirect `llvm::errs()` globally in LLVM, somehow?

What do you mean by "integrate directly with the IWYU source code"?

**Comment by Bu11etmagnet** [comment]
I'd suggest writing a wrapper script that runs iwyu with the output already redirected, and invoking that from the build system, e.g.

`include-what-you-use "$@" 1>>iwyu.out 2>>iwyu.err `

**Comment by kimgr** [comment]
I don't think this is anything we will pursue in the project. Plenty of other priorities. Closing.
