### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by donny-dont** [include-what-you-use/include-what-you-use#581]
Will there be any release binaries for IWYU going forward? 0.8 and earlier have binaries at https://include-what-you-use.org/downloads/.

**Comment by kimgr** [comment]
No, we gave up on binary releases as of IWYU 0.9 because we no longer have access to many of the target platforms (Windows, Mac). See the release notes for 0.9 (11 March 2018).

It should be fairly easy to build IWYU from source based on LLVM/Clang release packages. What platform are you on?

**Comment by donny-dont** [comment]
I'm on Windows. I haven't tried to build it out yet but I'm guessing its not too bad.

Is there any particular way to help you get a distribution? I know there's Appveyor for Windows builds.

**Comment by kimgr** [comment]
We're having enough trouble keeping up with Clang-compatible source releases, so unfortunately we can't take on the additional responsibility of getting binary releases out.

If someone wants to assume that responsibility, please reopen this issue and we can discuss ways forward. Thanks!
