### ISSUE TITLE
global include replaced: #include <QDir> becomes <qdir.h>

### ISSUE THREAD

**Issue by 3nids** [include-what-you-use/include-what-you-use#587]
Is there anyway that this doesn't happen?
Etiher by a missing include?
Or manually specifying a dictionary?

**Comment by kimgr** [comment]
IWYU ships with best-effort mapping files for QT, see `qt4.imp` and `qt5_4.imp`. You could try them and see if it works better.

**Comment by 3nids** [comment]
interesting. Is there any doc on how to use them or are you able to paste here the command?
Cheers!

**Comment by 3nids** [comment]
awesome, thanks a lot, should have been looking a bit more....
If I can ask another thing, do you know how to integrate this in the CMake call?
I tried:
> -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="path_to/include-what-you-use;--mapping_file=path_to/include-what-you-use/qt5_4.imp;-Xiwyu;any;-Xiwyu;iwyu;-Xiwyu;args" \
 
without success.
Thanks again for your quick replies.

**Comment by kimgr** [comment]
`--mapping_file` is an IWYU arg, so it needs to be prefixed with `-Xiwyu`:

```
-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="path_to/include-what-you-use;-Xiwyu;--mapping_file=path_to/include-what-you-use/qt5_4.imp..." \
```

Arguments without `-Xiwyu` are passed to the Clang embedded in IWYU.

The `...` is a placeholder for any other arguments you might want to pass.

**Comment by 3nids** [comment]
Perfect, many thanks!!!
(I could not edit your comment, but it misses a `;` before '...')

**Comment by kimgr** [comment]
Updated, thanks!

**Comment by 3nids** [comment]
actually, getting warnings in both case...looking at it

**Comment by kimgr** [comment]
Yes, QT is known problematic (or IWYU is, depending on your vantage point), so I wouldn't be surprised if there were false warnings even with mappings.
