### ISSUE TITLE
Removing headers from source file

### ISSUE THREAD

**Issue by dealre** [include-what-you-use/include-what-you-use#596]
I apologize because I know I probably shouldn't be posting for help in the issues section but I can't figure out where else to ask or if there's someone I can email. I'll be honest, I don't really know how to use iwyu much at all and I probably installed it wrong or just am generally misunderstanding how it is meant to be used, but help would be appreciated. 

What i'm trying to do is use iwyu to clean c source files of unnecessary headers, but I'm having some issues getting it to work how i'm imagining it's meant to. I'm running a 64bit Ubuntu 16.04.4 virtual machine on a windows and I used the following to install iwyu. I didn't really understand the instructions and I know the way I did it is somewhat round-a-bout.
```
$ sudo apt install iwyu
$ sudo apt install clang
$ sudo update-alternatives --install /usr/bin/clang /usr/bin/clang-3.7 100
```

i'm using the file `iwyu_tester.c` to test it
```
$ cat iwyu_tester.c
#include <stdio.h>
#include <sys/socket.h>
#include <string.h>

int main(){
    printf("hello world\n");
    return 0;
}
```

I then try to use iwyu on it the way i'm somewhat sure it's meant to be used
```
$ iwyu iwyu_tester.c
iwyu_tester.c should add these lines:

iwyu_tester.c should remove these lines:
- #include <string.h>  // lines 3-3
- #include <sys/socket.h>  // lines 2-2

the full include-list for iwyu_tester.c:
#include <stdio.h>  // for printf
---
```

It works all well and good, but what I don't know how to do is to get it to either rewrite the file it checked to comment out the includes, delete the include lines, or make a copy of the file that doesn't have the includes it suggests to remove. Also, if it could do it to a whole folder of c files, that would be great. Apparently you can do it with cmake or something?

I know iwyu is meant for c++ files, but I thought I found somewhere that c works also. I bet i'm just missing something silly, I'm not grasping the point of iwyu, or I'm just using it wrong. If someone could point me in the right direction, that would be very appreciated because I have been trying to figure this out for a few days now.

completely unrelated:
do you really pronounce iwyu as 'eye-double-you-why-you'?
I personally think 'eye-you' sounds a bit catchier

**Comment by vmartinv** [comment]
I'm not an expert neither but have you checked the section ["Applying fixes" in the README](https://github.com/include-what-you-use/include-what-you-use#applying-fixes)? That seems more or less what you need.

**Comment by dealre** [comment]
I tried running the suggested lines in "applying fixes" and I don't think it helped me much at all. 
I ran:
```
make -k CXX=/path/to/llvm/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out
python fix_includes.py < /tmp/iwyu.out
```
and also tried:
```
make -k CXX=/usr/share/llvm-3.7/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out
python fix_includes.py < /tmp/iwyu.out
```
I don't really know how iwyu works at all and if I need to figure out how to use / make a build in make/cmake or something, but I'm sort of out of ideas. Do you know if maybe anyone made a video on how to use iwyu, or if there are any instructions anywhere besides github?

Thanks for the help.

**Comment by dealre** [comment]
So I tried doing what applying fixes said to do:
```
make -k CXX=/path/to/llvm/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out
python fix_includes.py < /tmp/iwyu.out
```
got the python error: can't open file 'fix_includes.py': [Errno 2] No such file or directory
then tried:
```
make -k CXX=/user/share/llvm-3.7/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out
python fix_includes.py < /tmp/iwyu.out
```
which is the actual path to the right llvm version I think I need for clang, and got the same error.
I don't know what else to try to do, but if maybe there is some kind of simpler tutorial or maybe a video, then it would be very well appreciated if anyone would share.

Thanks for the response.

**Comment by dealre** [comment]
So I tried doing what applying fixes said to do:
```
make -k CXX=/path/to/llvm/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out
python fix_includes.py < /tmp/iwyu.out
```
got the python error: can't open file 'fix_includes.py': [Errno 2] No such file or directory
then tried:
```
make -k CXX=/user/share/llvm-3.7/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out
python fix_includes.py < /tmp/iwyu.out
```
which is the actual path to the right llvm version I think I need for clang, and got the same error.
I don't know what else to try to do, but if maybe there is some kind of simpler tutorial or maybe a video, then it would be very well appreciated if anyone would share.

Thanks for the response.

github keeps deleting my comment, can't even use github correctly

**Comment by dealre** [comment]
It would help alot if someone could possibly explain how they themselves use/installed iwyu because I bet I installed it wrong or something. Does it need to be built or something? I just don't understand.

**Comment by dealre** [comment]
I bet its not going to help to bump, but if anyone could help me out that would be well appreciated. I want to know how to remove unnecessary includes from a directory of source files and headers. Thanks.

**Comment by dealre** [comment]
I know this issue is more of one between the keyboard and chair, but If someone could give a detailed explanation/description of how to use iwyu, maybe even step by step, I would be eternally grateful.

**Comment by kimgr** [comment]
The Ubuntu `iwyu` package seems to have picked new names for the binaries, so it doesn't map 100% back to our documentation.

The relevant part for you is: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-run, but you need to use `iwyu` wherever the documentation says `include-what-you-use` and `fix_include` wherever the doc says `python fix_includes.py`

The key takeaway from the document is that `include-what-you-use` or `iwyu` acts as a replacement for the compiler you would normally use. And it needs the same compiler flags (`CFLAGS`/`CXXFLAGS`) as your normal build. This is because IWYU parses your code like a compiler would, but then generate an include report instead of generating code.

So what does your build system look like? Do you have a make system? CMake? Shell script? If you can configure that build system to use `iwyu` instead of `gcc`, it should just work:tm:.

Then pipe the output to `/usr/bin/fix_include`, which is the Ubuntu package's spelling of `fix_includes.py`, and it should apply fixes.

Make sure you're doing this on source-controlled code, so you can safely reset in case it does something you don't want.

**Comment by dealre** [comment]
Thanks so much for the response. Sadly i'm sort of not allowed to view the build or really much at all because I'm just an intern, but I'll try and get as much as I can. Thanks for the help.

**Comment by dealre** [comment]
since I wasn't going to be able to get the build, i'm just testing on a download of the linux kernel for now until I figure out how iwyu works. I tried running the following commands in the "how to run" section trying to figure out how it works, but they all ended up giving a load of errors saying stuff like "command not found" so i'm guessing I am using the wrong path for llvm? (I also tried them all with "CXX" instead of "CC" and with "llvm-3.7" instead of llvm, but figured adding those in this post would be a bit unnecessary)
```
make -k CC=/path/to/llvm/Debug+Asserts/bin/iwyu
make -k CC=/path/to/llvm/Release/bin/iwyu
make -k CC=/usr/lib/llvm/Debug+Asserts/bin/iwyu
make -k CC=/usr/lib/llvm/Release/bin/iwyu
make -k CC=/usr/share/llvm/Debug+Asserts/bin/iwyu
make -k CC=/usr/share/llvm/Release/bin/iwyu
make -k CC=/usr/include/llvm/Debug+Asserts/bin/iwyu
make -k CC=/usr/include/llvm/Release/bin/iwyu
```
so uh, what am I doing wrong exactly? did I install it wrong? am I using the wrong version? do I need to install something else? should I not try to build the linux kernel? psycho mantis?

**Comment by dealre** [comment]
tried to do the following command:
```
rdeal@rdeal-VirtualBox:~/Desktop/linux419$ make -k CC=/usr/bin/iwyu
```
(keep in mind, linux419 is the folder I extracted from a zip i downloaded at https://www.kernel.org and then renamed)  
and got:
```
rdeal@rdeal-VirtualBox:~/Desktop/linux419$ make -k CC=/usr/bin/iwyu

Makefile:595: include/config/auto.conf: No such file or directory

warning: argument unused during compilation: '-fsyntax-only'

<stdin>:1:1: error: expected identifier or '('

__GNUC__

^

<built-in>:9:18: note: expanded from here

#define __GNUC__ 4

                 ^



(<stdin> has correct #includes/fwd-decls)

warning: argument unused during compilation: '-fsyntax-only'

<stdin>:1:1: error: expected identifier or '('

__GNUC_MINOR__

^

<built-in>:7:24: note: expanded from here

#define __GNUC_MINOR__ 2

                       ^



(<stdin> has correct #includes/fwd-decls)
error: unable to handle compilation, expected exactly one compiler job in ''

  YACC    scripts/kconfig/zconf.tab.c

/bin/sh: 1: bison: not found
scripts/Makefile.lib:196: recipe for target 'scripts/kconfig/zconf.tab.c' failed

make[2]: *** [scripts/kconfig/zconf.tab.c] Error 127

  LEX     scripts/kconfig/zconf.lex.c

/bin/sh: 1: flex: not found

scripts/Makefile.lib:188: recipe for target 'scripts/kconfig/zconf.lex.c' failed

make[2]: *** [scripts/kconfig/zconf.lex.c] Error 127

make[2]: Target 'syncconfig' not remade because of errors.

Makefile:539: recipe for target 'syncconfig' failed

make[1]: *** [syncconfig] Error 2

Makefile:635: recipe for target 'include/config/auto.conf' failed

make: *** [include/config/auto.conf] Error 2

make: Failed to remake makefile 'include/config/auto.conf'.

error: unable to handle compilation, expected exactly one compiler job in ''

Compiler lacks asm-goto support.

arch/x86/Makefile:302: recipe for target 'checkbin' failed

make: *** [checkbin] Error 1

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

Error: kernelrelease not valid - run 'make prepare' to update it

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

error: unable to handle compilation, expected exactly one compiler job in ''

  CC      scripts/mod/empty.o

In file included from <built-in>:311:

In file included from <command line>:4:

././include/linux/kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found

#include <generated/autoconf.h>

         ^



(scripts/mod/empty.c has correct #includes/fwd-decls)

scripts/Makefile.build:305: recipe for target 'scripts/mod/empty.o' failed

make[2]: *** [scripts/mod/empty.o] Error 2

  CC      scripts/mod/devicetable-offsets.s

In file included from <built-in>:311:

In file included from <command line>:4:

././include/linux/kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found

#include <generated/autoconf.h>

         ^



scripts/mod/devicetable-offsets.c should add these lines:

#include "include/linux/stddef.h"   // for offsetof



scripts/mod/devicetable-offsets.c should remove these lines:



The full include-list for scripts/mod/devicetable-offsets.c:

#include <linux/kbuild.h>           // for DEFINE

#include <linux/mod_devicetable.h>  // for input_device_id, usb_device_id

#include "include/linux/stddef.h"   // for offsetof

---

scripts/Makefile.build:131: recipe for target 'scripts/mod/devicetable-offsets.s' failed

make[2]: *** [scripts/mod/devicetable-offsets.s] Error 3

make[2]: Target '__build' not remade because of errors.

scripts/Makefile.build:546: recipe for target 'scripts/mod' failed

make[1]: *** [scripts/mod] Error 2

make[1]: Target '__build' not remade because of errors.

Makefile:1067: recipe for target 'scripts' failed

make: *** [scripts] Error 2

make: Target '_all' not remade because of errors.

```
got any ideas of what i'm doing wrong?

**Comment by kimgr** [comment]
IWYU is based on the Clang compiler's parsing and semantic analysis engine, so if you can first get the kernel to build with Clang, it will be open for analysis by IWYU.

I know people use Clang to build the kernel, but I don't know how that works. Maybe you can google up details and learn more that way?

**Comment by kimgr** [comment]
I don't think there's much more we can do here. Please join the mailing list at https://groups.google.com/forum/#!forum/include-what-you-use if you want to throw around more ideas on how to use IWYU in your context.
