### ISSUE TITLE
iwyu fails to compile because clang removed some CastKinds

### ISSUE THREAD

**Issue by tschuett** [include-what-you-use/include-what-you-use#597]
Hi,

iwyu does not compile anymore since:
https://github.com/llvm-mirror/clang/commit/3aca0c6080221bacd74735ccb5e8efb0eb156997#diff-5e79a61628c5f95d3efe3050bba5f911

It adds and remove some CastKinds.

/llvm/tools/clang/tools/include-what-you-use/iwyu.cc:2056:12: error: ‘CK_ZeroToOCLEvent’ is not a member of ‘clang’
       case clang::CK_ZeroToOCLEvent: // OpenCL event_t is a built-in type.
            ^
/llvm/tools/clang/tools/include-what-you-use/iwyu.cc:2057:12: error: ‘CK_ZeroToOCLQueue’ is not a member of ‘clang’
       case clang::CK_ZeroToOCLQueue: // OpenCL queue_t is a built-in type.

**Comment by kimgr** [comment]
Now fixed, including the recently-added fixed-point casts.
