### ISSUE TITLE
iwyu_tool.py does not attend to clang flags

### ISSUE THREAD

**Issue by alacasta** [include-what-you-use/include-what-you-use#612]
# Enhancement proposal
It may be required in some cases to enable the possibility of using additional clang flags in combination with iwyu_tool. One example is when needing the following flag
```
-target i686-w64-mingw32
```
to be explicetly used by include-what-you-use.

# Background
include-what-you-use is usually called with the following arguments

```
include-what-you-use [-Xiwyu --iwyu_opt]... <clang opts> 
```

However, `iwyu_tool` limits its usage only to `-Xiwyu` assuming that calls like
```
ìwyu_tool.py -p . -- arg1
```
automatically translates the information into

```
-Xiwyu arg1
```
arguments to the `include-what-you-use` call. This is a design decission in favor of simplifying the calls of the tool:
```python
    # Force -Xiwyu prefix to iwyu_args so users don't have to provide prefix
    # explicitly.
    prefixes = ['-Xiwyu'] * len(iwyu_args)
    iwyu_args = list(sum(zip(prefixes, iwyu_args), ()))
```

# Possible modifications
The enhancement that i would like to be considered can be implemented respecting the current implementation.

By keeping `--` as an implicit separator of `-Xiwyu` flags and then include a `-clang` separator for clang specific flags, both can live at the same time. Pros include the non-breaking front-end specification enabling at the same time the possibility of postfixing the clang flags.

**Comment by kimgr** [comment]
Yes, I think this was the wrong decision on my part, to assume that trailing flags would always be IWYU flags. I think we should make a breaking change for next version where everything after `--` is passed verbatim to `include-what-you-use`, so IWYU flags need to be explictly specified with `-Xiwyu`.

**Comment by alacasta** [comment]
👍 IMO this would be the best option if not needed to keep backwards comptibility as suggested from my side.

Is it okay if I prepare something in that way?

**Comment by kimgr** [comment]
That would be great, thank you!
