### ISSUE TITLE
[iwyu_tool] Including Mocking library to tests

### ISSUE THREAD

**Issue by alacasta** [include-what-you-use/include-what-you-use#630]
# What?

It is not currently possible to use `mock` module in the unit tests as it is Travis CI configured at the moment.
the `unittest` module has many native functions that can be used in Python3 but they need to be accessed by mock module in python2 (the one used in the CI)

**Important**: This issue is blocking PR #629 

# Possible changes

I'd like to propose one of these changes

- [ ] To install the mock module in Travis CI
- [ ] To use python3 for the tests (changing from ` - python iwyu_tool_test.py` to ` - python3 iwyu_tool_test.py` at .travis.yml)
- [ ] To use kind of virtual environment (tox) with one of these configurations as well as for dev purposes

**Comment by kimgr** [comment]
I'd like to propose a fourth option:

[ ] Do not depend on any third-party Python libraries

We'll need to support Python 2 for the foreseeable future, as long as it's the default Python for any distro. Our approach so far has been to support both.

We are not interested in taking on third-party dependencies (or at least I'm not) beyond LLVM/Clang. Third-party deps are a liability as much as an asset, and versioning can be a nightmare. I prefer to keep IWYU free-standing in that regard.

The mocking in the tests looks fairly trivial to achieve with basic monkey patching.

**Comment by alacasta** [comment]
Thanks @kimgr 
I don't have the big picture of the project and of course, alternative approaches not requiring `mock` library are almost always reachable. 
From my side is okay the so-called fourth option 👍
