### ISSUE TITLE
IWYU removes a necessary include if there are a derived-to-base cast and a user-defined conversion in the same position

### ISSUE THREAD

**Issue by jbctaka** [include-what-you-use/include-what-you-use#650]
In this example, no changes should be suggested, but iwyu suggests removing include cast_and_user_defined_conversion-d2.h.

```
// cast_and_user_defined_conversion-d1.h
class Derived;
  
class X {
public:
  operator Derived*() const { return nullptr; }
} gX;


// cast_and_user_defined_conversion-d2.h
class Base { };
class Derived : public Base { };


// cast_and_user_defined_conversion.cc
#include "cast_and_user_defined_conversion-d1.h"
#include "cast_and_user_defined_conversion-d2.h"

Base* hello() {
  return static_cast< Base* >( gX );
}
```

In `VisitCastExpr(clang::CastExpr* expr)` function, iwyu checks if the cast expression is ptr-to-ptr cast. But iwyu uses `GetTypeOf(expr->getSubExprAsWritten())` as `from_type`, and this is not a pointer type in this case. So iwyu doesn't report the definition of Derived class is necessary.

Changing `const Type* const from_type = GetTypeOf(expr->getSubExprAsWritten());` to `const Type* const from_type = GetTypeOf(expr->getSubExpr());` will work in this case, but I don't know this change is correct.

**Comment by kimgr** [comment]
Thanks for the report! Have you tried changing to `getSubExpr` and it worked for your example? If so, you should be able to just run IWYU's tests -- that's how we know if things are "correct" or not :) I see `CastExpr` has a `getConversionFunction`; maybe we should use that to also report user-defined conversions invoked by a cast?

**Comment by jbctaka** [comment]
Thank you.
I tried changing to `getSubExpr` and it worked.
I'm trying to run tests now, but two tests fail before I make this change... (I build IWYU in macOS, so #484 may be related.) I will investigate this trouble.

I confirmed `CastExpr::getConversionFunction` returns a valid pointer at StaticCastExpr and ImplicitCast (DerivedToBase) in my example. So I agree we probably can use this function to report user-defined conversions use.

**Comment by kimgr** [comment]
I misunderstood the challenge here slightly.

I thought we didn't see the conversion function, and forgot to report the use of `X::operator Derived*()`, but as you describe, the problem is that the short-circuiting of non-ptr-to-ptr casts causes us to forget to report full use of `Base` (required for the `static_cast` between derived and base).

I've spent some time trying to find a way to phrase that in code, but still haven't come up with anything solid.

**Comment by kimgr** [comment]
I think I have this worked out now. You can try this branch if you want to test it with real code:
https://github.com/kimgr/include-what-you-use/commits/650-cast-conv

I'll add some proper tests based on your excellent repro before pushing a pull request.

**Comment by jbctaka** [comment]
Thank you!
I read your code. I think this code is clearer than before and will work with my real code. (I'm sorry I have not tested your code with my real code yet.)
