### ISSUE TITLE
command line option to match 'IWYU pragma: keep'

### ISSUE THREAD

**Issue by trixirt** [include-what-you-use/include-what-you-use#653]
In cases where it is impossible to edit a header ex/ stdio.h,  it would be useful to support the pragma keep as a command line option.  

So add the command line option
 --keep

Behaves like --also_needs in that it support glomming/heuristic file matching.
Will additional check likely in the pp handler InclusionDirective 
Reuses the existing kept_includes_ data handling.

i am starting work on this.

**Comment by kimgr** [comment]
Fixed by PR #654
