### ISSUE TITLE
glob-ing is not intuitive

### ISSUE THREAD

**Issue by trixirt** [include-what-you-use/include-what-you-use#660]

**Comment by trixirt** [comment]
To follow an issue raised in https://github.com/include-what-you-use/include-what-you-use/pull/654
glob-ing does not seem to work as expected when matching include paths.

Because this is likely os specific, a unit test (more_tests/iwyu_glob_test.cc) should be added.
Then tests added to cover expected values.
Then change iwyu glob logic to fix failures.

**Comment by kimgr** [comment]
Unfortunately we don't currently have a build target for the unit tests, so adding more tests won't help unless they're also built and executed.

I'm not sure how much effort we want to put into implementing a capable cross-platform glob -- when you say it doesn't work as expected, maybe you simply expect too much :)

**Comment by kimgr** [comment]
I just stumbled on a helper class in LLVM for glob matching: https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/Support/GlobPattern.h

This looks like it could come in handy, rather than rolling our own.

**Comment by kimgr** [comment]
This was fixed in https://github.com/include-what-you-use/include-what-you-use/commit/3538843036220c94325d2a97693262d9c93e6d28
