### ISSUE TITLE
error: unsupported option '--mapping_file=X' when invoking iwyu for header files

### ISSUE THREAD

**Issue by AndreasSchacherbauerWikitude** [include-what-you-use/include-what-you-use#664]
Hi, we generate a compile_commands.json file from our CMake project and then invoke the `iwyu_tool.py` script with the `--mapping_file` argument. While this works perfectly fine for .cpp files, we get the error `error: unsupported option '--mapping_file='` and the mappings defined in the mapping file (which work perfectly fine for .cpp files) are not considered.
Did we miss any important option or is iwyu not intended to work with compile_commands.json files that also include header files?

**Comment by kimgr** [comment]
Shouldn't make a difference. But if you're using a recent `iwyu_tool.py`, you need to prefix IWYU args with `-Xiwyu`, so something like `iwyu_tool.py -p . -- -Xiwyu --mapping_file=X`

**Comment by AndreasSchacherbauerWikitude** [comment]
thx @kimgr, that fixed it! Should have read the documentation more carefully. Guess I was to excited about the tool itself and it's capabilities that I overlooked that detail.

**Comment by insilications** [comment]
This specific usage of iwyu_tool should be documented: iwyu_tool.py -p . -- -Xiwyu --mapping_file=X
