### ISSUE TITLE
LLVM / Clang 8 was released

### ISSUE THREAD

**Issue by apaprocki** [include-what-you-use/include-what-you-use#668]
Can a new release be cut that is compatible with LLVM 8? Thanks

**Comment by kimgr** [comment]
I don't think the Debian packags for llvm-8 have been posted yet, so I can't safely take a branch that builds against them.

But I'll start up a local build from source and see if IWYU master is compatible with LLVM-8. I can't recall any breaking changes in the 8 timeframe, so hopefully it just works.

**Comment by ayoubserti** [comment]
Hi,
I 'brew install llvm8' and compile `include-what-you-use` against. It compile perfectly.

But it doesn't work, same errors as https://github.com/include-what-you-use/include-what-you-use/issues/484

**Comment by kimgr** [comment]
Oops, accidental close.

**Comment by jmccl** [comment]
If iwyu is installed on manjaro (and presumably arch) it breaks package update with this:

could not satisfy dependencies:
installing clang (8.0.0-3) breaks dependency 'clang<8.0' required by include-what-you-use

**Comment by kimgr** [comment]
Just pushed a release tag, I'll pick up the rest of the release activities in a while.

**Comment by kimgr** [comment]
Done, release is available both on GitHub and http://include-what-you-use.org.

**Comment by vmiklos** [comment]
Thanks. One remaining problem is that https://include-what-you-use.org/downloads/ links to https://include-what-you-use.org/downloads/include-what-you-use-0.12.src.tar.gz, but that is 403.

**Comment by kimgr** [comment]
@vmiklos Thanks for spotting this! I've changed the permissions now, we'll see when it's effective everywhere.
