### ISSUE TITLE
Segfault analyzing ledger-cli

### ISSUE THREAD

**Issue by tblyons** [include-what-you-use/include-what-you-use#670]
iwyu segfaults when trying to analyze src/filters.cc in https://github.com/ledger/ledger on master. I'm running clang_7.0 on x86_64 GNU/Linux 5.0.2.

Here is a copy of the -v7 log
[iwyu.zip](https://github.com/include-what-you-use/include-what-you-use/files/3000345/iwyu.zip)

**Comment by kimgr** [comment]
@tblyons Sorry I didn't pick this up earlier.

Do you also have information about the crash, i.e. a backtrace? The IWYU log doesn't give any details about that (but could provide some context for how we got there). Thanks!

**Comment by tblyons** [comment]
@kimgr no worries! I am still able to recreate the issue with `include-what-you-use 0.12 based on clang version 8.0.1 (tags/RELEASE_801/final)`

Here is what valgrind gave for the stack trace when the segfault occurred: https://gist.github.com/tblyons/5dc167b4a6408a8e0dee9bb3df67a54f

**Comment by kimgr** [comment]
Thank you, that looks like a bug we've seen before. I'll find it and link them up when I'm at a real keyboard.

**Comment by kimgr** [comment]
Duplicates #419.
