### ISSUE TITLE
silence warnings related to aliased types

### ISSUE THREAD

**Issue by akddv** [include-what-you-use/include-what-you-use#672]
Using include-what-you-use for clang 7, I have the following case:

```
// mytype.h
#include <string_view>
using MyType = std::string_view;
```

```
// main.cpp
#include "mytype.h"
int main()
{
  return MyType("hello") == MyType("friend");
}
```

IWYU will suggest to add the following includes:

> main.cpp should add these lines:
> #include \<string>       // for char_traits
> #include \<string_view>  // for operator==, basic_string_view
> 

The intent was to wrap the std::string_view type so adding those includes would not really make sense.

Note that replacing the main function with "`return MyType("hello").size()`" would not return any warning though, that is inline with my expectations.

While this seems to be related to some previous issues like maybe #105 and #111 , I could not find a workaround.

Is there a simple way to silence those kind of warnings?
Thanks for your help.

**Comment by kimgr** [comment]
I don't think so, no. Unless using a `typedef` instead of `using` nudges IWYU in the right direction, but I think we've seen before that it doesn't.

**Comment by akddv** [comment]
Thanks for your quick answer!

**Comment by kimgr** [comment]
Yes. We just haven't found a way to solve it yet. I don't remember exactly, but I don't think we've come around to trying very hard, either, so maybe it's easy to fix. :)
