### ISSUE TITLE
Suggesting extern template specializations

### ISSUE THREAD

**Issue by osiewicz** [include-what-you-use/include-what-you-use#685]
Hi,
I would like to ask whether it would be feasible to add some kind of template instantiation counter, which could then suggest potential candidates for explicit instantiation in single compilation unit & replacement with declaration in all others.
Example of what I mean:
```
// foo.cpp
#include "MyType.h"
void foo(){
    MyType<int> bar; // warning: instantiated in multiple TUs. Consider using extern template
    ....
}
```
could become
```
//MyType.cpp
#include "MyType.h"

template<>
class MyType<int>;
```
```
//MyType.h
... 
// previous content
extern template
class MyType<int>;
```
There could be some kind of diagnostic (perhaps "The template MyType<int> is instantiated in over X% translation units") that could point user to manually fix their code.
I don't think automatic fixer for that would be easy to write, because the preprocessor can be used within template definition, thus making analysis harder. I do however think that described diagnostic (which could be an opt-in) might help reduce the redundancy and compile times for users.
E: It is solely an idea that I would be happy to hack away - I am honestly not sure whether it is as easily doable as it sounds, though.

**Comment by kimgr** [comment]
I don't think this falls under IWYU's jurisdiction :)

Better to start on a dedicated clang tool to do this. You might have trouble with the "instantiated in multiple TUs" logic -- all clang tools run on a single TU at a time. So you would need to export the counter to some kind of intermediate file format and run a summary pass at the end.

But I don't see what it has to do with `#include` cleanup, so I think it's better suited somewhere else. Closing.
