### ISSUE TITLE
Is it necessary to set CXX=clang++ with cmake?

### ISSUE THREAD

**Issue by MamaShip** [include-what-you-use/include-what-you-use#689]
My project is built by cmake, and the compile tool is : arm32-linux-gnueabi-g++

When I try to use IWYU, I find that clang does not support some compile options/arguments:

`error: unknown argument: '-mno-sched-prolog'
error: unsupported option '-freg-struct-return' for target 'x86_64-unknown-linux-gnu'`

So I try to use my original compiler arm32-linux-gnueabi-g++ with cmake  parameter:

`-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;any;-Xiwyu;iwyu;-Xiwyu;args"`

It seems work. I can see some diagnostics from IWYU in my terminal.

Is that output reliable? Should I change compiler to clang (need huge efforts)?

**Comment by kimgr** [comment]
IWYU in general doesn't care about about target architecture, but some built-in preprocessor symbols may differ with the target. For example, I would guess `arm32-linux-gnueabi-g++` sets the `__arm__` symbol.

If you have conditional code and/or `#include` directives based on such a symbol, IWYU won't see it.

There's also some amount of machinery for inline assembly that will not work correctly unless IWYU has been built with support for the specific target (we initialize support for inline assembly for all targets, but "all targets" is configured at IWYU build-time).

But for the most part, it should work fine.

**Comment by kimgr** [comment]
Looks like this answered the question. Closing.
