### ISSUE TITLE
unnecessary dotdots

### ISSUE THREAD

**Issue by Akuli** [include-what-you-use/include-what-you-use#690]
Here is a minimal-ish example with 4 short files:

`bc.h`

```
#ifndef BC_H
#define BC_H
struct Bc {};
#endif
```

`interp.h`

```
#ifndef INTERP_H
#define INTERP_H
struct Interp {};
#endif
```

`main.c`

```
#include "bc.h"
#include "interp.h"
#include "objects/scope.h"
int main(int argc, char **argv)
{
	struct Interp interp;
	struct Bc bc;
}
```

`objects/scope.h`  (the only file in the `objects` subdirectory)

```
#ifndef OBJECTS_SCOPE_H
#define OBJECTS_SCOPE_H
#include "../interp.h"
#endif
```

I get this:

```
$ iwyu --version
include-what-you-use 0.7 based on clang version 3.9.1-1 (tags/RELEASE_391/rc2)
$ iwyu main.c

main.c should add these lines:
#include "objects/../interp.h"  // for Interp

main.c should remove these lines:
- #include "interp.h"  // lines 2-2
- #include "objects/scope.h"  // lines 3-3

The full include-list for main.c:
#include "bc.h"                 // for Bc
#include "objects/../interp.h"  // for Interp
---
```

I would expect IWYU to suggest `"interp.h"` instead of `"objects/../interp.h"`, or at least not complain about using `"interp.h"` instead of `"objects/../interp.h"`.

**Comment by Akuli** [comment]
This also happens with latest iwyu from `https://include-what-you-use.org/downloads/`

```
$ ~/iwyu/build/bin/include-what-you-use main.c 

main.c should add these lines:
#include "objects/../interp.h"  // for Interp

main.c should remove these lines:
- #include "interp.h"  // lines 2-2
- #include "objects/scope.h"  // lines 3-3

The full include-list for main.c:
#include "bc.h"                 // for Bc
#include "objects/../interp.h"  // for Interp
---
$ ~/iwyu/build/bin/include-what-you-use --version
include-what-you-use 0.12 based on clang version 8.0.1-svn360950-1~exp1~20190517005525.68 (branches/release_80)
```

**Comment by Akuli** [comment]
This shitty code (diff for latest master) fixes the problem. I would create a pull request if I wasn't so ashamed of writing C code into a C++ project. (I'm sorry, I have never done any string operations in C++.)

```diff
diff --git a/iwyu_path_util.cc b/iwyu_path_util.cc
index 5d37367..b88b300 100644
--- a/iwyu_path_util.cc
+++ b/iwyu_path_util.cc
@@ -134,7 +134,26 @@ string NormalizeFilePath(const string& path) {
   std::replace(normalized.begin(), normalized.end(), '\\', '/');
 #endif
 
-  return normalized.str();
+  const string str = normalized.str();
+  char *res = new char[str.length()+1];
+  strcpy(res, str.c_str());
+
+  // replace "a/../b" with "b", and "a/b/../c" with "a/c"
+  // note: this may break with funny symlinkings
+  // TODO: replace this c shit with c++ string functions
+  char *dotdot;
+  while((dotdot = strstr(res, "/../"))) {
+    char *p = dotdot;
+    while(p > res && *--p != '/')
+      ;
+    if(p != res)
+      p++;
+    memmove(p, dotdot+4, res + strlen(res) - dotdot - 4 + 1);
+  }
+
+  std::string stringres (res);
+  delete res;
+  return stringres;
 }
 
 string NormalizeDirPath(const string& path) {
```

**Comment by kimgr** [comment]
Thanks for the patch! I'm not sure why we haven't already gone that way. Do all the tests pass with this change?

**Comment by kimgr** [comment]
Thinking about this some more, I suspect this is papering over another bug, and maybe that's why we haven't done it. But it seems to me a "normalized" path should not have redundant dot-dots.

**Comment by Akuli** [comment]
I'm not really interested in trying to run the tests myself. Even getting IWYU to compile took me a couple hours.

**Comment by Akuli** [comment]
Is #681 related? It seems to be doing some stuff to relative includes, but I don't understand the code

**Comment by kimgr** [comment]
For what it's worth, tests all pass with the patch applied. I'll see if I can phrase it in terms of `llvm::Path` (which I believe has this functionality). I think it's a strict improvement to make canonical paths more canonical.

**Comment by Akuli** [comment]
Like I commented in the patch, this may not work with symlinks

```
akuli@Akuli-Desktop:~$ ln -s /usr a
akuli@Akuli-Desktop:~$ file a
a: symbolic link to /usr
akuli@Akuli-Desktop:~$ file lib
lib: cannot open `lib' (No such file or directory)
akuli@Akuli-Desktop:~$ file a/../lib
a/../lib: directory
akuli@Akuli-Desktop:~$ 
```

Here `a` points to `/usr`, so `a/..` points to `/` and `a/../lib` is then `/lib`.

I don't think anyone will actually notice this in IWYU though

**Comment by kimgr** [comment]
See PR #696 for a tentative fix. It's a shame about the symlinks, but we can always try this as a first approximation, and see what we can figure out if it causes problems in practice.
