### ISSUE TITLE
compiling instructions don't say that nothing works if you have llvm-4.0 installed

### ISSUE THREAD

**Issue by Akuli** [include-what-you-use/include-what-you-use#691]
I tried to compile from the latest master with cmake, and I got this:

```
CMake Error at CMakeLists.txt:85 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "include-what-you-use".  All uses of target_link_libraries with
  a target must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * /usr/lib/llvm-4.0/cmake/LLVM-Config.cmake:74 (target_link_libraries)
   * /usr/lib/llvm-4.0/cmake/AddLLVM.cmake:725 (target_link_libraries)



-- Found Git: /usr/bin/git (found version "2.11.0") 
-- Configuring incomplete, errors occurred!
See also "/home/akuli/sourcestuff/iwyubuild2/CMakeFiles/CMakeOutput.log".
```

After spending a couple hours on reading `target_link_libraries` docs and trying to modify `CMakeLists.txt`, I ran `sudo apt remove llvm-4.0`, and then the build worked. The package to use was `llvm-4.0`, because `/usr/bin/llvm-config` was a symlink to `/usr/bin/llvm-config-4.0`, and it got symlinked to `/usr/bin/llvm-config-8` when I removed `llvm-4.0`.

Please mention in the README that llvm versions other than the one needed for IWYU must not be installed when running `cmake`, but they may be installed again after `cmake`ing.

**Comment by Akuli** [comment]
I don't know what's going on. I have gotten my system to a state where the IYWU build is using `llvm-4.0` (bad), but my `llvm-config` is a symlink to `llvm-config-8`. I think it's easiest to `sudo apt remove llvm-<version>` before building IWYU.

**Comment by kimgr** [comment]
Did you use `-DCMAKE_PREFIX_PATH` in your CMake invocation, to select which LLVM installation to use?

**Comment by Akuli** [comment]
That makes it work. I think I copy/pasted it from the README, and it didn't work because I should have noticed `7` in the command and replaced it with `8`. Maybe mention that it must be replaced?

**Comment by Akuli** [comment]
I think it's also very confusing that if I don't have LLVM 7 installed and I say `-DCMAKE_PREFIX_PATH=/usr/lib/llvm-7`, I get an error message that says something about LLVM 4.0. The invalid `-DCMAKE_PREFIX_PATH` seems to get ignored without a warning (should be an error that stops cmake imo), and then for some reason it defaults to the *older* LLVM version that is installed on the system instead of the newer one.

**Comment by kimgr** [comment]
That `CMAKE_PREFIX_PATH` behavior seems to be how CMake works.

If you have more specific suggestions for improvements to the README I'd be happy to take them.

**Comment by kimgr** [comment]
See https://github.com/include-what-you-use/include-what-you-use/pull/693, I tried to provide more information in the How to build section.

**Comment by Akuli** [comment]
nice :D
