### ISSUE TITLE
Do no include "detail" headers

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/include-what-you-use#70]
Originally reported on Google Code with ID 70
```
Boost often separates out implementation details into a "detail" folder, e.g. <boost/thread/detail/thread.hpp>.
It would be nice if iwyu did not suggest these detail headers.

```

Reported by `leszek.swirski` on 2012-06-18 23:47:53

**Comment by delaitre** [comment]
Just wondering if it would be a good idea to commit those mapping files so that anybody could easily propose improvements. That would hopefully allow to have a fine tuned mapping in few months.

**Comment by vsapsai** [comment]
Thank you, @delaitre. That was a great idea to commit those mapping files.

Closing the issue as it seems to be resolved. For other Boost mapping fixes and enhancements please open separate issues/pull requests.
