### ISSUE TITLE
Need a pragma for 'forwarding header'

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#709]
currently if you have a forwarding header (a bit like iosfwd but a user one), IWYU says you don't need it and suggests you use a forward declaration

which is what a forwarding header is for

But the available pragmas only work in the file including the header

**Comment by kimgr** [comment]
I think this is `pragma: export`, but it doesn't work for forward-declarations, see #608. I think we can close this as a duplicate.

**Comment by ThosRTanner** [comment]
Agreed.

Closing - duplicate of #608
