### ISSUE TITLE
std::hash with libc++ does not handle inline namespaces correctly

### ISSUE THREAD

**Issue by chri7325** [include-what-you-use/include-what-you-use#713]
Using IWYU on a project that has stdlib=libc++ will try to incorrectly forward declare std types using libc++'s inline namespace. Spun off from https://github.com/include-what-you-use/include-what-you-use/issues/141.

When IWYU determines that a std type, for example hash, can be forward declared, it does not take into account the inline namespace or allow you to map it to a header.
```
test.h should add these lines:
#include <cstddef>     // for size_t
#include <cstdint>     // for uint8_t, uint32_t
#include <functional>  // for hash
namespace std { namespace __1 { template <class _Tp> struct __attribute__((type_visibility("default"))) hash; } }
```

This will then add the forward declare to the header

```
namespace std
{
namespace __1
{
template <class _Tp>
struct __attribute__((type_visibility("default"))) hash;
} // namespace __1
} // namespace std
```

This will lead to a compiler error
```
error: inline namespace reopened as a non-inline namespace [-Werror]
namespace __1
```

**Comment by kimgr** [comment]
@chri7325 I guess the inline namespace should be left out of the forward decl? Can you post an example of what IWYU generate for this situation?

**Comment by chri7325** [comment]
@kimgr I'm guessing hash shouldn't be tried to be forward declared in the first place right? I would think it should just `#include <hash>` when it finds it from the std. As for what IWYU generates, I've put the analysis output and what it actually applies to a header which is using hash. I'll see if I can come up with a simple repro since I cannot add the actual IP that I'm seeing with it.

**Comment by kimgr** [comment]
I think the fix is just:
```diff
diff --git a/iwyu_output.cc b/iwyu_output.cc
index ec936c5..af98046 100644
--- a/iwyu_output.cc
+++ b/iwyu_output.cc
@@ -386,6 +386,9 @@ string PrintForwardDeclare(const NamedDecl* decl,
     if (const RecordDecl* rec = DynCastFrom(ctx)) {
       fwd_decl = std::string(rec->getName()) + "::" + fwd_decl;
     } else if (const NamespaceDecl* ns = DynCastFrom(ctx)) {
+      if (ns->isInline())
+        continue;
+
       bool first = !seen_namespace;
       if (!seen_namespace) {
         seen_namespace = true;
```

But I'd like to see a contained repro case (ideally without reliance on libc++, but let's not get ahead of ourselves) to make sure this does the right thing. It passes all the current tests, at least.

**Comment by kimgr** [comment]
Here's a contained test case to demonstrate this:
```
// --- inline_ns.h
#ifndef INCLUDED_INLINE_NS
#define INCLUDED_INLINE_NS

namespace xyz {
inline namespace _1 {
struct Foo {
	int value;
};
}  // namespace _1
}  // namespace xyz

#endif // INCLUDED_INLINE_NS

// --- main.h
#include "inline_ns.h"

void f(xyz::Foo& foo);

// --- main.cc
#include "main.h"
#include <cstdio>
#include "inline_ns.h"

void f(xyz::Foo& foo) {
  printf("Hello %d", foo.value);
}
```
IWYU says:
```
$ include-what-you-use main.cc 

main.h should add these lines:
namespace xyz { namespace _1 { struct Foo; } }

main.h should remove these lines:
- #include "inline_ns.h"  // lines 1-1

The full include-list for main.h:
namespace xyz { namespace _1 { struct Foo; } }
---

(main.cc has correct #includes/fwd-decls)
```
The problem appears to be that the inline namespace loses its `inline` qualifier somewhere along the way, so there are two ways to solve this;
1) Print `inline namespace` for inline namespaces for forward-decls from IWYU
2) Disallow forward-declares involving inline namespaces

I started reading here: https://stackoverflow.com/questions/35737741/, and it seems to me forward-declaring symbols including these namespaces breaks their intent, i.e. to encapsulate details of the full symbol name.

If we generate a `namespace xyz { inline namespace _1 { struct Foo; } }`, your code is going to be thoroughly confused when the XYZ library introduces a new ABI versioning namespace `inline namespace _2`.

On the other hand, sometimes you want a forward-declare, even if it's not strictly allowed (such as with `std` symbols).

I'm not sure how to proceed here, but I'm tempted to institute a rule that says "don't suggest forward declares if the symbol's qualified name has an inline namespace".

**Comment by chri7325** [comment]
@kimgr sorry, I missed your last potential fix. I'll test it out to see if it resolves the hash issue. I couldn't get things to repro easily with hash using the examples on cppreference but it looks like you have a better test case for this. I'm curious as to why this only showed up for me with hash but none of the other std container types.

> I'm not sure how to proceed here, but I'm tempted to institute a rule that says "don't suggest forward declares if the symbol's qualified name has an inline namespace".
I think this would be a fair choice to make. I think IWYU does a good job of getting the right forward declares right but there are some situations where you have to massage it a bit to be deterministic. The complexity that inline namespaces provide might mean a lot more of `// IWYU pragmas` for a potentially small benefit.

**Comment by chri7325** [comment]
Looks like the fix has other unexpected consequences. I'm no longer getting the internal namespace in the analysis
```
test.h should add these lines:
#include <stdint.h>    // for uint8_t, uint32_t
#include <cstddef>     // for size_t
#include <functional>  // for hash
namespace std { template <class _Tp> struct __attribute__((type_visibility("default"))) hash; }
```
However, I now get compiler errors about ambiguous references to hash
```
test.h:88:8: error: reference to 'hash' is ambiguous
struct hash<Test>
       ^
/usr/local/rtc/llvm/9.0.0/bin/../include/c++/v1/typeindex:89:50: note: candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
test.h:22:52: note: candidate found by name lookup is 'std::hash'
struct __attribute__((type_visibility("default"))) hash;
```

**Comment by kimgr** [comment]
Oh yeah, the proposed fix doesn't work :)

I thought inline namespaces could be omitted both in type declarations (`std::hash<int>` vs `std::__1::hash<int>`) and in nested namespace forward declarations, but apparently not.

I don't think we can do much better than promoting fwd decl uses of symbols in an inline namespace to full uses.

**Comment by kimgr** [comment]
@chri7325 There's a potential fix up at https://github.com/include-what-you-use/include-what-you-use/pull/734. If you can, please give it a shot and see if it works in your context.

**Comment by chri7325** [comment]
@kimgr I tested out the fix you supplied and success! I'm no longer getting hash forward declares and my analysis now correctly supplies the right information
```
test.h should add these lines:
#include <stdint.h>    // for uint8_t, uint32_t
#include <cstddef>     // for size_t
#include <functional>  // for hash

test.h should remove these lines:

The full include-list for test.h:
#include <stdint.h>    // for uint8_t, uint32_t
#include <cstddef>     // for size_t
#include <functional>  // for hash
```

**Comment by kimgr** [comment]
@chri7325 \o/ I had an idea for better logging, so I'll put that in as well before I merge. Thanks!

**Comment by kimgr** [comment]
Merged to master, closing.
