### ISSUE TITLE
Tags for 0.12 and clang_8.0 branch are missing

### ISSUE THREAD

**Issue by proski** [include-what-you-use/include-what-you-use#715]
There is no tag for the 0.12 release.
```
$ git tag
0.11
clang_3.0
clang_3.2
clang_3.3
clang_3.4
clang_3.5
clang_3.6
clang_3.7
clang_3.8
clang_3.9
clang_4.0
clang_4.0-r2
clang_5.0
clang_6.0
clang_7.0
clang_8.0
```

The release page points to commit fe5275aa7b6a1372e96e8ff416c38d1790928893 that has tag `clang_8.0`

I believe there should be tags for all releases. Suppose that the support for Clang 8.0 is improved after the 0.12 release, and version 0.12.1 is released. They would need separate tags. The `clang_8.0` tag would be ambiguous.

Also, there is no `clang_8.0` branch. The user documentation instructs me to clone the repository and checkout the branch for the Clang version I'm using, presumably because it might have improvements over the last release. For Clang 8.0, there is no such branch.

```
$ git branch -r
  origin/HEAD -> origin/master
  origin/clang_3.2
  origin/clang_3.4
  origin/clang_3.5
  origin/clang_3.6
  origin/clang_3.7
  origin/clang_3.8
  origin/clang_3.9
  origin/clang_4.0
  origin/clang_5.0
  origin/clang_6.0
  origin/clang_7.0
  origin/master
```

Please fix it. I want to be sure that if there is any major issue that needs to be backported, the repository is setup to allow it.

**Comment by kimgr** [comment]
Thanks, yes. I haven't had much time for IWYU lately, so releases have lagged behind. I'll try to find the right commit to branch from.

**Comment by kimgr** [comment]
Done; I just pushed:

* A `clang_8.0` branch pointing to the `clang_8.0` tag
* An annotated `0.12` tag pointing to the `clang_8.0` tag

Thanks for noticing, this must have slipped in the release process.
