### ISSUE TITLE
LLVM / Clang 9 was released

### ISSUE THREAD

**Issue by apaprocki** [include-what-you-use/include-what-you-use#716]
http://releases.llvm.org/download.html#9.0.0

**Comment by kimgr** [comment]
Thanks for opening this, for tracking. There's several almost-finished PRs that I wanted to get into IWYU for LLVM-8, but that train has long passed, so maybe it's better to just package up 8 and 9 and move on.

**Comment by kimgr** [comment]
Here's the plan:

[x] Branch `clang_9.0` created
[x] Reverted Clang compat fixes on master that weren't necessary for Clang 9.0
[x] Found and fixed bug on FreeBSD, backported to `clang_9.0` branch
[x] Updated travis config to use LLVM/Clang 9 packages
[x] Tag `0.13` created
[ ] Update include-what-you-use.org with release notes
[ ] Update include-what-you-use.org with source package

Nearly there! I hope to get the rest done today, but I can't promise anything.

**Comment by kimgr** [comment]
IWYU 0.13 (aka Clang 9) is now live on https://include-what-you-use.org! :tada: :fireworks:
