### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [include-what-you-use/include-what-you-use#717]
[The website](https://include-what-you-use.org/) doesn't support IPv6.

Since the site seems to use CloudFront, fixing this should be as easy as [enabling IPv6 on the CloudFront distribution](https://aws.amazon.com/blogs/aws/ipv6-support-update-cloudfront-waf-and-s3-transfer-acceleration/) and [creating an AAAA ALIAS record pointing to it](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-cloudfront-distribution.html#routing-to-cloudfront-distribution-config).

**Comment by kimgr** [comment]
I'll look into it, thanks!

**Comment by kimgr** [comment]
IPv6 was already enabled, and the AAAA record should be set up now. Could you try it again and report back? Thanks.

**Comment by tambry** [comment]
Working now, thanks!
