### ISSUE TITLE
.moc includes should not be removed

### ISSUE THREAD

**Issue by reporter123** [include-what-you-use/include-what-you-use#721]
When using Qt any file containing a class derived from QObject must contain a line like this:
 #include "foo.moc"'
iwyu attempts to flag these for removal if it thinks they aren't used. This should not be done. Qt's automoc process already gives warnings for this as needed. Neither iwyu nor clang itself has the information needed to make this judgement at compile time. Incorrectly removing these lines results in cryptic link time errors about missing qt internal symbols. These files are auto generated by qt as needed and contain critical glue code for handling singles/slots.

**Comment by kimgr** [comment]
@reporter123 Please give the patch in PR #736 a shot and let me know if that works in a real Qt context.

**Comment by kimgr** [comment]
Merged to master.
