### ISSUE TITLE
Longer 'why' comments 

### ISSUE THREAD

**Issue by fperies** [include-what-you-use/include-what-you-use#724]
Hello,

Would it be possible to get longer 'why' comments ?:
Often, the string comment is not long enough:
#include \<new\>                   // for operato...

Thanks!

**Comment by fperies** [comment]
I've just noticed the max_line_length option. My bad !

**Comment by fperies** [comment]
Well, after a quick try with the following option from my CMakelists.txt:
set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE "/ebs/frperies/include-what-you-use/build/bin/include-what-you-use;-Xiwyu;any;-Xiwyu;**max_line_length=500**;-Xiwyu;iwyu;-Xiwyu;args")

I'm still getting short 'why' comments outputs. I'm wondering if this form is supported. Any clue ?

**Comment by kimgr** [comment]
Try `ebs/frperies/include-what-you-use/build/bin/include-what-you-use;-Xiwyu;--max_line_length=500"`

**Comment by fperies** [comment]
It works well ! Thank you for the trick !
