### ISSUE TITLE
iwyu confuses Vector with std::vector

### ISSUE THREAD

**Issue by shadeware** [include-what-you-use/include-what-you-use#725]
Vector.hpp:
```cpp
#include <vector>

namespace Ns
{
	template <class T>
	using Vector = std::vector<T>;
}
```

main.cpp:
```cpp
#include "Vector.hpp"

namespace Ns
{
	void f()
	{
		Vector<int> v = {1, 2, 3};
	}
}
```

Output:
```
$ include-what-you-use main.cpp 

main.cpp should add these lines:
#include <vector>  // for vector

main.cpp should remove these lines:
- #include "Vector.hpp"  // lines 1-1

The full include-list for main.cpp:
#include <vector>  // for vector
---
```

Adding `symbol Vector/Ns::Vector` to .imp did not help. 

iwyu version (clang is from apt.llvm.org):
```
$ include-what-you-use --version
include-what-you-use 0.12 (git:fe5275a) based on clang version 8.0.1-svn369350-1~exp1~20190820121219.79 (branches/release_80)
```

Unfortunately I was not able to build iwyu from master because of this error:
```
CMake Error at /usr/lib/llvm-10/lib/cmake/llvm/LLVMExports.cmake:1332 (message):
  The imported target "lit-cpuid" references the file

     "/usr/lib/llvm-10/bin/lit-cpuid"

  but this file does not exist.
```
(I have libclang-10-dev llvm-10-dev clang-10 installed from apt.llvm.org)

Is there workaround for clang_8.0 version? For example, can I put some pragmas in Vector.hpp?

edit: `--no_default_mappings` did not help either. Even renaming the class to `Vectorr` and file to TheVector.hpp did not help.

**Comment by kimgr** [comment]
This looks like the same problem as https://github.com/include-what-you-use/include-what-you-use/issues/460, right?

As for building, see our travis config at: https://github.com/include-what-you-use/include-what-you-use/blob/master/.travis.yml. For `lit-cpuid` I think you need to install `lldb` as well as the llvm packages, and then you need to create a missing symlink for the `clang` package to work. These are both bugs in the Clang LLVM packaging, we've just found funky workarounds.

**Comment by kimgr** [comment]
Actually, I see now that this uses an alias template, so it's probably closer to #703. Closing as duplicate.
