### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by wesleyw72** [include-what-you-use/include-what-you-use#751]
Are there any examples of using this with Bazel/Blaze? I assume that’s how it’s used within Google, it would be amazing if the BUILD files etc were open sourced.

**Comment by kimgr** [comment]
@wesleyw72 IWYU originated at Google, but none of the current maintainers are Googlers, so I'm not sure if it's used at all.

I don't know anything practical about Bazel, so I can't offer any advice there, but the usual approach should work -- replace the compiler with `include-what-you-use` and observe the results.

**Comment by kimgr** [comment]
There doesn't seem to be much we need to do here. I'll close this bug.
Feel free to send a patch with instructions for integrating with Bazel if you have them.

**Comment by illera88** [comment]
@wesleyw72 did you find a way to use IWYU with Bazel? I'm looking into it too

**Comment by storypku** [comment]
Hi all, I have recently completed a rough IWYU+Bazel integration implementation using the `aspect` rule of Bazel, inspired by the (Bazel-Clang-Tidy)[https://github.com/erenon/bazel_clang_tidy) project. Hope I could open source it in the next few months.

**Comment by storypku** [comment]
> pleted a rough IWYU+Bazel integration implementation using the `aspect` rule of Baz

Here it comes. https://github.com/storypku/bazel_iwyu . Tested on Ubuntu 18.04.6. Several improvement will be done in the next few days to make it more user-friendly. Suggestions/ideas/PRs are welcome.

**Comment by kimgr** [comment]
@storypku Very cool, thank you!
