### ISSUE TITLE
no such file or directory: 'g++' with CMake, ccache and g++

### ISSUE THREAD

**Issue by ilya-rusyanov** [include-what-you-use/include-what-you-use#758]
steps to reproduce:

`export CXX='ccache g++' && cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON path && ninja && iwyu_tool -p . ../file1.cpp ../file2.cpp`

gives

> error: no such file or directory: 'g++'

on each source file.

If building without ccache, everything goes fine.

cmake 3.13.4
ninja 1.8.2
include-what-you-use 0.11 based on clang version 7.0.1-3

**Comment by kimgr** [comment]
Maybe we need to resort to something like https://reviews.llvm.org/D64297.

**Comment by nico** [comment]
Using ccache via CXX tends to confuse cmake. Instead, pass these to cmake: `-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache`. Then things will likely work better.

**Comment by ilya-rusyanov** [comment]
> Using ccache via CXX tends to confuse cmake. Instead, pass these to cmake: `-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache`. Then things will likely work better.

This looks like the right way and I've been doing it wrong all my life. Thanks. Works like a charm.
