### ISSUE TITLE
unknown option -Wlogical-op

### ISSUE THREAD

**Issue by ilya-rusyanov** [include-what-you-use/include-what-you-use#760]
When running CMake v3.13.4 with Ninja v1.8.2 and g++8.3.0, manually specifying CXXFLAGS as '-Wlogical-op' gives

`warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Wunknown-warning-option]`

include-what-you-use 0.11 based on clang version 7.0.1-3 shipped with Debian 10.3

**Comment by i-ky** [comment]
`-Wlogical-op` is not among [diagnostics supported by clang](https://clang.llvm.org/docs/DiagnosticsReference.html).

**Comment by ilya-rusyanov** [comment]
> `-Wlogical-op` is not among [diagnostics supported by clang](https://clang.llvm.org/docs/DiagnosticsReference.html).

So what would be the the correct way to solve the issue(effectively ignoring the -Woption)?

Since iwyu_tool(frankly speaking that piece of software is the main aim for the issue) is somewhat independent of that particular GCC warning, I believe it could be absolutely safe to ignore the flag and even not to show the warning message.

Please correct me if I'm wrong.

**Comment by i-ky** [comment]
It's difficult to give recommendations without knowing your goals. I will assume that your project invokes IWYU during every build and gives developer freedom to pass custom compilation flags. In this case I'd suggest passing [`-Wno-unknown-warning-option`](https://clang.llvm.org/docs/DiagnosticsReference.html#wunknown-warning-option) into [`CXX_INCLUDE_WHAT_YOU_USE`](https://cmake.org/cmake/help/v3.13/prop_tgt/LANG_INCLUDE_WHAT_YOU_USE.html). This should silence warnings like the above and should not affect the effectiveness of IWYU.

But there is no single answer. I'm working on a project where developers don't have the freedom to customize compiler flags and our makefile automatically adds different flags depending on compiler identification (GCC, clang, ...). And we don't invoke IWYU on every build, we have a special "mode" for IWYU with flags based on clang's flags. This also works fine.

**Comment by ilya-rusyanov** [comment]
> It's difficult to give recommendations without knowing your goals. I will assume that your project invokes IWYU during every build and gives developer freedom to pass custom compilation flags. In this case I'd suggest passing [`-Wno-unknown-warning-option`](https://clang.llvm.org/docs/DiagnosticsReference.html#wunknown-warning-option) into [`CXX_INCLUDE_WHAT_YOU_USE`](https://cmake.org/cmake/help/v3.13/prop_tgt/LANG_INCLUDE_WHAT_YOU_USE.html). This should silence warnings like the above and should not affect the effectiveness of IWYU.
> 
> But there is no single answer. I'm working on a project where developers don't have the freedom to customize compiler flags and our makefile automatically adds different flags depending on compiler identification (GCC, clang, ...). And we don't invoke IWYU on every build, we have a special "mode" for IWYU with flags based on clang's flags. This also works fine.

Was expecting something like that(especially the Environment variable), but man iwyu(1) gave no sign of such behavior from software, so I assumed there's no support for that.

Thank you, you saved my time again.

**Comment by i-ky** [comment]
As far as I know, man page was added not that long ago (#732). I think your feedback will be welcomed.
