### ISSUE TITLE
iwyu disagrees that std::optional needs a full definition

### ISSUE THREAD

**Issue by steerlink** [include-what-you-use/include-what-you-use#780]
This is a simplified example of an issue I ran into this week. What is going on?

#### Steps to Reproduce

1. Create the following files

```c++
// date.h
class Date {
public:
  int hour = 0;
  int minute = 0;
  int second = 0;
};
```

```c++
// functions.h
#include <optional>

class Date;

std::optional<Date> get_default_date();
```
```c++
// functions.cpp
#include "functions.h"
#include "date.h"

std::optional<Date> get_default_date() {
  return std::optional<Date>(Date());
}
```
```c++
// thing.h
#include "date.h"
#include <optional>

std::optional<Date> get_date();
```
```c++
// thing.cpp
#include "thing.h"
#include "functions.h"

std::optional<Date> get_date() {
  return get_default_date();
}
```
2. Compile
```
clang++ -std=c++17 -c thing.cpp -c functions.cpp
```
3. IWYU
```
include-what-you-use -std=c++17 thing.cpp

...
thing.h should remove these lines:
- #include "date.h"  // lines 1-1
...
```
#### Analysis

Clang and GCC fail to compile if `thing.h` doesn't include `date.h`. If `date.h` is removed as suggested by IWYU the compiler yields

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:3697:69: error: 
      incomplete type 'Date' used in type trait expression
    : public integral_constant<bool, is_destructible<_Tp>::value && __has_trivial_destructor(_Tp)> {};
                                                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:539:5: note: 
      in instantiation of template class 'std::__1::is_trivially_destructible<Date>' requested here
    is_trivially_destructible<_Tp>::value &&
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/optional:586:15: note: 
      in instantiation of default argument for '__optional_move_assign_base<Date>' required here
    : private __optional_move_assign_base<_Tp>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thing.cpp:5:10: note: in instantiation of template class 'std::__1::optional<Date>' requested here
  return get_default_date();
```

**Comment by bence42** [comment]
I've had the same issue with optional. The type passed to optional may not be incomplete as it checks for e.g. is_constructible. Changing std::optional in the example to std::vector and running verbose shows that types used in vector will be marked full-info use as default.

Adding std::optional to iwyu_cache.cc solves this issues.

**Comment by kimgr** [comment]
@bence42 Wow, I didn't know that explicit whitelist was there. Could you try with the patch series from https://github.com/include-what-you-use/include-what-you-use/pull/775 (and without the `iwyu_cache.cc` patch) and see if it makes a difference? I'm curious if PR #775 obviates the need for those hardcoded names.

**Comment by bence42** [comment]
Thanks for the suggestion! PR #775 indeed fixes this ticket. 
One interesting thing I've found with #775: I would've assumed that adding STL types to `iwyu_cache.cc` improves performance as there's no need to traverse 4-5 layers of templates in the STL implementation to confirm that the template parameter is full use. Interestingly the time taken for IWYU to analyze its own source is identical with and without the hardcoded cache.
Any thoughts on that?

Output of include-what-you-use -std=c++17 thing.cpp with #775:
thing.hpp should add these lines:
class Date;

thing.hpp should remove these lines:
- #include "date.hpp"  // lines 2-2

The full include-list for thing.hpp:
#include <optional>  // for optional
class Date;
---

thing.cpp should add these lines:
#include "date.hpp"       // for Date

thing.cpp should remove these lines:

The full include-list for thing.cpp:
#include "thing.hpp"
#include "date.hpp"       // for Date
#include "functions.hpp"  // for get_default_date
---

**Comment by kimgr** [comment]
@bence42 Hmm, no, I don't have any immediate explanations for that. But it's hopeful, getting rid of caching is always nice. Are you using precompiled headers, by any chance?

**Comment by steerlink** [comment]
Thanks for addressing this issue @kimgr @jbytheway

**Comment by kimgr** [comment]
@bence42 I'm poking at some other template- and cache-related stuff in IWYU, and stumbled on this comment in `iwyu_cache.h`:
```
// For each of these, the answer is always the same for the given
// Decl (function call or class instantiation) with the same template
// args.  So we store this info in a cache, since it's very expensive
// to compute.
```

That "very expensive to compute" got me thinking -- I wonder if we've somehow inadvertently broken the cache, so it's _never_ effective. That would explain why your removing it made no difference. I'm guessing you're not thinking about this day-to-day, so I'm mostly leaving this as a reminder for myself if I ever circle back to it :smiley:
