### ISSUE TITLE
Using 'ccache' in compile_commands.json results in "error: no such file or directory: 'c++'"

### ISSUE THREAD

**Issue by Flowdalic** [include-what-you-use/include-what-you-use#789]
If ccache is used (as it is per default by meson if ccache is available), the compile_commands.json `command` will look like

```
{
    "directory": "/home/user/code/myproject/build-release",
    "command": "ccache cc -Itest/9f86d08@@simple_test@exe -Itest -I../test -I../include -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=gnu11 -O3 -pthread -UNDEBUG -MD -MQ 'test/9f86d08@@simple_test@exe/simple_test.c.o' -MF 'test/9f86d08@@simple_test@exe/simple_test.c.o.d' -o 'test/9f86d08@@simple_test@exe/simple_test.c.o' -c ../test/simple_test.c",
    "file": "../test/simple_test.c"
},
```

Since `ccache` acts as wrapper around the compiler invocation, this results in
 "error: no such file or directory: 'cc''" errors in the iwyu output.

**Comment by kimgr** [comment]
See also #758. 

I wonder if the bug is actually with Meson -- feels like `ccache` should not be part of the compilation database...?

**Comment by Flowdalic** [comment]
> I wonder if the bug is actually with Meson -- feels like `ccache` should not be part of the compilation database...?

I am not sure about that. Even if I would share the feeling that wrappers, like `ccache`, should not be part of the compilation database, what matters is how it is specified. And, as far as I can tell, meson's behavior if perfectly valid, [as per "this must be a valid command to rerun the exact compilation step for the translation unit in the environment the build system uses"](https://clang.llvm.org/docs/JSONCompilationDatabase.html).

I think the real fix would be to split the compiler executable(s) and the compiler arguments in the compilation database. Such a change would even be backwards compatible:

```
{
    "directory": "/home/user/code/myproject/build-release",
    "compiler_executables: "ccache cc",
    "compiler_arguments: "-Itest/9f86d08@@simple_test@exe -Itest -I../test -I../include -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=gnu11 -O3 -pthread -UNDEBUG -MD -MQ 'test/9f86d08@@simple_test@exe/simple_test.c.o' -MF 'test/9f86d08@@simple_test@exe/simple_test.c.o.d' -o 'test/9f86d08@@simple_test@exe/simple_test.c.o' -c ../test/simple_test.c",
    "command": "ccache cc -Itest/9f86d08@@simple_test@exe -Itest -I../test -I../include -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=gnu11 -O3 -pthread -UNDEBUG -MD -MQ 'test/9f86d08@@simple_test@exe/simple_test.c.o' -MF 'test/9f86d08@@simple_test@exe/simple_test.c.o.d' -o 'test/9f86d08@@simple_test@exe/simple_test.c.o' -c ../test/simple_test.c",
    "file": "../test/simple_test.c"
},
```

But even if build tools would generate such a compilation database, iwyu would want to support non-split compilation databases. Hence I hope we find a solution, like my proposed PR, that allows iwyu to deal with those.

**Comment by kimgr** [comment]
Good point. I think your PR looks good too, so let's add a workaround on the IWYU side.

**Comment by Flowdalic** [comment]
FYI I have created a feature request to split the compiler command into compiler executables and arguments in the JSON Compilation Database as [LLVM Bug #45829](https://bugs.llvm.org/show_bug.cgi?id=45829). Still, even if this would be fixed today, compilation database consumers like iwyu should continue to strip the compiler wrappers because it sure would take time until the new metadata appears the compilation database on user's systems.
