### ISSUE TITLE
IWYU does not recognize function uses inside enable-if's

### ISSUE THREAD

**Issue by RuijieYu** [include-what-you-use/include-what-you-use#792]
The tool insists that I remove a type-trait based header because it does not see any use in the code, but in really the header is heavily used in the template guards. My current workaround for this issue is to add a `constexpr` constant after the header inclusion that is left unused. 

`include-what-you-use 0.14 based on clang version 10.0.0`

**Comment by kimgr** [comment]
@RuijieYu Can you provide a reduced example? Thanks!

**Comment by jbytheway** [comment]
If you're describing the issue I suspect you are, then this is a clang issue.  Expressions inside template arguments simply don't appear in the AST, so there is nothing IWYU can do about it.

I mentioned this in a clang bug [here](https://bugs.llvm.org/show_bug.cgi?id=20666).  At the time I thought it was more related to the original report of that bug, but I think it applies to any expressions inside template arguments.  Probably it warrants a new bug report.

**Comment by RuijieYu** [comment]
Here is a contrived example that mimics my original issue. 

```cpp
/* struct.hpp */
#pragma once
#include "main.hpp"
template <class C>
struct S {
    C i;
    template <class = std::enable_if_t<IS_INTEGRAL<C>>>
    void run() {}
};

/* main.hpp */
#pragma once
#include <type_traits>
template <class T>
constexpr bool IS_INTEGRAL{std::is_integral_v<T>};

/* main.cpp */
#include "main.hpp"
#include "struct.hpp"

int main() {
    S<int> s{1};
    return s.i;
}
```

The result of IWYU for this set of code is the following: 
```text
$ include-what-you-use main.cpp --std=c++17

main.hpp should add these lines:

main.hpp should remove these lines:
- #include <type_traits>  // lines 3-3

The full include-list for main.hpp:
---

(main.cpp has correct #includes/fwd-decls)
```

I hope that this example helps you to investigate further or to decide that this issue relates to the upstream (clang).
