### ISSUE TITLE
Suggests fwd_decl for defined types

### ISSUE THREAD

**Issue by alephzero** [include-what-you-use/include-what-you-use#793]
Moving question from
https://stackoverflow.com/questions/61645966/is-typedef-allowed-before-definition#61646129
to here.

Running iwyu over the following:
```cpp
// foo.h

typedef struct foo_s foo_t;

struct foo_s {
  foo_t* next;
};
```

Results in:
```sh
$ iwyu -c foo.h 

foo.h should add these lines:
struct foo_s;

foo.h should remove these lines:

The full include-list for foo.h:
struct foo_s;
---
```

This is true across different versions of `iwyu`, including newer versions with `-Xiwyu --no_fwd_decls` added.

**Comment by kimgr** [comment]
I wonder if this is related: https://github.com/include-what-you-use/include-what-you-use/issues/682

I think that fix is only on master, and hasn't gone out in a release yet.

**Comment by kimgr** [comment]
I've played around with this a little, and it's still broken on master. Not quite sure what the root cause is, but the analysis seems sound all the way up until we determine desirability of uses.

**Comment by kimgr** [comment]
Superseded by #1065, see associated PR there.
