### ISSUE TITLE
Building for Windows, with LLVM10

### ISSUE THREAD

**Issue by greenkalx** [include-what-you-use/include-what-you-use#794]
I checked out clang_10 branch of include-what-you-use.
And checked out release/10.x branch of llvm-project.

I built LLVM, then build iwyu targeting the LLVM build folder with:

c:\work\build>cmake -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH="c:\work\llvm-project\build" ../include-what-you-use
-- IWYU: out-of-tree configuration
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.26.28805.0
-- The CXX compiler identification is MSVC 19.26.28805.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (find_package):
  Found package configuration file:

    c:/work/llvm-project/build/lib/cmake/clang/ClangConfig.cmake

  but it set Clang_FOUND to FALSE so package "Clang" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: LLVMCore
  LLVMMC LLVMSupport LLVMFrontendOpenMP LLVMMCParser LLVMBinaryFormat
  LLVMAnalysis LLVMBitReader LLVMBitWriter LLVMCoroutines LLVMCoverage
  LLVMipo LLVMIRReader LLVMAggressiveInstCombine LLVMInstCombine
  LLVMInstrumentation LLVMLTO LLVMLinker LLVMObjCARCOpts LLVMObject
  LLVMPasses LLVMProfileData LLVMRemarks LLVMScalarOpts LLVMTarget
  LLVMTransformUtils LLVMOption LLVMBitstreamReader LLVMAArch64CodeGen
  LLVMAArch64AsmParser LLVMAArch64Desc LLVMAArch64Disassembler
  LLVMAArch64Info LLVMAArch64Utils LLVMAMDGPUCodeGen LLVMAMDGPUAsmParser
  LLVMAMDGPUDesc LLVMAMDGPUDisassembler LLVMAMDGPUInfo LLVMAMDGPUUtils
  LLVMARMCodeGen LLVMARMAsmParser LLVMARMDesc LLVMARMDisassembler LLVMARMInfo
  LLVMARMUtils LLVMBPFCodeGen LLVMBPFAsmParser LLVMBPFDesc
  LLVMBPFDisassembler LLVMBPFInfo LLVMHexagonCodeGen LLVMHexagonAsmParser
  LLVMHexagonDesc LLVMHexagonDisassembler LLVMHexagonInfo LLVMLanaiCodeGen
  LLVMLanaiAsmParser LLVMLanaiDesc LLVMLanaiDisassembler LLVMLanaiInfo
  LLVMMipsCodeGen LLVMMipsAsmParser LLVMMipsDesc LLVMMipsDisassembler
  LLVMMipsInfo LLVMMSP430CodeGen LLVMMSP430AsmParser LLVMMSP430Desc
  LLVMMSP430Disassembler LLVMMSP430Info LLVMNVPTXCodeGen LLVMNVPTXDesc
  LLVMNVPTXInfo LLVMPowerPCCodeGen LLVMPowerPCAsmParser LLVMPowerPCDesc
  LLVMPowerPCDisassembler LLVMPowerPCInfo LLVMRISCVCodeGen LLVMRISCVAsmParser
  LLVMRISCVDesc LLVMRISCVDisassembler LLVMRISCVInfo LLVMRISCVUtils
  LLVMSparcCodeGen LLVMSparcAsmParser LLVMSparcDesc LLVMSparcDisassembler
  LLVMSparcInfo LLVMSystemZCodeGen LLVMSystemZAsmParser LLVMSystemZDesc
  LLVMSystemZDisassembler LLVMSystemZInfo LLVMWebAssemblyCodeGen
  LLVMWebAssemblyAsmParser LLVMWebAssemblyDesc LLVMWebAssemblyDisassembler
  LLVMWebAssemblyInfo LLVMX86CodeGen LLVMX86AsmParser LLVMX86Desc
  LLVMX86Disassembler LLVMX86Info LLVMX86Utils LLVMXCoreCodeGen LLVMXCoreDesc
  LLVMXCoreDisassembler LLVMXCoreInfo LLVMCodeGen LLVMExecutionEngine
  LLVMMCJIT LLVMRuntimeDyld LLVMSelectionDAG LLVMLineEditor

**Comment by greenkalx** [comment]
I got the build going, it created the Visual Studio solution and projects.
And the solution opens and builds in Visual Studio.
I needed to clean out the old CMakeCache.txt and CMakeFiles from a previous attempt.

**Comment by greenkalx** [comment]
The binary locks up Visual Studio 2019 when called from iwyu_for_vs_includetoolbox:
https://github.com/Wumpf/iwyu_for_vs_includetoolbox

It runs on command line fine, printing --help.

**Comment by greenkalx** [comment]
I pulled latest release/10.x branch of llvm-project and rebuilt.

https://github.com/Wumpf/iwyu_for_vs_includetoolbox/issues/1

**Comment by kimgr** [comment]
Thanks for closing the loop on this! And thanks for helping fix up includetoolbox, I wasn't aware that project existed (I'm no longer using Windows/Visual Studio, so I don't keep track).

**Comment by greenkalx** [comment]
Actually, I ended up going back to the build included with includetoolbox, as it wasn't doing any cleanup.

I had hoped the newer build with newer llvm would result in better cleanup, as the old one leaves for a lot of manual cleanup.
I don't know how clang-include-fixer compares, I would need to set up in linux and build its dbs:
https://clang.llvm.org/extra/clang-include-fixer.html

I built using your instructions in another thread, targeting the llvm build path:
cmake -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH="c:\work\llvm-project\build" ../include-what-you-use

**Comment by kimgr** [comment]
> I don't know how clang-include-fixer compares, I would need to set up in linux and build its dbs:
> https://clang.llvm.org/extra/clang-include-fixer.html

I think the primary selling point for `clang-include-fixer` is to add missing includes. Its analysis isn't as deep as IWYU's, as it doesn't clean out/move around unused includes.
