### ISSUE TITLE
How to use it with a qt project.

### ISSUE THREAD

**Issue by lynnYoun** [include-what-you-use/include-what-you-use#797]
I can use it normally by a file without include of QString,
but if i include QString in this file, then i use include-what-you-use,i'll get an error like this:
 fatal error: 'QString' file not found

how should i config it.i'm running include-what-you-use by this command: 
./include-what-you-use -Xiwyu --mapping_file=qt_5.12.imp /media/lynn/win10_data/shellWithOtherOs/code/.test/Test4PCH/g.hpp

could u tell me how to use include-what-you-use with a qt project please.

**Comment by kimgr** [comment]
@lynnYoun You need the entire compile command-line; IWYU needs the same compiler arguments your compiler uses for your source file.

Which build system are you using? Does it have facilities for replacing the compiler, e.g. `CXX` or `CC` variables?

**Comment by lynnYoun** [comment]
i'm using the ubuntu18.04 with g++ complier, the qmake config of mine is like this:
![image](https://user-images.githubusercontent.com/35143679/82273384-f2335b80-99af-11ea-8ca3-ca8084325d53.png)

**Comment by lynnYoun** [comment]
> @lynnYoun You need the entire compile command-line; IWYU needs the same compiler arguments your compiler uses for your source file.
> 
> Which build system are you using? Does it have facilities for replacing the compiler, e.g. `CXX` or `CC` variables?

i'm using the ubuntu18.04 with g++ complier, the qmake config of mine is like this:
![image](https://user-images.githubusercontent.com/35143679/82273384-f2335b80-99af-11ea-8ca3-ca8084325d53.png)

**Comment by lynnYoun** [comment]
@kimgr may be i found the way to do that , thank for your help sincere, i try to do this: 
make -B -k CXX=include-what-you-use>iwyu.out CFLAGS=" -Xiwyu --mapping_file=qt_5.12.imp"
and it detect all files in my projector.

**Comment by kimgr** [comment]
@lynnYoun Glad to hear it! I'll close this issue.
