### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by aminya** [include-what-you-use/include-what-you-use#798]
I was checking the downloads, but I could not find any binaries.
https://include-what-you-use.org/downloads/

Could you use a GitHub action or something to build binaries and release it?

**Comment by kimgr** [comment]
No, binaries are not planned again. That's too much work to release, and users never get quite what they want/need.

**Comment by blockspacer** [comment]
Hi.
What do you think about conan package for iwyu?

**Comment by kimgr** [comment]
@blockspacer I don't use conan myself so I don't have a strong opinion, but more packaging of IWYU is obviously better :)

We don't have capacity to maintain packaging like that, but we try to make IWYU easy to package (even if it's sometimes daunting with a big dependency like LLVM+Clang).

**Comment by kimgr** [comment]
No plans to provide packages from this project. Closing.
