### ISSUE TITLE
Compilation error on SLES 15

### ISSUE THREAD

**Issue by eyalroz** [include-what-you-use/include-what-you-use#808]
I'm using SuSE Enterprise Linux Server (SLES) v15 - woe is me...

Anyway, after getting past bug #809, I've now configured iwyu-0.14 and am trying to build it.

When I `make`, I get:
```
... etc etc ...
[ 92%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o
In file included from /usr/local/src/include-what-you-use/iwyu_preprocessor.cc:10:0:
/usr/local/src/include-what-you-use/iwyu_preprocessor.h:207:33: error: ‘FileEntryRef’ in namespace ‘clang’ does not name a type
   void FileSkipped(const clang::FileEntryRef& file, const clang::Token &filename,
                                 ^~~~~~~~~~~~
/usr/local/src/include-what-you-use/iwyu_preprocessor.h:207:8: error: ‘void include_what_you_use::IwyuPreprocessorInfo::FileSkipped(const int&, const clang::Token&, clang::SrcMgr::CharacteristicKind)’ marked ‘override’, but does not override
   void FileSkipped(const clang::FileEntryRef& file, const clang::Token &filename,
        ^~~~~~~~~~~
/usr/local/src/include-what-you-use/iwyu_preprocessor.cc:37:14: error: ‘clang::FileEntryRef’ has not been declared
 using clang::FileEntryRef;
              ^~~~~~~~~~~~
In file included from /usr/local/src/include-what-you-use/iwyu_output.cc:25:0:
/usr/local/src/include-what-you-use/iwyu_preprocessor.h:207:33: error: ‘FileEntryRef’ in namespace ‘clang’ does not name a type
   void FileSkipped(const clang::FileEntryRef& file, const clang::Token &filename,
                                 ^~~~~~~~~~~~
/usr/local/src/include-what-you-use/iwyu_preprocessor.cc:708:46: error: ‘FileEntryRef’ does not name a type; did you mean ‘GetFileEntry’?
 void IwyuPreprocessorInfo::FileSkipped(const FileEntryRef& file,
                                              ^~~~~~~~~~~~
                                              GetFileEntry
```
and some other more errors.

I'll mention the GCC version is 7.4.1 and the clang version is 7.0.1.

**Comment by kimgr** [comment]
If you're targeting clang 7, you need to use the `clang_7.0` branch in the IWYU repo, not 0.14, which targets clang 9. See https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build.

**Comment by eyalroz** [comment]
@kimgr : Well, in that case - I should get a message telling me that when I CMake. If build configuration concludes successfully that means that what I have on my system is good enough.

**Comment by aaronpuchert** [comment]
It's more that the `clang_X.0` branch guarantees that it compiles with Clang X, it doesn't mean it works only with that version. Overly sensitive configuration checks, especially between releases, would probably make development unnecessarily hard. And they don't help if you want to build a current master or against a current Clang master.

Though one could codify the oldest supported version and increase that after the first breaking change in a release cycle.

> If build configuration concludes successfully that means that what I have on my system is good enough.

Given the pace of changes in Clang and the proliferation of master builds that's probably impossible to achieve.

**Comment by kimgr** [comment]
Yeah, I agree. Unfortunately the docs will have to be read before configuring. Closing.
