### ISSUE TITLE
When CMake'ing, clang-X.Y.Z not accepted, clang-X demanded

### ISSUE THREAD

**Issue by eyalroz** [include-what-you-use/include-what-you-use#809]
I'm trying to configure iwyu 0.14 on my SLES 15 (SuSE enterprise), which has clang 7.0.1 installed.

I get a message saying that `/usr/bin/clang-7` is expected to exist. Indeed, it doesn't, but - `/usr/bin/clang` does, and so does `/usr/bin-clang-7.0.1`. Even if I create a symlink, at `/usr/local/bin/clang-7` - that's _still_ not good enough.

I believe the build configuration should succeed on my system without me having to jump through the hoop of creating `/usr/bin` symlinks.

**Comment by kimgr** [comment]
@eyalroz This sounds like a problem with the LLVM+Clang packaging on SuSE. IWYU doesn't do anything special, it mostly just uses CMake's `find_package()` on the `LLVM` and `Clang` packages. `find_package()` in turn delegates (as far as I know) to the respective package's `...Config.cmake`, which sets up the CMake environment.

Can you say something about _how_ you're configuring, and what CMake says exactly?

**Comment by eyalroz** [comment]
Well, I'm not at that computer right now, but I was using CMake 3.10.2 I think, and it was a plain vanilla configuration: `cd /path/to/iwu-src; mkdir build; cd build; cmake ..`  The only thing worth mentioning is that I was configuring it as the root user.

**Comment by aaronpuchert** [comment]
This is [SUSE bug 1120098](https://bugzilla.opensuse.org/show_bug.cgi?id=1120098), which was fixed after the package freeze of SLE 15 SP1. I ported the fix back to openSUSE Leap 15.1 after a [similar bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1138457) there, but SUSE decided that they don't want this in SLE15 SP1.

However, SP2 should have [llvm9 with the fix](https://build.opensuse.org/package/view_file/SUSE:SLE-15-SP2:GA/llvm9/llvm9.changes).

**Comment by kimgr** [comment]
@aaronpuchert Thanks for the clarification, closing this.
