### ISSUE TITLE
not support armv7-a

### ISSUE THREAD

**Issue by 1989wanghang** [include-what-you-use/include-what-you-use#811]
**error LOG:**
_# /usr/local/Cellar/include-what-you-use/0.14/libexec/bin/include-what-you-use /Users/hertz/Library/Android/sdk/ndk-bundle//toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ --sysroot=/Users/hertz/Library/Android/sdk/ndk-bundle//platforms/android-14/arch-arm -DNDEBUG -DPLATFORM_ANDROID -DRELEASE=1 -DUSE_RENDER_THREAD  /Users/hertz/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/hertz/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /Users/hertz/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -fexceptions -frtti -g1 -fPIC -pipe -O2 -Wall -W -fshort-wchar -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -g -Wno-attributes -Wno-comment -Wno-conversion-null -Wno-delete-non-virtual-dtor -Wno-ignored-qualifiers -Wno-invalid-offsetof -Wno-missing-field-initializers -Wno-reorder -Wno-sign-compare -Wno-switch -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-unused-function -Wno-unused-parameter -Wno-unused-result -Wno-unused-variable -Wno-write-strings -O3 -DNDEBUG -fPIC -Wno-deprecated-declarations -g -o CMakeFiles/Test.dir/Users/hertz/Test.cpp.o -c /Users/hertz/Test.cpp_
**warning: /Users/hertz/Library/Android/sdk/ndk-bundle//toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++: 'linker' input unused
warning: argument unused during compilation: '-mthumb'
warning: argument unused during compilation: '-mfpu=vfpv3-d16'
warning: argument unused during compilation: '-mfloat-abi=softfp'
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
error: unknown target CPU 'armv7-a'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64**

The above command is generated by "iwyu_tool.py -v -p /Users/hertz/build /Users/hertz/Test.cpp". The " /Users/hertz/build" is the directory for cmake which defined "CMAKE_EXPORT_COMPILE_COMMANDS=ON".

And iwyu version: 
$ include-what-you-use --version
include-what-you-use 0.14 based on clang version 9.0.1

**Comment by 1989wanghang** [comment]
change to use arm64-v8a

**Comment by kimgr** [comment]
It's a little convoluted -- you can configure when building clang (and thereby when building iwyu) which targets LLVM should support.

So if the IWYU binary you're using was built with a specific set of support targets (or the default?), which doesn't support your cross target, IWYU won't understand what to do with the target-specific `-m` switches. Same as for `clang`.

I think the only thing you can do to get full fidelity is to build LLVM+Clang from source with explicit support for the ARM targets in question, and then link IWYU with the resulting libraries.

But it sounds like you got `arm64-8a` to work? That's surprising, as the error message you got doesn't mention it as a supported target...?

**Comment by zhengjunling** [comment]
> It's a little convoluted -- you can configure when building clang (and thereby when building iwyu) which targets LLVM should support.
> 
> So if the IWYU binary you're using was built with a specific set of support targets (or the default?), which doesn't support your cross target, IWYU won't understand what to do with the target-specific `-m` switches. Same as for `clang`.
> 
> I think the only thing you can do to get full fidelity is to build LLVM+Clang from source with explicit support for the ARM targets in question, and then link IWYU with the resulting libraries.
> 
> But it sounds like you got `arm64-8a` to work? That's surprising, as the error message you got doesn't mention it as a supported target...?

Usually, clang is compiled to support all architectures by default.

I met the same problem, and bypassed it by specifying "--target=arm-linux-androideabi" manully after include-what-you-use command.

It seems that the IWYU tool can't identify which target should be used through the cross compiler.

**Comment by 1989wanghang** [comment]
> It's a little convoluted -- you can configure when building clang (and thereby when building iwyu) which targets LLVM should support.
> 
> So if the IWYU binary you're using was built with a specific set of support targets (or the default?), which doesn't support your cross target, IWYU won't understand what to do with the target-specific `-m` switches. Same as for `clang`.
> 
> I think the only thing you can do to get full fidelity is to build LLVM+Clang from source with explicit support for the ARM targets in question, and then link IWYU with the resulting libraries.
> 
> But it sounds like you got `arm64-8a` to work? That's surprising, as the error message you got doesn't mention it as a supported target...?

Like @zhengjunling, Finally I edit the file 'iwyu_tool.py', add "['-Xiwyu', '--pch_in_code'] ['--target=arm-linux-androideabi']" for variable 'command'. And if another platform is need, edit the 'iwyu_tool.py' again. It's work for me, though it seems some inconvenient.

**Comment by kimgr** [comment]
Thanks for more context!

You should be able to add custom args to the `iwyu_tool.py` invocation using `--` as a separator, for example;

    ./iwyu_tool.py -p /x/y/z abc.cpp -- -Xiwyu --pch_in_code --target=arm-linux-androideabi

That way at least you don't need to edit the script.

Detecting the target would be nice, but it feels like it's a rabbit hole to do it by hand. I wonder if it's possible to use the Clang API to do the resolution from cross-compiler name somehow.

**Comment by 1989wanghang** [comment]
> Thanks for more context!
> 
> You should be able to add custom args to the `iwyu_tool.py` invocation using `--` as a separator, for example;
> 
> ```
> ./iwyu_tool.py -p /x/y/z abc.cpp -- -Xiwyu --pch_in_code --target=arm-linux-androideabi
> ```
> 
> That way at least you don't need to edit the script.
> 
> Detecting the target would be nice, but it feels like it's a rabbit hole to do it by hand. I wonder if it's possible to use the Clang API to do the resolution from cross-compiler name somehow.

Thank you for sharing corrent command. 

The issue only happen on arm, arm64(aarch64) is fine. I think maybe the version of NDK is the trouble. For some reason, I have to use the NDK with n10e version. The current compile environment can not allow me to change to the newest NDK to ensure this guess.
