### ISSUE TITLE
No tags/releases for clang 9 and clang 10

### ISSUE THREAD

**Issue by csholmq** [include-what-you-use/include-what-you-use#825]
Found the branches for both clang 9 and 10. Not obvious that they would be there considering versioning after clang 8 changed format to e.g 0.12, etc.

**Comment by kimgr** [comment]
Is there a question or suggestion hiding in the above statement? 🙂

**Comment by csholmq** [comment]
Yes 😁 Would be a shame if people turned away from this great tool just because it doesn't mention anything above clang8 😉

**Comment by kimgr** [comment]
Oh, I see what you mean now. After forgetting to update the table in the README for clang 9, I resorted to the ellipsis to mean "and so on in sequence". I can see how it's hard to guess which iwyu version maps to which clang version, but you really only need to checkout the corresponding `clang_xx` tag or branch to build. So I guess I figured it was a little redundant.

**Comment by kimgr** [comment]
This was fixed by https://github.com/include-what-you-use/include-what-you-use/pull/822
