### ISSUE TITLE
clang/AST/DeclBase.h: No such file or directory???

### ISSUE THREAD

**Issue by bnadem** [include-what-you-use/include-what-you-use#830]
when i check file unix 
ls  -alt  /usr/lib/llvm-3.8/include/clang/AST/ASTConsumer.h

exit already!!!!!

**Comment by kimgr** [comment]
I don't understand, can you clarify?

**Comment by bnadem** [comment]
ok gut thank for replay:
i have cloned from gitub and i want to build
cmake with comand , give no error "cmake -G "Unix Makefiles" -DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-6.0 ../iwyu/include-what-you-use"
but when i run make i become this error **wyu/include-what-you-use/iwyu_ast_util.h:22:32: fatal error: clang/AST/DeclBase.h: No such file or directory**

but this file exist in my system with ls command!!!
-rw-r--r-- 1 root root 6557 Okt 20  2015 /usr/lib/llvm-3.8/include/clang/AST/ASTConsumer.h

**Comment by kimgr** [comment]
See https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build for detailed instructions.

Your cmake command probably said something about which LLVM version it found. Make sure that matches the branch you have checked out, and an LLVM version you have installed.

**Comment by kimgr** [comment]
> this file under llvm-3.8 exist , but under /user/lib/llvm-6.0 don't exist!

IWYU has had `#include "clang/AST/DeclBase.h"` there since it's first release, so it could also be that your LLVM 6.0 installation is broken.

**Comment by bnadem** [comment]
Thank you, you can close issues is working

Kim Gräsman <notifications@github.com> schrieb am So., 27. Sep. 2020, 10:08:

**Comment by kimgr** [comment]
Thank you.
