### ISSUE TITLE
Header for CLOCKS_PER_SEC is incorrect

### ISSUE THREAD

**Issue by cspiegel** [include-what-you-use/include-what-you-use#834]
When `CLOCKS_PER_SEC` is used, IWYU suggests `<sys/time.h>`, but this is a standard C macro that's defined in `<time.h>` (or `<ctime>` in C++).  It looks like `<sys/time.h>` isn't even meant to define this macro, and on my system at least, `CLOCKS_PER_SEC` is defined in `<bits/time.h>` which is only included by `<time.h>`, so IWYU may be getting crossed up somwhere.

This is Linux with glibc 2.31 and LLVM 10.0.1.

Test program:

```c
#include <time.h>

int main(void)
{
    CLOCKS_PER_SEC;
}
```

IWYU output:

```
t.c should add these lines:
#include <sys/time.h>  // for CLOCKS_PER_SEC

t.c should remove these lines:
- #include <time.h>  // lines 1-1

The full include-list for t.c:
#include <sys/time.h>  // for CLOCKS_PER_SEC
```

**Comment by aaron-prog** [comment]
Hello,

Would a mapping help in this case? https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md

**Comment by kimgr** [comment]
A mapping should help. It's just curious that this isn't covered by the default mappings. I'll take a look.

**Comment by kimgr** [comment]
Please try https://github.com/include-what-you-use/include-what-you-use/pull/838 and see if it helps. My narrowed down testcase succeeded with this patch:
```
$ cat tests/clocks_per_sec.cc 
#include <time.h>

int main() {
  return CLOCKS_PER_SEC;
}
```

**Comment by kimgr** [comment]
@cspiegel ^

**Comment by cspiegel** [comment]
Apologies, I didn't see the earlier message.  Yes, #838 does fix things.  Thank you!

**Comment by kimgr** [comment]
Thank you, merged!
