### ISSUE TITLE
Run iwyu_tool.py error when source file in compile_commands.json has huge -I  options

### ISSUE THREAD

**Issue by chouzz** [include-what-you-use/include-what-you-use#843]
When a file has too many options in the compile_commands.json, python script will get an error.

I debug `iwyu_tool.py` and I got `invocation.command`'s length is 435. This is a very big number，so the python script has an error while running. Is there any way to avoid this situation？

```log
Exception has occurred: WindowsError
[Error 87] 
  File "D:\work\include-what-you-use-src\iwyu_tool.py", line 266, in start
    stderr=subprocess.STDOUT
  File "D:\work\include-what-you-use-src\iwyu_tool.py", line 306, in start
    return Process.start(self)
  File "D:\work\include-what-you-use-src\iwyu_tool.py", line 351, in execute
    print(formatter(invocation.start(verbose).get_output()))
  File "D:\work\include-what-you-use-src\iwyu_tool.py", line 402, in main
    return execute(invocations, verbose, formatter, jobs)
  File "D:\work\include-what-you-use-src\iwyu_tool.py", line 461, in _bootstrap
    FORMATTERS[args.output_format], args.jobs, extra_args)
  File "D:\work\include-what-you-use-src\iwyu_tool.py", line 465, in <module>
    sys.exit(_bootstrap(sys.argv))
```

**Comment by chouzz** [comment]
This seems to be due to the length of the maximum parameter restricted by subprocess. But I don't know the best way to solve this problem，any suggestions？
https://stackoverflow.com/questions/2381241/what-is-the-subprocess-popen-max-length-of-the-args-parameter

**Comment by kimgr** [comment]
I think Windows tools have long used the concept of response files -- IIRC it's basically a text file with one line per input argument. I've never used them, but it seems to me you should be able to hack something into `iwyu_tool.py` to take overlong arg lists, write them into response files and then use `@somefile.rsp` on the command-line to `include-what-you-use`.

**Comment by chouzz** [comment]
Works for me，thanks.
