### ISSUE TITLE
Please fix following headers in default mappings. Thanks.

### ISSUE THREAD

**Issue by mohitmv** [include-what-you-use/include-what-you-use#844]
Please fix the mapping of following headers.

```
__bit_reference
__hash_table
__locale
__mutex_base
__tree
__tuple
_ctype.h
_types/_uint16_t.h
_types/_uint32_t.h
_types/_uint64_t.h
_types/_uint8_t.h
boost/graph/detail/adjacency_list.hpp
boost/graph/detail/edge.hpp
boost/numeric/ublas/detail/config.hpp
boost/preprocessor/facilities/detail/is_empty.hpp
boost/preprocessor/punctuation/detail/is_begin_parens.hpp
boost/regex/v4/basic_regex.hpp
boost/regex/v4/cpp_regex_traits.hpp
boost/regex/v4/match_flags.hpp
boost/regex/v4/match_results.hpp
boost/regex/v4/perl_matcher_common.hpp
boost/regex/v4/perl_matcher_non_recursive.hpp
boost/regex/v4/regex.hpp
boost/regex/v4/regex_fwd.hpp
boost/regex/v4/regex_match.hpp
boost/regex/v4/regex_search.hpp
boost/regex/v4/regex_token_iterator.hpp
boost/regex/v4/sub_match.hpp
boost/accumulators/framework/accumulator_set.hpp
boost/accumulators/framework/extractor.hpp
boost/algorithm/string/detail/classification.hpp
boost/container/detail/std_fwd.hpp
boost/container_hash/extensions.hpp
boost/detail/basic_pointerbuf.hpp
boost/fusion/iterator/deref.hpp
gmock/gmock-actions.h
gmock/gmock-generated-actions.h
gmock/gmock-generated-function-mockers.h
gmock/gmock-generated-matchers.h
gmock/gmock-matchers.h
gmock/gmock-more-actions.h
gmock/gmock-nice-strict.h
gmock/gmock-spec-builders.h
google/protobuf/stubs/common.h
google/protobuf/stubs/common.h
google/protobuf/stubs/port.h
google/protobuf/stubs/port.h
gtest/gtest-message.h
gtest/gtest-test-part.h
gtest/gtest_pred_impl.h
sys/_types/_int16_t.h
sys/_types/_int16_t.h
sys/_types/_int32_t.h
sys/_types/_int32_t.h
sys/_types/_int64_t.h
sys/_types/_int64_t.h
```

I am using latest release of IWYU with clang7 ( switched to clang7 branch). Probably these are fixed in latest branch and not propagated back to clang7 branch.

Thanks.

**Comment by kimgr** [comment]
We usually don't backport, we can barely keep up with supporting our mainline.

I can't say if these are fixed on master, but I think your best bet is to build custom mappings if you have a good idea of what the mapping relationships should look like.

**Comment by darkdragon-001** [comment]
Most mappings should be backwards compatible, so fixing them in master and just using them in your setup should be fine. I stumbled over some of these still in the clang11 branch, so I assume they are also still in master, but didn't have time to work on it yet. Especially when you are using LLVM's libc++, there seems to be quite some work missing: https://github.com/include-what-you-use/include-what-you-use/blob/master/libcxx.imp

**Comment by kimgr** [comment]
This issue does not have enough actionable information. I'm going to close it for lack of concrete things to do.
