### ISSUE TITLE
Get a cycle in include-mapping error when source file have a large number of #include

### ISSUE THREAD

**Issue by chouzz** [include-what-you-use/include-what-you-use#845]
include-what-you-use sometimes get an assertion failed error:

```
Cycle in include-mapping:

  "fwm_mac_sal.h" ->

  "fwm_mac_sal.h"

D:\src\github-src\include-what-you-use-src\iwyu_include_picker.cc:927: Assertion failed: Cycle in include-mapping
```

This happens:
1. Windows 10
2. The source file contains a large number of #include directly(at least 30+), and the #includes also contain many header files。

I have the following questions：
- In this case, the header file obviously contains itself，but I can't reproduce it with a simple example. I want to know when and why this kind of error occurs？
- I'm watching at the source code of include what you use, is it possible for me to fix this issue? What should I do?

**Comment by kimgr** [comment]
See issues #424 and #406. This has been around for a while, and I haven't had a chance to fully understand it yet. Let's keep further discussion on #424, I'll close this as a duplicate.
