### ISSUE TITLE
Fails to build with clang-11 (FileEntryRef)

### ISSUE THREAD

**Issue by sylvestre** [include-what-you-use/include-what-you-use#850]
as llvm-toolchain-11 is now live, I tried to upgrade iwyu to use -11 in Debian and it failed on:
```
In file included from /home/sylvestre/dev/debian/pkg-llvm/iwyu/iwyu_preprocessor.cc:10:
/home/sylvestre/dev/debian/pkg-llvm/iwyu/iwyu_preprocessor.h:207:33: error: ‘FileEntryRef’ in namespace ‘clang’ does not name a type; did you mean ‘FileEntry’?
  207 |   void FileSkipped(const clang::FileEntryRef& file, const clang::Token &filename,
      |                                 ^~~~~~~~~~~~
      |                                 FileEntry
/home/sylvestre/dev/debian/pkg-llvm/iwyu/iwyu_preprocessor.h:207:8: error: ‘void include_what_you_use::IwyuPreprocessorInfo::FileSkipped(const int&, const clang::Token&, clang::SrcMgr::CharacteristicKind)’ marked ‘override’, but does not override
  207 |   void FileSkipped(const clang::FileEntryRef& file, const clang::Token &filename,
      |        ^~~~~~~~~~~
```

Seems that it is caused by 
https://github.com/llvm/llvm-project/commit/4dc5573acc0d2e7c59d8bac2543eb25cb4b32984#diff-71d80537c5b81727428f80d25a1af7bac0986fd86162d49dcff978158513c7f7

**Comment by kimgr** [comment]
Which IWYU branch was this on?

I've successfully built IWYU `master` against Clang `llvmorg-11.0.0` recently (or at least I think I have :)), so I've been postponing cutting a `clang_11` branch until there's been a breaking change on LLVM/Clang trunk.

**Comment by sylvestre** [comment]
I tried with the last tagged 0.14 (as I am trying to upload only tagged release in Debian/Ubuntu)

**Comment by sylvestre** [comment]
And as I didn't notice any change for 9months+ on  iwyu_preprocessor.{h,cc}, i didn't try with master :)

**Comment by kimgr** [comment]
Right, we only keep master up to date; commit c2d74ac67a81734d99b294a182b7de3392b83872 has the fixup for the `FileEntryRef` change.

Sounds like it's time for me to put together a 0.15/clang_11 release...

**Comment by sylvestre** [comment]
@kimgr do you have an eta for the release ? (Sorry for the pressure, it is to know if I should cherry-pick the patch or wait for the release :)

**Comment by kimgr** [comment]
@sylvestre I'm hoping to get it done by Sunday, but I think I have most of the parts in order so it should be sooner. Primarily I want to test build on FreeBSD before I push the tags, and I haven't had time to check if there's a packaged llvm-11 for BSD yet.

So... somewhere between today and Sunday is my best estimate. :)

**Comment by kimgr** [comment]
@sylvestre `0.15` tag is pushed.

I'm working to finish up release communications.
