### ISSUE TITLE
IWYU Assertion failed because of location is not valid

### ISSUE THREAD

**Issue by chouzz** [include-what-you-use/include-what-you-use#861]
I got the following error when running iwyu in a huge project.
```
Assertion failed!
Program: D:\src\IWYU\bin\include-what-you-use.exe
File: D:/LLVM/include/clang/Basic/SourceLocation.h, Line 428
Expression: Loc.isValid()
```

I open SourceLocation.h and found:
```c++
427  bool isBeforeInTranslationUnitThan(FullSourceLoc Loc) const {
428    assert(Loc.isValid());
429    assert(SrcMgr == Loc.SrcMgr && "Loc comes from another SourceManager!");
430    return isBeforeInTranslationUnitThan((SourceLocation)Loc);
  }
```
It seems iwyu call `isBeforeInTranslationUnitThan` but without judge whether the position is valid. Iwyu calls this function in two places, and I can sure IWYU crashes at first palce.
https://github.com/include-what-you-use/include-what-you-use/blob/71220d36ea9179bb5db36a467dc9552d2e78c867/iwyu_location_util.h#L219
 https://github.com/include-what-you-use/include-what-you-use/blob/71220d36ea9179bb5db36a467dc9552d2e78c867/iwyu_ast_util.cc#L1073

And I add simple code to judge position is valid:

```c++
  if(a_loc.isInvalid() || b_loc.isInvalid())
    return false;
```
and 

```c++
if (redecl_loc.isValid() && first_decl_loc.isValid() && redecl_loc.isBeforeInTranslationUnitThan(first_decl_loc))
```

The problem was solved. I'm not sure that's the best solution, but I think iwyu should first judge the validity of the location before using it.

BTW, can I submit a PR for this issue? Is this the best solution？

**Comment by kimgr** [comment]
It would be interesting to see a small repro case (or a big one, if necessary)
