### ISSUE TITLE
iwyu preview is different the final result by fix_includes.py

### ISSUE THREAD

**Issue by 1989wanghang** [include-what-you-use/include-what-you-use#866]
iwyu return me like:

1) The full include-list for GL2Funs.cpp:
#include "stdafx.h"
#include "GL2Funs.h"
#include <stddef.h>
#include "gl2.h"
#include "gl2ext.h"

The order satify me, just leak blank line between "stdafx.h" and "GL2Funs.h" and <stddef.h>.

2) But after running fix_includes.py, the result show me:

#include <stddef.h>

#include "stdafx.h"
#include "GGL2Funs.h"
#include "gl2.h"
#include "gl2ext.h"

It break the right order from iwyu. I have try many flag combination of fix_includes.py, however no effect.

**Comment by kimgr** [comment]
@1989wanghang I wasn't aware that `fix_includes.py` had its own include sorting.

I'm assuming you use the `--pch_in_code` switch to IWYU to respect `#include "stdafx.h"`? I'm not sure how `GL2Funs.h` sorts where it does in that example, though. What does your `include-what-you-use` command look like?

**Comment by 1989wanghang** [comment]
yes, pch_in_code is used. 
command: 
iwyu_tool.py -p android_armeabi_v7a/build/android/armeabi-v7a/release GL2Funs.cpp -- -Xiwyu --pch_in_code -Xiwyu --transitive_includes_only -Xiwyu --target=arm-linux-androideabi

umm, maybe I should write a simple py to use the the output of iwyu directly.

**Comment by kimgr** [comment]
Ah. `GL2Funs.h` is the associated header of `GL2Funs.cpp`, so it sorts first (after an precompiled header). OK, that makes sense.

But yeah, looks like `fix_includes.py` is broken when there's a PCH directive in the code.
