### ISSUE TITLE
v0.15 build failure with Apple Clang

### ISSUE THREAD

**Issue by carlocab** [include-what-you-use/include-what-you-use#867]
Attempting to upgrade Homebrew's IWYU returned CI build failures here: https://github.com/Homebrew/homebrew-core/pull/65850

Homebrew builds with the system compiler (clang). This returned a long series of errors that look like
```
In file included from /usr/local/opt/llvm/include/llvm/ADT/SmallVector.h:17:
/usr/local/opt/llvm/include/llvm/Support/AlignOf.h:49:3: error: C++ requires a type specifier for all declarations
  alignas(::llvm::detail::AlignerImpl<T, Ts...>) char buffer[sizeof(
  ^
/usr/local/opt/llvm/include/llvm/Support/AlignOf.h:49:49: error: expected ';' at end of declaration list
  alignas(::llvm::detail::AlignerImpl<T, Ts...>) char buffer[sizeof(
                                                ^
                                                ;
In file included from /tmp/include-what-you-use-20201128-99314-l5cdfv/iwyu_ast_util.cc:12:
In file included from /tmp/include-what-you-use-20201128-99314-l5cdfv/iwyu_ast_util.h:19:
In file included from /tmp/include-what-you-use-20201128-99314-l5cdfv/iwyu_port.h:16:
In file included from /usr/local/opt/llvm/include/llvm/Support/raw_ostream.h:16:
In file included from /usr/local/opt/llvm/include/llvm/ADT/SmallVector.h:17:
/usr/local/opt/llvm/include/llvm/Support/AlignOf.h:49:3: error: C++ requires a type specifier for all declarations
  alignas(::llvm::detail::AlignerImpl<T, Ts...>) char buffer[sizeof(
  ^
/usr/local/opt/llvm/include/llvm/Support/AlignOf.h:49:49: error: expected ';' at end of declaration list
  alignas(::llvm::detail::AlignerImpl<T, Ts...>) char buffer[sizeof(
                                                ^
                                                ;
```

Compiling IWYU with LLVM clang instead is successful.

Build logs:
[iwyu-log.tar.gz](https://github.com/include-what-you-use/include-what-you-use/files/5685157/iwyu-log.tar.gz)

**Comment by kimgr** [comment]
What version is the system Clang here? It looks like the compiler stumbles on anything C++11 or later, so I wonder if the Apple Clang defaults to `-std=c++03` or something...?

**Comment by carlocab** [comment]
That's a complicated question to answer. According to Apple's version scheme:
```
❯ /usr/bin/clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
I can track down which tag at [Apple's fork](https://github.com/apple/llvm-project) this corresponds to. Last I check, I believe it was roughly Clang ~10 + patches.

**Comment by carlocab** [comment]
>Apple Clang defaults to `-std=c++03`

This may well be the case. Should I try something like passing `-std=c++{11,17}` to see if that helps?

**Comment by carlocab** [comment]
Though, from Clang docs:

>The default C++ language standard is gnu++14.

**Comment by kimgr** [comment]
Clang 10+ should be fine, that supports the C++14 dialect used by LLVM.

Note that there are no compile errors in include-what-you-use itself, they're all in either LLVM or libc++ headers. Weird.

Just for debugging, try adding a `-DCMAKE_CXX_FLAGS=-std=gnu++14` on the cmake line for the build and see what happens. 

In include-what-you-use, we rely on LLVM's packaged CMake system, so if something has gone wrong there (e.g. there's an accidental explicit `-std=c++03` somewhere), that might also cause problems. But I suppose that would be visible on the compiler command-line.

**Comment by Bu11etmagnet** [comment]
(Open source) Clang's default C++ standard has been C++14 since clang 6.0 :
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-60-CPP14

**Comment by kimgr** [comment]
Any news on this problem? I don't see that there's much we can do about this on the IWYU side, but it would be nice if Apple Clang builds worked.

**Comment by carlocab** [comment]
Sorry, I actually haven't managed to find the time to look at this yet. I'll do so in the next few days.

**Comment by carlocab** [comment]
Ok, had a look at this again.

>try adding a z-DCMAKE_CXX_FLAGS=-std=gnu++14` on the cmake line for the build and see what happens

This fixed it, though I'm not sure why. That should already be the default standard for Apple Clang...

**Comment by kimgr** [comment]
Here's a bit of a long-shot, but could you try building https://github.com/MaskRay/ccls with Apple Clang?

I see they explicitly enable C++17 at https://github.com/MaskRay/ccls/blob/master/CMakeLists.txt#L29, so a subsequent test case might be to comment out those three lines and see if you get the same kind of behavior.

I don't have access to a Mac environment, so if you could run this test for me, I can try and raise it with the LLVM folks and see if there's an upstream fix to have the LLVM build system announce the right C++ standard requirement.

**Comment by carlocab** [comment]
I can build ccls just fine. As you suggest, commenting out the three lines specifying the C++ standard leads to a build failure. Error log: [make.log](https://github.com/include-what-you-use/include-what-you-use/files/5799098/make.log)

**Comment by kimgr** [comment]
Thanks! That's a slightly more obvious error, as it fails in ccls itself whereas iwyu fails when parsing llvm headers. I'll try and ask around and see what the LLVM folks think. It could be that consumers of llvm (such as us) need to be explicit about c++ standard.

**Comment by carlocab** [comment]
> It could be that consumers of llvm (such as us) need to be explicit about c++ standard. 

This would help, but I suspect this might be a bug in Apple Clang, given that the states default standard is, in fact, `gnu++14`.

**Comment by DimitryAndric** [comment]
Apple seems to lower the default C++ standard in their version of clang, as shown with this simple program:

```
% clang++ -v
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

% cat cplusplus.cpp
#include <iostream>

int main(void)
{
  std::cout << "__cplusplus=" << __cplusplus << std::endl;
  return 0;
}

% clang++ cplusplus.cpp -o cplusplus

% ./cplusplus
__cplusplus=199711
```

That indicates the default is still `-std=c++98` (or likely `-std=gnu++98`). This is with Xcode 11.3.1 installed, which I believe is fairly recent. (The default standard is controlled by a CMake define `CLANG_DEFAULT_STD_CXX` when building llvm from source.)

**Comment by carlocab** [comment]
Same. It seems the documentation is inaccurate, or Apple forgot to set `CLANG_DEFAULT_STD_CXX` when building Clang.

```
❯ clang++ -v
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
❯ cat cplusplus.cpp
#include <iostream>

int main(void)
{
  std::cout << "__cplusplus=" << __cplusplus << std::endl;
  return 0;
}
❯ clang++ cplusplus.cpp -o cplusplus && ./cplusplus
__cplusplus=199711
```

**Comment by carlocab** [comment]
Reported to Apple as FB8972473.

As an aside, given one of the comments above, Apple Clang is actually open-source. Their repo is on GitHub: https://github.com/apple/llvm-project

**Comment by kimgr** [comment]
@DimitryAndric @carlocab Thanks for root-causing!

It's still not clear to me whether IWYU is responsible for setting a `-std=` to cover for constructs in the LLVM C++ API.

`llvm-config` knows what to do:
```
$ llvm-config-11 --cxxflags
-I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```

... but adding this to IWYU's `CMakeLists.txt`
```
message(STATUS "IWYU: cxxflags: ${CMAKE_CXX_FLAGS}")
```
gives:
```
$ cmake -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 -G Ninja ../../include-what-you-use
...
-- IWYU: cxxflags:  -fPIC -fvisibility-inlines-hidden -Werror=date-time -w -fdiagnostics-color -ffunction-sections -fdata-sections
...
```

It seems to me the CMake modules should set up the same cxxflags.

**Comment by carlocab** [comment]
Nice to see this fixed now. Though I do sympathise with your hesitation to require C++14 directly in your build scripts when it's not IWYU that needs it.
