### ISSUE TITLE
Add header mappings for Python(.h) / CPython

### ISSUE THREAD

**Issue by Flamefire** [include-what-you-use/include-what-you-use#869]
For CPython you must only include <Python.h>, not <listobject.h>, <dictobject.h>, <pylifecycle.h> and the like.
Could this be added to the repo as a default?

**Comment by kimgr** [comment]
Sure. If you have an environment up and running, could you sketch out a working `.imp`-file and open a PR?

**Comment by Flamefire** [comment]
Not really firm with imp files so here is a list of headers pulled in when including `Python.h`, so maybe someone else could convert this to an imp file:

```
abstract.h
bltinmodule.h
boolobject.h
bytearrayobject.h
bytesobject.h
cellobject.h
ceval.h
classobject.h
codecs.h
code.h
compile.h
complexobject.h
context.h
descrobject.h
dictobject.h
dtoa.h
enumobject.h
eval.h
fileobject.h
fileutils.h
floatobject.h
funcobject.h
genobject.h
import.h
intrcheck.h
iterobject.h
listobject.h
longintrepr.h
longobject.h
memoryobject.h
methodobject.h
modsupport.h
moduleobject.h
namespaceobject.h
object.h
objimpl.h
odictobject.h
osmodule.h
patchlevel.h
pyarena.h
pyatomic.h
pycapsule.h
pyconfig.h
pyctype.h
pydebug.h
pyerrors.h
pyfpe.h
pyhash.h
pylifecycle.h
pymacconfig.h
pymacro.h
pymath.h
pymem.h
pyport.h
pystate.h
pystrcmp.h
pystrtod.h
Python.h
pythonrun.h
pythread.h
pytime.h
rangeobject.h
setobject.h
sliceobject.h
structseq.h
sysmodule.h
traceback.h
tupleobject.h
typeslots.h
unicodeobject.h
warnings.h
weakrefobject.h
```

Created with `echo '#include "Python.h"' | g++ -I /home/alex/.pyenv/versions/3.7.4/include/python3.7m/ -E - | grep "/home/alex/.pyenv/versions/3.7.4/include/python3.7m/" | awk '{print $3;}' | sort -u | xargs -n1 basename`

**Comment by kimgr** [comment]
Thanks for the shell hack, that helps get me started.

I think what I want to do is;

- the equivalent of `grep -rh "#include \"" /usr/include/python3.8 | sort -u` to get a set of all Python headers included by other Python headers  (assuming `#include "xxx"` with quotes is only used for Python stuff)
- could use the equivalent of `find /usr/include/python3.8 -name "*.h"` to get the set of all Python headers and join with the above to make sure
- for each header, map `@[<"]header.h[>"]` to `<Python.h>`

`/usr/include/python3.8` above can be a placeholder for the Python include directory of your choice.

I'll work on a portable python script to generate that and we'll see how it pans out.

**Comment by kimgr** [comment]
@Flamefire Did you have a chance to test my python mapper for Python?

**Comment by Flamefire** [comment]
Sorry, was very busy. Tested but got an issue. See #870
