### ISSUE TITLE
--check_also flag ignored

### ISSUE THREAD

**Issue by Time0o** [include-what-you-use/include-what-you-use#871]
Passing `--check_also="*.hpp"` to iwyu compiled from the `clang_11` branch has no effect or at least not the effect I would have expect it to have.

I'm building my project with CMake and invoke `make -k CXX=iwyu_wrapper` where `iwyu_wrapper` is the following script:

```bash
#!bin/sh

/path/to/include-what-you-use --check_also="*.hpp" "$@"
```

This generates correct diagnostics, but only for source files (`.cpp`) and their associated headers (`.hpp`) but not any other headers.

Is this a bug or am I misunderstanding what `--check_also` does?

**Comment by kimgr** [comment]
Are you missing the `-Xiwyu` prefix for the check-also arg?

**Comment by Time0o** [comment]
@kimgr: I think that was the issue, in combination with what is mentioned in #633, the glob patterns have to be full paths apparently.
