### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by premalathasuresh** [include-what-you-use/include-what-you-use#875]

**Comment by premalathasuresh** [comment]
HI,

Am looking for using iwyu tool in your project. 

steps followed 
1. installed llvm-11 version
2.   mkdir iwyu
3.  cd iwyu/
4. git clone https://github.com/include-what-you-use/include-what-you-use.git
5.   cd include-what-you-use/
6. git checkout clang_11
7.  cd ../
8. mkdir build;cd build
9. sudo apt-get install libclang-11-dev
10. cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 ../include-what-you-use
11. make
12.  sudo make install

With above steps am able to install latest version of iwyu i.e. 0.15.
later when I run on the code I am unable to see redundant header files getting identified as output
**main.cpp** 
#include <iostream>
#include </home/premalatha/test/print.h>
#include </home/premalatha/test/dummy.h>
int main()
{
        print();
        return 0;
}

**dummy.h**
#include <iostream>
 void dummyprint() { std::cout << " dummprint " << std::endl; }

**print.h**
include <iostream>
void print() { std::cout << "print" << std::endl; }

the run command I used :
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
/usr/bin/iwyu_tool.py -p .

The output : 
In file included from /home/premalatha/test/main.cpp:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/iostream:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/ostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/ios:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/iosfwd:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/bits/postypes.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/cwchar:44:
/usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found
# include <stdarg.h>

Expectation : 
Since dummy.h is not used in main.cpp, I would expect that file to be shown as remove this file. 

Please suggest  if anything is missed. Thanks in advance.

**Comment by kimgr** [comment]
Hey,

This is the key piece of information:
> /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found

This is described in more detail in https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-install and #100.

I think the straightforward answer for you is to also install the `clang-11` package for your distribution. That contains the headers and puts them in the right place so that a default-installed `include-what-you-use` can find them.

**Comment by premalathasuresh** [comment]
Thanks a lot Kum.

I tried above way, it worked out very well on example code but when I tried on actual code base include-what-you-use still not able to find c++ libraries. 

In file included from /home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/boost/program_options.hpp:15:
In file included from /home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/boost/program_options/options_description.hpp:11:
In file included from /home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/boost/program_options/config.hpp:10:
In file included from /home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/boost/config.hpp:44:
/home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/boost/config/detail/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found
#  include <cstddef>
           ^~~~~~~~~

warning: argument unused during compilation: '-mthumb'
warning: argument unused during compilation: '-mfpu=neon'
warning: argument unused during compilation: '-mfloat-abi=hard'
warning: argument unused during compilation: '-mcpu=cortex-a9'
error: unknown warning option '-Werror=maybe-uninitialized'; did you mean '-Werror=uninitialized'? [-Werror,-Wunknown-warning-option]
In file included from /home/premalatha/clifford-1-5/libpdrpc-pd1600/src/endpoint.cpp:1:
In file included from /home/premalatha/clifford-1-5/libpdrpc-pd1600/include/libpdrpc-pd1600/endpoint.hpp:4:
/home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/libpdlinux/slotid.hpp:4:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~

warning: argument unused during compilation: '-mthumb'
warning: argument unused during compilation: '-mfpu=neon'
warning: argument unused during compilation: '-mfloat-abi=hard'
warning: argument unused during compilation: '-mcpu=cortex-a9'
error: unknown warning option '-Werror=maybe-uninitialized'; did you mean '-Werror=uninitialized'? [-Werror,-Wunknown-warning-option]
/home/premalatha/clifford-1-5/libpdrpc-pd1600/app/pdrpcsetmastercmd.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
warning: argument unused during compilation: '-mthumb'
warning: argument unused during compilation: '-mfpu=neon'
warning: argument unused during compilation: '-mfloat-abi=hard'
warning: argument unused during compilation: '-mcpu=cortex-a9'
error: unknown warning option '-Werror=maybe-uninitialized'; did you mean '-Werror=uninitialized'? [-Werror,-Wunknown-warning-option]
In file included from /home/premalatha/clifford-1-5/libpddrm/src/generateecm.cpp:1:
/home/premalatha/clifford-1-5/build/toolchain/sysroots/cortexa9t2hf-neon-poky-linux-gnueabi/usr/include/range/v3/algorithm/find_if.hpp:16:10: fatal error: 'utility' file not found
#include <utility>
         ^~~~~~~~~

^CTraceback (most recent call last):
  File "/usr/local/bin/iwyu_tool.py", line 473, in <module>
    sys.exit(_bootstrap(sys.argv))
  File "/usr/local/bin/iwyu_tool.py", line 469, in _bootstrap
    FORMATTERS[args.output_format], args.jobs, extra_args)
  File "/usr/local/bin/iwyu_tool.py", line 410, in main
    return execute(invocations, verbose, formatter, jobs)
  File "/usr/local/bin/iwyu_tool.py", line 359, in execute
    print(formatter(invocation.start(verbose).get_output()))
  File "/usr/local/bin/iwyu_tool.py", line 251, in get_output
    self.proc.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)

**Comment by kimgr** [comment]
Ah, cross-compilation. See if you can find any useful techniques in #811.

**Comment by premalathasuresh** [comment]
Thanks for the input, Appreciate your prompt response.

**Comment by premalathasuresh** [comment]
Hi Kim,

Landed up to another set of issues 

**Issue 1**

error: unknown warning option '-Werror=maybe-uninitialized'; did you mean '-Werror=uninitialized'? [-Werror,-Wunknown-warning-option]
In file included from /home/premalatha/clifford-1-5/libbcm45308cxx/src/types.cpp:8:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/ostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/ios:42:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/bits/ios_base.h:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/bits/locale_classes.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/string:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/bits/basic_string.h:5352:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/ext/string_conversions.h:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cstdlib:72:
/usr/local/include/stdlib.h:38:12: error: no member named 'abort' in namespace 'std'
using std::abort;
      ~~~~~^
/usr/local/include/stdlib.h:39:12: error: no member named 'atexit' in namespace 'std'


_**issue 2**_ 

Cycle in include-mapping:
  <boost/utility/in_place_factory.hpp> ->
  <boost/preprocessor/iteration/detail/iter/forward1.hpp> ->
  <boost/preprocessor/iteration/detail/iter/forward1.hpp>
/home/premalatha/iwyu/include-what-you-use/iwyu_include_picker.cc:932: Assertion failed: Cycle in include-mapping

Request you to suggest me a pointer to get out of this issue.

Thanks in advance.

**Comment by kimgr** [comment]
Issue 1: Sounds like: https://stackoverflow.com/questions/25322489/error-no-member-named-stod-in-namespace-std. Not sure how to best solve this for your cross-compilation use-case.

Issue 2: Sounds like: https://github.com/include-what-you-use/include-what-you-use/issues/424. Maybe you can find a workaround there.

**Comment by premalathasuresh** [comment]
Thanks a lot Kim.

**Comment by premalathasuresh** [comment]
Hi Kim,

I have done a small code change in iwyu_include_picker.cc to optimize the recommendations available for our project, is it possible for me to upload the code change in this platform. So that, it can be picked up by any one who is going through such issues. Please suggest.

**Comment by kimgr** [comment]
You should also be able to pick up the boost mappings using e.g. `-Xiwyu --mapping_file=boost-1.64-all.imp` (you need the right path to that mapping) to get better mappings for boost overall.

I'm reluctant to hard-code in arbitrary library names in IWYU itself (even more than what's already there).

**Comment by kimgr** [comment]
There does not seem to be much in this issue that's directly actionable, so I'll close it. Please open new, more focused issues if something else comes up.
