### ISSUE TITLE
iwyu_tool.py fails with AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by SoftwareApe** [include-what-you-use/include-what-you-use#903]
I got the tool to compile, however running `iwyu_tool` fails with the error message `iwyu_tool.py fails with AttributeError: 'NoneType' object has no attribute 'rfind'`.

On closer examination I found that the command starts with None. I traced it back to the global variable IWYU_EXECUTABLE.

For UX reasons if the executable can't be found it would be nice if it failed with an appropriate error message, e.g.

```python
IWYU_EXECUTABLE = find_include_what_you_use()
if IWYU_EXECUTABLE is None:
    print("ERROR: Failed to find IWYU executable. Set the environment variable IWYU_BINARY to the path to your binary, or add the binary to your system's search path.", file=sys.stderr)
    sys.exit(1)
```

**Comment by kimgr** [comment]
Thank you for the report. Yes, this should definitely be handled more gracefully. I'll see if I can find some time to work on this.

**Comment by kimgr** [comment]
@SoftwareApe Hmm, that's already checked for first thing in `main`... That error handling was added for the 0.14/clang_10 release. Which version did you see this in?

**Comment by SoftwareApe** [comment]
@kimgr Hi, I used the clang 8 version, since we're using clang 8 for the foreseeable future.

**Comment by kimgr** [comment]
I see. The backportable patch is here, fwiw: 3e17d6156c53c05c0ea10f6901cec02c6af7de35.

Closing this issue as it's already fixed on mainline.
