### ISSUE TITLE
fix_includes.py doesn't detect duplicates introduced via --check_also

### ISSUE THREAD

**Issue by darkdragon-001** [include-what-you-use/include-what-you-use#905]
`fix_includes.py` doesn't detect duplicates introduced via `--check_also=`. This has the consequence that the line numbers for removals are not accurate any more and the wrong lines are removed.

Suggestion: Keep track of processed files and ignore them when they appear a second time.

**Comment by kimgr** [comment]
@darkdragon-001 Thanks for the report! Can you give a reduced example?

**Comment by darkdragon-001** [comment]
Probably this resulted from the same file being processed multiple times with different representations of the same path (e.g. symlinks or `sub/../`. I will close it for now and reopen when I succeed to create a reduced example.
