### ISSUE TITLE
Add option ignore_glob to ignore certain paths/files

### ISSUE THREAD

**Issue by darkdragon-001** [include-what-you-use/include-what-you-use#912]
When running with CMake, it will also run for auto-generated files (e.g. Qt moc, Protobuf, ...) usually residing in `$CMAKE_CURRENT_BIN_DIR`. It would be nice, if this folder could be added as an ignore path such that iwyu does not run for these files.

**Comment by kimgr** [comment]
I wonder if this should be a feature request for the CMake IWYU integration?

**Comment by darkdragon-001** [comment]
Probably it fits there. Where is the CMake IWYU integration developed?

**Comment by kimgr** [comment]
I don't know, I think it's part of the CMake project, but they never coordinated with us, so I don't have any details.
