### ISSUE TITLE
include-what-you-use.1: Undocumented feature: read from stdin

### ISSUE THREAD

**Issue by alejandro-colomar** [include-what-you-use/include-what-you-use#915]
Hi,

I didn't find in the manual page that I could read from stdin, so I tried the common `-`, and kind of worked; I got this:

```
$ iwyu -
error: -E or -x required when input is from standard input
^C
```

But now, `-E` and `-x` are neither documented in the manual page, so what should I expect?

**Comment by kimgr** [comment]
The general expectation should be that `include-what-you-use` accepts the same arguments as `clang` for the corresponding version. Any iwyu-specific arguments are prefixed by `-Xiwyu`.

**Comment by alejandro-colomar** [comment]
Ahhh, it's a clang option.  Thanks!
