### ISSUE TITLE
False positive when included header has incorrect includes

### ISSUE THREAD

**Issue by ptomato** [include-what-you-use/include-what-you-use#926]
I've found a minimal example for a case where an included header's missing include is reported as an IWYU error in the .cpp file. (In my case, the equivalents of `b.h` and `c.h` are library headers, so I get an IWYU error in my code and can't easily change the library headers to have correct includes.)

**a.cpp**:
```c++
#include "c.h"

void a(C c) {
    c.method(42);
}
```

**b.h**:
```c++
#pragma once
#include <utility>
void b(int&& i);
```

**c.h**:
```c++
#pragma once
#include "b.h"

struct C {
  template <typename T>
  void method(T&& t) {
    return b(std::forward<T>(t));
  }
};
```

Command line:
```
$ include-what-you-use a.cpp 

a.cpp should add these lines:
#include <utility>  // for forward

a.cpp should remove these lines:

The full include-list for a.cpp:
#include <utility>  // for forward
#include "c.h"      // for C
---
```

Here, `c.h` should `#include <utility>` and `b.h` should not, but IWYU should not suggest anything to be changed in `a.cpp`.

**Comment by kimgr** [comment]
I just tried to repro this (sorry about the long delay) -- I suspected it had something to do with other problems around templates and `std::move` -- but it actually seems to work on mainline. I'm not quite sure what fixed it.

@ptomato Any chance you could take the latest IWYU for a spin with the code that triggered this originally? Thanks.

**Comment by ptomato** [comment]
Yes, this seems to have been fixed on the latest git commit, I don't get the error anymore with the original code either. Thanks.
