### ISSUE TITLE
False positive <type_traits> for enable_if_t and remove_reference<>::type

### ISSUE THREAD

**Issue by ptomato** [include-what-you-use/include-what-you-use#927]
In two cases I get false positives of `<type_traits>` for files that don't use it. Here are minimal examples of both cases. In both cases, it seems to be the header file that's at fault; any implementation file that includes it will get the false positive.

## Example 1

**a.cpp**:
```c++
#include "b.h"

enum class F {
    VAL = 1,
};

struct A {
    F a;

    bool method() {
        return a & F::VAL;
    }
};
```

**b.h**:
```c++
#pragma once
#include <type_traits>

struct B {
    operator bool() { return true; }
};

template <class E>
std::enable_if_t<true, B> operator&(E const&, E const&) {
    return B();
}
```

Command line:
```
$ include-what-you-use a.cpp

a.cpp should add these lines:
#include <type_traits>  // for enable_if_t

a.cpp should remove these lines:

The full include-list for a.cpp:
#include <type_traits>  // for enable_if_t
#include "b.h"          // for operator&
---
```

## Example 2

**a.cpp**:
```c++
#include "b.h"

char a() {
    B<char> b;
    return b.b()[0];
}
```

**b.h**:
```c++
#pragma once
#include <type_traits>

template <typename T>
struct B {
    std::add_pointer_t<T> b();
};
```

Command line:
```
$ include-what-you-use a.cpp

a.cpp should add these lines:
#include <type_traits>  // for remove_reference<>::type

a.cpp should remove these lines:

The full include-list for a.cpp:
#include <type_traits>  // for remove_reference<>::type
#include "b.h"          // for B
---
```

**Comment by kimgr** [comment]
Looks like `operator bool` triggers something in the first example:

* `std::enable_if_t<true, B>` resolves to `B`
* A call through `B::operator bool` is necessary to convert `B` to `bool` for return from `method`
* That call happens through `std::enable_if_t` even if it just happens to be a typedef/using decl for `B`

I think in a smaller, related example this would make more sense:
```
// a.h
#include <string>
typedef std::string MyString;

// t.cc
#include "a.h"
int f() {
    return MyString().size();
} 
```

In the above, it makes sense that the mention of `MyString` and call to `size` refer to `a.h`.

The complication with `enable_if` is that it's supposed to be transparent, so referring to `<type_traits>` looks off. I think `remove_reference` is similar -- it's a typedef that doesn't really want to introduce a new name, just massage types.

Not sure how to detect that more generally...

**Comment by kimgr** [comment]
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/ffe6c3fe3a1dac9a4b577f4b07ef378ede933554 (and, as it turns out, probably a bit before that).
