### ISSUE TITLE
C / POSIX types headers: which headers are to be supported?

### ISSUE THREAD

**Issue by alejandro-colomar** [include-what-you-use/include-what-you-use#929]
Hi,  I've seen some inconsistency in the C / POSIX types here.

For example, `gid_t` has (almost) all of the headers required by C or POSIX to define the type in the list (BTW, `<signal.h>` is missing):

```
  { symbol: [ "gid_t", private, "<sys/types.h>", public ] },
  { symbol: [ "gid_t", private, "<grp.h>", public ] },
  { symbol: [ "gid_t", private, "<pwd.h>", public ] },
  { symbol: [ "gid_t", private, "<stropts.h>", public ] },
  { symbol: [ "gid_t", private, "<sys/ipc.h>", public ] },
  { symbol: [ "gid_t", private, "<sys/stat.h>", public ] },
  { symbol: [ "gid_t", private, "<unistd.h>", public ] },
```

And then other types only have the minimum headers that define the type, such as `time_t`:

```
  { symbol: [ "time_t", private, "<sys/types.h>", public ] },
  { symbol: [ "time_t", private, "<time.h>", public ] },
```

All of the following shall also define `time_t`:
```
<sched.h>, <sys/msg.h>, <sys/select.h>, <sys/sem.h>, <sys/shm.h>,
<sys/stat.h>, <sys/time.h>, or <utime.h>
```

See <https://man7.org/linux/man-pages/man7/system_data_types.7.html>

**Comment by alejandro-colomar** [comment]
What do you prefer for new types, the minimum, or the maximum?

**Comment by kimgr** [comment]
I'm not sure how the current set was chosen, but it seems to me there's some element of good taste - relying on sys/msg.h for `time_t` would feel slightly off. 

I don't think minimum/maximum is the right tradeoff, rather just what 'makes sense' conceptually and practically. For example, `size_t` is enough like a builtin type that we have it mapped to a number of system headers. `time_t` is a little more special-purpose, so it's mapped more specifically.

Sorry I don't have a clear answer.

**Comment by alejandro-colomar** [comment]
> I'm not sure how the current set was chosen, but it seems to me there's some element of good taste - relying on sys/msg.h for `time_t` would feel slightly off.

Hmm.  IMHO, it depends on 2 points of view.  If you want a more strict (more iqwyu-like) approach, I'd only allow `<sys/types.h>` or `<time.h>` for `time_t`.

But then there's the other approach that POSIX mandates `<sys/msg.h>` to define `time_t`, and while I would never accept someone relying on that header just for `time_t`, maybe he's using features of that header, and they require using `time_t` too, so `<sys/msg.h>` should be enough, and IWYU shouldn't complain...

I think IWYU should allow for the second one, as it's standards compliant, and (eventhough a bit corrner casy) may be relevant for someone.  And then the good taste is moved to the programmer instead.

> 
> I don't think minimum/maximum is the right tradeoff, rather just what 'makes sense' conceptually and practically. For example, `size_t` is enough like a builtin type that we have it mapped to a number of system headers. `time_t` is a little more special-purpose, so it's mapped more specifically.
> 
> Sorry I don't have a clear answer.

I'm preparing a big PR with the inclusion of `clockid_t` and all other types defined in `system_data_types(7)`.  It has additions, and some removals.  We'll be able to discuss it better with the code.  Wait for a few minutes/hours for it :-)

**Comment by alejandro-colomar** [comment]
Fix this inconsistency in this PR: https://github.com/include-what-you-use/include-what-you-use/pull/930

**Comment by kimgr** [comment]
Yep, good points! I think the behavior we want is that iwyu _allows_ these 'secondary' headers, but never _suggests_ them.

The tricky case is when header a.h uses eg time_t, but only includes b.h, which transitively includes time.h. Then iwyu will find time_t in some private glibc header, and the mappings should lead back to time.h, not e.g. sys/msg.h.

As I understand it, iwyu should pick the first mapping in that case, so as long as they're properly ordered, everything should work out.

**Comment by alejandro-colomar** [comment]
> Yep, good points! I think the behavior we want is that iwyu _allows_ these 'secondary' headers, but never _suggests_ them.

Completely agree.  That was also the decision when writing the manual page system_data_types(7).

> 
> The tricky case is when header a.h uses eg time_t, but only includes b.h, which transitively includes time.h. Then iwyu will find time_t in some private glibc header, and the mappings should lead back to time.h, not e.g. sys/msg.h.
> 
> As I understand it, iwyu should pick the first mapping in that case, so as long as they're properly ordered, everything should work out.

Okay.
