### ISSUE TITLE
Resolution of regexp rules conflicting

### ISSUE THREAD

**Issue by zimin2000** [include-what-you-use/include-what-you-use#935]
I am using iwyu in a large codebase. We are using default mappings along with our custom mappings. One of the custom rule that we are using is hiding implementation in `-inl.h` header by exposing it `.h` counterpart:
```
    { include: ["@\"(.*)-inl.h\"", private, "@\"\\1.h\"", public ] },
```

That works fine, but for the case when both header files are in the `/internal/` folder:

```
xxx/internal/Header.h
xxx/internal/Header-inl.h
```

In this case, AFAIU, the above rule conflicts with the default treatment of the `/internal/` folder. Namely, according to a default rule files in `/internal/` assumed private, so `xxx/internal/Header.h` is declared private. However, on the other hand, the rule for `xxx/internal/Header-inl.h` declares `xxx/internal/Header.h` public.

This conflict leads to the following error:

```
xxx/iwyu_include_picker.cc:1064: Assertion failed: filepath_visibility_map_[quoted_filepath_pattern] == visibility Same file seen with two different visibilities: "xxx/internal/Header.h" Old vis: 2 New vis: 1
```

Is there a way to resolve this issue keeping both the default rules and using a regex rule for `-inl.h`?
What is the best way to resolve the issue ?

PS: I was trying to resolve the issue by updating the `-inl.h` rule and excluding the paths that has `/internal/` in the path, like the following:

```
    { include: ["@\"((?!.*/internal/).*)-inl.h\"", private, "@\"\\1.h\"", public ] },
```

But it turned out that `llvm::Regex` does not support this syntax.

**Comment by kimgr** [comment]
The `internal/` special casing is a Google-ism and could be removed. I can try and work up a patch unless you beat me to it.

**Comment by zimin2000** [comment]
Unfortunately, we are also following the same `internal/` approach and would like to keep it. 
So, the issue is not that in either of the rules, the issue is that the rules happen to overlap and the we would like to be able to resolve this overlap somehow.

**Comment by kimgr** [comment]
Could you try with this patch: https://github.com/include-what-you-use/include-what-you-use/pull/939?

I see no reason to rely on `llvm::Regex` when `std::regex` is available.

**Comment by zimin2000** [comment]
Seems to be working fine. Thank you!

**Comment by kimgr** [comment]
Great, thanks! #939 is merged, closing this.

**Comment by 4wrxb** [comment]
Sorry to poke a closed issue, but I came across this when trying to write mappings using backreferences like the above. What is required to enable this? It would be very powerful in enabling common patterns in our code like the following:

```json
  { include: [ "@.(.*)_base.h", private, "@\"\\1.h\"", public ] },
  { include: [ "@.(.*)_common.h", private, "@\"\\1.h\"", public ] },
  { include: [ "@.(.*)_template.h", private, "@\"\\1.h\"", public ] },
```

but the mapping file is not accepted

```
my_mapping.imp:13:5: error: Expected to-entry to be quoted include, but was '@"\1.h"'
  { include: [ "@.(.*)_base.h", private, "@\"\\1.h\"", public ] },
```
