### ISSUE TITLE
string_view for hash

### ISSUE THREAD

**Issue by kc9jud** [include-what-you-use/include-what-you-use#944]
Is it really a good idea to include `<string_view>` in addition to `<functional>` for `std::hash`? `std::hash` is absolutely declared in `<functional>`...

```
halfint.h:483:12: warning: std::hash needs a declaration, but does not provide or directly #include one.
halfint.h:487:13: warning: std::hash is defined in <string_view>, which isn't directly #included.

halfint.h should add these lines:
#include <string_view>  // for hash
namespace std { template <typename _Tp> struct hash; }

halfint.h should remove these lines:
- namespace std { struct hash; }  // lines 482-483
- namespace std { struct hash; }  // lines 482-483
```

**Comment by i-ky** [comment]
`std::hash` specializations for `std::string_view` & Co. are provided by `<string_view>`, see [this](https://en.cppreference.com/w/cpp/string/basic_string_view/hash). I guess IWYU is hinting that code uses one of specializations, not the `std::hash` template itself, but it's difficult to say for sure without seeing the code.

**Comment by kc9jud** [comment]
I think the only specialization I’m using is `std::hash<int>` — there’s nothing related to `<string_view>` in this header. The code generating this issue is [here](https://github.com/nd-nuclear-theory/am/blob/master/halfint.h)

**Comment by i-ky** [comment]
Looks fine to me. `<functional>` should be enough. Maybe IWYU gets confused by [`std::hash` forward declaration in `<string_view>`](https://en.cppreference.com/w/cpp/header/string_view#Forward_declarations).

**Comment by kimgr** [comment]
Hmm, that's weird. But IWYU's template expansion is pretty complex, so not surprising if it does the wrong thing. Can you find out what the AST looks like around the problematic construct? Using e.g. `-Xiwyu --v6`.

**Comment by kimgr** [comment]
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/ffe6c3fe3a1dac9a4b577f4b07ef378ede933554 (and, as it turns out, probably a bit before that).
