### ISSUE TITLE
Publish Windows build to Chocolatey

### ISSUE THREAD

**Issue by mcandre** [include-what-you-use/include-what-you-use#946]
Hi,

What an interesting utility! Could we publish this to the Chocolatey Windows package manager, to streamline installation for Windows developers?

https://chocolatey.org/

**Comment by kimgr** [comment]
I'm out of the Windows ecosystem these days, but it's a goal for IWYU to build for Windows (working well is work-in-progress). 

We're happy to help package maintainers, but we don't have bandwidth to maintain packages ourselves, so they would have to live outside of the IWYU repo.

If you're up for it, feel free to package IWYU for Chocolatey!

**Comment by kimgr** [comment]
The IWYU project does not maintain packaging, but we welcome bug reports/patches that make packaging easier. Closing.
