### ISSUE TITLE
Not warning when headers are not used for anything

### ISSUE THREAD

**Issue by mcandre** [include-what-you-use/include-what-you-use#947]
I added half a dozen test headers that I definitely don't use, such as time.h, stdatomic.h, and so on. I configured cmake according to the regular documentation. But still no errors or warnings appear. Don't know why.

Latest stable iwyu and cmake via apt-get in Ubuntu 20.04.

It's worth noting that neither iwyu, nor LINK_WHAT_YOU_USE, nor cppclean are reporting any findings for my dummy headers and dummy linked libraries. So strange. Even lld doesn't seem to care when I link pthread, in an application that doesn't use threads.

I also tried deheader. deheader does report findings, but its algorithm is too simplistic and prohibits foo.c from including foo.h. So 4 out of 4 linters are failing me today.

**Comment by kimgr** [comment]
So this is a cmake project with a source file foo.c with lots of unused `#include` directives? And you're using cmake's `C_INCLUDE_WHAT_YOU_USE` flag to enable IWYU [1]?

I can't see why that wouldn't work except if your cmake version is too old. If you can reduce this to one `CMakeLists.txt` and one source file, could you post them inline together with your cmake invocations?

[1] https://cmake.org/cmake/help/latest/prop_tgt/LANG_INCLUDE_WHAT_YOU_USE.html

**Comment by sketch34** [comment]
It would be really helpful to see some example input and expected output from `iwyu` somewhere in the docs. I'm having the same issue where I have integrated it with my cmake project but I am getting no output from it, but perhaps my expectations for what it can detect are incorrect. In my case I know I'm using boost "uber headers" a lot (e.g. `boost/beast.h`) where I know I'm only declarations from a few of the more specific headers.

**Comment by kimgr** [comment]
s@sketch34 Yes, it should. If there's literally _no_ output, I would expect that the cmake integration is not working. It's a little verbose to describe an example in the docs, because we'd need to include both twp headers, a source file, an invocation and the expected output. The test suite has a bunch of examples like that.

**Comment by sketch34** [comment]
Okay thanks I'll give it another go.

**Comment by philippefoubert** [comment]
FYI i have the same behavior on my lubuntu 20.04
```
$ uname -a
Linux lubuntu-dev 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
trying IWYU (ver 0.12 based on clang version 9.0.1-10) with CMake (ver 3.16.3) on the following Github project:
https://github.com/maurer-treutner/iwyu_sample/tree/master/src

Regards,
Philippe.

**Comment by philippefoubert** [comment]
> FYI i have the same behavior on my lubuntu 20.04
> 
> ```
> $ uname -a
> Linux lubuntu-dev 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> trying IWYU (ver 0.12 based on clang version 9.0.1-10) with CMake (ver 3.16.3) on the following Github project: https://github.com/maurer-treutner/iwyu_sample/tree/master/src
> 
> Regards, Philippe.

**I rebuilt IWYI**:
```
mkdir -p ~/iwyu && cd ~/iwyu
git clone https://github.com/include-what-you-use/include-what-you-use.git
cd ~/iwyu/include-what-you-use
git checkout clang_10
mkdir -p ~/iwyu/build && cd ~/iwyu/build
cmake -G "Unix Makefiles" -DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-10 ~/iwyu/include-what-you-use
make
make install
```
(now, it get IWYI version 0.14 (git:aa7c663) based on clang version 10.0.0-4ubuntu1)

**=> it solved the issue.**

**Comment by kimgr** [comment]
Given the information at hand, I can't see any obvious IWYU problems here. Closing, feel free to reopen with more details if you have them.
