### ISSUE TITLE
Feature: option to exit on first warning (a-la -warnings-as-errors)

### ISSUE THREAD

**Issue by hgkjshegfskef** [include-what-you-use/include-what-you-use#948]
It would be useful to provide an option similar to clang-tidy's `-warnings-as-errors`. This flag makes clang-tidy fail upon first warning and cmake build fails with an error code. I found this option of clang-tidy to be very useful in continuous integration, which makes the whole build fail if the linter produces a warning. I think it is an important property of a linter to be able to fail and produce non-zero exit code upon first diagnostic.

I have searched in this repository and on google and did not find a similar option in iwyu.

Example use-case: `cmake -S . -B build -DCMAKE_CXX_CLANG_TIDY='clang-tidy;-warnings-as-errors=*' -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE='include-what-you-use;-Xiwyu;--warnings-as-errors'`

What do you think about adding such capability?

**Comment by i-ky** [comment]
The problem is that IWYU _always_ returns non-zero exit code. See #440.

I suppose CMake simply ignores IWYU's exit code and analyzes its output instead. Your suggestion sounds like something that can be implemented completely on CMake side. After all, it's up to CMake how to handle IWYU output.

**Comment by hgkjshegfskef** [comment]
Understood. Closing in favor of #440.
