### ISSUE TITLE
Request: user-defined suffixes to choose "associated header"

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#954]
Hi,

Currently IWYU will associate "foo_test.cpp" to "foo.h", so that the former can rely on includes from the latter and doesn't need to re-include them. This is implemented here:

https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_path_util.cc#L111

Sometimes we implement code like "foo.h", "foo_x86.cpp", "foo_aarch64.cpp" and let the build system decide which source file to compile based on platform. However IWYU is not able to tell that "foo_x86.cpp" is associated with "foo.h"(and can rely on its headers), so it complains that foo_x86.cpp should include "foo.h" plus its headers.

Would it be possible to make this configurable? I.e. let the user specify a list of regex/suffixes, additional to e.g. "_test". For example clang-format implements this via "IncludeIsMainRegex":

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by carlosgalvezp** [comment]
I just realized there's an "associated" pragma that does exactly this, nevermind!

**Comment by kimgr** [comment]
@carlosgalvezp Ah, I had forgotten about that, thanks for the reminder  :-)
