### ISSUE TITLE
Any instruction how to build it on windows?

### ISSUE THREAD

**Issue by xahon** [include-what-you-use/include-what-you-use#956]
I tried to blindly build it as a cmake project and it says it wants llvm package. I tried one from conan https://conan.io/center/search/llvm-core but it looks like it wants something else. Should I install llvm from official installer for windows or should I clone it and build myself? Definition `-DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-6.0`, what path should I pass in order to build it on windows? It looks like iwyu is heavily based on clang stuff, will it work with MSVC compiler?

**Comment by kimgr** [comment]
I think last I built on Windows, I built all of llvm+clang first and then used the build directory as CMAKE_PREFIX_PATH when I configured IWYU.

**Comment by kimgr** [comment]
It should work with MSVC, if it doesn't, bug reports and patches are welcome.

**Comment by jonesmz** [comment]
I happened to also be looking into how to do this.

Here's a *SUPER* janky script that I whipped together to get clang building on windows without needing to install external dependencies.
```bash
mkdir D:\builds\clang\
mkdir D:\builds\build-clang\
cd D:\builds\clang\

git clone --depth 1 --branch v1.2.11 https://github.com/madler/zlib.git
git clone --depth 1 --branch llvmorg-12.0.1 --config core.autocrlf=false https://github.com/llvm/llvm-project.git
git clone --depth 1 --branch 0.14 https://github.com/include-what-you-use/include-what-you-use.git

echo<<<EOF > D:\builds\clang\CMakeLists.txt
cmake_minimum_required(VERSION 3.12.0)
project(BuildClang)

add_subdirectory(zlib)

set(LLVM_ENABLE_PROJECTS "")
list(APPEND LLVM_ENABLE_PROJECTS clang)
list(APPEND LLVM_ENABLE_PROJECTS libcxx)
list(APPEND LLVM_ENABLE_PROJECTS libcxxabi)
list(APPEND LLVM_ENABLE_PROJECTS lldb)
list(APPEND LLVM_ENABLE_PROJECTS lld)
list(APPEND LLVM_ENABLE_PROJECTS polly)

set(LLVM_ENABLE_ZLIB ON)

set(LLVM_TARGETS_TO_BUILD "")
list(APPEND LLVM_TARGETS_TO_BUILD ARM)
list(APPEND LLVM_TARGETS_TO_BUILD AArch64)
list(APPEND LLVM_TARGETS_TO_BUILD X86)
list(APPEND LLVM_TARGETS_TO_BUILD BPF)
list(APPEND LLVM_TARGETS_TO_BUILD WebAssembly)

add_library(ZLIB::ZLIB ALIAS zlibstatic)
set(ZLIB_FOUND TRUE CACHE BOOL "")
get_target_property(INTERFACE_INCLUDE_DIRECTORIES zlibstatic ZLIB_INCLUDE_DIRS)
string(TOUPPER ${CMAKE_BUILD_TYPE} build_type)
##
# The last thing that the FindPackage script does is set ZLIB_LIBRARY
# But CMake doesn't make it easy to figure out the destination path
# for the library at configuration time.
# E.G. this'll throw an error.
##
#get_target_property(ZLIB_LIBRARY zlibstatic LOCATION_${build_type})

##
# Alternatively, a replacement for FindZLIB.cmake could be dropped into a folder
# on the CMAKE_MODULE_PATH.
#
# With contents matching the above
##
#set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

add_subdirectory(llvm-project/llvm)

# iwyu's cmake script is all sorts of broken
#add_subdirectory(include-what-you-use)
EOF

cmake.exe -Thost=x64 -DCMAKE_BUILD_TYPE=Release -S D:\builds\clang -B D:\builds\build-clang\

cmake.exe --build D:\builds\build-clang\ --parallel
```bash

**Comment by kimgr** [comment]
I think the README is mostly valid for Windows as well: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build. The CMake details are just different.

* Clone and build Clang as per https://clang.llvm.org/get_started.html.
* Clone `include-what-you-use` to a separate tree
* Configure IWYU with CMake with `-DCMAKE_PREFIX_PATH=D:\clang\build\tree`

If there are any problems along the way there, please ask, and we can see if we can figure them out.

**Comment by cglf** [comment]
Since this is still open, someone might find the exact steps I used to build iwyu and llvm from scratch on Windows 10 x64 with useful. MSVC 2019 must be installed, and Git and CMake are required to be in the environment path to use these commands verbatim. Start by opening a command prompt (not powershell) and `cd` into an empty folder somewhere. Then execute these commands to build and install LLVM 13.0.0 then IWYU 0.17:
```
set "WD=%CD:\=/%"

mkdir ".\build\llvm"
mkdir ".\install\llvm"
git clone -b llvmorg-13.0.0 https://github.com/llvm/llvm-project.git
cmake -S "%WD%/llvm-project/llvm" -B "%WD%/build/llvm" -G "Visual Studio 16 2019" -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%WD%/install/llvm" -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
cmake --build ".\build\llvm" --target INSTALL --config Release

mkdir ".\build\iwyu"
mkdir ".\install\iwyu"
git clone -b 0.17 https://github.com/include-what-you-use/include-what-you-use.git
cmake -S "%WD%/include-what-you-use" -B "%WD%/build/iwyu" -G "Visual Studio 16 2019" -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%WD%/install/iwyu" -DLLVM_DIR="%WD%/install/llvm/lib/cmake/llvm" -DClang_DIR="%WD%/install/llvm/lib/cmake/clang"
cmake --build "%WD%/build/iwyu" --target INSTALL --config Release
```

For powershell the steps would be the same, but the `set` and `mkdir` commands would have to be changed to powershell equivalents.

**Comment by kimgr** [comment]
@jonesmz @xahon Building as part of the llvm tree is now a supported configuration, as of https://github.com/include-what-you-use/include-what-you-use/pull/1032.

Documentation here: https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build-as-part-of-llvm

Hopefully that works for Windows too.

I'm going to close this issue, thanks for all the nice build scripts!
