### ISSUE TITLE
[Feature Request]: Support backreferences in include mapping's to-entry

### ISSUE THREAD

**Issue by 4wrxb** [include-what-you-use/include-what-you-use#959]
Inspired by #935 with suggestion from kimgr.

> Yeah, that would be nice. I think that logic is driven from `IncludePicker::FinalizeAddedIncludes`, from brief inspection it looks like it should be possible to use regex replacement.

It's going to be at least a month before I can make any attempt at this, but in the meantime I see one other area where I would like some guidance for IWYU's behavior.

In `IncludePicker::AddMappingsFromFile` include mappings are validated either as `IsQuotedFilepathPattern` for from-entry or  `IsQuotedInclude` for to-entry. `IsQuotedFilepathPattern` simply accepts any pattern beginning with '@'. Is it acceptable to use the same definition when checking the to-entry? Regex itself will behave predictably in terms of the substitution even if it's wrong from an `#include` standpoint, but it can be hard to check & validate all possible forms of backreference so I would rather err on the side of making the user figure it out.

**Comment by kimgr** [comment]
Yes, I think it makes sense to loosen validation for @-prefixed entries.

**Comment by kimgr** [comment]
As of PR #1123, commit 6fb66575fba17039d1be6c1fc3dca08623163460, there's now support for replacements with backreferences for all regex dialects.
