### ISSUE TITLE
Resolving <errno.h> on different platforms

### ISSUE THREAD

**Issue by stemp3** [include-what-you-use/include-what-you-use#964]
Hello, I'm using include-what-you-use as a pre-commit hook for my C projects and am having trouble with <errno.h>. Specifically, on macOS I get the following anywhere <errno.h> is used.

```
test.c:1:1: error: add the following line
#include <sys/errno.h>  // for ENOMEM
test.c:3:1: error: remove the following line
#include <errno.h>
```

My application builds and runs fine, so I assume include-what-you-use is using the wrong header to resolve the symbols? Is there something I can do to ensure that <errno.h> is used instead of <sys/errno.h>?

**Comment by stemp3** [comment]
I was able to resolve this by adding a custom mapping for errno.h and passing that to my hook with --mapping-file.

**Comment by kimgr** [comment]
Nice, that's the recommended way to do it. We still only have builtin mappings for GNU-like sysroots.
