### ISSUE TITLE
Export a forward declaration (e.g., for an opaque type)?

### ISSUE THREAD

**Issue by osandov** [include-what-you-use/include-what-you-use#971]
Let's say the public header `public.h` for my library defines some interfaces, including an opaque pointer type:

```c
struct opaque;

struct opaque *create_opaque(void);

enum my_enum {
	FOO,
	BAR,
	BAZ,
};
```

And I have an internal header that uses those interfaces:

```c
#include "public.h"

void use_opaque(struct opaque *);
void use_enum(enum my_enum);
```

Ideally, IWYU would realize that `public.h` "exports" a declaration of `struct opaque`, so "private.h" doesn't need a forward declaration. However, this is not the case:

```console
$ include-what-you-use private.h

private.h should add these lines:
struct opaque;

private.h should remove these lines:

The full include-list for private.h:
#include "public.h"  // for my_enum
struct opaque;
---
```

Is there any way to avoid this? The declaration of `struct opaque` really is a part of the interface provided by `public.h`, so requiring forward declarations seems silly.

**Comment by kimgr** [comment]
Yes, it does seem annoying, but unfortunately, I don't think there's a knob to work around it. You could try with `struct opaque; // IWYU pragma: export` in the public header, but I suspect IWYU is more trigger-happy with suggesting fwd-decls.

**Comment by osandov** [comment]
The pragma didn't help. I could add a mapping that `public.h` provides `struct opaque`, but then that would miss full uses.

Would it be possible to make the pragma work for this?

**Comment by kimgr** [comment]
I'm not sure. I wonder if `pragma: no_forward_declare` is more in line with this example: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-no_forward_declare?

**Comment by kimgr** [comment]
Support for `IWYU pragma: export` on fwd decls was added in https://github.com/include-what-you-use/include-what-you-use/pull/1164. It's not yet in a release, so you would have to build from master. Could you give it a shot?

**Comment by osandov** [comment]
This worked for me, thank you for adding it!
