### ISSUE TITLE
Iwyu in ci

### ISSUE THREAD

**Issue by stefaneicher** [include-what-you-use/include-what-you-use#984]
Hi,
can you recommed me how i can use iwyu in ci?
I want to enforce that there are no iwyu issues and if so let the build pipline fail.

I need somenting like
"Iwyu-check.py" that fails on errors.

Regards Stefan

**Comment by vmiklos** [comment]
Here is one way to do it:

https://github.com/vmiklos/odfsig/blob/2b1a042e0e9bbf69b3e377652b6793fd29e1be0b/.github/workflows/tests.yml#L54-L60

which leads to simply searching in the log:

https://github.com/vmiklos/odfsig/blob/2b1a042e0e9bbf69b3e377652b6793fd29e1be0b/scripts/build.sh#L107

**Comment by stefaneicher** [comment]
Great thanks for your answer
